### ISSUE TITLE
Hiding of hashing password stored in plain text in config.inc.php

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1010]
Hi
Is there any way of hiding/hashing or using vars that can be stored in another file/location for the passwords in config.inc.php that are stored under $ldap_dn_search_password or $db_password . I'm using $auth["type"] = "ldap";

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2784](https://sourceforge.net/p/mrbs/support-requests/2784)

**Comment by jberanek** [comment]
You could read another file inside config.inc.php, or read from an environment variable that you set in your web server configuration.

File:
~~~php
$ldap_dn_search_password = get_file_contents("/path/to/password_file");
~~~

Environment variable:
~~~php
$ldap_dn_search_password = $_ENV['MRBS_LDAP_SEARCH_PASSWORD'];
~~~

**Comment by campbell-m** [comment]
Or you could `include` another file which contains the sensitive config settings.
