### ISSUE TITLE
Minor: With unset($booking_types); edit_area / edit_area_handler give an sql error

### ISSUE THREAD

**Issue by being-peace** [meeting-room-booking-system/mrbs-code#11]
The described way to eliminate booking_types is to unset($booking_types) (see systemdefaults.inc.php)

// If you don't want to use types then uncomment the following line.  (The booking will
// still have a type associated with it in the database, which will be the default type.)
// unset($booking_types);

Unfortunately, this gives an sql error when editing an area, because the default_type field is not filled any longer and the edit_area_handler sets the default_type to "NULL", which is invalid.

Uncaught exception 'MRBS\DBException' in /var/www/html/lib/MRBS/DB.php at line 93
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'default_type' cannot be null
SQL: UPDATE mrbs_area SET area_name=?,sort_key=?,disabled=?,timezone=?,area_admin_email=?,min_create_ahead_enabled=?,max_create_ahead_enabled=?,min_delete_ahead_enabled=?,max_delete_ahead_enabled=?,max_duration_enabled=?,max_per_day_enabled=0,max_secs_per_day_enabled=0,max_per_week_enabled=0,max_secs_per_week_enabled=0,max_per_month_enabled=0,max_secs_per_month_enabled=0,max_per_year_enabled=0,max_secs_per_year_enabled=0,max_per_future_enabled=0,max_secs_per_future_enabled=0,private_enabled=?,private_default=?,private_mandatory=?,private_override=?,approval_enabled=?,reminders_enabled=?,enable_periods=?,periods=?,confirmation_enabled=?,confirmed_default=?,default_type=?,times_along_top=? WHERE id=?

There are several options, and I don´t know, which is most appropriate:

a) Make the column NULLable in table.*.sql and an upgrade*.sql
b) Change the description that the standard way to remove types is to have only one type (edit_entry won´t ask for the type in that case).
c) Change edit_area_handler /edit_area that they paste the default_type, even in there is not booking_types.
d) Leave it broken, as it is not the most common use case.

I would suggest c). What is your preference? I could submit a pull request...

**Comment by campbell-m** [comment]
Thanks for spotting this.  Yes, I think (c) is the way to go and I've committed it in [01eb4cd5](https://github.com/meeting-room-booking-system/mrbs-code/commit/01eb4cd56d78f235c0702569e64571b236cc559e).

**Comment by jberanek** [comment]
@being-peace : Are you able to verify @campbell-m 's fix in https://github.com/meeting-room-booking-system/mrbs-code/commit/01eb4cd56d78f235c0702569e64571b236cc559e ?

**Comment by being-peace** [comment]
@campbell-m @jberanek 
It fixes the particular problem, but has a drawback that is does not take into account "admin_only" types. If there where only "admin_only" types, an empty selection would be displayed.
A better and slightly simpler solution for this is here https://github.com/meeting-room-booking-system/mrbs-code/compare/main...being-peace:edit_area_no_types

Additionally it fixes a similar inconsistency in edit_entry: If there was no booking_type, the selection was not displayed. If there where only "admin_only" types, an empty selection would be displayed.

BTW: I would find it better, if get_type_options() would require an explicit choice if we want to admin or the non-admin types. It is used only edit_area that uses the implicit get_type_options() == get_type_options(false) .

**Comment by campbell-m** [comment]
Yes, I agree that's a better fix and I've now committed it to the main branch.   However I didn't commit the change to edit_area_handler.php as I think it's redundant.  The lines earlier on in the file

~~~php
if (!isset($area_default_type))
{
  $area_default_type = $area_defaults['default_type'];
}
~~~

should ensure that `$area_default_type` is set.

**Comment by being-peace** [comment]
Yes, your fix and my fix are logically identical, I had just placed it at a different position.

Thanks.
