### ISSUE TITLE
session_php.inc line 53 warning

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1106]
Thank you so much for MRBS. I implemented it for the first time before my holidays. Today first day after coming back to work unfortunately something is wrong. It returns this message in stead of opening in the browser:
"Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /customers/e/a/7/u-huset.dk/httpd.www/mrbs/lang/lang.da:1) in /customers/e/a/7/u-huset.dk/httpd.www/mrbs/session/session_php.inc on line 53 Warning: Cannot modify header information - headers already sent by (output started at /customers/e/a/7/u-huset.dk/httpd.www/mrbs/lang/lang.da:1) in /customers/e/a/7/u-huset.dk/httpd.www/mrbs/index.php on line 27"
Can I do anything to alter anything? I am not too familiar with php. Thanks.
SonjaS

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/368](https://sourceforge.net/p/mrbs/support-requests/368)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
