### ISSUE TITLE
cannot get mrbs to connect to a db on a remote server

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1114]
I have been trying to set mrbs up to use for work, My website and databases are all on dreamhost so "localhost" does not work. I cannot seem to connect to my remote server, for some reason it won't recognise http in the hostname?? how can I fix this.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/376](https://sourceforge.net/p/mrbs/support-requests/376)

**Comment by campbell-m** [comment]
Closed as out of date.
