### ISSUE TITLE
MRBS layout broken in  only firefox 

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1170]
HI

in my MRBS, i have created 2 custom tables on top of day,week and month view files.

the code i used is 

echo "<div id=\"dwm\">\n";
echo "<table width=\"200\" border=\"0\"><tr><td width=\"90\" align=\"center\" bgcolor=\"#e78a00\"><strong>Confirmed</strong></td><td width=\"94\" align=\"center\" bgcolor=\"#739621\"><strong>Tentative</strong></td></tr></table>";

i directly added the line in to .php files. after that it showing correctly on chrome and IE. but on firefox, it showing right side , with out of page layout

the reason i added is, users can easily identify the booking status. bcoz i used different colors for confirmed and tentative meetins.

how can i fix this issue, or is there any other way to add this?

thanks & regards,
Ben

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/434](https://sourceforge.net/p/mrbs/support-requests/434)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
