### ISSUE TITLE
Overview of weeks and rooms

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1194]
Is it possible to see an overview of a week, with all appointments of all rooms?
Because we can only see the appointments of a week of 1 room, and not all rooms.

Thanks

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/458](https://sourceforge.net/p/mrbs/support-requests/458)

**Comment by campbell-m** [comment]
This is now possible in MRBS.
