### ISSUE TITLE
Week or Monthly view

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1198]
Hi All

I have just introduced MRBS to this new company I am working for which I used to use in my old job as well. Although I didn't set it up at my old place so I'm not sure how they managed to get the Area view working for weeks or months. It looked something like my beautifully paint edited attachment below.

I was wondering if anyone else had managed to get this rolling, my old job seems a bit reluctant to give me these files. Which I will definitely send in if they do.

Thanks in advance

Steve

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/462](https://sourceforge.net/p/mrbs/support-requests/462)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/462/attachment/Monthly%20overview.jpg

**Comment by campbell-m** [comment]
MRBS can now display bookings for all rooms in an area in the week and month views.
