### ISSUE TITLE
Full Name instead of user id in Login page and email notification     

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1239]
Dear Campbell,

Let me first thank you for all your  inputs in MRBS implementation. By applying all your inputs and solution I successfully configured MRBS in my home.

Need your help for some more.

Using your inputs I have successfully changed the view_entry.php to see cretaed by persone full name instead of user ID.

But i need your help to implement same thing to Login Header and email notification also.
 

   

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/504](https://sourceforge.net/p/mrbs/support-requests/504)

**Comment by campbell-m** [comment]
MRBS now uses the user's display name wherever possible.
