### ISSUE TITLE
Background-image

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1286]
Hi, thanks for this great system. I want to ask for some help cause my developer skills are very basic specially with CSS.

I want to use an expanded background image as in [this site](http://www.sanpatricio.edu.ar ). I got the .jpg and copied out css instructions as i detail below: 

**body {
	background-image: url(images/fondo.jpg);
	background-repeat: repeat-x;
}**

So i went and edited mrbs's CSS file and tried the following:

**body {font-size: small;
    margin: 0;
    padding: 0;
    color:            <?php echo $standard_font_color ?>;
    font-family:      <?php echo $standard_font_family ?>;
    backround-image: url(XXX);
    background-repeat: repeat-x;
}**

where in XXX i tried all this with all variatons posible, plain, begining and endind with " and ': 

fondo.jpg (i put the image in stylesheet dir)
../images/fondo.jpg (i put the image in images under mrbs/web directory)
http://s13.postimg.org/kdb608oif/fondo.jpg (uploaded image)

Can you tell what am i doind wrong? 

Thanks

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/551](https://sourceforge.net/p/mrbs/support-requests/551)

**Comment by newtonpal** [comment]
> solved this on my own as well. thanks for the system anyway
> 
> Original comment by: *anonymous

Hello!
Can you share how to do it?
Thanks in advance!
