### ISSUE TITLE
Remove old SQL upgrade scripts and documentation

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#13]
Could it be time to remove the noise and confusion of the upgrade.*.sql scripts and the discussion of them in UPGRADE/INSTALL?

**Comment by campbell-m** [comment]
Yes, definitely!

**Comment by dorianim** [comment]
Just out of intereset: 
How are upgrades going to be performed then?

**Comment by dorianim** [comment]
Ohh, you talking about the upgrade.*.sql files in the project root, right?
Sorry for the confusion 🤦‍♀️
