### ISSUE TITLE
The time shows probelm

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1343]
Dear Sir,

I was setting the MRBS using times mode.
Is that possible to change the display time to 9:00 - 9:30?
Same as the Attach file.

Thank you.

Regards,

Joe

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/610](https://sourceforge.net/p/mrbs/support-requests/610)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/610/attachment/times.jpg

**Comment by campbell-m** [comment]
This is now possible by setting

~~~php
$show_slot_endtime = true;
~~~

in the MRBS config file.
