### ISSUE TITLE
Only white screen

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1348]
hello,
I've set up a subdomain mrbs.realschule-schoellnach.de and a database. I logged in there successfully and created spaces etc. When clicking on the room booking system, the page was white - to see any error messages!

What can I do?

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/615](https://sourceforge.net/p/mrbs/support-requests/615)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
