### ISSUE TITLE
LDAP Setup with sAMAccountName, show CN in viewentry.php

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1381]
Good day,

I have LDAP setup fine for authentication using the latest version.  Users login using thei sAMAccountName.  Instead of showing created by: [Their sAMAccountName] is it possible to show their CN name their?  So it shows their full name instead of just a username.  

I've looked through all the tickets and I couldn't find a solution for this, though I saw one person thanked someone for it.

Regards,
Peter

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/651](https://sourceforge.net/p/mrbs/support-requests/651)

**Comment by campbell-m** [comment]
This is now possible in MRBS.  The default config setting is

~~~php
$ldap_name_attrib = 'cn';
~~~
