### ISSUE TITLE
Show all rooms in Week view

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1400]
[Transferred from https://sourceforge.net/p/mrbs/support-requests/667/]

Hi, it's me again.

Just another question, that you have been ask already a tousand times...
When I had the 'incorrect' version 4.1.11 running whith the wrong report, I managed to get a weekly overview over all rooms (six) by just adding a for loop over the room ID's in week.php... However this is not possible anymore.

I googled a lot and found a lot of posts but not really a solution. Somewhere you were metioning to change something in the week_table_innerhtml function in functions_table.inc. 
Is there any existing code for this, or are you working on that?

It would be a great feature!

Thanks again, you did a great job!

Best,
Thea

Reported by: campbell-m

Original Ticket: [mrbs/support-requests/671](https://sourceforge.net/p/mrbs/support-requests/671)

**Comment by campbell-m** [comment]
It's now possible to see all the rooms in an area in the week and month views.
