### ISSUE TITLE
Blank Time Field and No Month text after Upgrade

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1471]
Hi, we have updated our MRBS to latest version today and have found that we are missing TIME (the fields are there but no time showing) and also where we see the MONTH, all we see is 2015 and not the days of week/actual month.

On upgrading, we did receive an error that advised that the TimeZone was not set - we found the entry in config ($timezone = "Europe/London";) and removed the "\\" which then continued the upgrade with no further issues.

Having read a few pointers on forums, is this likely to be something related to the default timezone which may NOT have been set originally (but now has/is) and so the times do not show? (though not sure how that would affect Month view) - If I go into an entry already in the calendar, it shows no start/end time also

I am picking update up from a previous member of staff so have quite limited (so far) knowledge of the system, but any help would be greatly appreciated

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/743](https://sourceforge.net/p/mrbs/support-requests/743)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/743/attachment/2015-05-26_16-13-10.png
  https://sourceforge.net/p/mrbs/support-requests/743/attachment/2015-05-26_16-13-27.png

**Comment by campbell-m** [comment]
I assume this has now been resolved.
