### ISSUE TITLE
unknown user

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1474]
Dear Support
Recently one of our user unable to login to mrbs portal.this happend to selected user only, and this user been able to login to system with out any issue all the while,issue arise from yesterday for the firs time and this issue happend again to another user today, not sure what could be the issue, any help for me to diagnose the issue to troubleshoot. we are user LDAP to access to the booking system

Reported by: kirup

Original Ticket: [mrbs/support-requests/746](https://sourceforge.net/p/mrbs/support-requests/746)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
