### ISSUE TITLE
Room List 

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1475]
I have an issue were the room list is pushing the calendar down the page. ( see attachment )
Can I either widen the page view or somehow wrap the rooms list?

Any help would be appreciated.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/747](https://sourceforge.net/p/mrbs/support-requests/747)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/747/attachment/Untitled.png

**Comment by campbell-m** [comment]
I assume this has now been resolved.
