### ISSUE TITLE
Regard all DB are fine, and create first user fine, but unable to login in

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1477]
Well, installed tables in DB, and upload web files fine, able to open the site and create the first user which is the admin, but for somehow when you log in, you always get "You do not have the necessary rights to view this page." no any other errors

Using phymyadmin check the DB, and the DB tables does have my user in the list and set as admin.

really have no idea why and how to fix it.

base on the test, DB does accept the enter from website. but for somehow, when you login in, looks like the data you enter unable to send to DB for match.

I did setup
$auth["type"]="db";

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/749](https://sourceforge.net/p/mrbs/support-requests/749)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
