### ISSUE TITLE
MBRS implementation

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1489]
Hi All, I am very happy to get support from you. i am new to MRBS and we have downloaded and started implementing the same. 

Current Status- we have created and implemented the mrbs, created the required rooms, now i need to integrate my windows Active Directory to login. I tried and can't able to do this. Can you please help me. MRBS Version - MRBS 1.4.11

with regards,
Dhinakaran K

Reported by: styledhina

Original Ticket: [mrbs/support-requests/761](https://sourceforge.net/p/mrbs/support-requests/761)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
