### ISSUE TITLE
Blank screen after adding an area or room.

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1500]
Fresh install
Logged in as administrator
Added an area
When I go back to see the schedule, screen is blank, no header, no footer, nothing displayed on the screen at all in day.php and week.php.  Site displays when changing to /month.php in the url. 
If I go back and remove the area, page is displayed fine.
Checked config.inc.php, nothing out of the ordinary. Not using periods. 

Meeting Room Booking System:	MRBS 1.4.11
Database:	MySQL 5.6.25-0ubuntu0.15.04.1
System:	Linux MRBS 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:45 UTC 2015 i686
Server time:	Fri 21 Aug 2015 14:00:53 CDT
PHP:	5.6.4-4ubuntu6.2

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/773](https://sourceforge.net/p/mrbs/support-requests/773)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
