### ISSUE TITLE
mrbs locale setting

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1530]
Dear all,
   I have an question on setting the locale on mrbs.  When I use the following coding in the config.inc.php
   
   /**********
 * Language
 *&********/

// Set this to 1 to use UTF-8 in all pages and in the database, otherwise
// text gets entered in the database in different encodings, dependent
// on the users' language
$unicode_encoding = 1;

// Set this to a different language specifier to default to different
// language tokens. This must equate to a lang.* file in MRBS.
// e.g. use "fr" to use the translations in "lang.fr" as the default
// translations
$default_language_tokens = "en";

// Set this to 1 to disable the automatic language changing MRBS performs
// based on the user's browser language settings. It will ensure that
// the language displayed is always the value of $default_language_tokens,
// as specified above
$disable_automatic_language_changing = 1;

// Set this to a valid locale (for the OS you run the MRBS server on)
// if you want to override the automatic locale determination MRBS
// performs
$override_locale = "en";

// faq file language selection. IF not set, use the default english file.
// IF your language faq file is available, set $faqfilelang to match the
// end of the file name, including the underscore (ie. for site_faq_fr.html
// use "_fr"
$faqfilelang = "en"; 

// This next require must be done after the definitions above, as the definitions
// are used in the included file
require_once "language.inc";

I can set all the wording in the site into english , BUT on the left hand corner, It given out Warning: Server failed to set locale to 'en']  Is that problem related the mrbs or appserv setting. Please kindly advice

I currently in Hong Kong 

Thanks & regards

Stephen HO

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/805](https://sourceforge.net/p/mrbs/support-requests/805)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
