### ISSUE TITLE
Correct Date

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1554]
Hi there,

I just upgraded to MRBS and everything is working fine.  However, when I log in, it doesn't go to the correct date, November 18, 2015.  Instead, it goes to July 2015.  Is there any way I can fix this?

Thank you!

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/829](https://sourceforge.net/p/mrbs/support-requests/829)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
