### ISSUE TITLE
Set default type based on Area

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1582]
Is there any way to set the default Type based on Area? We have one area that is exclusively Internal, but most areas are External... It would be a huge timesaver if the default could be External, except in that one area where the default would instead be Internal.

Reported by: aslum

Original Ticket: [mrbs/support-requests/858](https://sourceforge.net/p/mrbs/support-requests/858)

**Comment by campbell-m** [comment]
This is now possible in MRBS.
