### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1593]
Hi Mr. Campbell

I got issue on my meeting room booking. Whenever we submit our booking, it keep displaying the following error

Fatal error: unfortunately the database is not available at the moment.

Can you help me to solve this issues?

Thank You

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/869](https://sourceforge.net/p/mrbs/support-requests/869)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
