### ISSUE TITLE
MRBS Speed Performance

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#173]
Hello, 
I was wondering if there is any way to optimize the MRBS to make it faste to respond. Our department is complaining about 2-3 seconds screen refresh when navigatinf dates and 3-4 second for switching between Areas. To us, it seems reasonable but we wanted to ask just in case.

Here are the specifics:
Hard coded MRBS authentication.
Simple installation with no integration to other apps.
 Configuration details MRBS version	MRBS 1.7.3
$auth['type']	config
$auth['session']	php
Server details Database	MySQL 5.5.45
System	Windows NT WSAA-APPWC01 10.0 build 14393 (Windows Server 2016) AMD64
Server time	9/10/2019 8:55:12 AM
Server software	Microsoft-IIS/10.0
PHP	7.3.1
Network: 1GB

Any suggestion will be appreciated.

Reported by: *anonymous

Original Ticket: [mrbs/patches/88](https://sourceforge.net/p/mrbs/patches/88)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
