### ISSUE TITLE
Time of reservation are all off by 5 hours.  

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1860]
Maryann Thompson here at the County of Hunterdon ran the latest update, now the times are all off by 5 hours. any help would be appreciated.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1139](https://sourceforge.net/p/mrbs/support-requests/1139)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
