### ISSUE TITLE
Would like to improve performance of mrbs

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1871]
[Transferred from the general mailing list]

We are running version 1.49+svn / MSQL 5.5.45 / PHP 5.5.36 /Server 2012 R2 standard.

We have eight areas with an average of about a dozen rooms in each.

If we are not logged in we can switch from area to area fairly quickly but once we are logged in switching from area to area takes longer than it should. Also, once a booking is made saving it takes a long time – worst offender of all.

Can anybody suggest what (if anything) can be done to improve performance ?

This is a dedicated VM sitting on VMWare ESxi.

Reported by: campbell-m

Original Ticket: [mrbs/support-requests/1150](https://sourceforge.net/p/mrbs/support-requests/1150)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
