### ISSUE TITLE
ERROR: PHP's 'ldap' extension is not installed/enabled. Please check your MRBS and web server configuration.

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1916]
I'm trying to configure one of my MRBS systems to use LDAP authentication yet I'm getting this error:ERROR: PHP's 'ldap' extension is not installed/enabled. Please check your MRBS and web server configuration.

I've made sure that the php_ldap.dll is uncommented and I've ran a restart on the IIS server.  Also, I've turned on the ldap_debug and it isn't showing anything (I'm guessing because it isn't getting passed a certain point).  

Any help will be great.  This isn't a huge rush, but trying something.
Thanks

Reported by: warnertaylor

Original Ticket: [mrbs/support-requests/1199](https://sourceforge.net/p/mrbs/support-requests/1199)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
