### ISSUE TITLE
delete all bookings at once

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1975]
Hi,

I am installing MRBS for a new facility.

I backed up the previous facility's files and db, restored file systems files and database with ease on an Apache server with cPanel.

BUT: I want to delete all bookings: past, today and future on this "new" installation because I worked a lot on the configuration. I simply want a clean slate as far as bookings are concerned.

I ran a report in hopes of finding a "delete" function, but no bulk delete option.

Thank you,
Meno

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1259](https://sourceforge.net/p/mrbs/support-requests/1259)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
