### ISSUE TITLE
e-mail notice

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#1998]
Hi,

I'd like to make the booker to input the e-mail address per booking, and send the e-mail to that address, except room or area administrator.

I know I can add the extra field to the entry page.
How can I send the e-mail to that address automatically when the booker make a booking?

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1282](https://sourceforge.net/p/mrbs/support-requests/1282)

**Comment by campbell-m** [comment]
Duplicate of #1997.
