### ISSUE TITLE
MRBS\\DB factory not found error

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2008]
Hi,

Thanks for mrbs tool. It was really helpful.

I installed mrbs tool in ubuntu with Php5, pgsql and it worked fine.
I followed the same instructions in debian, but I am running into an issue. I could not see the start date and end date while trying to book a room ( I mean the calendar objects). Browser console shows that js.php files are not loaded. I added error logging and reproduced the same issue. I am getting the below mentioned error in the apache2 error log file.

 PHP Fatal error:  Class 'MRBS\\DBFactory' not found in /var/www/web/dbsys.inc on line 39
 
 I am not seeing any error in the UI apart from the dates field missing.

Any pointers to fix this issue will be helpful.

Thanks.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1292](https://sourceforge.net/p/mrbs/support-requests/1292)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
