### ISSUE TITLE
Rewording of "Rooms"

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2073]
Hi,
I am completey new to PHP, so this might not be a sensible question. But how difficult would it be to replace the word "Room" on the booking in form(s) to something else like "Resource" (or my particular case "instrument"). It seems a really good system, but I want it to book out a scientific instrument, rather than a meeting room?

Many thanks,
Aid

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1361](https://sourceforge.net/p/mrbs/support-requests/1361)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
