### ISSUE TITLE
release notes for 1.9.3 and 1.9.4 are duplicated

### ISSUE THREAD

**Issue by wohenbushuang** [meeting-room-booking-system/mrbs-code#21]
release [1.9.3](https://github.com/meeting-room-booking-system/mrbs-code/releases/tag/mrbs-1_9_3)  and [1.9.4](https://github.com/meeting-room-booking-system/mrbs-code/releases/tag/mrbs-1_9_4)

**Comment by jberanek** [comment]
Thanks for spotting this mistake, I've now fixed the release notes for 1.9.3.
