### ISSUE TITLE
Trouble with the last two slots to book

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2135]
I'm using the 1.6.1 version and I have trouble when try to book the last two slots making click over them the reservation´s form not open, ¿is a version trouble or setup?, the area is parametrized with the next values:
id	1
disabled	0
area_name	Biblioteca1
sort_key	Biblioteca1
timezone	America/Bogota
area_admin_email	
resolution	1800
default_duration	1800
default_duration_all_day	0
morningstarts	7
morningstarts_minutes	0
eveningends	21
eveningends_minutes	30
private_enabled	1
private_default	1
private_mandatory	1
private_override	none
min_create_ahead_enabled	1
min_create_ahead_secs	0
max_create_ahead_enabled	1
max_create_ahead_secs	1296000
min_delete_ahead_enabled	1
min_delete_ahead_secs	0
max_delete_ahead_enabled	1
max_delete_ahead_secs	1296000
max_per_day_enabled	0
max_per_day	1
max_per_week_enabled	1
max_per_week	2
max_per_month_enabled	0
max_per_month	8
max_per_year_enabled	0
max_per_year	50
max_per_future_enabled	0
max_per_future	100
max_duration_enabled	1
max_duration_secs	7200
max_duration_periods	0
custom_html	
approval_enabled	0
reminders_enabled	0
enable_periods	0
confirmation_enabled	0
confirmed_default	1

Thanks regardles!!!

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1424](https://sourceforge.net/p/mrbs/support-requests/1424)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
