### ISSUE TITLE
Query Enties Start/Ent Time 

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2138]
Hello,

I'm creating a custom php page to query only today's approve entries in all areas and rooms as a table (needed by our users) I have created the page with needed data but the problem is with the start_time and end_time format to be displayed as a regulrar date & time format not UNOX timestamp. I have tried many options but none worked. How can this be done? or is there another way to view today's approved entries without the calendar layout? Thanks.

Reported by: mabdelhady

Original Ticket: [mrbs/support-requests/1427](https://sourceforge.net/p/mrbs/support-requests/1427)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
