### ISSUE TITLE
How do I query to $tbl_entry and $tbl_room to fetch the data

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2185]
I have to select @match area and @match room and query to the two tables($tbl_entry and $tbl_room).
How I suppose to do?
Any suggestions

Reported by: janardhana

Original Ticket: [mrbs/support-requests/1475](https://sourceforge.net/p/mrbs/support-requests/1475)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/1475/attachment/mrbs.png

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
