### ISSUE TITLE
Timeline to highlighting the current time 

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2196]
Hello! 
It is possible to insert a timeline to highlight the current time? See the file attached 
Thank you for your help in advance.
Cheers Vanessa 

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1485](https://sourceforge.net/p/mrbs/support-requests/1485)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/1485/attachment/mrbs_timeline.png

**Comment by campbell-m** [comment]
This feature has now been implemented in MRBS.
