### ISSUE TITLE
from mysql to mysqli 

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2208]
I have updated my php from 5.4 to 7.0 and as result of this upgradation mysql is no longer valid. I tried updating config.inc.php by chnaging the $dbsys = mysql to mysqli but still getting errors . Apart from that I have also the mysql .inc to mqsli.inc(updating the functions as well) but still no result.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1499](https://sourceforge.net/p/mrbs/support-requests/1499)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
