### ISSUE TITLE
Cosmetic Issue - How to centre entries in MRBS

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2226]
[Transferred from the general mailing list]

Hi Folks.

I’ve created a new install of MRBS (1.7.1) and just looking to make a cosmetic change to entries but for the life of me I can’t remember how I did it.

I’m looking to ‘centre’ entries so it looks visually correct on screen.

I’ve trawled back through past emails and even tried looking online in the MRBS website but am I right in saying there has been a ‘purge’ of older requests or am I just looking in the wrong place.

Many thanks

Reported by: campbell-m

Original Ticket: [mrbs/support-requests/1517](https://sourceforge.net/p/mrbs/support-requests/1517)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
