### ISSUE TITLE
Loading MRBS in an Iframe

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2230]
Hello,

How should MRBS be configured to allow it loading from an iframe tag?  We have some issues with the "X-Frame-Options" policy and it only shows a blank page.

Thanks.

Reported by: hvdesign

Original Ticket: [mrbs/support-requests/1521](https://sourceforge.net/p/mrbs/support-requests/1521)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
