### ISSUE TITLE
Weekly Booking

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2307]
Hey there!

I do have some troubles with MRBS.
I am not able to book a room for every month or year. It will be booked for the first day of series only.

The edit_entry.php and config.inc.php have been modified by a different employee, unfortunately I am not able to contact him and I do not own any documentation about recent changes.

It would be awesome if you could tell me, why it does not work properly.

Greetings!

Reported by: cehring

Original Ticket: [mrbs/support-requests/1599](https://sourceforge.net/p/mrbs/support-requests/1599)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/1599/attachment/edit_entry.php

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
