### ISSUE TITLE
MRBS Running on Synology NAS

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2313]
Hi,

I've been using MRBS for a number of yers now on successive Windows servers using the MySQL version.

Have just ported over to a Synology NAS and created DB and associated tables from scratch.

The following error occurs on accessing the fromt page

*Fatal error: unfortunately the database is not available at the moment.*

I turned on error checking using 

```php
error_reporting(-1);
ini_set('display_errors', '1');
```

I placed this in internalconfig.inc.php file

I then got the following additonal error messages:

```
E_USER_NOTICE in /volume1/web/rooms/language.inc at line 865
Server failed to set locale to 'en_GB.UTF-8'
Uncaught exception 'MRBS\DBException' in /volume1/web/rooms/lib/MRBS/DB.php at line 75
SQLSTATE[HY000] [1045] Access denied for user 'mrbs'@'localhost' (using password: YES)
SQL: 
Params: 
#### *#0 /volume1/web/rooms/lib/MRBS/DBFactory.php(25): MRBS\DB->construct('localhost', 'mrbs', 'mrbs', 'mrbs', false, NULL)
#####1 /volume1/web/rooms/dbsys.inc(46): MRBS\DBFactory::create('mysql', 'localhost', 'mrbs', 'mrbs', 'mrbs', false, NULL)
#####2 /volume1/web/rooms/dbsys.inc(96): MRBS\db()
#####3 /volume1/web/rooms/defaultincludes.inc(30): requireonce('/volume1/web/ro...')
#####4 /volume1/web/rooms/week.php(6): require('/volume1/web/ro...')
#####5 {main}
#### MRBS GET: Array
#### (
####     [year] => 2018
####     [month] => 09
####     [day] => 11
#### )
#### MRBS POST: Array
#### (
#### )
#### MRBS SESSION: Array
#### *
```
Have I missed something obvious?

Thanks

Paul Haysom

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1606](https://sourceforge.net/p/mrbs/support-requests/1606)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
