### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2380]
Hello!
We are unable to schedule rooms as we get the following erorr message when saving schedules =

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\bokning\web\mysql.inc on line 62

System info:

Meeting Room Booking System:	MRBS 1.4.8
Database:	MySQL 5.5.8
System:	Windows NT SEJARPAPSSC0001 6.2 build 9200 (Windows Server 2008 R2 Standard Edition) i586
Server time:	2/4/2019 4:45:21 PM
PHP:	5.3.5

Please assist?

Best Regards!
Andreas Barjosef

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1677](https://sourceforge.net/p/mrbs/support-requests/1677)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
