### ISSUE TITLE
MRBS 1.7.3 - Unable to load dll's for MySQL at startup

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2430]
Hope someone can help:  I am trying to start MRBS 1.7.3 with MySQL and having a miserable time at it.  First, I tried using it with PHP 5.6.40.  This threw an exception and failed:

"Uncaught exception 'MRBS\DBException' in E:\WWW\Drupal\sites\FLTC\mrbs\web\lib\MRBS\DB.php at line 78 could not find driver SQL:"

So I updated PHP to version 7.3.3, and it threw the same exception, except the php error log shows a different error:

[29-Mar-2019 17:17:39 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_mysql.dll'  tried: C:\Downloads\php-7.3.3-nts-Win32-VC15-x64\ext\php_mysql.dll

The dll *is* present in that location, however.

It's looking like I forgot to register something or missed a step when setting things up, but I can't figure out what.  Any help would be appreciated.  (I've attached the two PHP error logs.)

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1728](https://sourceforge.net/p/mrbs/support-requests/1728)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/1728/attachment/php-7.3.3_errors.log
  https://sourceforge.net/p/mrbs/support-requests/1728/attachment/php53_errors.log

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
