### ISSUE TITLE
Remove rooms filter in week and month view

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2431]
Hello,
 is it possibile to remove the room filter in week and months views? Can you please help me to do it?
 
 Thanks a lot,
 Br

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1729](https://sourceforge.net/p/mrbs/support-requests/1729)

**Comment by campbell-m** [comment]
This feature is now supported in MRBS.
