### ISSUE TITLE
MYSQL Crash

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2472]
Uncaught exception 'MRBS\DBException' in /opt/lampp/htdocs/mrbs/web/lib/MRBS/DB.php at line 185
SQLSTATE[42S02]: Base table or view not found: 1932 Table 'mrbs.mrbs_area' doesn't exist in engine
SQL: SHOW COLUMNS FROM mrbs_area

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1770](https://sourceforge.net/p/mrbs/support-requests/1770)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
