### ISSUE TITLE
LDAP error

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2479]
Hi,
I have moved my MRBS installation to a new server - all seems OK until I try to login, then I 
get "ERROR: PHP's 'ldap' extension is not installed/enabled. Please check your MRBS and web server configuration."
I have checked my PHP setting, and the extension=php_ldap.dll is there - I have also restarted the server - still doen't work.
What else am I missing....?

many thanks,

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1778](https://sourceforge.net/p/mrbs/support-requests/1778)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
