### ISSUE TITLE
Another little customization

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2480]
I tried to insert a text at the bottom of the page to insert useful information. I tried to create a bar like in the header but I couldn't get a text in the middle of the space. Could you help me?

Reported by: simona1974

Original Ticket: [mrbs/support-requests/1779](https://sourceforge.net/p/mrbs/support-requests/1779)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/1779/attachment/Footer.jpg

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
