### ISSUE TITLE
LDAP problem

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2481]
I have had MRBS running on my webserver with no problems, for months.....
Now, suddenly, I get 'unknown user' when anybody tries to login....
All other sites on my webserver, that use LDAP for authentication are still working fine - its just MRBS thats stopped working....

Any ideas...?

thanks,
Dave.

Reported by: dnlees

Original Ticket: [mrbs/support-requests/1780](https://sourceforge.net/p/mrbs/support-requests/1780)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
