### ISSUE TITLE
To use login details from other database

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2484]
I raised this one at the Patches Ticket #82. Howver, when i change the auth type to db_ext and the databse details. But i still cannot seem to login. Any advise? 

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1783](https://sourceforge.net/p/mrbs/support-requests/1783)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
