### ISSUE TITLE
Mail not working

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2510]
If user check box is  uncheck  "**do not send mail**" option on Add Entry form and click on  save button, will get  below error.

######  {main}

Reported by: indphpsel

Original Ticket: [mrbs/support-requests/1809](https://sourceforge.net/p/mrbs/support-requests/1809)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/1809/attachment/Mrbs.JPG

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
