### ISSUE TITLE
Calendar Wont Save Bookings

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2525]
I have recently updated to the new version of MRBS. I go in to add an event into the calendar, fill out the information, submit it, but the event is not saving? Help!

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1826](https://sourceforge.net/p/mrbs/support-requests/1826)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
