### ISSUE TITLE
custom field vocab_override not used in email

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2532]
Hi

I've added a custom field and it's working great - love how easy you made it! I added the required line to lang.en:

`$vocab_override['en']['entry.class_name'] = "Class Name";`

This is used as I expected on the site, but it doesn't get used in the email notifications. The email still uses 'class_name'. Is there something else I need to add to the lang file?

thanks :)

Reported by: kenadams

Original Ticket: [mrbs/support-requests/1833](https://sourceforge.net/p/mrbs/support-requests/1833)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
