### ISSUE TITLE
New interface room listing

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2587]
Hi, for new interface is there any option to change room listing from drop down list to list all room? Reason I am asking this is to create more user friendly interface. User can easily click on the room intead of choose using drop down listing. Thank you.

![](https://i.imgur.com/TGMbe5R.png)

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/1890](https://sourceforge.net/p/mrbs/support-requests/1890)

**Comment by campbell-m** [comment]
No, I am afraid there is no option.
