### ISSUE TITLE
$private_override Variable - where to get this?

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2606]
Hello,

where are the settings variables stored?

I need to get $private_override. But whenever i use this variable, i dont get it.

Thx, greeting Mathias

Reported by: trm

Original Ticket: [mrbs/support-requests/1910](https://sourceforge.net/p/mrbs/support-requests/1910)

**Comment by campbell-m** [comment]
Closed following no response.
