### ISSUE TITLE
What´s the easiest way to automate an import?

### ISSUE THREAD

**Issue by being-peace** [meeting-room-booking-system/mrbs-code#27]
**Describe the problem you're facing/question you have**
I would like to do a call to import.php (with URL) automatically, with a cron job. How to do this? What is the best way to implement this?
Add some cli interface (like in reports.php)? Try to extract the post parameters and use them as get parameters (and hack around with the csrf_token)?

**Browser details (please complete the following information):**
 - OS: hosted linux

**Server details (please complete the following information):**
 - MRBS version 1.9.4/1.10

**Additional context**

**Comment by being-peace** [comment]
Hm, I would just have to hack around the "checkToken()" in import.php and then get parameters work. So I think, we can close this.

**Comment by campbell-m** [comment]
Yes, report.php is a good example, including omitting the checkToken() if you're running from the CLI.
