### ISSUE TITLE
SMTP Issue - "Could not instantiate mail function. [DEBUG] Failed to send email: Could not instantiate mail function."

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2749]
Hi All,

I am having issues with getting our SMTP Emails to work with MRBS. I am encoutering an issue stating 
"Could not instantiate mail function.
[DEBUG] Failed to send email: Could not instantiate mail function."

Attached is my SMTP Settings.
** Note i have tired with autentication enabled with valid credentials but same issue **

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2055](https://sourceforge.net/p/mrbs/support-requests/2055)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/2055/attachment/smtp_debug.txt

**Comment by campbell-m** [comment]
I assume this has now been resolved.
