### ISSUE TITLE
Assign users in reserve

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2774]
I am using mrbs for a gym and I create room reservation for different classes. Is there a way to add users to these classes "reservations" and thus see how many people will be in the reservation?

Thanks a lot

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2080](https://sourceforge.net/p/mrbs/support-requests/2080)

**Comment by campbell-m** [comment]
This is now possible with the "registration" feature.
