### ISSUE TITLE
No such host is known error

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2775]
Hi 
This is probably a simple one to fix but can't work it out.

I'm getting the below message when I load mrbs, I have just updated to 1.6 then 1.6.1 and have used a new config.inc.php with this release. The db.php at line 62 points to the password used and to recreate mrbs user with new password which I have done but to no avail. Can you help please?  

~~~text
Uncaught exception 'MRBS\DBException' in D:\MRBS\web\lib\MRBS\DB.php at line 67
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No such host is known.
SQL:
Params:
#0 D:\MRBS\web\lib\MRBS\DBFactory.php(25): MRBS\DB->__construct('http://mrbs.man...', 'mrbs', 'MRBS-Password', 'mrbs', false, 8081)
#1 D:\MRBS\web\dbsys.inc(39): MRBS\DBFactory::create('mysql', 'http://mrbs.man...', 'mrbs', 'MRBS-Password', 'mrbs', false, 8081)
#2 D:\MRBS\web\dbsys.inc(74): MRBS\db()
#3 D:\MRBS\web\defaultincludes.inc(29): require_once('D:\\MRBS\\web\\dbs...')
#4 D:\MRBS\web\index.php(9): require('D:\\MRBS\\web\\def...')
#5 {main}
MRBS GET: Array
(
)
MRBS POST: Array
(
)
~~~

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2081](https://sourceforge.net/p/mrbs/support-requests/2081)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
