### ISSUE TITLE
No mini-calendar showing - upgrade to 1.8

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2776]
Hi.

I just upgraded my installation from 1.7.4.1 to 1.8.  There were a couple of stutters during the FTP process, but eventually all seemed to go well.  However, when I checked out the new version, I couldn't see the mini-cals I normnally see.  Additionally, the legends along the 'header'  (Log-in, Reports etc) had gone.  I'm attaching an image to try and show this.   My image doesn't show it, but the time-slots (l/h side of screen) had also shrunk in width, so that for example, 5.00
showed as 
5.0
0

I don't see that anyone else is reporting this, so I'm thinking maybe a hiccup with the upload.  But I thouight I'd ask here in case there's an alternative explanation.  Thanks for any input.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2082](https://sourceforge.net/p/mrbs/support-requests/2082)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/2082/attachment/MRBS1.jpg

**Comment by campbell-m** [comment]
I asssume this has been resolved by now.
