### ISSUE TITLE
Unable to run new configured MRBS

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2815]
Today I had configured Ubuntu + Mysql + Phpmyadmin+ apache2 .  After that I had copied  all the data of mrbs/web to /var/www/html/mrbs/web 
After that I made changes 
1. Create databae mrbs
2.  run tables through tables.my.sql
3.  run mysql 
4.  connect mrbs
5.  show tables
6.  it is showing following tables
7.      -> ;
+----------------+
| Tables_in_mrbs |
+----------------+
| mrbs_area      |
| mrbs_entry     |
| mrbs_repeat    |
| mrbs_room      |
| mrbs_sessions  |
| mrbs_users     |
| mrbs_variables |
| mrbs_zoneinfo  |
+----------------+
mysql> select * from mrbs_variables;
+----+------------------+------------------+
| id | variable_name    | variable_content |
+----+------------------+------------------+
|  1 | db_version       | 63               |
|  2 | local_db_version | 1                |
+----+------------------+------------------+

    8.  config.inc.php-sample to config.inc.php
    9.  open config.inc.php
    10.  changes time zone =Asia/Kolkata
    11.  db_host="142.147.12.151"
    12.  db_persist="TRUE"
    
    After running in browser
    http://142.147.12.151/mrbs/web/index.php
    then I had found the error of
    This page isn’t working right now142.147.12.151 can't currently handle this request.
HTTP ERROR 500

Pl. suggest, what changes need to design

Thanks in advance
Jitendra Kanungo
Indore
9755097224

Reported by: jitendrakanungo

Original Ticket: [mrbs/support-requests/2121](https://sourceforge.net/p/mrbs/support-requests/2121)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
