### ISSUE TITLE
Problema con autentificacion CAS en MRBS

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2820]
Hola, ayuda no puedo iniciar autentificacion con autentificacion CAS.
Mrbs versionn 1.80

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2127](https://sourceforge.net/p/mrbs/support-requests/2127)

**Comment by campbell-m** [comment]
Closed following no response.
