### ISSUE TITLE
Set Start and End Times

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2852]
I am trying to change the default start and end times for room bookings (8:00 AM - 21:00).  I have edited the config.inc.php file with the following lines, and it still is set on the default 7:00 - 19:00.

// TIMES SETTINGS
// --------------
// The beginning of the first slot of the day (DEFAULT VALUES FOR NEW AREAS)
$morningstarts         = 8;   // must be integer in range 0-23
$morningstarts_minutes = 0;   // must be integer in range 0-59

// The beginning of the last slot of the day (DEFAULT VALUES FOR NEW AREAS)
$eveningends           = 21;  // must be integer in range 0-23
$eveningends_minutes   = 30;   // must be integer in range 0-59

Not sure what  I am missing.

Thanks

Reported by: techguy1

Original Ticket: [mrbs/support-requests/2159](https://sourceforge.net/p/mrbs/support-requests/2159)

**Comment by tli47** [comment]
> The config settings just determine the default settings for _new_ areas. For existing areas login to MRBS as an admin, go to the Rooms page and edit the area in question.
> 
> Original comment by: campbell-m

why my admin account looks like the following picture? I have no an entry of time in rooms
![1695270045432](https://github.com/meeting-room-booking-system/mrbs-code/assets/26863079/aa4ae75a-93b9-4595-ae0e-b746139f3d27)

**Comment by campbell-m** [comment]
You are editing a _room_.   The times are set for an area, so you should edit the _area_.  On the Rooms page select the area and then click the Edit icon (little pencil).
