### ISSUE TITLE
css problem?

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2853]
the div position are placed in the wrong places, the page view is not right. how to figure?

the old one:http://brain.bnu.edu.cn/mrbs/help.php?day=3&month=9&year=2020&area=7&room=27
the new one:http://braincrb.bnu.edu.cn/help.php?view=day&page_date=2020-09-03&area=4&room=1

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2160](https://sourceforge.net/p/mrbs/support-requests/2160)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
