### ISSUE TITLE
Change Database from PostgreSQL to MySQL

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2877]
Hi Together

Is there a way, to transfer the all Data from a PostgreSQL Server to a MySQL Server?
Thx a lot
Marco

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2184](https://sourceforge.net/p/mrbs/support-requests/2184)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
