### ISSUE TITLE
failed to open stream

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2887]
Hi Guys I'm recieving this error please help

Warning: require_once(config.inc): failed to open stream: No such file or directory in C:\XAMPP\htdocs\mrbs\web\defaultincludes.inc on line 24

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2194](https://sourceforge.net/p/mrbs/support-requests/2194)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
