### ISSUE TITLE
Bookings displaying one hour late

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2888]
Hi
We have been using MRBS for a couple of months with no issues, however this week the bookings have started to be displayed as an hour later than the UNIX start time in the database (e.g. a 9am booking with a UNIX start time of 1602234000 is displaying as 10am on the calendar and edit_entry screens). We are using a Windows server and the timezone is set as Europe/London on both the server and in the config.inc file. I have been assured by our IT department that no changes have been made to the server by them. Please could you advise what is causing this and how we can resolve the issue?
Thank you

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2195](https://sourceforge.net/p/mrbs/support-requests/2195)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
