### ISSUE TITLE
UX for changing profile (e.g. email/password)

### ISSUE THREAD

**Issue by being-peace** [meeting-room-booking-system/mrbs-code#29]
**Describe the problem you're facing/question you have**
Is it true, ordinary users can´t change their email/password/display name? A password change is only possibly using the "forget password" function. Or do I miss something?

**Server details (please complete the following information):**
 - MRBS version 1.10

**Comment by campbell-m** [comment]
Yes, they can.  Just click on your name in the Users table and edit your details.

**Comment by being-peace** [comment]
Ah, I thought in the default setup, ordinary users can´t see the users table, as in https://mrbsdemo.uk.to/mrbs/

**Comment by campbell-m** [comment]
The demo system uses config not db authentication to prevent users messing up the system.

**Comment by being-peace** [comment]
Thanks.

**Comment by being-peace** [comment]
Still some things are somehow unexpected. Perhaps there has been some alignment in the typical behaviour of web-interfaces, or it´s just my subjective expectations that...
1. for changing my profile/password I would click on my name.
2. an ordinary users should not see the list of all users.
3. the list of all my bookings would be a separate menu item.
What is your feeling towards that?

**Comment by campbell-m** [comment]
(1) and (3).   This is just the historical behaviour of MRBS.  I suppose that for new users it could look strange and could be improved.

(2) This is a config option.

**Comment by campbell-m** [comment]
By the way, could you open a new issue for new topics please rather than reopening an old one and changing the title!  Thanks.

**Comment by being-peace** [comment]
Thanks for the hint about reopening. I thought in this case, it might be a better explanation for the initial issue, but in general you are right.

**Comment by jberanek** [comment]
No particular change to the UX is planned at this time.
