### ISSUE TITLE
automatically transfer to some calendar

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#2991]
Unfortunately I could not find anything in the search.
Is there any way to automatically transfer the booked appointments to some online calendar. The main thing is no manual steps and somehow get into the calendar of a smartphone.

Reported by: mmuller

Original Ticket: [mrbs/support-requests/2301](https://sourceforge.net/p/mrbs/support-requests/2301)

**Comment by campbell-m** [comment]
See also Issue #3742.
