### ISSUE TITLE
(minor) "Back" Button does not restore End-Date in some conditions

### ISSUE THREAD

**Issue by being-peace** [meeting-room-booking-system/mrbs-code#30]
**Describe the bug**
When a multi-day booking has a conflict, going back from the conflict page to the booking pages sets clears the end date.

**To Reproduce**
1. Create a booking with a conflict over several days.
2. Click on save
3. Click on Back
4. End-date is set to Start-date

**Expected behavior**
End-date as before

**Server details (please complete the following information):**
 - MRBS version 1.10

**Comment by campbell-m** [comment]
OK, I'll take a look.
