### ISSUE TITLE
Uncaught exception 'Error' in /www/meeting/functions.inc at line 1789

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3024]
Hi Everyone
When I change the level for a user to administrator I have a problem in functions.inc 
Please help me.

Error below:

Class 'PHPMailer\PHPMailer\PHPMailer' not found
~~~
#0 /www/meeting/functions.inc(1803): MRBS\validate_email()
#1 /www/meeting/edit_users.php(1011): MRBS\validate_email_list()
#2 {main}
~~~

MRBS GET: Array
(
)
MRBS POST: Array
(
    [csrf_token] => 902c324d713aa835920db5d916d5c922d1c944c3f63587a8b8b9a6b8ad5a35ff
    [id] => 305
    [f_level] => 1
    [f_name] => minhtri
    [f_display_name] => Vo Minh Tri
    [f_email] => 
    [password0] => 123
    [password1] => 123
    [update_button] => Save
)
MRBS SESSION: Array
(
    [csrf_token] => 902c324d713aa835920db5d916d5c922d1c944c3f63587a8b8b9a6b8ad5a35ff
    [user] => MRBS\User Object
        (
            [username] => letung
            [display_name] => Le Thanh Tung
            [email] =>
            [level] => 2
            [id] => 304
            [password_hash] => $2y$10$Bp6TWI0F3umbxe8/ZgCNVO2n.NP2LEHBQoWC4r5OZBHKzNa7FBZOe
            [timestamp] => 2021-04-05 17:39:19
            [last_login] => 1618454356
            [reset_key_hash] => $2y$10$BLtYRMp0egqyT0RlZKzYcueWChFDl363M3jA8ybZ1Hw4WYam8JHfy
            [reset_key_expiry] => 1617705559
        )

)

Reported by: zoom2x

Original Ticket: [mrbs/support-requests/2335](https://sourceforge.net/p/mrbs/support-requests/2335)

**Comment by campbell-m** [comment]
Closed following no response.
