### ISSUE TITLE
The calendar is not displayed and the user record is not saved

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3059]
Good day,
I am sorry for my english. MRBS is shown to me, see picture.
I was looking for an error and the Chrome console is:
Uncaught SyntaxError: Invalid or unexpected token general.js.php? area = 2 & v = 1621710330
Please help.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2371](https://sourceforge.net/p/mrbs/support-requests/2371)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/2371/attachment/calendar.jpg

**Comment by campbell-m** [comment]
Closed due to no response.
