### ISSUE TITLE
How to config when booking , system send email to admin or anyone

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3077]
Sorry, I'm a newbie. I installed MRBS and booking, everything OK. Please teach me step by step how to book a room, system will send an email to admin or anyone. Thanks so much.

Reported by: abckids1983

Original Ticket: [mrbs/support-requests/2389](https://sourceforge.net/p/mrbs/support-requests/2389)

**Comment by HONGNGUYEN2023** [comment]
Hi all; I got an error message when I change the setting below to true for the Mrbs 1.11.4 version. the email sent to admin but the error message after clikc "Approve" 
$mail_settings['admin_on_bookings']      = true;  // the addresses defined by $mail_settings['recipients'] below
$mail_settings['area_admin_on_bookings'] = true;  // the area administrator
$mail_settings['room_admin_on_bookings'] = true;  // the room administrator
$mail_settings['booker']                 = true;  // the person making the booking
$mail_settings['book_admin_on_approval'] = true;  // the booking administrator when booking approval is enabled****
