### ISSUE TITLE
Area

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3100]
Hello, is area and room field on the new mrbs version deactivated?  How can I activate it again? TY!

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2415](https://sourceforge.net/p/mrbs/support-requests/2415)

Attachments:
  https://sourceforge.net/p/mrbs/support-requests/2415/attachment/Screenshot-1.png

**Comment by campbell-m** [comment]
The area and room can now only be selected via a drop-down, not a list.
