### ISSUE TITLE
url-question

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3111]
I have a question about the URL:
index.php?view=day&view_all=0&page_date=2021-09-29&area=7&room=169

I want to make a kiosk mode/view mode to pick info about a room. I need to autorefresh the view, and the URL has a fixed date.

I have not tested yet, but how will this wotk if the date changes to tomorrow? What about a parameter like "today" to avoid the result to be a specified date?

Perhaps do I misunderstand. Is there a auto refresh routine to make this keed updated eg every 30 minutes?

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2426](https://sourceforge.net/p/mrbs/support-requests/2426)

**Comment by campbell-m** [comment]
There is now a Kiosk mode on MRBS.
