### ISSUE TITLE
Can I add holidays to my calendar? 

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3118]
Can I add holidays to my calendar? 

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2433](https://sourceforge.net/p/mrbs/support-requests/2433)

**Comment by embeh** [comment]
Hi,

can this be done on a per-room basis? Setting $hidden_days to (0,6), for example, will remove the weekend for every available room in MRBS. We would like to do this only for one of the rooms...

Thanks!

**Comment by campbell-m** [comment]
> can this (hide weekends) be done on a per-room basis?

No, sorry, it can't.  But if you only want to do it for one of the rooms then just book out that room at weekends.
