### ISSUE TITLE
Error after importing iCal: $vocab["fatal_db_error"] = "Fataler Fehler..."

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3206]
Hi, I am trying to upload iCal files to MRBS and I get the error: "Fataler Fehler: Leider steht die Datenbank im Moment nicht zur Verfügung."

It's this: $vocab["fatal_db_error"] = "Fataler Fehler: Leider steht die Datenbank im Moment nicht zur Verfügung.";

Can someone help me and let me know what the issue is? How do I solve this? Thanks in advance.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2521](https://sourceforge.net/p/mrbs/support-requests/2521)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
