### ISSUE TITLE
Forgotten password email link broken

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3246]
Hi there, 

I've forgotten my password. When i receive an email to reset my password it gives me a error message

https://https/brothersinneed.org.au/booking/reset_password.php?action=reset&usernames%5B0%5D=bnbooking&key=74d52409876e51f9169a170aae259c7a90573f5f3a15b5949c4c0b5edc489908

I can be contacted on info@brothersinneed.org.au to have this rectified. 

Thank you 

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2561](https://sourceforge.net/p/mrbs/support-requests/2561)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
