### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3253]
Dear sir:
Warning: require_once(config.inc.php): failed to open stream: No such file or directory in C:\xampp\htdocs\mrbs\defaultincludes.inc on line 24

Fatal error: require_once(): Failed opening required 'config.inc.php' (include_path='C:\xampp\htdocs\mrbs\') in C:\xampp\htdocs\mrbs\defaultincludes.inc on line 24

please help me
thank you!!

Reported by: allenhu

Original Ticket: [mrbs/support-requests/2568](https://sourceforge.net/p/mrbs/support-requests/2568)

**Comment by campbell-m** [comment]
I am assume this has now been resolved, one way or another.
