### ISSUE TITLE
how to integrate mrbs into wordpress

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3269]
Hi, I wanted to know if it is possible to integrate this project into wordpress. What are the requirements, if any?
Wordpress version: 6.0.1
PHP version: 7.4.30 (Supports 64bit values)
database server version: 10.3.35-MariaDB-log-cll-lve

Reported by: nicovon

Original Ticket: [mrbs/support-requests/2584](https://sourceforge.net/p/mrbs/support-requests/2584)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
