### ISSUE TITLE
Custom field options arrays not working in 1.10.0

### ISSUE THREAD

**Issue by aclark4life** [meeting-room-booking-system/mrbs-code#33]
**Describe the bug**
Custom field options arrays not working in 1.10.0, similar to https://sourceforge.net/p/mrbs/support-requests/2379/

**To Reproduce**
1. Create a custom field as described here: https://github.com/meeting-room-booking-system/mrbs-code/blob/main/INSTALL#L143

**Expected behavior**

["MRBS will then recognise them
and handle them automatically, displaying the information in the lists of rooms
and users and allowing you to edit the data in the appropriate forms."
](https://github.com/meeting-room-booking-system/mrbs-code/blob/main/INSTALL#L155-L157)

**Screenshots**

<img width="1076" alt="Screen Shot 2022-01-10 at 11 16 43 AM" src="https://user-images.githubusercontent.com/72164/148801613-0b92a725-78e5-49be-9e7a-962bb3698884.png">

<img width="1440" alt="Screen Shot 2022-01-10 at 11 24 12 AM" src="https://user-images.githubusercontent.com/72164/148801888-7ee228bc-2d3b-4b9a-a8b1-9bcf3187151f.png">

<img width="603" alt="Screen Shot 2022-01-10 at 11 28 42 AM" src="https://user-images.githubusercontent.com/72164/148801855-c40c94ea-8afd-4c23-8388-47c007e2101d.png">

"PI" is a textarea instead of a select field.

**Comment by campbell-m** [comment]
Ah, OK, I understand the issue now - thanks.  Fix to follow soon.

**Comment by aclark4life** [comment]
Thank you @campbell-m ! Confirmed fixed
