### ISSUE TITLE
MRBS Rooms disappeared

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3372]
Hello, could anyone help me please? I am looking for some support.  The MRBS went down 3 days ago, it's come back up but all the rooms are missing, past/future and nothing can be created, reports not working either.  I dont have any IT support at the moment who can check it.  Any guidance?

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2687](https://sourceforge.net/p/mrbs/support-requests/2687)

**Comment by campbell-m** [comment]
No response received.  Assumed to be resolved.
