### ISSUE TITLE
HTTP error 500 with PHP 8.0 and above

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3396]
I am supposed to switch from PHP 7.4 to 8.0 or above by 31-03-2023. 
I'm on MRBS 1.11.0 which should work with 8.2. But I'm getting HTTP error 500 after changing the PHP-version. After switching back to 7.4 the error is gone. 

Any idea? 

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2714](https://sourceforge.net/p/mrbs/support-requests/2714)

**Comment by campbell-m** [comment]
Closing as no response received.
