### ISSUE TITLE
Custom field not visible when booking 

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#3435]
We have a requirement for users to fill in additional fields when posting, but then they should only be visible to creators and admins. 
The columns are created in the table "room" are also visible when viewing the room.
What setting is now necessary that the fields are also visible when booking the room.

Reported by: *anonymous

Original Ticket: [mrbs/support-requests/2754](https://sourceforge.net/p/mrbs/support-requests/2754)

**Comment by fuzezeze** [comment]
If I added custom fields in entry and repeat, can I set only part of room show these fields when user booking?

**Comment by campbell-m** [comment]
> If I added custom fields in entry and repeat, can I set only part of room show these fields when user booking?

See Issue #3584
