### ISSUE TITLE
MRBS and SAML - Chrome and Edge Cookie Issues

### ISSUE THREAD

**Issue by Gergama** [meeting-room-booking-system/mrbs-code#3465]
Hi all,

We've been using MRBS for a number of years now and recently been told we had to migrate to SAML authentication from CAS.  I've set-up a new, clean instance of MRBS v1.11.1 on IIS with PHP 7.4.30. I've only added the database and SAML authentication configuration portions to config_inc.  

I am able to authenticate into MRBS using Firefox v115.0.2 and everything functions normally.  Hurray!  When I try using Chrome (v114.0.5735.199) or Edge--a different outcome.  I go through the normal authentication process without problem, however, when I am returned to MRBS it shows that I'm not logged in,  When I check the developers console,  I can see a cookie has not been set like in Firefox.  Another oddity I found is authenticating using Chrome in an iOS environment works just fine, so it seems limited to the desktop version

I'm at a loss for trying to figure out what is happening.  Does anyone have any ideas of what the problem may be and/or, a way to trace why a cookie is not being set in Chrome/Edge?  I don't have a lot of experience with SAML, but I have been able to implement it on several other applications without issue.

Many thanks for any assistance you may be able to provide--I'd sure appreciate any help!
Allan

**Comment by campbell-m** [comment]
I suspect it's something to do with the CORS policy.

**Comment by Gergama** [comment]
Thanks for pointing me in a direction.  While CORS wasn't the issue, I was able to narrow down the issue was being cause by something at the server (IIS) settings.  When I moved my code to a different environment, everything was working normally in all browsers.  When I have more time, I'll try to find out what the precise issue was.  For now, I'm glad we should be able to go into production again soon.

**Comment by BrzIGH** [comment]
Hi Gergama,

I am trying to configure SAML authentication on IIS 10. Can you please give me some idea of what you needed to install and configure ?

Thanks

**Comment by Gergama** [comment]
Hi BrzIGH,

I'm not sure what your asking for.  Are you having problems installing SimpleSAMLphp on your IIS server or do you have it installed and you're trying to configure MRBS? 

Cheers,
Gergama

**Comment by BrzIGH** [comment]
I have installed MRBS and need some guidance on how to configure SAML authentication.

We need to migrate from LDAP authentication.


Thanks



Goran
________________________________

**Comment by Gergama** [comment]
Hi Goran,

Our SAML environment is managed by our central IT unit, so I can't be of much help with those specifics.  After I had MRBS installed, I asked our central IT folk to release the following identity attributes (e.g., username, emailaddress, etc.) from SAML for use in MRBS.  These can vary according to how SAML is setup.  I then adjusted the /web/config.php file to make them accessible to MRBS (see below).

Hope this helps,
Allan

/***********************************************
 * Authentication settings - read AUTHENTICATION
 ***********************************************/

$auth["type"] = "saml"; // How to validate the user/password.
$auth["session"] = "saml"; // How to get and keep the user ID.

// 'auth_saml' configuration settings
// (assuming Active Directory attributes):
$auth['saml']['ssp_path'] = $_SERVER['DOCUMENT_ROOT'].'/simplesamlphp_book';  // must be an absolute and not a relative path
$auth['saml']['authsource'] = 'default-sp';
$auth['saml']['attr']['username'] = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/username';
$auth['saml']['attr']['email'] = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress';
$auth['saml']['attr']['givenName'] = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname';
$auth['saml']['attr']['surname'] = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname';

// MRBS session initialisation can interfere with session handling in some
// SAML libraries.  If so, set this to true.
$auth['saml']['disable_mrbs_session_init'] = false;

**Comment by BrzIGH** [comment]
Thanks !

That looks fairly straight-forward. The part I was concerned with is the simplesaml config part mentioned in the docs.

Can you please confirm that you did not touch that ?

Thanks again.

**Comment by Gergama** [comment]
No, I didn't have to change anything in the AuthSaml.php file.

**Comment by BrzIGH** [comment]
The documentation states the following:

SAML Authentication
-------------------

Set in config.inc.php

$auth['type'] = 'saml';
$auth['session'] = 'saml';
$auth['saml']['ssp_path'] = '/opt/simplesamlphp';
$auth['saml']['authsource'] = 'default-sp';
$auth['saml']['attr']['username'] = 'sAMAccountName';
$auth['saml']['attr']['mail'] = 'mail';
$auth['saml']['admin']['memberOf'] = ['CN=Domain Admins,CN=Users,DC=example,DC=com'];

This scheme assumes that you've already configured SimpleSamlPhp,
and that you have set up aliases in your webserver so that SimpleSamlPhp
can handle incoming assertions.  Refer to the SimpleSamlPhp documentation
for more information on how to do that.

https://simplesamlphp.org/docs/stable/simplesamlphp-install
https://simplesamlphp.org/docs/stable/simplesamlphp-sp

Can you confirm that you did not do anything mentioned in the bolded paragraph ?

**Comment by BrzIGH** [comment]
Did you do anything described in the following text (bolded):

**This scheme assumes that you've already configured SimpleSamlPhp,
and that you have set up aliases in your webserver so that SimpleSamlPhp
can handle incoming assertions.  Refer to the SimpleSamlPhp documentation
for more information on how to do that.

https://simplesamlphp.org/docs/stable/simplesamlphp-install
https://simplesamlphp.org/docs/stable/simplesamlphp-sp**

Thanks

**Comment by Gergama** [comment]
No, SimpleSAMLphp was set-up by our central IT department.  I don't believe there was anything they had to change in the standard SimpleSAMLphp configuration specifically for MRBS authentication other than exposing the identify attributes.

Cheers,
Allan

**Comment by BrzIGH** [comment]
Hi Allan, 

can you please put me in touch with whoever set up SimpleSAML.php for you ? I coudl use their help on setting up SimpleSAML on IIS10.

Thanks

**Comment by jberanek** [comment]
> Hi Allan,
> 
> can you please put me in touch with whoever set up SimpleSAML.php for you ? I coudl use their help on setting up SimpleSAML on IIS10.
> 
> Thanks

I'd say you be best off following https://simplesamlphp.org/support/

**Comment by Gergama** [comment]
Hi Goran,

Unfortunately, that would be out of scope service for our central IT Service unit.  If you need help specifically with installing and configuring SimpleSAMLphp, I agree with John Beranek and recommend contacting the SimpleSAMLphp support forum directly.  It appears they have a very active support group to help users.  https://simplesamlphp.org/support/ 

Allan

**Comment by BrzIGH** [comment]
Fair enough. Thanks
