### ISSUE TITLE
Cell Height in Week Monthly View

### ISSUE THREAD

**Issue by bladeHP** [meeting-room-booking-system/mrbs-code#3467]
HI,
How can I increase the height of the cells only in the weekly and monthly view?
the daily one is fine like this.

MRBS 1.11.0

Thank you

**Comment by campbell-m** [comment]
Is that for the "all rooms" view in the week and month views?  Or the single room view?

**Comment by bladeHP** [comment]
only for "all rooms" in week and month views

thank you

**Comment by campbell-m** [comment]
Create a custom CSS file (see systemdefaults.inc.php for how to do this) and add the rule

~~~css
.all_rooms tbody th,
.all_rooms tbody td {
  min-height: 4.5em; /* adjust to suit */
}

~~~

**Comment by bladeHP** [comment]
Great!!!

I have one more question: I use MRBS as a calendar to manage technicians, where instead of rooms there are the names of the technicians.
Is it possible to "block" the lunch break or not display the time from 12.30 to 14.00?
I don't want to use the "periods" because then the reports don't add up the hours.

thanks for your time

**Comment by campbell-m** [comment]
The only way to do it is to book out the lunch break with a booking called "Lunch break" or something.  You could additionally give it a type of, say, "Not available".

By the way, in future could you raise a new ticket for a new topic please.  Thanks.

**Comment by bladeHP** [comment]
sorry, you are right, next time I will open a new ticket.

thank you for your time!
