### ISSUE TITLE
Fatal error (uncaught) "Return value of MRBS\get_mrbs_locale() must be of the type string"

### ISSUE THREAD

**Issue by gregaprimc** [meeting-room-booking-system/mrbs-code#3468]
Dear,
when using different browsers to access the MRBS I get a fatal uncaught error: Fatal error: Uncaught TypeError: Return value of MRBS\get_mrbs_locale() must be of the type string, null returned in /volume1/web/mrbs/language.inc:318 Stack trace: #0 /volume1/web/mrbs/language.inc(188): MRBS\get_mrbs_locale('en-GB,en;q=0.5') #1 /volume1/web/mrbs/defaultincludes.inc(30): require_once('/volume1/web/mr...') #2 /volume1/web/mrbs/index.php(8): require('/volume1/web/mr...') #3 {main} thrown in /volume1/web/mrbs/language.inc on line 318.

What seems to be the problem?
I get it on computer as well as mobile (Mozilla and Safari). For now, Edge did not have that problem.
Screenshot computer - ![Screenshot 2023-07-17 122907](https://github.com/meeting-room-booking-system/mrbs-code/assets/139761258/143eadee-cabc-4e61-8f87-de945bece436)

Screenshot phone - ![unnamed](https://github.com/meeting-room-booking-system/mrbs-code/assets/139761258/d17b8fa7-c32e-4a18-97fd-534dfd421f1d)

Accessed via a computer Win 11 (Edge, Mozilla) and iPhone (iOS 16.5.1)
MRBS version 1.11.3 running on Synology NAS, Apache 2.4, PHP 7.4, MySQL database (myPHP).
Kind regards, Gregor

**Comment by campbell-m** [comment]
What have you got the following set to in your config file?

`$override_locale`
`$disable_automatic_language_changing`
`$default_language_tokens`
`$cli_language`

**Comment by campbell-m** [comment]
Thanks. On a browser that fails, what have you got the browser language preferences set to?

**Comment by gregaprimc** [comment]
I tried US and UK (attached screen capture).

V V tor., 18. jul. 2023 ob 10:23 je oseba campbell-m <
***@***.***> napisala:

**Comment by campbell-m** [comment]
[test_locale.zip](https://github.com/meeting-room-booking-system/mrbs-code/files/12083411/test_locale.zip)

Could you run the attached test program in your MRBS folder please (at the same level as config.inc.php) and post the output here?  The file is zipped to keep GitHub happy, so you'll need to unzip it first.  The output should look something like this:

~~~text
Locale test
intl extension loaded: true
$disable_automatic_language_changing: false
$default_language_tokens: en
$cli_language: en
$override_locale:
HTTP_ACCEPT_LANGUAGE: en-GB,en;q=0.9,pt-BR;q=0.8,pt;q=0.7,vi;q=0.6,zh-CN;q=0.5,zh;q=0.4,ru;q=0.3,de-CH;q=0.2,de;q=0.1,ar;q=0.1,ko;q=0.1,en-AU;q=0.1,uz;q=0.1,es-MX;q=0.1,es;q=0.1,ga;q=0.1,sr;q=0.1,hy;q=0.1,ku;q=0.1,en-US;q=0.1,gl;q=0.1,ca;q=0.1
$aliased_header: en-GB,en;q=0.9,pt-BR;q=0.8,pt;q=0.7,vi;q=0.6,zh-CN;q=0.5,zh;q=0.4,ru;q=0.3,de-CH;q=0.2,de;q=0.1,ar;q=0.1,ko;q=0.1,en-AU;q=0.1,uz;q=0.1,es-MX;q=0.1,es;q=0.1,ga;q=0.1,sr;q=0.1,hy;q=0.1,ku;q=0.1,en-US;q=0.1,gl;q=0.1,ca;q=0.1
Line 329
en-GB
Converted to BCP47: en-GB
$locale: en-GB
~~~

**Comment by gregaprimc** [comment]
Hi, thanks for the help and sure the output is here:

Locale test
intl extension loaded: false
$disable_automatic_language_changing: false
$default_language_tokens: en
$cli_language: en
$override_locale:
HTTP_ACCEPT_LANGUAGE: en-GB,en;q=0.5
$aliased_header: en-GB,en;q=0.5
Line 329

Converted to BCP47:
Fatal error: Uncaught TypeError: Return value of MRBS\get_mrbs_locale()
must be of the type string, null returned in
/volume1/web/mrbs/test_locale.php:346 Stack trace: #0
/volume1/web/mrbs/test_locale.php(207):
MRBS\get_mrbs_locale('en-GB,en;q=0.5') #1 {main} thrown in
/volume1/web/mrbs/test_locale.php on line 346

V V tor., 18. jul. 2023 ob 18:14 je oseba campbell-m <
***@***.***> napisala:

**Comment by campbell-m** [comment]
I've now fixed this in [1422e7b](https://github.com/meeting-room-booking-system/mrbs-code/commit/1422e7b6206055f2974dfd1635381ad5c1e0e576).  Please could you confirm.

**Comment by campbell-m** [comment]
I think the problem was occurring because I suspect you don't have the 'en' or 'en-GB' locales installed on your server.

**Comment by gregaprimc** [comment]
Hi, there is no fatal error anymore; however, under Firefox, there are
still some issues. See attached screenshot - this is the landing page. I
can access Rooms and other menus, but the calendar does not appear on the
main page. Under Edge, it still works.

V V sre., 19. jul. 2023 ob 11:55 je oseba campbell-m <
***@***.***> napisala:

**Comment by campbell-m** [comment]
Did you forget the screenshot?

**Comment by gregaprimc** [comment]
Ammm, no, it was attached. Here it is once more. The filename is
"Screenshot 2023-07-24 092307.png". Did you get it?

V V pon., 24. jul. 2023 ob 10:01 je oseba campbell-m <
***@***.***> napisala:

**Comment by campbell-m** [comment]
No, there's no screenshot.  I think it may be that you need to login to GitHub rather than reply by email.

**Comment by gregaprimc** [comment]
I guess the system removes it. Here it is, hopefully ... posting on GitHub.
![Screenshot 2023-07-24 092307](https://github.com/meeting-room-booking-system/mrbs-code/assets/139761258/a5dcfacb-4e0c-4af8-b762-f5ccad7f70c3)

**Comment by campbell-m** [comment]
You're getting that message because you haven't got the 'en' or 'en-GB' locales installed on your server.  You either need to install one of those locales or else set `$override_locale` to a locale that is installed.   You can find out what locales are installed using `locale -a` or else seeing which language a browser that works uses.   You can see the browser language preferences on the MRBS Help page.
