### ISSUE TITLE
rotate text in week ad month view

### ISSUE THREAD

**Issue by bladeHP** [meeting-room-booking-system/mrbs-code#3469]
Hi,
how i can rotate (vertical) description text in week and month view only for "all rooms"

Thank You

**Comment by campbell-m** [comment]
Add the custom CSS rule:

~~~css
.all_rooms tbody td a div {
  transform: rotate(-90deg);
}
~~~

**Comment by bladeHP** [comment]
Thank you,
unfortunately this way the cell is also rotated, is it possible to rotate only the text?

Thank You

**Comment by campbell-m** [comment]
Sorry, try

~~~css
.all_rooms tbody td a div {
  writing-mode: vertical-rl;
  text-orientation: mixed;
}
~~~

**Comment by bladeHP** [comment]
unfortunately this doesn't work, in the sense that the text is not turned.
I tried with a new browser session and private browsing.

tested with chrome and firefox

**Comment by campbell-m** [comment]
![rotate](https://github.com/meeting-room-booking-system/mrbs-code/assets/87438215/84efa60c-aa1b-4101-8806-426d27349961)

This is what I am getting.  Are you not seeing the same thing?

**Comment by bladeHP** [comment]
sorry morrison, i was probably doing something wrong...
now it works perfectly
I modified like this:

.all_rooms tbody td a div {
  writing-mode: vertical-rl;
  transform: rotate(180deg);
}

Thank you
