### ISSUE TITLE
Date Picker Getting Stuck Loading

### ISSUE THREAD

**Issue by crookja** [meeting-room-booking-system/mrbs-code#3472]
I have updated from version 1.10.0 to 1.11.0 and 1.11.3,

Everything works fine in 1.10.0 but if I install any later version it gets stuck 'Loading' when I click on a date in the date picker or change the view to Week or Month

Steps to reproduce the behaviour:
1. Go to mrbs page.
2. Click on the next day in the mini calendar date picker 

**Expected behavior**
Load that dates bookings

**Screenshots**
![Screenshot 2023-07-25 115049](https://github.com/meeting-room-booking-system/mrbs-code/assets/8509704/1be6e8ee-ecfe-4811-8564-0ef8bd7aa83f)

**Browser details (please complete the following information):**
 - Windows 10 
 - Chrome, Edge and firefox

Configuration details
MRBS version	MRBS 1.11.3
Database schema version	82
Database local schema version	1
$auth['type']	none
$auth['session']	nt
Server details
Database	MySQL Community Server - GPL 8.0.17
System	Windows NT E4043S01SV011 10.0 build 17763 (Windows Server 2016) AMD64
Server time	Tuesday, 25 July 2023 at 11:49:29 W. Australia Standard Time
Server software	Microsoft-IIS/10.0
PHP	7.2.19
Extensions	Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom, exif, filter, gd, gettext, hash, iconv, imap, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, soap, standard, tidy, tokenizer, wddx, wincache, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib

**Comment by campbell-m** [comment]
Can you check that all the sources loaded?  This would be the result if js/refresh.js.php hadn't loaded.

**Comment by crookja** [comment]
Doesn't look like js/refresh.js.php has loaded as you said, why would this be happening? Something to do with my config?

![Screenshot 2023-07-26 074304](https://github.com/meeting-room-booking-system/mrbs-code/assets/8509704/925d891a-9e04-4213-937f-5f473bcef26a)

**Comment by crookja** [comment]
I have found it doesn't load if I go to http://mrbs-test/ but if I go to http://mrbs-test/index.php it works.

IIS as the default document set as Index.php I don't know why this is occurring.

**Comment by campbell-m** [comment]
What happens if you set the default document to "index.php" (lower case)?

**Comment by crookja** [comment]
That fixed it, weirdly case-sensitive. Thanks for your great support, love MRBS been using it for many years.
