### ISSUE TITLE
warning and Fatal error - MRBS 

### ISSUE THREAD

**Issue by shiju4224** [meeting-room-booking-system/mrbs-code#3473]
Warning: require_once(config.inc.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\mrbs\web\defaultincludes.inc on line 25

Fatal error: Uncaught Error: Failed opening required 'config.inc.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\mrbs\web\defaultincludes.inc:25 Stack trace: #0 C:\xampp\htdocs\mrbs\web\index.php(8): require() #1 {main} thrown in C:\xampp\htdocs\mrbs\web\defaultincludes.inc on line 25

**Comment by shiju4224** [comment]
can you please provide the config.inc.php file

**Comment by campbell-m** [comment]
See the instructions in the INSTALL document.

**Comment by shiju4224** [comment]
now i install the config.inc.php file the below error is showing

please check with below link
(https://github.com/meeting-room-booking-system/mrbs-code/assets/126764984/913b30e3-e644-40f4-9ce2-a8299510d0be)

**Comment by campbell-m** [comment]
Have you configured your database details in the config.inc.php file?  You need to set your own details for

~~~php
// Which database system: "pgsql"=PostgreSQL, "mysql"=MySQL
$dbsys = "mysql";
// Hostname of database server. For pgsql, can use "" instead of localhost
// to use Unix Domain Sockets instead of TCP/IP. For mysql "localhost"
// tells the system to use Unix Domain Sockets, and $db_port will be ignored;
// if you want to force TCP connection you can use "127.0.0.1".
$db_host = "localhost";
// If you need to use a non standard port for the database connection you
// can uncomment the following line and specify the port number
// $db_port = 1234;
// Database name:
$db_database = "mrbs";
// Schema name.  This only applies to PostgreSQL and is only necessary if you have more
// than one schema in your database and also you are using the same MRBS table names in
// multiple schemas.
//$db_schema = "public";
// Database login user name:
$db_login = "mrbs";
// Database login password:
$db_password = 'mrbs-password';
// Prefix for table names.  This will allow multiple installations where only
// one database is available
$db_tbl_prefix = "mrbs_";
// Set $db_persist to TRUE to use PHP persistent (pooled) database connections.  Note
// that persistent connections are not recommended unless your system suffers significant
// performance problems without them.   They can cause problems with transactions and
// locks (see http://php.net/manual/en/features.persistent-connections.php) and although
// MRBS tries to avoid those problems, it is generally better not to use persistent
// connections if you can.
~~~

Read the INSTALL document for more details.

**Comment by shiju4224** [comment]
hi,
below mentioned configured database, but again the same error is showing (before shared screen shot). please check and advise.

<?php // -*-mode: PHP; coding:utf-8;-*-
namespace MRBS;

use IntlDateFormatter;

require_once 'lib/autoload.inc';

/**************************************************************************
 *   MRBS Configuration File
 *   Configure this file for your site.
 *   You shouldn't have to modify anything outside this file.
 *
 *   This file has already been populated with the minimum set of configuration
 *   variables that you will need to change to get your system up and running.
 *   If you want to change any of the other settings in systemdefaults.inc.php
 *   or areadefaults.inc.php, then copy the relevant lines into this file
 *   and edit them here.   This file will override the default settings and
 *   when you upgrade to a new version of MRBS the config file is preserved.
 *
 *   NOTE: if you include or require other files from this file, for example
 *   to store your database details in a separate location, then you should
 *   use an absolute and not a relative pathname.
 **************************************************************************/

/**********
 * Timezone
 **********/

// The timezone your meeting rooms run in. It is especially important
// to set this if you're using PHP 5 on Linux. In this configuration
// if you don't, meetings in a different DST than you are currently
// in are offset by the DST offset incorrectly.
//
// Note that timezones can be set on a per-area basis, so strictly speaking this
// setting should be in areadefaults.inc.php, but as it is so important to set
// the right timezone it is included here.
//
// When upgrading an existing installation, this should be set to the
// timezone the web server runs in.  See the INSTALL document for more information.
//
// A list of valid timezones can be found at http://php.net/manual/timezones.php
// The following line must be uncommented by removing the '//' at the beginning
$timezone = "Asia/Dubai";


/*******************
 * Database settings
 ******************/
// Which database system: "pgsql"=PostgreSQL, "mysql"=MySQL
$dbsys = "mysql";
// Hostname of database server. For pgsql, can use "" instead of localhost
// to use Unix Domain Sockets instead of TCP/IP. For mysql "localhost"
// tells the system to use Unix Domain Sockets, and $db_port will be ignored;
// if you want to force TCP connection you can use "127.0.0.1".
$db_host = "localhost";
// If you need to use a non standard port for the database connection you
// can uncomment the following line and specify the port number
// $db_port = 1234;
// Database name:
$db_database = "mrbs";
// Schema name.  This only applies to PostgreSQL and is only necessary if you have more
// than one schema in your database and also you are using the same MRBS table names in
// multiple schemas.
//$db_schema = "public";
// Database login user name:
$db_login = "root";
// Database login password:
$db_password = '12345';
// Prefix for table names.  This will allow multiple installations where only
// one database is available
$db_tbl_prefix = "mrbs_";
// Set $db_persist to TRUE to use PHP persistent (pooled) database connections.  Note
// that persistent connections are not recommended unless your system suffers significant
// performance problems without them.   They can cause problems with transactions and
// locks (see http://php.net/manual/en/features.persistent-connections.php) and although
// MRBS tries to avoid those problems, it is generally better not to use persistent
// connections if you can.
$db_persist = false;


/* Add lines from systemdefaults.inc.php and areadefaults.inc.php below here
   to change the default configuration. Do _NOT_ modify systemdefaults.inc.php
   or areadefaults.inc.php.  *

**Comment by shiju4224** [comment]
[db.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/12168840/db.txt)

**Comment by campbell-m** [comment]
Are you sure that the database details are correct?

**Comment by shiju4224** [comment]
yes, 
can u please check with the same DB to your end.
is any additional code is required ???
or please share any video link or anything to learn more about the MRBS application

**Comment by shiju4224** [comment]
hi,
i make new DB , DB name is mrbs and import table.my sql file. it successfully add.
then change $db_host, $db_database, $db_port, $db_login and $db_password
but now this error is showing
E_USER_WARNING in C:\xampp\htdocs\mrbs\web\lib\MRBS\DB.php at line 108
please check and help me
thanks

**Comment by campbell-m** [comment]
I think one or more of $db_host, $db_database, $db_port, $db_login and $db_password will be wrong.

**Comment by shiju4224** [comment]
can u please connect through remote support and check ??

**Comment by campbell-m** [comment]
Sorry, I don't have time to connect through remote support.   Your config file should work if the database details are correct.  Try setting `$db_host` to "127.0.0.1" instead of "localhost" to see if that makes a difference.  Also, what have you got `$db_port` set to, if anything?

**Comment by shiju4224** [comment]
hi,
can u please share exact process to implement this application.
i try to all possible way its show 
E_USER_WARNING in C:\xampp\htdocs\mrbs\web\lib\MRBS\DB.php at line 108
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it
MRBS GET: Array
(
)
MRBS POST: Array
(
)

please help me 

Thanks

**Comment by campbell-m** [comment]
What have you got `$db_port` set to, if anything?

**Comment by shiju4224** [comment]
i already add the $db_port, but the page cannot load.
please find the attached file for your reference, please check and help me
if u want remote i will share to you

[error3.pdf](https://github.com/meeting-room-booking-system/mrbs-code/files/12179712/error3.pdf)
[config.pdf](https://github.com/meeting-room-booking-system/mrbs-code/files/12179713/config.pdf)
[error 4.pdf](https://github.com/meeting-room-booking-system/mrbs-code/files/12179714/error.4.pdf)

**Comment by campbell-m** [comment]
Is your database server on a different machine to your web server?  If so, you should check that your database server has been configured to allow remote access from your particular web server.

**Comment by shiju4224** [comment]
No, database and web server is in same machine.

**Comment by campbell-m** [comment]
OK.  Then is there any reason why you are not using "localhost" for `$db_host` instead of the IP address?

**Comment by shiju4224** [comment]
No, there is no particular reason.
i  follow you posted videos and doing the configuration 
can u please edit and share the  config file where the changes required.

**Comment by campbell-m** [comment]
Try setting

~~~php
$db_host = "localhost";
~~~

**Comment by shiju4224** [comment]
Same error is showing.

this s my any-desk Id :322841139
please check and help
[error 6.pdf](https://github.com/meeting-room-booking-system/mrbs-code/files/12180036/error.6.pdf)
[error 5.pdf](https://github.com/meeting-room-booking-system/mrbs-code/files/12180037/error.5.pdf)

**Comment by campbell-m** [comment]
Make sure the encoding of your config.inc.php file is UTF-8.

**Comment by shiju4224** [comment]
yes, its UTF-8
[error 7.pdf](https://github.com/meeting-room-booking-system/mrbs-code/files/12180393/error.7.pdf)

**Comment by campbell-m** [comment]
Can you verify that the username and password are correct by logging in from the command line or another application?

**Comment by shiju4224** [comment]
is it possible to share any working project with you, i want to cross check the errors.

**Comment by campbell-m** [comment]
Everything looks OK.  The problem is that MySQL is refusing your connection.  Things to try are:

1. Check the port number.  Is 3307 correct?  3306 is the default, though 3307 is common.
2. Have you granted the user privileges?
3. Search the internet for solutions. For example, look at [this thread](https://stackoverflow.com/questions/668275/cant-connect-to-mysql-with-php).

**Comment by campbell-m** [comment]
I haven't heard anything more, so assume this issue has now been resolved.
