### ISSUE TITLE
Not recognising admin users.

### ISSUE THREAD

**Issue by crookja** [meeting-room-booking-system/mrbs-code#3475]
MRBS is not recognising admin users. Using the below config worked in previous version 1.10 now not recognising these users as admin in version 1.11.3 (not the real e-numbers in the post).

$auth["type"] = "none";
$auth["session"] = "nt";

unset($auth["admin"]);
$auth["admin"][] = "e0000001";		// User1 
$auth["admin"][] = "e0000002";		// User2 
$auth["admin"][] = "e0000003";		// User3 
$auth["admin"][] = "e0000004";		// User4

**Comment by campbell-m** [comment]
I've just tested this and can't reproduce it.  Is MRBS recognising a user, eg "e0000001", even though it is not recognising them as an admin?  What is the username in the top right hand corner?

**Comment by campbell-m** [comment]
I haven't heard anything more, so assume this issue has now been resolved.
