### ISSUE TITLE
Update Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by brunocalado** [meeting-room-booking-system/mrbs-code#3476]
I have updated the Brazilian Portuguese translation for the project and would like to share the updated file with the community.

[lang.pt-br.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/12186065/lang.pt-br.txt)

**Comment by campbell-m** [comment]
Many thanks.  Now committed in [3e202fe](https://github.com/meeting-room-booking-system/mrbs-code/commit/3e202fe51cb6c5c32c7d09da25f4f6ece16abffc).
