### ISSUE TITLE
Nginx Server Conf

### ISSUE THREAD

**Issue by unclesam87** [meeting-room-booking-system/mrbs-code#3478]
**Describe the problem you're facing/question you have**
I am trying to build up an mrbs system on an nginx webserver, but not been able to open the webpage properly.
Getting 404 and 403 Errors, logs of nginx dont show anything at the moment related to that problem.
chmod of directory is 750, files are 640, owner is www-data (standard user for nginx)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Chrome, Edge

**Server details (please complete the following information):**
 - MRBS version 1.11,3
 - Web server: Nginx
 - OS: Debian 11
 - PHP version: 8.0 FPM
 - Database used: MariaDB 10.x

my serverconf file looks like that at the moment:
```
server {
    listen 80;

    server_name name of server;

    rewrite ^ https://name-server$request_uri? permanent;
}

server {
    listen 443 ssl http2;

    ssl_certificate /etc/letsencrypt/live/servername/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/servername/privkey.pem;
    ssl_stapling on;

    server_name servername;

    root /var/www/servername

    location / {
        try_files $uri /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }
}

```

**Comment by campbell-m** [comment]
What happens if you have a simple index.php consisting of

~~~php
<?php
echo "Hello World";
~~~

**Comment by campbell-m** [comment]
Are they index.php pages that you are running successfully?

**Comment by unclesam87** [comment]
sorry for the late response: yes there are several index.phps that are working

**Comment by campbell-m** [comment]
Are you getting any error messages in your PHP error log?

**Comment by campbell-m** [comment]
I haven't heard anything more, so assume this issue has now been resolved.
