### ISSUE TITLE
MRBS requires MariaDB version 10.0.2 or higher.

### ISSUE THREAD

**Issue by LaBraeTech** [meeting-room-booking-system/mrbs-code#3481]
I am running 5.5.68-MariaDB.  The README says the minimum requirement is "MySQL (5.5.3 and above) or PostgreSQL 8.2 or above."  When upgrading from 1.10.0 to 1.11.3 I get the message "MRBS requires MariaDB version 10.0.2 or higher. This server is running version 5.5.68."

At the beginning of INSTALL it says: "MRBS works with both MySQL (Version 5.5.3 and above, though MySQL Version
5.7.5 and above or MariaDB Version 10.0.2 and above are recommended) and
PostgreSQL (Version 8.2 and above) systems.  [The reason that if you are using
MySQL you are recommended to use MySQL Version 5.7.5 and above or MariaDB
Version 10.0.2 and above is that these versions support multiple locks and thus
enable MRBS to use a custom database session handler.  This is more secure than
the standard file based session handler, easier to configure and enables MRBS
to be used on clustered web servers.]"  

How can get I MRBS working with 5.5.68, or is the minimum requirements really 10.0.2?  

**Server details (please complete the following information):**
 - MRBS version 1.11.3
 - OS: CentOS 7
 - Database used: 5.5.68-MariaDB

**Comment by campbell-m** [comment]
Sorry, I think this is a bug in MRBS.  I think the minimum version of MariaDB required is 5.5.3, though 10.0.2 is necessary if you want to use the custom database session handler, instead of PHP's default files based handler.  To fix it change line 32 of lib/MRBS/DB_mysql.php from 

~~~php
~~~

to

~~~php
~~~

I'll commit a fix.

**Comment by campbell-m** [comment]
Finger trouble in the last comment - I've now edited it.

**Comment by campbell-m** [comment]
Fixed in [d6e2f70](https://github.com/meeting-room-booking-system/mrbs-code/commit/d6e2f70fb659a38267c49d266a7e6b79b78c43b7).

**Comment by LaBraeTech** [comment]
How do you use PHP's default files based handler instead of the custom database session handler?

**Comment by campbell-m** [comment]
MRBS will do it automatically.

**Comment by jberanek** [comment]
You really should get off MariaDB 5.5 though...
![Screenshot_20230802-212306~2](https://github.com/meeting-room-booking-system/mrbs-code/assets/571708/4203c604-4f2f-4298-b5e6-cba4a74c8436)
