### ISSUE TITLE
restrict rooms booking by individual user

### ISSUE THREAD

**Issue by antham1616** [meeting-room-booking-system/mrbs-code#3482]
is it possible to restrict rooms booking by individual user

for example 

room 1: all users
room 2: admins
room 3: admins + user(***)

thanks in advance

**Comment by campbell-m** [comment]
You'll need to modify the MRBS code, in particular the function `getWritable()` in mrbs_auth.inc.

**Comment by iamsumesh** [comment]
@antham1616 please let me know, if you found solution for this.

**Comment by antham1616** [comment]
iam

> @antham1616 please let me know, if you found solution for this.

hi this worked for me

https://github.com/meeting-room-booking-system/mrbs-code/issues/3146

**Comment by embeh** [comment]
FYI I just created a feature request for this: #3509
