### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by antham1616** [meeting-room-booking-system/mrbs-code#3483]
what is required to setup multisite? and how does it work? (ie. is there a dropdown for which site is used?)

Many thanks

**Comment by campbell-m** [comment]
See the section on Multisite in the INSTALL document, which I've just made clearer in [7cc0d94](https://github.com/meeting-room-booking-system/mrbs-code/commit/7cc0d94d12e1e9c36d296cbfa20010baa7cc665d).

There isn't a drop-down (though you could construct one on another page).  Instead the sites
are reached by specifying the sitename in the query string, eg `index.php?site=sitename`.
