### ISSUE TITLE
limit periods by room not period

### ISSUE THREAD

**Issue by antham1616** [meeting-room-booking-system/mrbs-code#3484]
Hi, would it be possible to limit available periods by room rather than area? or would it be possible to show multiple areas in the calendar view as if they were rooms?

maybe a js function on view?

**Comment by antham1616** [comment]
the principle is if i made one area called service for example

which had 3 rooms:
1 that would be availbe for 6 sessions a day
1 that would be availbe for 4 sessions a day
1 that would be availbe for 2 sessions a day

rather than having to book it out for all the slots/periods which makes it look like its in use i only wish to show the amount by room not by area

**Comment by campbell-m** [comment]
If you define another type, for example "Unavailable", and use that type when booking the slots out as unavailable, then they will appear in a different colour and not look as though they are in use.
