### ISSUE TITLE
Area selector visible in kiosk mode

### ISSUE THREAD

**Issue by pmonstad** [meeting-room-booking-system/mrbs-code#3486]
Running 1.11.1 in kiosk mode the area selector is visible. Should not be visable at all, I guess as it confuse users.

**Comment by pmonstad** [comment]
Possible to hide it with a css tweak?

**Comment by campbell-m** [comment]
Create a custom CSS file (see systemdefaults.inc.php for how) and add the rule

~~~css
nav.main_calendar > nav {
  display: none;
}
~~~

**Comment by pmonstad** [comment]
Thanks!

**Comment by pmonstad** [comment]
Hm, no it doea not work as expected. I want to hide the selector in kiosk mode but is hide in standard mode as well.

**Comment by campbell-m** [comment]
Oh, sorry.  Try

~~~css
body[data-kiosk] nav.main_calendar > nav {
  display: none;
}
~~~

**Comment by pmonstad** [comment]
Thanks. Now it works!
