### ISSUE TITLE
connection to database

### ISSUE THREAD

**Issue by rslettebo** [meeting-room-booking-system/mrbs-code#3494]
**Describe the problem you're facing/question you have**
We dont have access to our database.

**Browser details (please complete the following information):**
Windows
Chrome

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]
 - Web server: [e.g. Apache 2.4.48]
 - OS: [e.g. CentOS 7.9]
 - PHP version: 7.4.33
 - Database used: MySQL 5.7.40-cll-lve - MySQL Community Server - (GPL)

**Additional context**
mrbs.salem.no

We get the following error message: 
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aestcvuo_mrbs.table_name' doesn't exist

**Comment by campbell-m** [comment]
Which version of MRBS are you using?  And could you give more details of the error message please including the file and line number that produced it and the stack trace if there was one.

**Comment by rslettebo** [comment]
Where can I find which version we are using?

Here you can find the error message: 
[
www.mrbs.salem.no](url)

**Comment by campbell-m** [comment]
You can find the version number on the MRBS Help page.  If that isn't loading you will find it in the file version_num.inc.

What happens if you set `$debug = true;` in your MRBS config.inc.php file?

**Comment by rslettebo** [comment]
$mrbs_version_number = '1.5.0';

**Comment by campbell-m** [comment]
You are running a very old version of MRBS.   Have you been running it for a while and was it working before?  If so, what has changed?

**Comment by rslettebo** [comment]
Yeah. We implemented it in 2015 and havent changed it before now. But it has been running just fine for all this years. But we newly changed our website-provider. 

Is it possible to get out booking with dates and time from the Phpadmin?

**Comment by campbell-m** [comment]
I would suggest trying to get it working first and then upgrading to the latest release.   Have you transferred your database across to the new server?  Can you add the following two lines to the bottom of the file internalconfig.inc.php and post any error messages here?

~~~php
ini_set('display_errors', '1');
error_reporting(-1);
~~~

**Comment by rslettebo** [comment]
The database is transferred. 

I tried to add the lines and saved changes. But i cant see any error message. Where would i find it?

**Comment by campbell-m** [comment]
I thought you said you had changed your website provider?   Is your website running on a new server?

**Comment by rslettebo** [comment]
Yeah, but we only changed the dns-pointer. So the database is at the same webhotel.

**Comment by campbell-m** [comment]
I haven't heard anything more, so assume this issue is now resolved.

**Comment by rslettebo** [comment]
Hi,

Thanks for email. Everything is now fixed.

Kind regards
Runar

Fra: campbell-m ***@***.***>
Sendt: onsdag 4. oktober 2023 13:25
Til: meeting-room-booking-system/mrbs-code ***@***.***>
Kopi: Runar Wold Slettebø ***@***.***>; Author ***@***.***>
Emne: Re: [meeting-room-booking-system/mrbs-code] connection to database (Issue #3494)


I haven't heard anything more, so assume this issue is now resolved.
