### ISSUE TITLE
a login error with pop3 auth_type

### ISSUE THREAD

**Issue by tli47** [meeting-room-booking-system/mrbs-code#3497]
**Describe the bug**
A PHP Fatal error "Maximum execution time of 30 seconds exceeded in C:\Program Files\mrbs-1.11.3\web\lib\MRBS\Auth\AuthPop3.php on line 95" shows when use a pop3 auth type.

**To Reproduce**
1. Go to systemdefaults.inc.php file and configure it as a pop3 auth
2. Restart Web server
3. login with my email account that saved in pop3 server

**Expected behavior**
Could use email login successfully.

**Screenshots**
Login and Error:
<img width="342" alt="1693362442755" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/26863079/b22b7942-a9b8-454b-adfd-1185b653af08">

<img width="804" alt="1693361697181" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/26863079/3422d9da-6b0b-419f-a127-5308ca16cc1b">

systemdefaults.inc.php:
<img width="663" alt="1693361837891" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/26863079/b8a5f853-e918-47a2-994a-afafd63ba74b">

<img width="463" alt="1693361889014" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/26863079/5406d045-52b2-422a-8a3f-2ca4be9adc8a">

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser Edge/Chrome
 - Version 109.0.1518.115/116.0.5845.111

**Server details (please complete the following information):**
 - MRBS version 1.11.3
 - Web server: windows IIS 
 - OS: windows server 2012 R2 Datacenter Build 9600
 - PHP version: php-8.2.9-nts-Win32-vs16-x64
 - Database used: MySQL Ver 8.0.33 for Win64 on x86_64

**Additional context**
1.This pop3 server could reach in this mrbs server.
2.db auth could work normally.

**Comment by campbell-m** [comment]
What happens if you try authenticating using 'imap_php' or 'imap'?

**Comment by campbell-m** [comment]
I've reduced the timeout on the stream to 15 seconds in [a4f5538](https://github.com/meeting-room-booking-system/mrbs-code/commit/a4f5538972eb2d897d12b4d3dcda3d89de053675).  By default the timeout was 60 seconds, which meant that you were first hitting the maximum PHP execution time of 30 seconds, resulting in a fatal error.

Still, it's probably better to use the 'imap_php' or 'imap' authentication types.

**Comment by tli47** [comment]
@campbell-m Thanks for your reply firstly. Since our email server is POP3 server,so I guess I shouldn't just use "imap" and "imap_php" here? But still have a try, I changed auth type to 'imap' and 'imap_php', both of them showed a maximum timeout...

I saw the commit a4f5538 of reducing time, but maybe just a different timeout message show in my case. In my opion, if in a normal process, 15 seconds auth maybe enough, so what's the probable reason in my case?

**Comment by campbell-m** [comment]
Yes, the fix only avoids the maximum execution time fatal error.  Your connection will still time out.

This is not a bug in MRBS, but probably a problem with your MRBS and or mail server configurations.  I think you can still use 'imap_php' but you should try different port settings and different settings of the following config variables:

~~~php
// 'auth_imap_php' configuration settings
$auth["imap_php"]["hostname"] = "localhost";
// You can also specify any of the following options:
// Specifies the port number to connect to
//$auth["imap_php"]["port"] = 993;
// Use SSL
//$auth["imap_php"]["ssl"] = true;
// Use TLS
//$auth["imap_php"]["tls"] = true;
// Turn off SSL/TLS certificate validation
//$auth["imap_php"]["novalidate-cert"] = true;
~~~

**Comment by tli47** [comment]
@campbell-m 
Thank you, now pop3 auth works for me.
I checked my mail server and my mrbs pop3 server configuration, and changed my port to **110**(maybe this is a default pop3 port), and it works... 

Before, port 465 is from other internal people who told the internal pop3 server port, and maybe that is client port... Don't know the difference between these ports. Anyway, as you said, this is not a bug in MRBS, I'll close this ticket, and thank you again. :thumbsup:
