### ISSUE TITLE
Some expert advice on upgrading from MRBS 1.8 to latest...

### ISSUE THREAD

**Issue by embeh** [meeting-room-booking-system/mrbs-code#3500]
Hey,

we have long and happily been running MRBS 1.8.0 on Ubuntu 20, using Apache 2.4.41, MySQL 8.0.34 and PHP 7.4.3.
Slowly, all of those are getting a bit old so I am thinking of upgrading them all (to Ubuntu 22, MRBS 1.11.3 and whatever is needed in terms of database and PHP).

One special aspect here is that over time, we have accumulated a few customizations to several .inc files (e.g. footer.inc, styling.inc, functions_sessions.inc, session_php.inc, functions_table.inc, functions_view.inc), and to mrbs.css.php, config.inc.php. 
None of them are major changes from what I can see and I could generate patch files for most of them, but given that 1.8.0 is almost three years old, chances are those changes do not directly transfer to the lastest version?

Ideally, I would like to set up a second instance of MRBS and transfer all those changes and then switch to the new one but I am unclear on what I would need to do for this in terms of the database (obviously I would not like to mess up all our existing bookings or cause a longer downtime).

So more concisely, some questions:
- What  are the steps needed to upgrade mrbs from 1.8.0 to 1.11.3?
- What would be the best way to transfer our customizations?
- Can we continue with MySQL, or should we migrate to MariaDB, and if so, how?
- How can I run two mrbs instances at the same time on the same Apache server? One for current use, one for upgrading? May they share the same DB?

So, before I start I wanted to quickly pick your brains on what possible pitfalls there might be? Any advice on how to do this in a smart way? Any do's/dont's with regards to the database or PHP?

Thanks much in advance!

**Comment by campbell-m** [comment]
> What are the steps needed to upgrade mrbs from 1.8.0 to 1.11.3?

The instructions are in the UPGRADE document.  Before you do anything take backups of your database and web folder.

> Can we continue with MySQL, or should we migrate to MariaDB, and if so, how?

MySQL is fine.

> How can I run two mrbs instances at the same time on the same Apache server? One for current use, one for upgrading? May they share the same DB?

I'm afraid you won't be able to because the 1.11.3 database schema is incompatible with the 1.8.0 one.  I would suggest taking a dump of your existing tables and then creating a test system by either importing them into a different database or doing a global replace of the database prefix and then importing the edited dump into the same database.  Then run your 1.11.3 system against the test database and re-apply your customisations.  When you are happy that everything is working, copy your modified 1.11.3 system to your production web folder.

**Comment by campbell-m** [comment]
Obviously  you should have your 1.11.3 test system in a separate web folder

**Comment by embeh** [comment]
> > What are the steps needed to upgrade mrbs from 1.8.0 to 1.11.3?
> 
> The instructions are in the UPGRADE document. Before you do anything take backups of your database and web folder.

Thanks! I did read the UPGRADE but it stops listing any further changes "prior 1.8.0" so I got the impression that maybe no database structure changes were made after that?

Backups are planned, thanks for the reminder.

> I'm afraid you won't be able to because the 1.11.3 database schema is incompatible with the 1.8.0 one. I would suggest taking a dump of your existing tables and then creating a test system by either importing them into a different database or doing a global replace of the database prefix and then importing the edited dump into the same database. Then run your 1.11.3 system against the test database and re-apply your customisations. 

Is there some better way of re-applying them rather than going through each file one by one and manually inserting code, given the step from 1.8.0 to 1.11.3?

Thanks a lot!

**Comment by campbell-m** [comment]
The better way for the future would be to take a fork of MRBS and apply your changes to the fork. Then you will be able to use the GitHub merge tools.
