### ISSUE TITLE
New Menu-Item

### ISSUE THREAD

**Issue by vanfassbender** [meeting-room-booking-system/mrbs-code#3501]
I would like to set another menu entry, but it should only be visible when logged in and only when you are admin. 
Can you help me?

**Comment by antham1616** [comment]
If you are using 1.10.0 or above 
edit your header.inc file on lines 221-228 by adding a row such as this

  $menu_items['rooms'] = 'admin.php';

  if ($auth['type'] == 'db')
  {
    $menu_items['user_list'] = 'edit_users.php';
	**$menu_items['dashboard'] = 'documents.php';**
  }

this will now be seen only by admins

**Comment by vanfassbender** [comment]
Can you also tell me what I need to set that this page can also be viewed only by admin. 
if you know the direct link, then you still come on it.

**Comment by campbell-m** [comment]
If the page is in the MRBS web folder then add the following to the beginning of the file:

~~~php
<?php
namespace MRBS;

require "defaultincludes.inc";

// Check the user is authorised for this page
checkAuthorised(this_page());
~~~

**Comment by vanfassbender** [comment]
when i enter the code, i get a white page.

<img width="944" alt="Bildschirmfoto 2023-09-10 um 16 10 21" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/45555144/3e0b1e34-4baa-4062-9b4d-ee844e91ae06">


![Uploading Bildschirmfoto 2023-09-10 um 16.11.17.png…]()

**Comment by vanfassbender** [comment]
<img width="966" alt="Bildschirmfoto 2023-09-10 um 16 11 17" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/45555144/5a6ea95a-a776-4763-80f9-f942a3de8713">

**Comment by campbell-m** [comment]
You don't need to modify mrbs_auth.inc because the default for unknown pages is 2.

You're getting the white page because you haven't got a closing `?>` tag.  You need

~~~php
<?php
namespace MRBS;

require "defaultincludes.inc";

// Check the user is authorised for this page
checkAuthorised(this_page());

?>
~~~

**Comment by vanfassbender** [comment]
nun erhalte ich diese fehlermeldung
![Uploading Bildschirmfoto 2023-09-10 um 16.37.28.png…]()

**Comment by vanfassbender** [comment]
now i get this error message
<img width="1679" alt="Bildschirmfoto 2023-09-10 um 16 37 28" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/45555144/9ad3e8f0-a748-41e6-ab6f-227dffc67eac">

when I do it without the code, it looks like this by the way 
<img width="1627" alt="Bildschirmfoto 2023-09-10 um 16 39 20" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/45555144/d965a975-0bfb-45ea-92fc-f36ce7712564">

**Comment by campbell-m** [comment]
Have a look in your PHP error log to find out what the error is.  Or else set `$debug = true;` in your config file to display the error in your browser.

**Comment by vanfassbender** [comment]
Uncaught exception 'Error' in /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/history.php at line 184
Class "MRBS\mysqli" not found
#0 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [last_page] => /mrbs/
    [this_page] => /mrbs/history.php
    [csrf_token] => a1a80077d949a63d992f621f890af1247e8d8be61c2c25078377e71ebc25e96e
    [user] => MRBS\User Object
        (
            [username] => fassbender
            [display_name] => fassbender
            [email] => vanessa.fassbender@uk-essen.de
            [level] => 3
            [data:protected] => Array
                (
                    [id] => 1355
                    [password_hash] => $2y$10$WCKM/8E7HSUHe7t9YPy8pe.Cxipz4FwP.OSW4.hsmHHi9VFcIbgbW
                    [timestamp] => 2023-09-10 12:39:25
                    [last_login] => 1694356247
                    [Telefon] => 1279
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

#0 MRBS\generate_backtrace() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:221]
#1 MRBS\output_error() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:264]
#2 MRBS\output_exception_error(object) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:272]
#3 MRBS\exception_handler(object)

E_WARNING in /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc at line 878
Cannot modify header information - headers already sent by (output started at /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/history.php:10)
MRBS GET: Array
(
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [last_page] => /mrbs/
    [this_page] => /mrbs/history.php
    [csrf_token] => a1a80077d949a63d992f621f890af1247e8d8be61c2c25078377e71ebc25e96e
    [user] => MRBS\User Object
        (
            [username] => fassbender
            [display_name] => fassbender
            [email] => vanessa.fassbender@uk-essen.de
            [level] => 3
            [data:protected] => Array
                (
                    [id] => 1355
                    [password_hash] => $2y$10$WCKM/8E7HSUHe7t9YPy8pe.Cxipz4FwP.OSW4.hsmHHi9VFcIbgbW
                    [timestamp] => 2023-09-10 12:39:25
                    [last_login] => 1694356247
                    [Telefon] => 1279
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

#0 MRBS\generate_backtrace() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:221]
#1 MRBS\output_error() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:251]
#2 MRBS\error_handler(2, Cannot modify header information - headers already sent by (output started at /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/history.php:10), /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc, 878)
#3 header(Content-Type: text/html; charset=utf-8) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc:878]
#4 MRBS\http_headers(array) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/Themes/default/header.inc:621]
#5 MRBS\print_theme_header(NULL, true, false) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc:921]
#6 MRBS\print_header(NULL, true) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc:890]
#7 MRBS\print_simple_header() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:297]
#8 MRBS\fatal_error(Oh je! Leider ist in MRBS ein schwerwiegender Fehler aufgetreten. Bitte konsultieren Sie Ihren Systemadministrator.) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:287]
#9 MRBS\exception_handler(object)

E_WARNING in /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc at line 865
Cannot modify header information - headers already sent by (output started at /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/history.php:10)
MRBS GET: Array
(
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [last_page] => /mrbs/
    [this_page] => /mrbs/history.php
    [csrf_token] => a1a80077d949a63d992f621f890af1247e8d8be61c2c25078377e71ebc25e96e
    [user] => MRBS\User Object
        (
            [username] => fassbender
            [display_name] => fassbender
            [email] => vanessa.fassbender@uk-essen.de
            [level] => 3
            [data:protected] => Array
                (
                    [id] => 1355
                    [password_hash] => $2y$10$WCKM/8E7HSUHe7t9YPy8pe.Cxipz4FwP.OSW4.hsmHHi9VFcIbgbW
                    [timestamp] => 2023-09-10 12:39:25
                    [last_login] => 1694356247
                    [Telefon] => 1279
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

#0 MRBS\generate_backtrace() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:221]
#1 MRBS\output_error() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:251]
#2 MRBS\error_handler(2, Cannot modify header information - headers already sent by (output started at /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/history.php:10), /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc, 865)
#3 header(Pragma: no-cache) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc:865]
#4 MRBS\expires_header(0) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc:881]
#5 MRBS\http_headers(array) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/Themes/default/header.inc:621]
#6 MRBS\print_theme_header(NULL, true, false) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc:921]
#7 MRBS\print_header(NULL, true) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc:890]
#8 MRBS\print_simple_header() called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:297]
#9 MRBS\fatal_error(Oh je! Leider ist in MRBS ein schwerwiegender Fehler aufgetreten. Bitte konsultieren Sie Ihren Systemadministrator.) called at [/var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions_error.inc:287]
#10 MRBS\exception_handler(object)

E_WARNING in /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/functions.inc at line 866
Cannot modify header information - headers already sent by (output started at /var/www/vhosts/optimistic-turing.92-205-189-134.plesk.page/httpdocs/mrbs/history.php:10)
MRBS GET: Array
(
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [last_page] => /mrbs/
    [this_page] => /mrbs/history.php
    [csrf_token] => a1a80077d949a63d992f621f890af1247e8d8be61c2c25078377e71ebc25e96e
    [user] => MRBS\User Object
        (
            [username] => fassbender
            [display_name] => fassbender
            [email] => vanessa.fassbender@uk-essen.de
            [level] => 3
            [data:protected] => Array
                (
                    [id] => 1355
                    [password_hash] => $2y$10$WCKM/8E7HSUHe7t9YPy8pe.Cxipz4FwP.OSW4.hsmHHi9VFcIbgbW
                    [timestamp] => 2023-09-10 12:39:25
                    [last_login] => 1694356247
                    [Telefon] => 1279
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

**Comment by campbell-m** [comment]
Looks like a namespace problem.  Try this code instead:

~~~php
<?php
require "defaultincludes.inc";

// Check the user is authorised for this page
\MRBS\checkAuthorised(\MRBS\this_page());
?>
~~~

**Comment by vanfassbender** [comment]
this a awesome! thank you very much! it works!
