### ISSUE TITLE
Booking permission per item or per area

### ISSUE THREAD

**Issue by embeh** [meeting-room-booking-system/mrbs-code#3509]
This is the _one_ feature that we are missing in MRBS (currently version 1.8.0, hopefully upgrading soon):

We have many items in our MRBS; some of them may be booked by **every authenticated user**, while others may only by **booked by a few special** users (more than one, though).

Right now, we use one LDAP group to grant users general permission to add new entries, but this is 'all or nothing'.

Since we are using LDAP authentication, ideally we would be able to define an LDAP group name 'per item' (or 'per area', if that is easier?) that a user needs to be a member of in order to be allowed to create a new entry.

If there are hacks or workarounds to implement this, I am open to suggestions.

Thanks!

**Comment by campbell-m** [comment]
As you are using LDAP you could try out [the roles branch](https://github.com/meeting-room-booking-system/mrbs-code/tree/roles).  This will do what you want as it enables you to assign roles to users and groups and for each role you can define read/write/admin rights per room and user.  However it's still under development, so test it before switching over to using it live.  All feedback welcome.

**Comment by embeh** [comment]
I was not aware of the branch, thank you!

**Comment by campbell-m** [comment]
The branch is still under development and has only really been tested with LDAP.  That said, it may work with 'db' authentication.  However the default permissions are the same as standard MRBS, ie you can write in all areas.  So if you want to stop somebody writing in an area you have to explicitly deny them write access.

(By the way, in future could you raise a new issue for a new topic please?  Thanks)
