### ISSUE TITLE
entry.name is visible for private entries

### ISSUE THREAD

**Issue by basti-schr** [meeting-room-booking-system/mrbs-code#3510]
entry.name is visible in weekly table view, but not in detail view, month view or day view for foreign users. 

This only happens from Version 1.11.2, not in 1.11.1

**To Reproduce**
1. Create a new area and allow private entries in this area
2. Create a new entry and make it private
3. switch the user and select the area/room
4. see that you can see the short description when you are in week view.

**Expected behavior**
Other users other than the creator should not be able to see the short description (entry.name) from private entries.

**Screenshots**

![Bildschirmfoto vom 2023-09-16 22-52-57](https://github.com/meeting-room-booking-system/mrbs-code/assets/17143678/dfbd5ca7-dd79-4ea5-afb7-3dc6acd6018a)
![Bildschirmfoto vom 2023-09-16 22-53-06](https://github.com/meeting-room-booking-system/mrbs-code/assets/17143678/c89d3272-7504-4b9e-ac30-93f3f087fbc2)

**Browser details (please complete the following information):**
- any (tested with FF 117.0b9)

**Server details (please complete the following information):**
 - MRBS version [from 1.11.2]
 - Web server: [Apache/2.4.53 ]
 - OS: [e.g. CentOS 7.9]
 - PHP version: [8.1]
 - Database used: [MySQL 8.0.32]

**Additional context**
I reproduced on the demo server in the _dud_ area.

**Comment by campbell-m** [comment]
Thanks for spotting this.  Now fixed in [8d7d7c2](https://github.com/meeting-room-booking-system/mrbs-code/commit/8d7d7c2dcb455557f9c418fede0e33a7caed64f7).

**Comment by basti-schr** [comment]
Thank you for fixing this so quickly! :rocket:
