### ISSUE TITLE
Tables aren't sorted according to locale

### ISSUE THREAD

**Issue by Langveisfra** [meeting-room-booking-system/mrbs-code#3518]
<img width="305" alt="image" src="https://github.com/meeting-room-booking-system/mrbs-code/assets/132160113/241d703a-f02b-4cbc-8971-910d32d929f2">

In version 1.11.4 tables are not sorting according to the language given by the browser or variables language selection.
In Norwegian the last letters of the alphabet are (in sorted order):
X
Y
Z
Æ
Ø
Å

Also "aa" is sorted as "å".

Enclosed is the user table with an erratic sorting order.
$override_locale = "nb-NO";

**Comment by campbell-m** [comment]
#3522 should fix the issue for the Name and Username columns in the Users table and also the Room Name column in the Rooms table.  However there are other columns still not sorted properly in these and other tables and I'll try and gradually work through them.

**Comment by campbell-m** [comment]
I think I've now fixed all the tables so that they respect the chosen locale.  However if you spot any columns that aren't being sorted properly please re-open this ticket.

**Comment by Langveisfra** [comment]
Great Campbell! I'll give it a try tomorrow!

**Comment by Langveisfra** [comment]
Tested. Seems fine. Thank you Campbell!
