### ISSUE TITLE
MRBS version 1.11.0- how to set "To request bookings for this area please email" 

### ISSUE THREAD

**Issue by meklulose** [meeting-room-booking-system/mrbs-code#3524]
**Describe the problem you're facing/question you have**
We had an older version of MRBS where we can set email address and it would show up in the browser under "To request bookings for this area please email:". How do I set this is MRBS version 1.11.0? We have migrated the database from the older version but can't see the email populated in the browser. And I can't find where I can make "To request bookings for this area please email:" show up.

**Browser details (please complete the following information):**
 - Browser- chrome

**Server details (please complete the following information):**
 - MRBS version 1.11.0
 - Web server: nginx
 - PHP version:  7.4.33
 - Database used: MySQL

**Additional context**
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/81180944/35452905-7969-4fd1-937a-882bd1ea6640)

**Comment by campbell-m** [comment]
Somebody must have made some custom changes to your installation of MRBS in the past, as that message has never been in the product.   If you want it back again you'll need to modify the code again, but it's not trivial as presumably the contact information should change when you select a new area.
