### ISSUE TITLE
Admin approval not showing MRBS 1.11.4

### ISSUE THREAD

**Issue by sakhoojee** [meeting-room-booking-system/mrbs-code#3530]
I am using MRBS 1.11.4 and i cannot approve reject bookings there is no indication available on display

as in previous version i can see notification on my dashboard and can allow and reject bookings please help me to resolve this issue.
 
i have attached both screen shorts as reference 

![Screenshot 2023-10-05 140057](https://github.com/meeting-room-booking-system/mrbs-code/assets/126671405/6c74b07e-5209-4270-8829-0e7f33db4dd9)
![Screenshot 2023-10-05 140152](https://github.com/meeting-room-booking-system/mrbs-code/assets/126671405/40f05647-1497-446a-962e-7b31190c4276)

**Comment by campbell-m** [comment]
What was the version number of the previous version?  Are both versions using the same config file and are they both using the same database tables?  Have you made any changes to the code of either version?

**Comment by sakhoojee** [comment]
I just copy old version config file and system default file in new version
MRBS.

**Comment by campbell-m** [comment]
You should not copy the old systemdefaults.inc.php file to the new version.   Can you use the new systemdefaults.inc.php file please?  (If you had made any changes to the systemdefaults file you should make those changes to the config file instead).

**Comment by sakhoojee** [comment]
Dear campbell-m

thank you for your help now i am able to send email through gmail smtp
backend mail but unfortunately still not receiving admin notifications and
approved and reject page even now i am not receiving notifications on old
version too please help me to resolved this issue.

kind regards.

**Comment by campbell-m** [comment]
What was the old version number?  Had you made any changes to it?  And have you made any changes to the new version?  And are they both using the same database tables?

**Comment by sakhoojee** [comment]
Thankyou for prompt reply, i am using  MRBS 1.10.0 and new latest is  MRBS
1.11.4 with same database which is installed locally, i just copy new
version on xampp htdocs folder and copy old config file and system default
file to new version of MRBS,
and also please guide me that what is the proper way of updating version of
MRBS.

**Comment by campbell-m** [comment]
The proper way of updating is described in the UPGRADE document.

You should not copy across the old systemdefaults.inc.php file to the new version.  You should use the version that comes with the new release.  You should not make any changes to systemdefaults.inc.php.  If you need to change any settings you should put the new settings in config.inc.php, which overrides systemdefaults.inc.php.

**Comment by campbell-m** [comment]
Has this now been resolved?

**Comment by sakhoojee** [comment]
Yes, it's done.
