### ISSUE TITLE
Custom CSS to this text

### ISSUE THREAD

**Issue by newtonpal** [meeting-room-booking-system/mrbs-code#3536]
Hello 
I need help to create a custom css field to the text in the attach.
I have this but doesn't work
Thanks!

form#**get_new_password** p {
  max-width: 170rem;
  font-size: larger;
  line-height: 2rem;

![Screenshot 2023-10-15 at 19-11-33 Reserva de Espaços e Equipamentos](https://github.com/meeting-room-booking-system/mrbs-code/assets/147189164/f890d4fc-ad71-45b3-beb0-53ab157479a6)

**Comment by campbell-m** [comment]
It's not working because there's no `form#get_new_password`.  Try

~~~css
.reset_password p {
  max-width: 170rem;
  font-size: larger;
  line-height: 2rem;
}
~~~

**Comment by newtonpal** [comment]
Thanks @campbell-m 
It works. Thanks for the excellent resource!
Have an excellent day!
