### ISSUE TITLE
Change Log Off Action

### ISSUE THREAD

**Issue by theuntoldmomente** [meeting-room-booking-system/mrbs-code#3537]
Hi, I am using ADFS to store user session and I do not want to change because everything is working fine except, I cannot kill the session from MRBS. Thus, I decided to redirect user to our $mrbs_company_url when user click the 'Log Off' button to let them get out of the system, even they are not actually logged out. How do I achieve this?

**Comment by campbell-m** [comment]
The best thing to do is to write a class, eg lib/MRBS/Session/SessionADFS that extends SessionWithLogin and then override the `logoffUser() method`.  You might also need an AuthADFS class.

**Comment by theuntoldmomente** [comment]
Already implemented that. Thanks!
