### ISSUE TITLE
Unable to send email notification

### ISSUE THREAD

**Issue by lamdhoang** [meeting-room-booking-system/mrbs-code#3539]
Hi, I have been modifying codes to test how emails will be sent to the recipients. However, it always raises the following error:

![Screenshot 2023-10-17 152442](https://github.com/meeting-room-booking-system/mrbs-code/assets/146929385/16bc4d81-cf85-4a15-9ce4-fa028bf12ae4)

Would you mind checking the errors and making some code suggestions? Here is the code for your reference 

$mail_settings['from'] = 'from_admin@gmail.com';     //larry.d.hoang
$mail_settings['use_from_for_all_mail'] = true;
$mail_settings['use_reply_to'] = true;
$mail_settings['organizer'] = '';
$mail_settings['recipients'] = 'from_admin@gmail.com';     //larry.d.hoang
$mail_settings['cc'] = 'another_email@gmail.com';         //hoangduclam1309
$mail_settings['treat_cc_as_to'] = true;

$mail_settings['admin_on_bookings']      = true;  // the addresses defined by $mail_settings['recipients'] below
$mail_settings['area_admin_on_bookings'] = false;  // the area administrator
$mail_settings['room_admin_on_bookings'] = false;  // the room administrator
$mail_settings['booker'] = true;  // the person making the booking
$mail_settings['book_admin_on_approval'] = false;

$mail_settings['on_new']    = true;   // when an entry is created
$mail_settings['on_change'] = true;  // when an entry is changed
$mail_settings['on_delete'] = true;  // when an entry is deleted

// It is also possible to allow all users or just admins to choose not to send an
// email when creating or editing a booking.  This can be useful if an inconsequential
// change is being made, or many bookings are being made at the beginning of a term or season.
$mail_settings['allow_no_mail']  = false;
$mail_settings['allow_admins_no_mail'] = false;  // Ignored if 'allow_no_mail' is true
$mail_settings['no_mail_default'] = false;

$mail_settings['details']   = true; // Set to true if you want full booking details;
                                     // otherwise you just get a link to the entry
$mail_settings['html']      = false; // Set to true if you want HTML mail
$mail_settings['icalendar'] = false;

$mail_settings['admin_lang'] = 'en';   // Default is 'en'.
$mail_settings['admin_backend'] = 'smtp';

$smtp_settings['host'] = 'smtp.gmail.com';  // SMTP server ssl://smtp.gmail.com' or localhost
$smtp_settings['port'] = 587;           // SMTP port number: 25, 465, 587
$smtp_settings['auth'] = true;        // Whether to use SMTP authentication
$smtp_settings['secure'] = 'tls';         // Encryption method: '', 'tls' or 'ssl' 

$smtp_settings['username'] = '****';       // Username (if using authentication)
$smtp_settings['password'] = '****';
//$smtp_settings['hostname'] = '';
//$smtp_settings['helo'] = '';

$mail_settings['domain'] = '';
$mail_settings['username_suffix'] = '';

$smtp_settings['disable_opportunistic_tls'] = false;

$smtp_settings['ssl_verify_peer'] = false;
$smtp_settings['ssl_verify_peer_name'] = false;
$smtp_settings['ssl_allow_self_signed'] = true;

$mail_settings['ics_filename'] = "booking";
$mail_settings['debug'] = true;
$mail_settings['debug_output'] = 'browser';
$mail_settings['disabled'] = false;

Server details:
- MRBS Version: MRBS 1.11.4
- Database: mariadb-1:11.1.2
- system: Linux
- PHP: 8.1.20

**Comment by campbell-m** [comment]
Have you followed the two links in the error messsage?

One problem could be is that you have entered an incorrect password for Gmail.  This should not be your normal password, but an app password that you need to get from your Gmail settings.

**Comment by lamdhoang** [comment]
Do you mean I need to have Gmail opened in order for emails to be sent? 

Or do you mean I need to set username and password in the following fields:

$smtp_settings['username'] = username/email I set from $smtp_settings['from']
$smtp_settings['password'] = password of the email I set from $smtp_settings['from']

**Comment by jberanek** [comment]
You need to set those items, after creating an app password as explained at
https://support.google.com/accounts/answer/185833?hl=en

**Comment by lagethomas** [comment]
I have a similar problem, but in my case the sending is Successful and the emails never arrive.

**Comment by campbell-m** [comment]
If the sending is successful then it's probably not arriving because it's bounced or it's in a spam folder.

**Comment by lagethomas** [comment]
I managed to resolve it and notify. Now it's 100%
