### ISSUE TITLE
Found Security Issues with Medium Risk Level

### ISSUE THREAD

**Issue by theuntoldmomente** [meeting-room-booking-system/mrbs-code#3541]
Hi, my company perform a security testing analysis on MRBS and found THREE Medium Risk Level which need to be handled.

1. Application Error Disclosure: datatables.js
This page contains an error/warning message that may disclose sensitive information like the location of the file that produced the unhandled exception. This information can be used to launch further attacks against the web application. The alert could be a false positive if the error message is found inside a documentation page.

2. Content Security Policy (CSP) Header Not Set
3. Missing anti-clickjacking header

Can you help me how to resolve these security issue? Unless they are resolved, the security team won't allow me to implement the system in our ogranization.

**Comment by campbell-m** [comment]
1. Are you running MRBS with `$debug = true;` in your config file?  If so, you should set it to `false` in a production environment. If not, what is the message that you are seeing?
2. You would normally set your CSP header in your web server (eg Apache, IIS).
3. Anti-clickjacking headers have been superseded by CSP.
