### ISSUE TITLE
Different privileges level based on uid with LDAP

### ISSUE THREAD

**Issue by Metz01** [meeting-room-booking-system/mrbs-code#3546]
Hi,
I've connected correctly my MRBS site to my local LDAP server. Now what I want to achive is, once the  process of authentication end correctly, to set the privileges based on the uid. I know to which uid give permission 1, 2 or 0, but which is the safest way to let the AuthLdap.php file know this list of user but preventing an external user to modify that list?

Thank you all for the support in advance

**Comment by campbell-m** [comment]
Users that are not logged in have level 0.  Users that are logged in have level 1, unless they are admins when they are level 2.  You set the admin privileges by editing your MRBS config.inc.php file and you have two choices:

1. You specify the admins in the config file be setting `$auth['admin']`, eg `$auth['admin'][] = 'Metz01'`.
2. By specifying an LDAP group or groups that the admins must be members of.  See the settings in systemdefaults.inc.php (but put the settings in config.inc.php and do not edit systemdefaults.inc.php):

~~~php
// The DN of the LDAP group that MRBS admins must be in. If this is defined
// then the $auth["admin"] is not used.
// This can be an array.
// $ldap_admin_group_dn = 'cn=admins,ou=whoever,dc=example,dc=com';

// The LDAP attribute that holds group membership details. Used with
// $ldap_admin_group_dn, above.
// This can be an array.
$ldap_group_member_attrib = 'memberof';
~~~

**Comment by Metz01** [comment]
And maybe it's a too specific question, but if I may ask:
How can I add a new role (2 and admin will become 3) who can insert and delete his own bookings 
and to the just logged users (no role, 1) just the privileges to see the the reservation and see the event details?

**Comment by campbell-m** [comment]
It sounds like the [roles branch](https://github.com/meeting-room-booking-system/mrbs-code/tree/roles) might be what you want.  It's still under development but there are a number of sites using it.  However I suggest you test it yourself with a separate database as it will upgrade your existing database tables if you install it there.

It allows you to define roles and assign those roles to users and groups.  For each role you can assign permissions for rooms and groups.

**Comment by Metz01** [comment]
Thank you for the help. I'll have a look at it!

**Comment by Metz01** [comment]
I have one question, is it possible to set de default role as 0?
To explain, I set the 
`$auth['deny_public_access'] = TRUE; `
so no one can access the site before the login.
Now I want every one that is not write as user in the config file is set with the role 0.
