### ISSUE TITLE
Error when attempting to approve series booking

### ISSUE THREAD

**Issue by EnthuWafi** [meeting-room-booking-system/mrbs-code#3549]
**Describe the bug**
An error pops up whenever I attempt to approve a series booking. This does not occur when approving an entry, however.

**To Reproduce**
1. In config.inc.php `$mail_settings['icalendar'] = true;$approval_enabled = true; `
2.  Use a user account to create a repeat/series booking
3.  Go on an admin account and attempt to approve the series

**Expected behavior**
Based on the error log returl, it should've redirected the user to the pending.php page.

**Screenshots**
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/108134135/2ea69c3d-fa68-4f97-a0ad-f647450f3577)
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/108134135/1fdd026a-b615-46d6-8c27-dd68fc7f3963)

**Browser details:**
 - Windows 11
 - Chrome
 - Version 118.0.5993.118 (Official Build) (64-bit)

**Server details:**
 - MRBS version 1.11.4 (and also MRBS version 1.11.3)
 - Apache/2.4.56 (Win64) 
 - Windows 11
 - PHP version: 8.2.4
 - Database used: Server version: 10.4.28-MariaDB

**Additional context**
Although it outputs an error, it seems to work just fine. It sends an email to the user, with the iCalendar attached to it. 

I originally discovered this bug using MRBS 1.11.3. I attempted to clone the current MRBS version and see if the problem was fixed then.

**Comment by HONGNGUYEN2023** [comment]
Hi Enthu; I also have an issue with 1 entry and the series too. the error message : 500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.

Can you share the config file for me please

**Comment by campbell-m** [comment]
Now fixed in [95275e6](https://github.com/meeting-room-booking-system/mrbs-code/commit/95275e691c08066dd269037aedd25351828ea3cb).

**Comment by EnthuWafi** [comment]
Thanks, it works just fine now!
