### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by BrzIGH** [meeting-room-booking-system/mrbs-code#3551]
Windows server 2019
IIS 10
Php 8.2.12
Php Manager for IIS 1.5
MySql Server 8.0.35

config.inc.php configured with timezone and db connection. When I launch the home page I get: 
Whoops ! MRBS has encountered a fatal error. Please consult your system administrator...

Not sure where to start looking... Any suggestions

I have an old version that runs just fine....trying a test build for migration to different authentication method.

PHP error log shows:
[01-Nov-2023 19:00:15 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_gd2.dll' (tried: C:\Program Files\php-8.2.12-Win32-vs16-x64\ext\php_gd2.dll (The specified module could not be found), C:\Program Files\php-8.2.12-Win32-vs16-x64\ext\php_php_gd2.dll.dll (The specified module could not be found)) in Unknown on line 0
[01-Nov-2023 19:00:15 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_xmlrpc.dll' (tried: C:\Program Files\php-8.2.12-Win32-vs16-x64\ext\php_xmlrpc.dll (The specified module could not be found), C:\Program Files\php-8.2.12-Win32-vs16-x64\ext\php_php_xmlrpc.dll.dll (The specified module could not be found)) in Unknown on line 0

**Comment by campbell-m** [comment]
Set `$debug  = true;` in your MRBS config file to get the detailed error message in the browser.

**Comment by BrzIGH** [comment]
Get this:

E_USER_DEPRECATED in C:\inetpub\wwwroot\init.inc at line 19
MRBS has detected that you do not have the PHP 'intl' extension loaded on your server and so it is using the deprecated strftime() function instead. You are recommended to enable the 'intl' extension.
#0 MRBS\generate_backtrace() called at [C:\inetpub\wwwroot\functions_error.inc:219]
#1 MRBS\output_error() called at [C:\inetpub\wwwroot\functions_error.inc:249]
#2 MRBS\error_handler(16384, MRBS has detected that you do not have the PHP 'intl' extension loaded on your server and so it is using the deprecated strftime() function instead. You are recommended to enable the 'intl' extension., C:\inetpub\wwwroot\init.inc, 19)
#3 trigger_error(MRBS has detected that you do not have the PHP 'intl' extension loaded on your server and so it is using the deprecated strftime() function instead. You are recommended to enable the 'intl' extension., 16384) called at [C:\inetpub\wwwroot\init.inc:19]
#4 require_once(C:\inetpub\wwwroot\init.inc) called at [C:\inetpub\wwwroot\defaultincludes.inc:34]
#5 require(C:\inetpub\wwwroot\defaultincludes.inc) called at [C:\inetpub\wwwroot\index.php:8]
Uncaught exception 'MRBS\Exception' in C:\inetpub\wwwroot\lib\MRBS\DBFactory.php at line 39
Undefined constant PDO::MYSQL_ATTR_FOUND_ROWS. Check that the PDO MySQL driver is enabled in your php.ini file.
#0 C:\inetpub\wwwroot\dbsys.inc(63): MRBS\DBFactory::create()
#1 C:\inetpub\wwwroot\dbsys.inc(74): MRBS\db()
#2 C:\inetpub\wwwroot\lib\MRBS\Session\Session.php(56): MRBS\db_schema_version()
#3 C:\inetpub\wwwroot\lib\MRBS\Session\Session.php(23): MRBS\Session\Session->init()
#4 C:\inetpub\wwwroot\lib\MRBS\Session\SessionWithLogin.php(31): MRBS\Session\Session->__construct()
#5 C:\inetpub\wwwroot\lib\MRBS\Session\SessionPhp.php(19): MRBS\Session\SessionWithLogin->__construct()
#6 C:\inetpub\wwwroot\lib\MRBS\Session\SessionFactory.php(14): MRBS\Session\SessionPhp->__construct()
#7 C:\inetpub\wwwroot\mrbs_auth.inc(33): MRBS\Session\SessionFactory::create()
#8 C:\inetpub\wwwroot\init.inc(40): MRBS\session()
#9 C:\inetpub\wwwroot\defaultincludes.inc(34): require_once('...')
#10 C:\inetpub\wwwroot\index.php(8): require('...')
#11 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
)

#0 MRBS\generate_backtrace() called at [C:\inetpub\wwwroot\functions_error.inc:219]
#1 MRBS\output_error() called at [C:\inetpub\wwwroot\functions_error.inc:262]
#2 MRBS\output_exception_error(object) called at [C:\inetpub\wwwroot\functions_error.inc:270]
#3 MRBS\exception_handler(object)

**Comment by BrzIGH** [comment]
After enabling pdo-mysql I am down to this:

E_USER_DEPRECATED in C:\inetpub\wwwroot\init.inc at line 19
MRBS has detected that you do not have the PHP 'intl' extension loaded on your server and so it is using the deprecated strftime() function instead. You are recommended to enable the 'intl' extension.
#0 MRBS\generate_backtrace() called at [C:\inetpub\wwwroot\functions_error.inc:219]
#1 MRBS\output_error() called at [C:\inetpub\wwwroot\functions_error.inc:249]
#2 MRBS\error_handler(16384, MRBS has detected that you do not have the PHP 'intl' extension loaded on your server and so it is using the deprecated strftime() function instead. You are recommended to enable the 'intl' extension., C:\inetpub\wwwroot\init.inc, 19)
#3 trigger_error(MRBS has detected that you do not have the PHP 'intl' extension loaded on your server and so it is using the deprecated strftime() function instead. You are recommended to enable the 'intl' extension., 16384) called at [C:\inetpub\wwwroot\init.inc:19]
#4 require_once(C:\inetpub\wwwroot\init.inc) called at [C:\inetpub\wwwroot\defaultincludes.inc:34]
#5 require(C:\inetpub\wwwroot\defaultincludes.inc) called at [C:\inetpub\wwwroot\edit_users.php:44]

**Comment by campbell-m** [comment]
So now enable the Intl extension.

**Comment by BrzIGH** [comment]
Yes, I did. Thank you. I can see the initial admin set up screen and no more debug errors.
