### ISSUE TITLE
Import mysql database from older version

### ISSUE THREAD

**Issue by BrzIGH** [meeting-room-booking-system/mrbs-code#3552]
Currently running mrbs 1.6.1 without problems.

Just built mrbs 1.11.4. I sit safe to import the mysql dump from the old set up ?

Thanks

**Comment by campbell-m** [comment]
Yes, but only if you drop all the 1.11.4 tables first. Then once you have imported the 1.6.1 tables you will be prompted to upgrade the database. 

Take a back up of everything first.

**Comment by BrzIGH** [comment]
Tx!
