### ISSUE TITLE
Timestamps 1h apart with PHP 8.1

### ISSUE THREAD

**Issue by lagethomas** [meeting-room-booking-system/mrbs-code#3559]
I came across a situation.
When using PHP 8.1, when you schedule the time it comes out wrong.
Ex.: I schedule from 07:00 to 08:00 and it shows on the calendar and email notification as 08:00 to 09:00, that is, it registers 1 hour apart and when you go to edit the schedule it is with the time set correctly on the editing screen.
I switched to PHP 7.4 and everything worked perfectly as it should.

**Comment by lagethomas** [comment]
I checked, in the versions that work correctly, "intl" is not installed and in the version that is causing problems, "intl is installed"
![php8 1_intl](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/0f359ea2-3423-49ef-b127-d820fcc1e391)
![extensões_php](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/298ce104-e7c3-4984-90fc-dfd861c4afac)
![mail_lang](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/88bf6109-1c28-4342-a487-190befc1d9e4)
![over_lang](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/b032d8a6-d972-4a9b-8fa6-efb2844c4850)
![php7 4_intl](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/489b5aa7-74f1-42b5-8a28-505ba1623887)

**Comment by campbell-m** [comment]
Thanks.  And could you let me know the answers to the other questions please so that I can try and reproduce it?

**Comment by lagethomas** [comment]
I reinstalled "intl" from php 8.1 to test and it recorded the data correctly. It seems that this extension somehow impacts functionality.

**Comment by campbell-m** [comment]
Sorry, I see that you have!  Except which date are you making a booking for?

**Comment by lagethomas** [comment]
> Desculpe, vejo que você tem! Exceto para qual data você está fazendo uma reserva?

I will simulate a reservation with the extension installed and place it here for analysis.

**Comment by lagethomas** [comment]
> Sorry, I see that you have! Except which date are you making a booking for?

Video of simulation
https://drive.google.com/file/d/1-7LkWqH7kiy1CB-EBLxYxKHrSSWn-d9-/view?usp=sharing

**Comment by campbell-m** [comment]
Can you try setting `$override_locale = 'pt-BR';` to see if that makes a difference to the calendar display?

**Comment by lagethomas** [comment]
> $override_locale = 'pt_BR';

It didn't work, it keeps marking the time with 1 hour more.
It only works if I remove the "intl" from the installed extensions. With the extension installed, the video presents this behavior.

**Comment by campbell-m** [comment]
I cannot reproduce the problem.  It could be that the problem is that the ICU library on your server is out of date.  The "intl" extension uses the ICU library to get timezone information, whereas `strftime()`, which is used if the "intl" extension is not available, but is deprecated from PHP 8.1, uses PHP's timezone database.

My understanding is that Brazil abandoned daylight saving time (DST) in 2019.  So if your ICU library predates 2019 and still thinks that Brazil is operating DST, then you will get times that are one hour out in Brazilian summer.

An interesting test would be to try making a booking for a date in June, when there would have been no DST, and see if the problem happens in June.  If it doesn't then I suspect it's the ICU libary.

You can check the ICU library version, in particular the ICU TZData version, by running `phpinfo()`.  Under "intl" you should see something like:

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/87438215/7e31ec7d-ed96-452a-b1a5-97fb295cc04e)

**Comment by lagethomas** [comment]
> phpinfo()

This is the verion here.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/c606564d-aa86-4c09-a268-b44f8f7b3aec)

**Comment by campbell-m** [comment]
Looks like your TZ data is from 2018, just before the end of DST in Brasil.  What happens if you try and make a booking for June (either 2023 or 2024)?

**Comment by lagethomas** [comment]
> Parece que seus dados TZ são de 2018, pouco antes do final do horário de verão no Brasil. O que acontece se você tentar fazer uma reserva para junho (2023 ou 2024)?

By carrying out this test, it registers correctly.
I use CentOS 7 and it seems to me that there is no way to update libicu.

Is there any way around this in the config file?

**Comment by lagethomas** [comment]
I'm compiling libicu 74.1 here to see if it works. If it's right, I'll post the procedure as a solution here

**Comment by lagethomas** [comment]
I managed to solve it here. To contextualize.
I use aaPanel as my web panel and the installations of php, mysql, openlitspeed modules are all done in it.
I used aaPanel on CentOS7 and uploaded it to Debian 10 for testing.
In Debian 10 I compiled icu, because what was in it was 63 and it gave the same problem.
After compilation the ICU version is 72.1.

For anyone who wants to know aaPanel. Very good and I've been using it for a long time.
https://www.aapanel.com/new/index.html

If you are going to use aaPanel and I don't know if it is a particularity of it, because the installation of the modules is different. Just download the corresponding intl.so version here
https://github.com/shivammathur/icu-intl
Once downloaded, navigate to the folder
/usr/local/lsws/lsphp81/lib/php/20210902

If I use OenLiteSpeed ​​as a web server and replace intl.so.

I did this and it resolved.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/d0705010-b66b-4fe6-aa01-1f2ee5893739)


aaPanel


![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/3ae5b810-b60a-47b3-a1c3-a6a6b1c0ba08)

**Comment by campbell-m** [comment]
Good, glad it's solved.  For those who can't easily update their ICU library I'm going to make the use of the "intl" extension a config option as you suggest.

**Comment by campbell-m** [comment]
It's not that easy to make the use of the "intl" extension controllable by a config variable as the IntlDateFormatter constants are used in systemdefaults.inc.php, and so there's a bootstrapping problem.

However what I have done in [c631aaa](https://github.com/meeting-room-booking-system/mrbs-code/commit/c631aaa12fee6b0f5090885db7c79ac73d41d139) is to restructure the code so that there's just a one line edit to make to force MRBS to use `strftime()`.

**Comment by campbell-m** [comment]
In the latest code in the main branch there is now a config variable, `$force_strftime`, for forcing the use of the emulation using strftime() even when the 'intl' extension is loaded.

**Comment by lagethomas** [comment]
> It's not that easy to make the use of the "intl" extension controllable by a config variable as the IntlDateFormatter constants are used in systemdefaults.inc.php, and so there's a bootstrapping problem.
> 
> However what I have done in [c631aaa](https://github.com/meeting-room-booking-system/mrbs-code/commit/c631aaa12fee6b0f5090885db7c79ac73d41d139) is to restructure the code so that there's just a one line edit to make to force MRBS to use `strftime()`.

Even applying these updates I still face this time problem.
I'm going to upload another version of PHP just for mrbs and run it without intl.

**Comment by campbell-m** [comment]
Have you downloaded the latest code from the main branch (a complete release)?  If so, all you need to do now is set in your config file

~~~php
$force_strftime = true;
~~~

**Comment by lagethomas** [comment]
> Have you downloaded the latest code from the main branch (a complete release)?  If so, all you need to do now is set in your config file
> 
> ~~~php
> $force_strftime = true;
> ~~~
> 

The version that is in git is the same as the one I already use, unless the corrections were applied and the version numbering has not changed.  I'll test it tomorrow with the information you gave me.  Thanks!

**Comment by campbell-m** [comment]
To check that you've got a version that supports `$force_strftime` search for that setting in systemdefaults.inc.php.

**Comment by lagethomas** [comment]
> Para verificar se você tem uma versão compatível, `$force_strftime`pesquise essa configuração em systemdefaults.inc.php.

I downloaded the latest version from Git and didn't find $force_strftime = true; in the configuration file, even though I manually put all the changes in the corresponding files, it doesn't respect it and the time is 1h different.
Can I send the exact link to the complete file with the correction? I might be downloading it wrong.

**Comment by campbell-m** [comment]
Yes, send the link.

**Comment by lagethomas** [comment]
> Sim, envie o link.
I downloaded it here and I didn't see the reference you told me in the configuration file
https://github.com/meeting-room-booking-system/mrbs-code/releases/tag/v1.11.4

**Comment by campbell-m** [comment]
Ah, that's for the latest released code.  For the latest development code you need to download from https://github.com/meeting-room-booking-system/mrbs-code .  Follow the green Code button and treat it like a whole new release.

**Comment by lagethomas** [comment]
> > Não é tão fácil tornar o uso da extensão "intl" controlável por uma variável de configuração, já que as constantes IntlDateFormatter são usadas em systemdefaults.inc.php e, portanto, há um problema de inicialização.
> > No entanto, o que fiz em [c631aaa](https://github.com/meeting-room-booking-system/mrbs-code/commit/c631aaa12fee6b0f5090885db7c79ac73d41d139) foi reestruturar o código para que haja apenas uma edição de uma linha para forçar o uso do MRBS `strftime()`.
> 
> Mesmo aplicando essas atualizações ainda enfrento esse problema de tempo. Vou fazer upload de outra versão do PHP apenas para mrbs e executá-la sem intl.

I tested it here and now it works, everything seems to be corrected. Thanks!!!
