### ISSUE TITLE
View events without login

### ISSUE THREAD

**Issue by lagethomas** [meeting-room-booking-system/mrbs-code#3561]
I have a suggestion:
Here, when you click to see the registered event, it asks for login, it would be interesting for anyone, regardless of being logged in, to be able to see who scheduled it and what is scheduled.
As we use in the company, sometimes an intern without access wants to check if there is a vacancy in the room at the request of a director, but this intern does not have a user in the system and this limits him or her from seeing the information.
What can be done is when booking you have the option of being a public or private event, with public being the default.
When marking as private it would require a password.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/d325eec2-4fdf-4016-9df5-d2c9f29fcd34)

**Comment by lagethomas** [comment]
> Não tenho certeza se entendi esse pedido corretamente. Já é possível para alguém sem login, por exemplo seu estagiário, ver se há vaga livre; eles simplesmente não conseguem ver os detalhes das reservas.

That's the point, it would be nice for him to see the scheduling detail if a booking was marked as public.

**Comment by campbell-m** [comment]
You can make view_entry.php open to the public by editing `get_page_level()` in mrbs_auth.inc.

**Comment by lagethomas** [comment]
> You can make view_entry.php open to the public by editing `get_page_level()` in mrbs_auth.inc.

It worked out making this change.
