### ISSUE TITLE
MRBS LDAP authentication Failed

### ISSUE THREAD

**Issue by asz10245** [meeting-room-booking-system/mrbs-code#3566]
Hi ,
I try to use ldap authentication  on my MRBS system, but it show account not exist or wrong password, and also enabled the debug, but i can't see anything in apache log, please help to advise, thanks.

 - MRBS version [1.10.0]
 - Web server: [Apache 2.4.37]
 - OS: [Rocky Linux 8.8]
 - PHP version: [8.2.12]
 - Database used: [MySQL 8.0.35]

$auth["type"] = "ldap"; 
$ldap_host = "10.10.11.16";
$ldap_port = 3268;
$ldap_base_dn = "ou=users,dc=xtg,dc=com";
$ldap_user_attrib = "uid";
$ldap_dn_search_dn = "cn=account,cn=Users,dc=xtg,dc=com";
$ldap_dn_search_password = "mypassword";
$ldap_debug = false;
$ldap_debug_attributes = false;

**Comment by campbell-m** [comment]
Set `$ldap_debug = true;` in your MRBS config file.  The debug output will appear in your config file.

**Comment by asz10245** [comment]
> `$ldap_debug = true;`在 MRBS 設定檔中設定。調試輸出將出現在您的設定檔中。
Hi , 
Yes, i have enabled the debug mode, it says "can't contact LDAP server". But the setting is same with my MRBS server and it's working in my old server, please help, thanks.

**Comment by campbell-m** [comment]
Have you got a firewall between the new server and LDAP that's blocking the LDAP port?

**Comment by asz10245** [comment]
> Have you got a firewall between the new server and LDAP that's blocking the LDAP port?

Hi ,
No they're in same network segment and in same VM host using same vSwtich. So i don't why it can't contract...

**Comment by campbell-m** [comment]
Can you connect if you use MRBS 1.4.6 or 1.5 on the new server (assuming that those are the versions that connect successfully on the old server)?

**Comment by asz10245** [comment]
> Can you connect if you use MRBS 1.4.6 or 1.5 on the new server (assuming that those are the versions that connect successfully on the old server)?

Hi,
I think it will have some issue about compatibility due to the newest version of MySQL and PHP in old MRBS version.

**Comment by jberanek** [comment]
Is the issue perhaps to do with trust of the TLS certificate on the LDAP server? TLS trust is a per host/per PHP installation thing.

**Comment by lagethomas** [comment]
I'll share my ldap configuration, I wish I could get it to work, but this one worked.


```
$ldap_host = 'SEU_IP';
$ldap_port = 389;
$ldap_v3 = true;
$ldap_tls = false;
$ldap_base_dn = "DC=dominio,DC=com,DC=br";
$ldap_dn_search_dn = "CN=USER_LDAP,CN=Users,DC=dominio,DC=com,DC=br";
$ldap_dn_search_password = "SUA_SENHA";
$ldap_disable_referrals = true;
$ldap_get_user_email = true;
$ldap_email_attrib = 'mail';
$ldap_unbind_between_attempts = false;
$ldap_debug = false;
```

**Comment by asz10245** [comment]
> Is the issue perhaps to do with trust of the TLS certificate on the LDAP server? TLS trust is a per host/per PHP installation thing.

Hi il,
I didn't use TLS, the issue has been sovled, thanks for your reply

**Comment by asz10245** [comment]
> I'll share my ldap configuration, I wish I could get it to work, but this one worked.
> 
> ```
> $ldap_host = 'SEU_IP';
> $ldap_port = 389;
> $ldap_v3 = true;
> $ldap_tls = false;
> $ldap_base_dn = "DC=dominio,DC=com,DC=br";
> $ldap_dn_search_dn = "CN=USER_LDAP,CN=Users,DC=dominio,DC=com,DC=br";
> $ldap_dn_search_password = "SUA_SENHA";
> $ldap_disable_referrals = true;
> $ldap_get_user_email = true;
> $ldap_email_attrib = 'mail';
> $ldap_unbind_between_attempts = false;
> $ldap_debug = false;
> ```

Hi ,
Thanks, i found the root cause, its selinux casue this issue, i have disabled it and it'sworking now

**Comment by asz10245** [comment]
> Can you connect if you use MRBS 1.4.6 or 1.5 on the new server (assuming that those are the versions that connect successfully on the old server)?

Hi ,
Thanks for your help, selinux is the root cause
