### ISSUE TITLE
MRBS cookie properties

### ISSUE THREAD

**Issue by wgseligman** [meeting-room-booking-system/mrbs-code#3568]
My parent institution recently did a security audit of my web server that runs only MRBS. Among their complaints were that the MRBS session cookies did not include the following properties:

```
SameSite
HttpOnly
Secure
```

I have:

```
$auth["session"] = "php";
$auth["type"] = "imap";
```
so I'm not sure how cookies figure into this at all. How do I set these properties within MRBS?

**Server details:**
 - MRBS version 1.11.4
 - Web server: 2.4.57
 - OS: AlmaLinux 9
 - PHP version: 8.0.30
 - Database used: MariaDB 10.5.22

**Comment by campbell-m** [comment]
You can set these values in your server's php.ini file.  See [this manual page](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-secure).

I will also look at setting them in MRBS.

**Comment by wgseligman** [comment]
Thanks!

I tried editing `php.ini`. My memory is a bit confused (I was working on this at 4AM), but I recall that using MRBS left an MRBS_SESSID cookie that had the properties I'd set, there was also a PHPSESSID cookie that did not. 

What worked was adding this two lines to my `/etc/httpd/conf/httpd.conf` file (I'm running Apache):

```
Header always edit Set-Cookie (.*) "$1;HttpOnly;Secure;SameSite=Strict"
Header onsuccess edit Set-Cookie (.*) "$1;HttpOnly;Secure;SameSite=Strict"
```

This might be overkill, but since the `always` and `onsuccess` conditions are triggered in different ways, I decided not to risk it. After that, both cookies had the properties I wanted. 

Thanks again!

**Comment by campbell-m** [comment]
MRBS now sets these properties in [133b664](https://github.com/meeting-room-booking-system/mrbs-code/commit/133b664c56d7d3d152d9a15344a40c98cc1544fa).

I don't know where your PHPSESSID cookie is coming from.  I don't think it's from MRBS.

**Comment by wgseligman** [comment]
Excellent! I copied the revised code into my installation. I didn't remove my other changes to `/etc/php.ini` and `/etc/httpd/conf/httpd.conf`, so I didn't see any explicit changes to the cookies. But the code didn't crash and MRBS is behaving normally. 

Thanks!
