### ISSUE TITLE
Add username in the daily overview

### ISSUE THREAD

**Issue by bks0401** [meeting-room-booking-system/mrbs-code#3569]
Hi

Is it possible to add the user name that booked the room so that it can be seen in the overview.

So it first writes the short description followed by the user name
Version 1.11.0

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/147808398/9e0054b5-30e6-41f6-bf09-7326e98a9e92)

thanks in advance

Bruno

**Comment by campbell-m** [comment]
You can do one of two things:

1. You can set `$default_name_display_name = true;` in your config file.  This will automatically pre-fill the brief description field on the booking form with the user's display name.  However the field can be edited by the user, so you may prefer

2. Edit the function `prepare_entry()` in functions_table.inc and at the beginning add the following lines:

~~~php
  $creator = auth()->getUser($entry['create_by']);
  $entry['name'] .= ' (' . $creator->display_name . ')';
~~~

**Comment by bks0401** [comment]
Thanks
