### ISSUE TITLE
Login with multiple ADs

### ISSUE THREAD

**Issue by lagethomas** [meeting-room-booking-system/mrbs-code#3572]
Is it possible to integrate LDAP from multiple ADs? If so, what is the limit of ADs that can be connected to import users?

I implemented it in the company I work for and I wanted to try to expand it to other units in the future, but to do so I would need to connect the AD of each unit to the system so that people can log in and reserve rooms in their location.

**Comment by campbell-m** [comment]
Yes, your MRBS LDAP settings can be arrays.  See the comments in systemdefaults.inc.php.  You can have as many elements in the array as you like - until you hit a system memory limit, but I doubt you will have that many.

**Comment by lagethomas** [comment]
> Yes, your MRBS LDAP settings can be arrays. See the comments in systemdefaults.inc.php. You can have as many elements in the array as you like - until you hit a system memory limit, but I doubt you will have that many.

Show, thank you very much.
We have more than 10 ads

**Comment by lagethomas** [comment]
How would I configure 2 or more ads?  I saw that you have to put it in the array, but what would the array of users to authenticate, passwords and base dn look like?  Do you have any example?

**Comment by campbell-m** [comment]
Here's an example:

~~~php
$ldap_host = ['SEU_IP', 'SEU_IP2'];
$ldap_port = 389;
$ldap_v3 = true;
$ldap_tls = false;
$ldap_base_dn = ["DC=dominio,DC=com,DC=br", "DC=dominio2,DC=com,DC=br"];
$ldap_dn_search_dn = ["CN=USER_LDAP,CN=Users,DC=dominio,DC=com,DC=br", "CN=USER_LDAP2,CN=Users,DC=dominio2,DC=com,DC=br"];
$ldap_dn_search_password = ["SUA_SENHA", "SUA_SENHA2"];
$ldap_disable_referrals = true;
$ldap_get_user_email = true;
$ldap_email_attrib = 'mail';
$ldap_unbind_between_attempts = false;
$ldap_debug = false;
~~~

The settings can be either arrays or scalars.   If it's a scalar then that value applies to all hosts.  If it's an array then it must have the same number of elements as all the other arrays (two in the example above).

**Comment by lagethomas** [comment]
> Here's an example:
> 
> ~~~php
> $ldap_host = ['SEU_IP', 'SEU_IP2'];
> $ldap_port = 389;
> $ldap_v3 = true;
> $ldap_tls = false;
> $ldap_base_dn = ["DC=dominio,DC=com,DC=br", "DC=dominio2,DC=com,DC=br"];
> $ldap_dn_search_dn = ["CN=USER_LDAP,CN=Users,DC=dominio,DC=com,DC=br", "CN=USER_LDAP2,CN=Users,DC=dominio2,DC=com,DC=br"];
> $ldap_dn_search_password = ["SUA_SENHA", "SUA_SENHA2"];
> $ldap_disable_referrals = true;
> $ldap_get_user_email = true;
> $ldap_email_attrib = 'mail';
> $ldap_unbind_between_attempts = false;
> $ldap_debug = false;
> ~~~
> 
> The settings can be either arrays or scalars.   If it's a scalar then that value applies to all hosts.  If it's an array then it must have the same number of elements as all the other arrays (two in the example above).
> 

Thanks!
