### ISSUE TITLE
MRBS: could not start sessions fatal error

### ISSUE THREAD

**Issue by Metz01** [meeting-room-booking-system/mrbs-code#3575]
Hello,

I'm currently working with MRBS and encountered an issue when attempting to deploy it on a production machine using Docker. Initially, I tested everything on my local machine, and it worked as expected. To enhance portability, I decided to containerize the application with separate containers for the database and the application.

I've created Dockerfiles for both containers, but during the build process, I'm encountering numerous warnings and an error message, which I'll include at the end of this message. Initially, I suspected Docker or my configuration, but after testing some pages, it seems that the connection to the database is established correctly using the database information provided in the MRBS configuration file.

This leads me to believe that the issue might be elsewhere. Could someone assist me with this?

Thank you for your help.

----

The web page output:
`Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator.`

Attached the file with all the warnings and the error message (I also set $debug = true;):
[MRBS_Warnings_and_error.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/13472734/MRBS_Warnings_and_error.txt)

**Comment by Metz01** [comment]
Thank you for your prompt response.

I made progress by resolving the issue with the database connection. After removing $debug = true; and generating the correct locale, the application now correctly detects the database and redirects me to the login page, as expected.

However, a new challenge has emerged related to connecting to the LDAP server. The error message `Can't contact LDAP server` is now being encountered. I haven't delved into troubleshooting this yet, but if needed, I'll open a new issue here. Any suggestions you may have are greatly appreciated.

**Comment by campbell-m** [comment]
Probably best to open a new issue for the LDAP problem, but two things to check are

1. Your LDAP host and port settings in your MRBS config file.
2. Whether there's a firewall in place blocking traffic on the LDAP port.
