### ISSUE TITLE
Change in server

### ISSUE THREAD

**Issue by AndreBotha47** [meeting-room-booking-system/mrbs-code#3583]
Good day. We have been using MRBS for 4 years and are extremely happy. We have however changed from server and after the hosting company did the transfer to the new server, MRBS simply reports ERROR 500 when required to run the day.php

This page isn’t working ???.com is currently unable to handle this request.
HTTP ERROR 500

**Browser details (please complete the following information):**
OS: Windows
Browser: Chrome
 - Version 120.0.6099.109

**Server details (please complete the following information):**
$mrbs_version = "MRBS 1.4.11";
AlmaLinux v8.9.0 STANDARD standard vs 116.0.7
PHP vs: PHP Version 8.1.26
Database used: Server version: 8.0.35 - MySQL Community Server - GPL

**Additional context**
The website URL is hosted on GoDaddy, but we run the MRBS program from an InMotion Hosting server (If this could have an influance). When we run MRBS from the old server (using hosting URL address), MRBS still works fine, but not on the new server.

**Comment by campbell-m** [comment]
Have a look in your PHP error log to see the detailed error message.

I suspect that the issue may be that MRBS 1.4.11 is a very old version and not compatible with PHP 8.1.26.  Either change your PHP version to PHP 7.2 for the time being to get MRBS going, or else upgrade MRBS to the latest version.

**Comment by campbell-m** [comment]
Yes, as I thought: `get_magic_quotes_runtime()` was removed from PHP 8.0.  You either need to downgrade PHP or upgrade MRBS.

**Comment by AndreBotha47** [comment]
Thank you for your amazing help. I know what to do now all thanks to you.
