### ISSUE TITLE
add a note in add entry page

### ISSUE THREAD

**Issue by fuzezeze** [meeting-room-booking-system/mrbs-code#3587]
Hi sir, I want to add a note in the add entry page. But it looks the add custom field function only support add a input field. Is there any method I can add a text in the add entry page and display to user?

Thanks a lot.

**Comment by campbell-m** [comment]
Edit edit_entry.php and after the block of code that looks like this

~~~php
if(isset($id) && !$copy)
{
  $form->addHiddenInput('id', $id);
}

$fieldset = new ElementFieldset();
$fieldset->addLegend(get_vocab($token));
~~~

ie round about line 1725, depending on the version, add the lines

~~~php
$note = new ElementDiv();
$note->setAttribute('id', 'my_message')
     ->setText("Your message", true);
$fieldset->addElement($note);
~~~

You can use the div's id to add some custom CSS styling.

**Comment by fuzezeze** [comment]
Thanks a lot campbell. May I ask where should I put the css declaration? Or is I don't want to add custom CSS styling, can I use code $note ->setAttribute('my_message') instead?

Thanks

**Comment by fuzezeze** [comment]
Thanks a lot campbell. May I ask where should I put the css declaration? Or if I don't want to add custom CSS styling, can I use code $note ->setAttribute('my_message') instead?

Thanks

**Comment by fuzezeze** [comment]
My version is a bit old, so the code looks a bit different, should I put the code you teach me at the place after below codes?
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/43137278/954bf61c-bace-490a-9781-dca1a424615f)

**Comment by campbell-m** [comment]
Your code is indeed a bit old.  I strongly recommend you upgrade to the latest version of MRBS.  But if you don't want to do that yet, can you let me know which version of MRBS you are running so that I can work out how to modify it?  The code I gave you won't work with your version of MRBS.

**Comment by campbell-m** [comment]
Assuming an unchanged version of 1.6.1, then at line 1149, immediately after

~~~html
<form class="form_general" id="main" action="edit_entry_handler.php" method="post">
  <fieldset>
  <legend><?php echo get_vocab($token); ?></legend>
~~~

add

~~~html
  <p>Your message</p>
~~~

**Comment by fuzezeze** [comment]
Thanks! it works
