### ISSUE TITLE
Remove one booking type

### ISSUE THREAD

**Issue by bks0401** [meeting-room-booking-system/mrbs-code#3588]
Hi

Is it possible to remove one of the types, External or Type Internal, so that there is only one to choose when booking?

Version 1.11.4

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/147808398/e0671141-a210-49a1-a40e-3b7b794f76ce)

/Bruno

**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Browser details (please complete the following information):**

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]
 - Web server: [e.g. Apache 2.4.48]
 - OS: [e.g. CentOS 7.9]
 - PHP version: [e.g. 7.4.23]
 - Database used: [e.g. MySQL 8.0.26]

**Additional context**

**Comment by campbell-m** [comment]
Just put

~~~php
unset($booking_types);
~~~

in your config file.  Bookings will still have a type associated with them in the database, which will be the default type.
