### ISSUE TITLE
Why the time display incompletely？

### ISSUE THREAD

**Issue by liuch0115** [meeting-room-booking-system/mrbs-code#3589]
![4BE32EA2-0FCD-46FC-BBF3-D2F16031C69E](https://github.com/meeting-room-booking-system/mrbs-code/assets/155701569/ca802dc2-0b9c-47fc-8655-5f3827724992)
![2757C12D-838A-4FBC-A7C2-42C5A39FCAF1](https://github.com/meeting-room-booking-system/mrbs-code/assets/155701569/695b3604-4784-45a1-b5f6-a93e2dc295ef)

how to slove it？  Thanks

**Comment by campbell-m** [comment]
Three questions:

1. Which version of MRBS are you using?
2. What language are you using?  Either what is `$override_locale` set to in your config file or what are your browser language preferences as shown on the MRBS Help page?
3. Is the 'intl' extension installed on your system?  The answer will be on the MRBS Help page when you log in as an admin.

**Comment by campbell-m** [comment]
Also

4. Which version of PHP are you running?

**Comment by liuch0115** [comment]
1.MRBS Version is 1.11.4;
2. I didn’t  set $override_locale ,and my language is zh-cn;
3. PHP version is 7.3.4
![03507695-EB91-423C-997F-146CC807F76A](https://github.com/meeting-room-booking-system/mrbs-code/assets/155701569/005c43fe-a0be-453c-8f23-e18392d497c9)

**Comment by liuch0115** [comment]
> Also
> 
> 4. Which version of PHP are you running?

1.MRBS Version is 1.11.4;
2. I didn’t set $override_locale ,and my language is zh-cn;
3. PHP version is 7.3.4
![9EE41F09-7A4F-4C1A-AAD6-42B6460D603C](https://github.com/meeting-room-booking-system/mrbs-code/assets/155701569/4ca77924-3496-493c-8688-4263e5343185)

**Comment by campbell-m** [comment]
I can reproduce the problem.  It should work properly if you enable the 'intl' extension in your php.ini file.  But I will work on a fix for the case when 'intl' is disabled over the next few days.

**Comment by campbell-m** [comment]
I have now fixed this in [e56895e](https://github.com/meeting-room-booking-system/mrbs-code/commit/e56895e42a4fe456a4ec7174bfd8aaef2bc527bf).

**Comment by liuch0115** [comment]
> I can reproduce the problem. It should work properly if you enable the 'intl' extension in your php.ini file. But I will work on a fix for the case when 'intl' is disabled over the next few days.

Thanks very much.I fix the problem through enable the ‘intl’ extension.
