### ISSUE TITLE
Booking periods

### ISSUE THREAD

**Issue by dougbevan** [meeting-room-booking-system/mrbs-code#3590]
Greetings,

How can we adjust the booking period availability?  For instance, If I want to book a day (let's say Jan 30th) starting at the beginning of the day, we need to go the Jan 29th and select "12 am".  Is there any way to make Jan 30th inclusive of 12am as well, so that it's easier to select a full day?

Also, after booking a reservation, it currently goes back to the main page.  Is there any way to make it return to the previous view, the overview of the room that was just booked?  This would be a way for clients to confirm the entry.

**Comment by dougbevan** [comment]
Very good -- that fixes the time period issues we were having.

For the post-booking behavior:  For the room view, if I start from a particular Area + Room, then add an entry, I am returned to the Area + "All" instead of the specific room.  We'd like it to return to the Area + Room we started from when the entry was created.

**Comment by campbell-m** [comment]
> For the post-booking behavior: For the room view, if I start from a particular Area + Room, then add an entry, I am returned to the Area + "All" instead of the specific room. We'd like it to return to the Area + Room we started from when the entry was created.

Which version of MRBS are you running?

**Comment by dougbevan** [comment]
Version 1.9.4

**Comment by campbell-m** [comment]
You should upgrade to the latest version, 1.11.4.

**Comment by dougbevan** [comment]
Is there any way to fix it in 1.9.4 in the meantime?  I will schedule the upgrade too.

**Comment by campbell-m** [comment]
> Is there any way to fix it in 1.9.4 in the meantime?

Yes, but I'm afraid it would take more time than I have got to work out what it is.
