### ISSUE TITLE
Error Fatal

### ISSUE THREAD

**Issue by D1A9N8O4** [meeting-room-booking-system/mrbs-code#3591]
Hola, tengo problemas al visualizar las habitaciones y la descripcion de las entradas es una pagina en blanco sin nada de informacion.

error_log

`[09-Jan-2024 01:02:01 America/Santiago] Uncaught exception 'TypeError' in /2024/functions.inc at line 1588
MRBS\get_area_settings(): Argument #1 ($area) must be of type int, string given, called in /2024/Themes/default/header.inc on line 558
#0 /2024/Themes/default/header.inc(558): MRBS\get_area_settings('1')
#1 /2024/functions.inc(882): MRBS\print_theme_header(Array, false, false)
#2 /2024/view_entry.php(741): MRBS\print_header(Array)
#3 {main}

MRBS GET: Array
(
    [view] => day
    [year] => 2024
    [month] => 1
    [day] => 8
    [area] => 1
    [id] => 1
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [last_page] => /2024/index.php?view=day&view_all=1&year=2024&month=1&day=8&area=1&room=1
    [this_page] => /2024/view_entry.php?view=day&year=2024&month=1&day=8&area=1&id=1
    [csrf_token] => 045f3bec8ad468d9ae6c09783e8eb84101184e31935f61017da44cf1078393dc
    [user] => MRBS\User Object
        (
            [username] => admin
            [display_name] => admin
            [email] => mi@correo.com
            [level] => 2
            [data:protected] => Array
                (
                    [id] => 1
                    [password_hash] => $2y$10$znRUvl1lM1cagnlxl.OGw.DyjoLkwTCX42INdtHTQwAX3.EBAjhAW
                    [timestamp] => 2024-01-08 12:12:32
                    [last_login] => 1704771853
                    [reset_key_hash] => 
                    [reset_key_expiry] => 0
                )

        )

)

[09-Jan-2024 01:02:01 America/Santiago] PHP Fatal error:  Uncaught TypeError: MRBS\print_unsupported_message(): Argument #1 ($context) must be of type array, null given, called in /2024/Themes/default/header.inc on line 665 and defined in /2024/Themes/default/header.inc:502
Stack trace:
#0 /2024/Themes/default/header.inc(665): MRBS\print_unsupported_message(NULL)
#1 /2024/functions.inc(882): MRBS\print_theme_header(NULL, true, false)
#2 /2024/functions.inc(851): MRBS\print_header(NULL, true)
#3 /2024/functions_error.inc(295): MRBS\print_simple_header()
#4 /2024/functions_error.inc(285): MRBS\fatal_error('\xC2\xA1Mala suerte! ...')
#5 [internal function]: MRBS\exception_handler(Object(TypeError))
#6 {main}
  thrown in /2024/Themes/default/header.inc on line 502`

![Captura de pantalla 2024-01-09 a la(s) 01 16 46](https://github.com/meeting-room-booking-system/mrbs-code/assets/18706386/acb7dfca-c32a-42e8-976c-1442869f707c)

![Captura de pantalla 2024-01-09 a la(s) 01 18 20](https://github.com/meeting-room-booking-system/mrbs-code/assets/18706386/adcae331-d5d6-4141-87d5-01f8cb2a576c)

**Comment by campbell-m** [comment]
Can you try upgrading to the latest code in the [main branch](https://github.com/meeting-room-booking-system/mrbs-code)?

**Comment by D1A9N8O4** [comment]
La versión es la más reciente disponible en el main branch, fue descargada minutos antes de publicar el requerimiento de ayuda.

**Comment by D1A9N8O4** [comment]
MySQL

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/18706386/eacc24e2-3770-4c1c-8b6e-68553a729559)

**Comment by campbell-m** [comment]
I don't know why this is happening.  Can you run the attached diagnostic version of view_entry.php please and let me know the output? (You'll need to unzip the file first).
[view_entry.zip](https://github.com/meeting-room-booking-system/mrbs-code/files/13874695/view_entry.zip)

It should look something like

~~~text
array(7) { ["view"]=> string(3) "day" ["view_all"]=> int(1) ["year"]=> int(2024) ["month"]=> int(1) ["day"]=> int(9) ["area"]=> int(20) ["room"]=> int(51) }
~~~

**Comment by campbell-m** [comment]
Thanks.  Can you try this version of mrbs_sql.inc and see if it fixes the problem?

[mrbs_sql.zip](https://github.com/meeting-room-booking-system/mrbs-code/files/13875172/mrbs_sql.zip)

**Comment by D1A9N8O4** [comment]
Excelente, ahora se visualiza la información de la reserva en view entry.

Actualmente, solo quedaría resolver el poder visualizar las habitaciones en 

'''
2024/admin.php?view=day&page_date=2024-01-09&area=1&room=1
'''

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/18706386/0f6eb88b-514d-4dc7-9613-dd98ba865e7a)

**Comment by campbell-m** [comment]
What error message are you getting in your PHP error log?

**Comment by D1A9N8O4** [comment]
´´´
[09-Jan-2024 11:53:07 America/Santiago] Uncaught exception 'TypeError' in /2024/admin.php at line 21
MRBS\generate_room_delete_form(): Argument #1 ($room) must be of type int, string given, called in /2024/admin.php on line 565
#0 /2024/admin.php(565): MRBS\generate_room_delete_form('1', 1)
#1 {main}
´´´

**Comment by campbell-m** [comment]
Now fixed in [b6f9a24](https://github.com/meeting-room-booking-system/mrbs-code/commit/b6f9a24aae602a91387c7046fbee5d77f1fd9774).

**Comment by D1A9N8O4** [comment]
Estimado @campbell-m el error queda resuelto con tus indicaciones, una vez mas agradezco tu apoyo constante en el proyecto

**Comment by D1A9N8O4** [comment]
@campbell-m 
Creo que producto de las modificaciones ahora la vista semanal y mensual a dejado de funcionar.

error_log

```
[09-Jan-2024 12:51:23 America/Santiago] Uncaught exception 'TypeError' in /2024/functions_table.inc at line 802
MRBS\week_table_innerhtml(): Argument #2 ($view_all) must be of type int, bool given, called in /2024/index.php on line 452
#0 /2024/index.php(452): MRBS\week_table_innerhtml('week', false, 2024, 1, 9, 1, 1, NULL)
#1 {main}


[09-Jan-2024 12:51:23 America/Santiago] PHP Fatal error:  Uncaught TypeError: MRBS\print_unsupported_message(): Argument #1 ($context) must be of type array, null given, called in /2024/Themes/default/header.inc on line 665 and defined in /2024/Themes/default/header.inc:502
Stack trace:
#0 /2024/Themes/default/header.inc(665): MRBS\print_unsupported_message(NULL)
#1 /2024/functions.inc(882): MRBS\print_theme_header(NULL, true, false)
#2 /2024/functions.inc(851): MRBS\print_header(NULL, true)
#3 /2024/functions_error.inc(295): MRBS\print_simple_header()
#4 /2024/functions_error.inc(285): MRBS\fatal_error('\xC2\xA1Mala suerte! ...')
#5 [internal function]: MRBS\exception_handler(Object(TypeError))
#6 {main}
  thrown in /2024/Themes/default/header.inc on line 502
  ```

**Comment by campbell-m** [comment]
Are you still having issues or can this be closed?

**Comment by campbell-m** [comment]
I am closing this as I haven't heard anything more.
