### ISSUE TITLE
Es Locale error

### ISSUE THREAD

**Issue by fidegr** [meeting-room-booking-system/mrbs-code#3592]
Hi, I am having the following error on my mrbs installation

Notice: Server failed to set locale to ["es.UTF-8","es-ES.UTF-8","es_ES.UTF-8"] for language tag 'es'....

This is the language setting

$disable_automatic_language_changing = 1;
$mail_settings['admin_lang'] = 'es';
$default_language_tokens = "es";
$faqfilelang = "_es"; 
$db_persist = FALSE;
$weekstarts = 1;
$theme = "default";
#default_view = "week";
$override_locale = "es"; 
$display_timezone = true;

**Comment by campbell-m** [comment]
What operating system are you running on your server?  Have you got the 'es' locale installed?

**Comment by campbell-m** [comment]
I haven't heard back so assume this is now resolved.
