### ISSUE TITLE
Several Booking days

### ISSUE THREAD

**Issue by hornse** [meeting-room-booking-system/mrbs-code#3593]
Hi there,

I defined several areas f.e. A and B and each area has got 5 rooms. All Rooms of area A should be bookable on Monday and tuesday (the other days shouldn't be visible nor bookable) and all rooms of area B should be bookable on Tuesday and Friday  (the other days shouldn't be visible nor bookable).

So I need different booking days for different areas. Is ist possible to realise?

Thanks for helping

Sebastian

**Comment by campbell-m** [comment]
The best thing to do is just book out the days that aren't bookable in each area as "Unavailable".  You could also use a new type "Unavailable" for this and make it for use by admins only.

As well as doing that you could also use the `$hidden_days` config variable, which is a global setting and applies to all areas, to hide the days that aren't bookable in either area, ie Wednesday, Thursday, Saturday and Sunday:

~~~php
$hidden_days = [0, 3, 4, 6];  // Su, We, Th, Sa
~~~

**Comment by hornse** [comment]
Thanks for answering! I will try this
