### ISSUE TITLE
How to get the design of the demo page?

### ISSUE THREAD

**Issue by AR1803** [meeting-room-booking-system/mrbs-code#3594]
I took a look on your demo page and liked it, so I got the installation via docker-compose  and was wondering about the dark design. How can I change it to the style of the demo pages? Thank you.

**Comment by campbell-m** [comment]
That should be the default design, so I am not quite sure why you are not getting it.  Can you post a screenshot of what you are getting?

**Comment by AR1803** [comment]
Thank you  for your fast feedback.  I really like the design of the demos . I also have no clue where to change the company name. Thank you very much. 
![mrbs](https://github.com/meeting-room-booking-system/mrbs-code/assets/157016790/a50d5df3-c3fb-4fab-9d5a-63383b29cf90)

**Comment by campbell-m** [comment]
Thanks.  I don't recognise that at all.  Can you post the URL of where you got the code. Maybe it's from a fork?

**Comment by AR1803** [comment]
You are right. https://github.com/dorianim/modern-mrbs-theme

**Comment by campbell-m** [comment]
OK.  You can change the company name by setting in your config.inc.php file:

~~~php
$mrbs_company = "Your Company";
~~~
