### ISSUE TITLE
Only Admin should book repeat

### ISSUE THREAD

**Issue by hornse** [meeting-room-booking-system/mrbs-code#3595]
Hi there,
I am looking for a way, that only admin should book repeat (or no one!). Is it possible to customise the GUI so that the displays for serial bookings are not visible?

with kind regards

Sebastian

**Comment by campbell-m** [comment]
Just set in your config file

~~~php
$auth['only_admin_can_book_repeat'] = treat;
~~~

**Comment by hornse** [comment]
Perfect Thanks
