### ISSUE TITLE
Request assistance in how to upgrade 1.4.11 to the newest version on our Server (CPANEL based).

### ISSUE THREAD

**Issue by AndreBotha47** [meeting-room-booking-system/mrbs-code#3597]
**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Browser details (please complete the following information):**

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]
 - Web server: [e.g. Apache 2.4.48]
 - OS: [e.g. CentOS 7.9]
 - PHP version: [e.g. 7.4.23]
 - Database used: [e.g. MySQL 8.0.26]

**Additional context**

**Comment by campbell-m** [comment]
You should download the latest release and then follow the steps in the UPGRADE document.

**Comment by AndreBotha47** [comment]
Hi, I tried to follow the steps, but am unable to get the program to run. Could you please assist.

**Comment by campbell-m** [comment]
Can you give more details please?  What happens or doesn't happen?  What are you seeing in your PHP error log?

**Comment by AndreBotha47** [comment]
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/98016481/ff0e5590-6e17-4371-b008-e4777eddffa1)

With 1.4.11 there was the DAY.PHP that ran. I notice now with the latest version there is no more DAY.PHP ... I have no idea if I am doing this correctly. I am going to return 1.4.11 with config file. Is it possible to Anydesk me to assist me in updating the program correctly?

**Comment by AndreBotha47** [comment]
I know the path is correct as it does display the logo when I enter the logo's path.
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/98016481/276fc8f6-1553-42f2-b0a3-f43de1ab1316)

**Comment by AndreBotha47** [comment]
We moved from a web server to a dedicated server, so the server address changed, but it is also a different PHP version. The program and database was transferred from previous server to the new one, but since then it just does not work.

**Comment by campbell-m** [comment]
There is no more day.php: just run index.php.  I am afraid I do not have time to help via AnyDesk.

**Comment by AndreBotha47** [comment]
Let me just confirm. The database is in place and the config file is in place. When I update the program. Could I simply just upload the new version to the server (CPANEL based) and overwrite?

**Comment by campbell-m** [comment]
What you should do is:

1. Take a backup of your database tables in case something goes wrong and you need to revert to 1.4.11.
2. Take a copy of your 1.4.11 web folder in case something goes wrong.
3. Upload the new version to the server, to a new folder, eg mrbs_tmp
4. Copy your old config file into mrbs_tmp
5. Run mrbs_tmp/index.php.  You will be asked to enter your _database_ username and password so that the database can be upgraded.
6. When you are happy with the new system rename mrbs to mrbs_old and mrbs_new to mrbs.

**Comment by AndreBotha47** [comment]
I will do all these steps now. Thank you. I will call again when I am done and I hope being successful.

**Comment by AndreBotha47** [comment]
what would be the quickest way to upload it to the server (mbs_tmp)?

**Comment by campbell-m** [comment]
Use FTP, eg through the Filezilla program.

**Comment by AndreBotha47** [comment]
Thank you. Let me do that.

**Comment by AndreBotha47** [comment]
Good day again. I wish to thank you for all your support. IT WORKS!!!! Thank you thank you thank you. I think I was just stressing a bit and made stupid mistakes. Thank you again!

**Comment by campbell-m** [comment]
Good.  Although it's working, you might want to check your PHP error log for possible messages about settings that have changed in the config file.  Some variables have been renamed in later versions of MRBS.
