### ISSUE TITLE
Hi, I have contacted you earlier on how to upgrade from 1.4.11 to the newest version. I am really struggling. Could somebody please assist me in this regard as we are unable to use the program due to the PHP version too new for 1.4.11 The database is all good; I just need to upgrade the program. 

### ISSUE THREAD

**Issue by AndreBotha47** [meeting-room-booking-system/mrbs-code#3598]
**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Browser details (please complete the following information):**

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]
 - Web server: [e.g. Apache 2.4.48]
 - OS: [e.g. CentOS 7.9]
 - PHP version: [e.g. 7.4.23]
 - Database used: [e.g. MySQL 8.0.26]

**Additional context**

**Comment by campbell-m** [comment]
See my response to Issue #3597 .
