### ISSUE TITLE
Changing the denotation of bookings not yet approved

### ISSUE THREAD

**Issue by campbell-m** [meeting-room-booking-system/mrbs-code#3599]
(Moved from Issue #3585)

Hello! For bookings yet to be approved, how can we change the ? char on the calendar display to something else such as a prefix of [TO BE APPROVED] or something of that sort to make it more clear that the booking has'nt been approved as yet.

**Comment by campbell-m** [comment]
Create a custom CSS file (see systemdefaults.inc.php for how to do this) and add the rule

~~~css
.awaiting_approval a::before {
  content: '[TO BE APPROVED]';
}
~~~

**Comment by sauadmin** [comment]
Thanks, it works.
