### ISSUE TITLE
Dates in E-Mails are no longer traslated

### ISSUE THREAD

**Issue by Stachelritter** [meeting-room-booking-system/mrbs-code#36]
**Describe the problem you're facing/question you have**
After updating from 1.9.4 to 1.10.0, dates in E-Mail notifications are no longer translated, although the rest of the e-mail content is translated correctly.

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 99.0

**Server details (please complete the following information):**
 - MRBS version 1.10.0
 - Web server: Apache
 - OS: Linux four 4.15.18-13-pve # 1 SMP PVE 4.15.18-37 x86_64
 - PHP version: 8.0.16
 - Database used: MySQL 5.7.25

**Additional context**
Maybe important configuration globals in config.inc.php
$strftime_format['datetime24']         = "%A %d %B %Y %R"; 
$mail_settings['admin_lang'] = 'de';

Browser language preferences: de, en-US, en

**Comment by campbell-m** [comment]
Mmm, I can't reproduce this.   What PHP extensions are installed on your system?  The answer is on the MRBS Help page when logged in as an admin.

**Comment by Stachelritter** [comment]
The following extensions are installed: 
Core,  FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2,  calendar, cgi-fcgi, ctype, curl, date, dba, dom, enchant, exif,  fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap,  intl, json, libxml, limiter, mbstring, mysqli, mysqlnd, openssl, pcntl,  pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, session, shmop,  soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm,  tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib

The dates shown in view_entry.php or pending.php (and all other webpages) are also translated correctly. Only in the e-mail the date is in english, but with the correct format defiend in $strftime_format['datetime24']. Changing the format doesn't help.

**Comment by campbell-m** [comment]
Thanks.  Can you try two things please:

1. If you are able to then temporarily disable the intl extension and see if that makes a difference?
2. With the intl extension enabled, run the attached test program in your MRBS folder (ie at the same level as config.inc.php) and post the output here?  Note that you'll have to rename it from test.php.txt to test.php as GitHub won't let me attach a .php file.
[test.php.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/8494977/test.php.txt)

**Comment by Stachelritter** [comment]
Unfortunately, I am not able to disable the extension on the server running mrbs.
The output of your testfile: 
array(3) { [0]=> string(8) "de.UTF-8" [1]=> string(11) "de-DE.UTF-8" [2]=> string(11) "de_DE.UTF-8" }

**Comment by campbell-m** [comment]
Thanks.  Can you try the following, slightly modified, test file please?  It should echo the current date and time.
[test.php.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/8495542/test.php.txt)

**Comment by Stachelritter** [comment]
I'm sorry, but it echos the current date and time in english.

**Comment by campbell-m** [comment]
That's OK - I'd have been surprised if it wasn't in English.   Here's another test program.
[test.php.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/8496857/test.php.txt)

**Comment by Stachelritter** [comment]
And here's the next result:
de.UTF-8: Friday 15 April 2022 17:59
de-DE.UTF-8: Freitag 15 April 2022 17:59
de_DE.UTF-8: Freitag 15 April 2022 17:59
de: Freitag 15 April 2022 17:59

**Comment by campbell-m** [comment]
OK, thanks.  I'll need to think about that. The problem is to with what values of $locale are accepted by IntlDateFormatter.

**Comment by campbell-m** [comment]
In the short term you could try setting your admin_lang to 'de-DE' or 'de_DE'.

**Comment by Stachelritter** [comment]
When I set the variable to de_DE or de-DE, the date in the email is translated, but the rest of the email is not. The web application is also still translated correctly.

**Comment by campbell-m** [comment]
Try copying lang.de to lang.de_DE

**Comment by Stachelritter** [comment]
Unfortunately, this does not work either.

**Comment by campbell-m** [comment]
Sorry.  Try copying lang.de to lang.de_de and lang.de-de

**Comment by Stachelritter** [comment]
Thanks, this works. 
Is there anything else I can do to help you find the cause?

**Comment by campbell-m** [comment]
I think the problem is to do with the way MRBS interacts with your server.  Can you give me more details of your server please?  Is it run by a hosting company?  If so which one?   Or are you running your own Linux distro?  If so, which one?

**Comment by campbell-m** [comment]
Thanks.  What's the output of phpinfo() for the intl extension?

**Comment by Stachelritter** [comment]
<html><body>
<h2><a name="module_intl">intl</a></h2>


Internationalization support | enabled
-- | --
ICU version | 52.1
ICU Data version | 52.1
ICU Unicode version | 6.3


</body>
</html>
<html><body>


Directive | Local Value | Master Value
-- | -- | --
intl.default_locale | no value | no value
intl.error_level | 0 | 0
intl.use_exceptions | Off | Off


</body>
</html>

**Comment by campbell-m** [comment]
One more test.  Could you run the attached test program and post the output please?  It should list the locales available on your system.
[test.php.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/8645237/test.php.txt)

**Comment by Stachelritter** [comment]
I assume this is an isolated incident that does not affect many other people. Unfortunately, I can't test any more because the hoster has migrated my tariff to a more modern server. There, everything works fine...

**Comment by Stachelritter** [comment]
Thanks for your patience! :)

**Comment by campbell-m** [comment]
Yes, nobody else has reported this problem and I think it was to do with something odd about your old server.   Maybe there's a way MRBS could handle such cases better, but until someone else reports a similar problem it's probably not worth worrying about.

Glad everything's working fine now.
