### ISSUE TITLE
Calendars position

### ISSUE THREAD

**Issue by AndreBotha47** [meeting-room-booking-system/mrbs-code#3601]
I am using the current version of MRBS 1.11.4 and it works perfectly.

Is there possibly a method or setting I could change to position the 2 calendars on top  of the bookings register.

The reason for that is to have more width available on the desktop area for the bookings register. 

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/98016481/c554c7a4-7d21-4829-8b0d-aca3f8f19117)

Thank you
Andre Botha

**Comment by campbell-m** [comment]
Set in your config file

~~~php
$display_mincals_above = true;
~~~

Note that this will only work if the browser window is tall enough.

**Comment by AndreBotha47** [comment]
Thank you very much. Thank you for identiying the situation regarding the height of the browser window.

**Comment by campbell-m** [comment]
The other thing you can do is just not display them at all:

~~~php
$display_mincals = false;
~~~

**Comment by AndreBotha47** [comment]
Thank you for the amazing feedback; like always.

**Comment by campbell-m** [comment]
Try doing a hard refresh of your browser to clear CSS and JavaScript files from its cache.

**Comment by campbell-m** [comment]
> Hi!, I can't get the mincals above neither hide them.
First tried: $display_mincals_above = true;
Then: $display_mincals = false;

> It's seem as if mrbs wasen't reading the config.inc.php

See Issue #3808.
