### ISSUE TITLE
php 8 upgrade doesn't work

### ISSUE THREAD

**Issue by Metz01** [meeting-room-booking-system/mrbs-code#3602]
Hello,

I recently upgraded PHP from version 7.3 to 8.2 while experimenting with simpleSAML. Prior to this change, everything worked seamlessly. However, after the upgrade, I encountered a series of warnings and errors:
```

Notice: Server failed to set locale to ["en-US.UTF-8","en_US.UTF-8"] for language tag 'en-US'. in /var/www/html/rooms/language.inc on line 175

...

Uncaught exception 'Exception' in /var/www/html/rooms/lib/MRBS/Session/Session.php at line 110
MRBS: could not start sessions
#0 /var/www/html/rooms/lib/MRBS/Session/Session.php(24): MRBS\Session\Session->init(2592000)
#1 /var/www/html/rooms/lib/MRBS/Session/SessionWithLogin.php(31): MRBS\Session\Session->__construct()
#2 /var/www/html/rooms/lib/MRBS/Session/SessionPhp.php(19): MRBS\Session\SessionWithLogin->__construct()
#3 /var/www/html/rooms/lib/MRBS/Session/SessionFactory.php(14): MRBS\Session\SessionPhp->__construct()
#4 /var/www/html/rooms/mrbs_auth.inc(33): MRBS\Session\SessionFactory::create('php')
#5 /var/www/html/rooms/init.inc(40): MRBS\session()
#6 /var/www/html/rooms/defaultincludes.inc(34): require_once('/var/www/html/r...')
#7 /var/www/html/rooms/index.php(8): require('/var/www/html/r...')
#8 {main}
```

Any idea of where the problem is?
Thank you for the support.

**Comment by campbell-m** [comment]
Which version of MRBS are you running?

**Comment by campbell-m** [comment]
And what have you got `$auth['type']` and `$auth['session']` set to?

**Comment by Metz01** [comment]
Unforunatly I had to go back to php 7.4 for time reasons, and got what I was trying to achive, so I can no longer reproduce the error easly.
By the way, I made a fork at the commit 3e0bd34 of mrbs of the 23/11/24. 
As for the second question, I had: $auth["type"] = "ldap"; 
About the $auth['session'] I don't remember where to find it.

In any case, thanks for the support
