### ISSUE TITLE
Problem in displaying rooms and added users

### ISSUE THREAD

**Issue by Lucaccc** [meeting-room-booking-system/mrbs-code#3604]
Good morning. 
I have installed the platform on hosting altervista and I can reach it online.
The problem is that: when I enter rooms/ users these are not viewable from the admin side, nor from other users.
I specify that the data entered are present in the db.

Thank you!

**Comment by campbell-m** [comment]
There is a known problem with the Altervista platform: see https://github.com/meeting-room-booking-system/mrbs-code/issues/3579.

Can you try editing the method updateTimestamp() in the file lib/MRBS/SessionHandlerDb.php and changing line 245 (roughly, depending on version) from

~~~php
      $result = (1 === db()->command($sql, $sql_params));
~~~

to

~~~php
      $result = true;
~~~

If that works then it is the same problem.

**Comment by Lucaccc** [comment]
> There is a known problem with the Altervista platform: see #3579.
> 
> Can you try editing the method updateTimestamp() in the file lib/MRBS/SessionHandlerDb.php and changing line 245 (roughly, depending on version) from
> 
> ```
>       $result = (1 === db()->command($sql, $sql_params));
> ```
> 
> to
> 
> ```
>       $result = true;
> ```
> 
> If that works then it is the same problem.

Good morning.
I did, but I still have the same problem.

**Comment by campbell-m** [comment]
Which version of MRBS are you running?
