### ISSUE TITLE
Hide the Created by: from everyone other than admins.

### ISSUE THREAD

**Issue by mcrockettrvu** [meeting-room-booking-system/mrbs-code#3608]
Is there an easy way to hide the Created by: field on created entries from everyone except admins?  We have a large user base, and there have been concerns of stalking from a couple of individuals.  We want for admins to still be able to see that field, but hide it from everyone else.

**Comment by campbell-m** [comment]
Yes.  All you need to do is to change the area settings for the area in question from the Rooms page and under privacy settings select "Treat all bookings as private, ignoring their privacy settings".  Then in your config file set

~~~php
$is_private_field['entry.name'] = false;
$is_private_field['entry.description'] = false;
$is_private_field['entry.create_by'] = true;  // create_by is true by default, so you don't really need this
$is_private_field['entry.modified_by'] = false;
~~~

**Comment by mcrockettrvu** [comment]
I think that did exactly what I needed it to.  Thanks again for your help.
