### ISSUE TITLE
upgrading OS to 22.04 php upgrading to 8.1 from 7.4 and mrbs from 1.7 to latest version

### ISSUE THREAD

**Issue by iainmsi** [meeting-room-booking-system/mrbs-code#3611]
I'm getting a php error after my php version was upgraded during an OS upgrade r  PHP Fatal error:  __autoload() is no longer supported, use spl_autoload_register() instead in /var/www/bookings/rooms/lib/PHPMailer/PHPMailerAutoload.php on line 45

I did try and alter the file but didn't seem to work, and I didn't want to really downgrade php back to versionn 7.4

**Comment by campbell-m** [comment]
You need to upgrade to the latest version of MRBS.  Download the code and follow the instructions in the UPGRADE document.

**Comment by campbell-m** [comment]
I assume this can now be closed?

**Comment by iainmsi** [comment]
Yes this can be closedOn 26 Feb 2024, at 15:05, campbell-m ***@***.***> wrote:﻿
I assume this can now be closed?
