### ISSUE TITLE
Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/html/language.inc on line 176

### ISSUE THREAD

**Issue by jaigori** [meeting-room-booking-system/mrbs-code#3615]
**Describe the bug**
After a new fresh installation from git and I try to access to MRBS I get this error:

> Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/html/language.inc on line 176

**To Reproduce**
1. Clone from git: git clone https://github.com/meeting-room-booking-system/mrbs-code.git
2. Change to the directory: docker_app
3. docker-compose up -d
4. Try access to : http://localhost:8080/
5. Get the error

**Browser details (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS (Spanish)
 - Browser: Firefox
**Server details (please complete the following information):**
 - MRBS version : last from github
 - Web server: docker
 - PHP version: docker
 - Database used:docker

**Additional context**
I read somothing about this bug, but I cant get solve the problem. 
After access to the docker 
`docker run -it docker_app_www bash
locale -a 
C
C.UTF-8
POSIX

root@327eade05e13:/var/www/html# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

`

**Comment by campbell-m** [comment]
You need to install the 'en' locale on your server, together with any other locales you may want to use, eg 'es' (given that you have Spanish Ubuntu).

**Comment by jaigori** [comment]
Hi, I modified the Docker file and add this lines:
```
RUN apt-get update && apt-get install -y locales && \
  sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && \
  sed -i 's/^# *\(en_GB.UTF-8\)/\1/' /etc/locale.gen && \
  locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

```An now everything is working fine.
thanks.
