### ISSUE TITLE
ldap no longer working after upgrade from 1.71  to 1.1.4

### ISSUE THREAD

**Issue by iainmsi** [meeting-room-booking-system/mrbs-code#3616]
Hi I can no longer login via ldap
i'm seeing this Auth\\AuthLdap->action(811): no DN determined, not calling callback, referer: 
initial bind failed: Inappropriate authentication [Anonymous Simple Bind Disabled.],

in my config.inc.php

~~~php
$ldap_host = "xxxxxxxxx";
$ldap_v3 = false;
$ldap_base_dn[] = "ou=xxx, o=xxx";
$ldap_base_dn[] = "ou=xxx, o=xxx";
$ldap_user_attrib = "cn";
~~~

thanks

**Comment by campbell-m** [comment]
Could you post the full (redacted) debug output please when you have `$ldap_debug = true;`?

**Comment by iainmsi** [comment]
I've reverted the server back to working so can go back into the logs but I did take this before doing so

[Wed Feb 21 20:29:23.569022 2024] [php:notice] [pid 8845] [client 130.209.17.62:62992] \nE_USER_WARNING in /var/www/bookings/rooms/lib/MRBS/Auth/AuthLdap.php at line 855\nInappropriate authentication\nMRBS GET: Array\n(\n)\nMRBS POST: Array\n(\n    [csrf_token] => ee13b327d929663667ac3e2d6e5f258d61b1c51ad1efb7786f83e926c021fee2\n    [target_url] => index.php\n    [action] => SetName\n    [username] => ****\n    [password] => ****\n)\nMRBS SESSION: Array\n(\n    [last_page] => /rooms/admin.php\n    [this_page] => /rooms/admin.php\n    [csrf_token] => ee13b327d929663667ac3e2d6e5f258d61b1c51ad1efb7786f83e926c021fee2\n    [user] => \n)\n\n, referer: https://bookings.tcrc.gla.ac.uk/rooms/admin.php
[Wed Feb 21 20:29:23.569050 2024] [php:notice] [pid 8845] [client 130.209.17.62:62992] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(754): initial bind failed: Inappropriate authentication [Anonymous Simple Bind Disabled.], referer: https://bookings.tcrc.gla.ac.uk/rooms/admin.php
[Wed Feb 21 20:29:23.569067 2024] [php:notice] [pid 8845] [client 130.209.17.62:62992] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(811): no DN determined, not calling callback, referer: https://xxxxxxxxx/rooms/admin.php
root@bookings:/var/www/bookings/rooms#
root@bookings:/var/www/bookings/rooms# [Wed Feb 21 20:29:23.569050 2024] [php:notice] [pid 8845] [client 130.209.17.62:62992] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(754): initial bind failed: Inappropriate authentication [Anonymous Simple Bind Disabled.], referer: https://xxxxxxx/rooms/admin.php
bash: syntax error near unexpected token `('
root@bookings:/var/www/bookings/rooms# [Wed Feb 21 20:29:23.569067 2024] [php:notice] [pid 8845] [client 130.209.17.62:62992] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(811): no DN determined, not calling callback, referer: https://xxxxxxxx/rooms/admin.php

**Comment by campbell-m** [comment]
Thanks.  I suspect it's because you haven't got `$ldap_dn_search_dn` and `$ldap_dn_search_password` set.  These are now needed because MRBS now retrieves users' details such as didplay name and email address.  See

~~~php
// If you need to search the directory to find the user's DN to bind
// with, set the following to the attribute that holds the user's
// "username". In Microsoft AD directories this is "sAMAccountName"
// This can be an array.
//$ldap_dn_search_attrib = "sAMAccountName";

// If you need to bind as a particular user to do the search described
// above, specify the DN and password in the variables below
// These two parameters can be arrays.
// $ldap_dn_search_dn = "cn=Search User,ou=Users,dc=example,dc=com"; // Any compliant LDAP
// $ldap_dn_search_dn = "searchuser@example.com"; // A form which could work for AD LDAP
// $ldap_dn_search_password = "some-password";
~~~

**Comment by iainmsi** [comment]
hi it's eDirectory not AD we use would $ldap_dn_search_attrib = "sAMAccountName"; not be $ldap_dn_search_attrib = "uid";
and would i still need to use some stored credentials to bind or i'd still get anonymous bind error?

**Comment by campbell-m** [comment]
I'm not familiar with eDirectory, but yes probably 'uid'.  And yes, you'd need to use some stored credentials.

**Comment by iainmsi** [comment]
ok got the login sorted by creating a service account and adding 
$ldap_dn_search_attrib = "uid";
$ldap_dn_search_dn = "cn=xxxx,ou=Service,o=xxxxx";
$ldap_dn_search_password = "xxxxxxx";  however I can login fine I see the calendar entries  when I try and add an entry edit_entry.php some times I can start adding information but usually it crashes aww Error code: RESULT_CODE_HUNG

any ideas?

**Comment by campbell-m** [comment]
I haven't met this one before.  A search for "RESULT_CODE_HUNG" suggests trying a different browser or disabling Chrome extensions.

**Comment by iainmsi** [comment]
Unfortunately other users testing find the same the its hanging and crashing when you try to add an entry - I might add it crashes chrome and edge but works in firefox?

**Comment by campbell-m** [comment]
Can you try two things:

1. Setting `$debug = true;` in your config file and see if you get any error messages in yoiur browser?
2. Looking in Chrome's Developoment Tools and seeing if you get any error messages in the browser console?

**Comment by iainmsi** [comment]
[client xxx.xxx.xx.xx:53219] \nE_USER_NOTICE in /var/www/bookings/rooms/lib/MRBS/Form/Form.php at line 90\nPossible CSRF attack from IP address xxx.xxx.xx.xx\n#0 MRBS\\generate_backtrace() called at [/var/www/bookings/rooms/functions_error.inc:219]\n#1 MRBS\\output_error() called at [/var/www/bookings/rooms/functions_error.inc:249]\n#2 MRBS\\error_handler(1024, Possible CSRF attack from IP address xxx.xxx.xxx.xxx, /var/www/bookings/rooms/lib/MRBS/Form/Form.php, 90)\n#3 trigger_error(Possible CSRF attack from IP address xxx,xxx xxxxx1024) called at [/var/www/bookings/rooms/lib/MRBS/Form/Form.php:90]\n#4 MRBS\\Form\\Form::checkToken() called at [/var/www/bookings/rooms/edit_entry_handler.php:77]\n, referer: https://bookings.mvls.gla.ac.uk/rooms/edit_entry.php?view=day&year=2024&month=2&day=26&area=2&room=16&hour=12&minute=3

**Comment by iainmsi** [comment]
chrome says 
A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form.
To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.

**Comment by iainmsi** [comment]
I've disabled mailed settings but no difference.

**Comment by campbell-m** [comment]
> A form field element has neither an id nor a name attribute

Strange.  I wonder whether this has been inserted by a Chrome extension?  Can you identify the form field element?

Another thing to try is install Chrome Canary (without any extensions) and see if you get the error then.

**Comment by campbell-m** [comment]
Can you identify the form field element?

**Comment by iainmsi** [comment]
i'm seeing this in chrome
Deprecated feature used
Unload event listeners are deprecated and will be removed.
1 source
onloadwff.js:71

**Comment by campbell-m** [comment]
What happens if you run MRBS from an incognito tab in Chrome?

**Comment by iainmsi** [comment]
still the same freezes

**Comment by iainmsi** [comment]
Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.

JQMIGRATE: Migrate is installed with logging active, version 3.4.0
jquery-migrate-3.4.0.js:135 JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray

**Comment by iainmsi** [comment]
No label associated with a form field
A <label> isn't associated with a form field.
To fix this issue, nest the <input> in the <label> or provide a for attribute on the <label> that matches a form field id.

**Comment by campbell-m** [comment]
I can only think of two things to try:

1.  Trying to eliminate LDAP as the cause, by changing `$auth['type']` to 'db' - just for testing.
2.  If your site is on the internet and you're prepared to give me a test login, you can contact me at cimorrison at users dot sourceforge dot net.  If not, I completely understand.

**Comment by iainmsi** [comment]
its working with $auth['type'] to 'db'

**Comment by iainmsi** [comment]
thats all i'm seeing in the apache log [Mon Feb 26 11:43:01.224292 2024] [php:notice] [pid 125119] [client xxx.xxx.xx.xxx:57543] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(741): binding with search_dn and search_password, referer: https://xxx.xxx.xx.xxx/rooms/edit_entry.php?view=day&year=2024&month=3&day=20&area=2&                                                 room=7&hour=18&minute=0
[Mon Feb 26 11:43:01.234116 2024] [php:notice] [pid 125119] [client xxx.xxx.xx.xxx:57543] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(758): initial bind was successful, referer: https://xxx.xxx.xx.xxx/rooms/edit_entry.php?view=day&year=2024&month=3&day=20&area=2&room=7&hour=18&                                                 minute=0
[Mon Feb 26 11:43:01.234163 2024] [php:notice] [pid 125119] [client xxx.xxx.xx.xxx:57543] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(763): searching using base_dn 'ou=student, o=gla' and filter '(uid=xxx)', referer: https://xxx.xxx.xx.xxx/rooms/edit_entry.php?view=day&year=20                                                 24&month=3&day=20&area=2&room=7&hour=18&minute=0
[Mon Feb 26 11:43:01.235753 2024] [php:notice] [pid 125119] [client xxx.xxx.xx.xxx:57543] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(781): 0 entries found, no unique dn, referer: https://xxx.xxx.xx.xxx/rooms/edit_entry.php?view=day&year=2024&month=3&day=20&area=2&room=7&hour=1                                                 8&minute=0
[Mon Feb 26 11:43:01.235800 2024] [php:notice] [pid 125119] [client xxx.xxx.xx.xxx:57543] [MRBS DEBUG] MRBS\\Auth\\AuthLdap::getUsernamesCallback(525): base_dn 'ou=student, o=gla', referer: https://xxx.xxx.xx.xxx/rooms/edit_entry.php?view=day&year=2024&month=3&day=20&area=2&r                                                 oom=7&hour=18&minute=0
[Mon Feb 26 11:43:01.235825 2024] [php:notice] [pid 125119] [client xxx.xxx.xx.xxx:57543] [MRBS DEBUG] MRBS\\Auth\\AuthLdap::getUsernamesCallback(554): searching with base_dn 'ou=student, o=gla' and filter '(objectclass=*)', referer: https://xxx.xxx.xx.xxx/rooms/edit_entry.ph                                                 p?view=day&year=2024&month=3&day=20&area=2&room=7&hour=18&minute=0
[Mon Feb 26 11:43:04.394362 2024] [php:notice] [pid 125119] [client xxx.xxx.xx.xxx:57543] [MRBS DEBUG] MRBS\\Auth\\AuthLdap::getUsernamesCallback(565): 68151 entries found in 3.1541790962219 seconds, referer: https://xxx.xxx.xx.xxx/rooms/edit_entry.php?view=day&year=2024&mont                                                 h=3&day=20&area=2&room=7&hour=18&minute=0

**Comment by campbell-m** [comment]
Ah, the problem may be that your LDAP directory is very large and MRBS isn't good at handling these (it needs to do paged searches, but doesn't yet).  Can you try setting

~~~php
$get_display_names_all_at_once = false;
~~~

**Comment by iainmsi** [comment]
$get_display_names_all_at_once = false;  just in the config.inc.php  doesn't seem to make a difference

**Comment by campbell-m** [comment]
What's the LDAP debug output when you have `$get_display_names_all_at_once = false;`?

**Comment by iainmsi** [comment]
is strange it works in firefox and also its the edit entry page that crashes not the initial login

**Comment by campbell-m** [comment]
Yes, I don't understand why it works in Firefox and not Chrome.  What exactly does the crash look like?  Where do you see the RESULT_CODE_HUNG message?

**Comment by iainmsi** [comment]
you get a page unresponsive message with wait or exit if you exit you get a AW, SNAP! something went wrong displaying this web page.
Error code: RESULT_CODE_HUNG

**Comment by campbell-m** [comment]
One more thing to try.  Can you set

~~~php
$auth['admin_can_only_book_for_self'] = true;
~~~

This stops admins being presented with a select drop-down of all available users on the edit_entry page.  On your site there are lots of them and it could be causing Chrome to run out of memory.

**Comment by iainmsi** [comment]
that's it working thankyou

**Comment by campbell-m** [comment]
Good.  You can now undo `$get_display_names_all_at_once = false; `.  Retrieving display names all at once will improve performance for things like reports.
