### ISSUE TITLE
How to restrict ordinary users from booking only 5 rooms at the same time period

### ISSUE THREAD

**Issue by wobuzhidaobug** [meeting-room-booking-system/mrbs-code#3617]
**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Browser details (please complete the following information):**

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]
 - Web server: [e.g. Apache 2.4.48]
 - OS: [e.g. CentOS 7.9]
 - PHP version: [e.g. 7.4.23]
 - Database used: [e.g. MySQL 8.0.26]

**Additional context**

**Comment by wobuzhidaobug** [comment]
> 如果您运行的是 MRBS 1.11.4，则需要`$prevent_simultaneous_bookings = true`在配置文件中进行设置。这将防止普通用户同时预订多个房间。要将限制增加到 5，您需要在 mrbs_sql.inc 中进行以下代码更改：
> 
> 1. 删除第 544 行：
> 
> ```
>       $sql .= " LIMIT 1";
> ```
> 
> 2. 将第 548 行更改为
> 
> ```
>       if ($res->count() > 0)
> ```
> 
> 到
> 
> ```
>       if ($res->count() >= 5)
> ```
> 
> 3. 将第 2369 行更改为
> 
> ```
>         if ($non_admin_rooms > 1)
> ```
> 
> 到
> 
> ```
>         if (($auth['only_admin_can_select_multiroom'] && $non_admin_rooms > 1) || ($prevent_simultaneous_bookings && $non_admin_rooms > 5))
> ```

Where can I change the content of the prompt:
（1）You cannot have bookings for two different rooms at the same time

**Comment by campbell-m** [comment]
In your config file:

~~~php
$vocab_override["en"]["no_simultaneous_bookings"]        = "You cannot have bookings for two different rooms at the same time";
$vocab_override["zh-cn"]["no_simultaneous_bookings"]        = "You cannot have bookings for two different rooms at the same time";
$vocab_override["zh-tw"]["no_simultaneous_bookings"]        = "You cannot have bookings for two different rooms at the same time";
~~~

**Comment by campbell-m** [comment]
Sorry, I've just realised that the solution above won't work.  The problem is much more complicated.  I'll think some more about it.

**Comment by campbell-m** [comment]
Not as complicated as I thought.  I've added this feature to the main branch in [1c1459f](https://github.com/meeting-room-booking-system/mrbs-code/commit/1c1459fab0f01c90f715708c6c558b75e8632027).   To use the code download the latest MRBS code from [this page](https://github.com/meeting-room-booking-system/mrbs-code) by following the green Code button.  Treat it like a new release and set in your config file

~~~php
$prevent_simultaneous_bookings = true;
$max_simultaneous_bookings = 5;
$vocab_override["zh-cn"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
$vocab_override["zh-tw"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
~~~

**Comment by wobuzhidaobug** [comment]
> 没有我想象的那么复杂。[我已将此功能添加到1c1459f](https://github.com/meeting-room-booking-system/mrbs-code/commit/1c1459fab0f01c90f715708c6c558b75e8632027)的主分支中。要使用该代码，请按照绿色代码按钮从此[页面下载最新的 MRBS 代码。](https://github.com/meeting-room-booking-system/mrbs-code)将其视为新版本并在配置文件中设置
> 
> ```
> $prevent_simultaneous_bookings = true;
> $max_simultaneous_bookings = 5;
> $vocab_override["zh-cn"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
> $vocab_override["zh-tw"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
> ```
thank you very much

**Comment by wobuzhidaobug** [comment]
> > 没有我想象的那么复杂。[我已经把前面的功能添加到1c1459f](https://github.com/meeting-room-booking-system/mrbs-code/commit/1c1459fab0f01c90f715708c6c558b75e8632027)的主分支中。要使用该代码，请按照绿色代码按钮然后[页面下载最新的MRBS代码。](https://github.com/meeting-room-booking-system/mrbs-code)将其新版本并在配置文件中设置
> > ```
> > $prevent_simultaneous_bookings = true;
> > $max_simultaneous_bookings = 5;
> > $vocab_override["zh-cn"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
> > $vocab_override["zh-tw"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
> > ```
> 
> 非常感谢

Excuse me ，How to work by area, not by global

**Comment by wobuzhidaobug** [comment]
> Not as complicated as I thought. I've added this feature to the main branch in [1c1459f](https://github.com/meeting-room-booking-system/mrbs-code/commit/1c1459fab0f01c90f715708c6c558b75e8632027). To use the code download the latest MRBS code from [this page](https://github.com/meeting-room-booking-system/mrbs-code) by following the green Code button. Treat it like a new release and set in your config file
> 
> ```
> $prevent_simultaneous_bookings = true;
> $max_simultaneous_bookings = 5;
> $vocab_override["zh-cn"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
> $vocab_override["zh-tw"]["no_simultaneous_bookings"] = "You cannot have bookings for more than %d room(s) at the same time";  // Translate as appropriate
> ```

Excuse me ，How to work by area, not by global

**Comment by campbell-m** [comment]
I've now added code in [25d6ec0](https://github.com/meeting-room-booking-system/mrbs-code/commit/25d6ec014481059bfa0536964a831255d83101ab) to allow you just to count the number of simultaneous bookings in an area.  You should download the new code and set

~~~php
$simultaneous_ignore_other_areas = true;
~~~

**Comment by wobuzhidaobug** [comment]
> I've now added code in [25d6ec0](https://github.com/meeting-room-booking-system/mrbs-code/commit/25d6ec014481059bfa0536964a831255d83101ab) to allow you just to count the number of simultaneous bookings in an area. You should download the new code and set
> 
> ```
> $simultaneous_ignore_other_areas = true;
> ```

Ok !Thank you very much !
