### ISSUE TITLE
Error adding an entry. Argument 1 passed to MRBS\round_t_down() must be of the type int, string given

### ISSUE THREAD

**Issue by jaigori** [meeting-room-booking-system/mrbs-code#3619]
**Describe the problem you're facing/question you have**
After a fresh installation, I create an area with a room. When I try to add an entry and I get this error:

```
Uncaught exception 'TypeError' in /var/www/html/functions.inc at line 2024
Argument 1 passed to MRBS\round_t_down() must be of the type int, string given, called in /var/www/html/lib/MRBS/Map.php on line 85
#0 /var/www/html/lib/MRBS/Map.php(85): MRBS\round_t_down('1708844400', 1800, 1708844400)
#1 /var/www/html/functions_table.inc(1248): MRBS\Map->add(Array, 0, 1708844400, 1708885800)
#2 /var/www/html/functions_table.inc(810): MRBS\week_room_table_innerhtml('week', 0, 2024, 2, 25, 1, 1, NULL)
#3 /var/www/html/index.php(441): MRBS\week_table_innerhtml('week', 0, 2024, 2, 25, 1, 1, NULL)
#4 {main}

```

**Browser details (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser [Firefox or Chrome]

**Server details (please complete the following information):**
 - MRBS : Last clone from github
 - Web server: using the provide from Dockerfile
 - OS: using the provide from Dockerfile
 - PHP version: using the provide from Dockerfile
 - Database used: using the provide from Dockerfile

**Additional context**
If I inspect the database I can view the new record in the "mrbs_entry" table. 
This is an export file from phpMyadmin:
```
INSERT INTO `mrbs_entry` (`id`, `start_time`, `end_time`, `entry_type`, `repeat_id`, `room_id`, `timestamp`, `create_by`, `modified_by`, `name`, `type`, `description`, `status`, `reminded`, `info_time`, `info_user`, `info_text`, `ical_uid`, `ical_sequence`, `ical_recur_id`, `allow_registration`, `registrant_limit`, `registrant_limit_enabled`, `registration_opens`, `registration_opens_enabled`, `registration_closes`, `registration_closes_enabled`) VALUES
(1, 1708844400, 1708848000, 0, NULL, 1, '2024-02-26 16:15:42', 'admin', '', 'P44', 'I', '', 0, NULL, NULL, NULL, NULL, 'MRBS-65dcb92e81b5a-0c1aa9a3@localhost', 0, NULL, 0, 0, 1, 1209600, 0, 0, 0);

```

If I go to this url: http://localhost:8080/report.php  I can view my entry!! And in fact I can edit it. But when I go to the main page index.php I get the error or "Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator."

**Comment by campbell-m** [comment]
Are you sure you're using the latest code?  The `round_t_down()` call is on line 82 of Map.php, not 85 as it says in the stack trace above.

**Comment by jaigori** [comment]
I start from the begining and I download again the source code. I get the same error although the error give in the correct line 82:
```

Argument 1 passed to MRBS\round_t_down() must be of the type int, string given, called in /var/www/html/lib/MRBS/Map.php on line 82
#0 /var/www/html/lib/MRBS/Map.php(82): MRBS\round_t_down('1709035200', 60, 1709035200)
#1 /var/www/html/functions_table.inc(574): MRBS\Map->add(Array, 27, 1709035200, 1709035260)
#2 /var/www/html/index.php(451): MRBS\day_table_innerhtml('day', 2024, 2, 27, 1, 1, NULL, NULL)
#3 {main}
```
However, the record it's inserted in the "mrbs_entry" table database.

Any suggestion?

**Comment by campbell-m** [comment]
I can now reproduce the problem.  I am working on a fix.

**Comment by campbell-m** [comment]
I've committed a temporary fix on [59065bd](https://github.com/meeting-room-booking-system/mrbs-code/commit/59065bd5f34cd5941a2a33087c37999b0c4c825d).  I'll work on a better fix.

**Comment by jaigori** [comment]
I think it's the same error in the roles branch.

**Comment by campbell-m** [comment]
I've just pushed the change to the roles branch.
