### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by iainmsi** [meeting-room-booking-system/mrbs-code#3623]
hi I thought our system was working since we worked through the ldap issues but user has reported this Uncaught exception 'TypeError' in /var/www/bookings/rooms/functions_table.inc at line 512\nMRBS\\day_table_innerhtml(): Argument #6 ($room_id) must be of type int, null given, called in /var/www/bookings/rooms/day.php on line 18\n#0 /var/www/bookings/rooms/day.php(18): MRBS\\day_table_innerhtml()\n#1 {main}\n\nMRBS GET: Array\n(\n    [area] => 2\n    [room] => 8\n)\nMRBS POST: Array\n(\n)\nMRBS SESSION: Array\n(\n    [last_page] => /rooms/day.php?area=2&room=8\n    [this_page] => /rooms/day.php?area=2&room=8\n    [csrf_token] => e83f8f2d86484be9365b359e5dee1969c58ed4d0836469beebb97461c7805f8d\n    [user] => MRBS\\User Object\n        (\n            [username] => xxxx\n            [display_name] => xxxx\n            [email] => xxxxxxxxxxxxxxx\n            [level] => 2\n            [data:protected] => Array\n                (\n                )\n\n        )\n\n)\n\n#0 MRBS\\generate_backtrace() called at [/var/www/bookings/rooms/functions_error.inc:219]\n#1 MRBS\\output_error() called at [/var/www/bookings/rooms/functions_error.inc:262]\n#2 MRBS\\output_exception_error(object) called at [/var/www/bookings/rooms/functions_error.inc:270]\n#3 MRBS\\exception_handler(object)\n

**Comment by campbell-m** [comment]
Looking at the stack trace I see the error was generated by a call to /rooms/day.php.   This page no longer exists in 1.11.4 so I suspect your user has a bookmark referencing the old page.  Can you as them to retry by going to /rooms/index.php?

**Comment by iainmsi** [comment]
brill thats what it is this can be closed

**Comment by campbell-m** [comment]
By the way, if you haven't already done so you should delete day.php, week.php and month.php.

**Comment by iainmsi** [comment]
thanks
