### ISSUE TITLE
Example ical import file

### ISSUE THREAD

**Issue by awip308** [meeting-room-booking-system/mrbs-code#3624]
**Describe the problem you're facing/question you have**
Can you please send me an example file for the import as an ical file. We use repetitions once a week over a certain period of time. As well as individual appointments. 

**Browser details:**
 - Browser chrome, safari, edge

**Server details:**
 - MRBS version 1.9.2
 - Web server: Apache
 - OS: Linux 
 - PHP version: 7.4.30
 - Database used: MySQL 10.3.28-MariaDB

**Comment by campbell-m** [comment]
The easiest thing to do is to create one yourself by exporting in iCal format from view_entry.php or report.php.

For more information on the format see [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545).  One thing to note is that it is important to note that line endings must be CRLF.
