### ISSUE TITLE
Error when trying to delete a Room that has reservations - Argument 1 passed to MRBS\time_date_string() must be of the type int, string given, 

### ISSUE THREAD

**Issue by jaigori** [meeting-room-booking-system/mrbs-code#3625]
**Describe the bug**
If you try to delete a room with reservations you have this error:
```
Uncaught exception 'TypeError' in /var/www/html/functions.inc at line 1869
Argument 1 passed to MRBS\time_date_string() must be of the type int, string given, called in /var/www/html/del.php on line 163
#0 /var/www/html/del.php(163): MRBS\time_date_string('1709208060')
#1 {main}
```
I'am in the **ROLES** branch, but I think It doesn't matter.

**To Reproduce**
1. Create a room
2. Do a reservation 
3. Try to delete the room

**Expected behavior**
View list of the entries to be delete

**Browser details (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser ; firefox

**Server details (please complete the following information):**
 - MRBS : last from github - ROLES branch
 - Web server: Docker
 - PHP version: Docker 
 - Database used:Docker

**Additional context**
I think is the same problem related with "declare(strict_types=1);"

**Comment by campbell-m** [comment]
Thanks for spotting this.  Now fixed in [0078bb2](https://github.com/meeting-room-booking-system/mrbs-code/commit/0078bb2bb9cbfdd325b7f92ad96823fc1b6a9929).
