### ISSUE TITLE
styling.inc

### ISSUE THREAD

**Issue by LanceJonesUK** [meeting-room-booking-system/mrbs-code#3631]
On line 32 of the default theme styling.inc file, it says:

$main_table_header_border_color = "#dddddd";    // border colour for day/week/month tables - header

I can change the "#dddddd" to a different colour and it updates the vertical lines in the tables for day / week / month.

Is it possible to do the same thing with the horizontal lines? I assume that colour is $body_background_color but I can't find where to edit it.

I am grateful to anyone who can point me to where I can make the edit.

**Comment by campbell-m** [comment]
Which view do you want to change them in?  In the day view there aren't any horizontal lines because there are the zebra stripes.

**Comment by LanceJonesUK** [comment]
> Which view do you want to change them in? In the day view there aren't any horizontal lines because there are the zebra stripes.

Ah thank you - that makes sense - I have adjusted the colours with custom css. All fixed - thank you once again.
