### ISSUE TITLE
Incorrect week view title

### ISSUE THREAD

**Issue by Lithimlin** [meeting-room-booking-system/mrbs-code#3638]
I'm having trouble with the date formatting in the title of the week view and I'm not sure if it's a bug or misconfigured:

In the week view, weeks that start and end in the same year and month are shown as:

**Week n | dd - MMMM dd, YYYY**

when it should be

**Week n | MMMM  dd - dd, YYYY**

Here's what should be the relevant section of the config:

```php
// The title of the week view calendar when the years and
// months are the same for the start and end of the week
$datetime_formats['view_week_date'] = array(
  'skeleton' => 'd',
  'pattern' => 'd'
);

// The title of the week view calendar when just the years
// are the same for the start and end of the week
$datetime_formats['view_week_month'] = array(
  'skeleton' => 'dMMMM',
  'pattern' => 'd MMMM'
);

// The title of the week view calendar (end of the week)
$datetime_formats['view_week_year'] = array(
  'date_type' => IntlDateFormatter::LONG,
  'time_type' => IntlDateFormatter::NONE
);
```

**Comment by campbell-m** [comment]
This has already been fixed in the latest version of the code in the [main branch](https://github.com/meeting-room-booking-system/mrbs-code).  You'll need to download the full set of files by following the green Code button.  Treat it like a new release.
