### ISSUE TITLE
Language not changing

### ISSUE THREAD

**Issue by Metz01** [meeting-room-booking-system/mrbs-code#3639]
Hi, 
I'm using the last release of MRBS, everything works fine, but when I enter using a browser with the default language it-IT the only thing that changes is the calendar on the left side of the main page, but everything else remain in English.
Thank you for the attention.

**Comment by campbell-m** [comment]
I can't reproduce this.  Some questions:

1. What browser are you using?
2. What are your browser language preferences (as shown on the MRBS Help page)?
3. What, if anything, is `$override_locale` set to?
4. Do you have the 'intl' extension installed (answer on the Help page)?

**Comment by Metz01** [comment]
Thank you for the response.
to answer your questions:

1. It happens in basically all browser
2. language preference order: it-it, en-US, en
3. If it should be in the config file, then I have none set
4. No, I don't have the 'intl' extension installed, is that the problem?

**Comment by campbell-m** [comment]
No, it should work with or without the 'intl' extension.

Can you set `$language_debug = true;` in your config file please and see what output you get in your PHP error log?

**Comment by Metz01** [comment]
Sorry for the delay in the response, here it is the output of what you requested:
[MRBS DEBUG] $locale: en,
[MRBS DEBUG] $lang: en,
[MRBS DEBUG] $disable_automatic_language_changing: false, 
[MRBS DEBUG] $default_language_tokens: en
[MRBS DEBUG] $cli_language: en,
[MRBS DEBUG] $override_locale: ,
[MRBS DEBUG] HTTP_ACCEPT_LANGUAGE: it-it,en-US;q=0.8,en;q=0.6, 
[MRBS DEBUG] $aliased_header: it-it,en-US;q=0.8,en;q=0.6,

**Comment by Metz01** [comment]
Giving you this made me realize that the problem might be in the locales installed in my docker container. And that was it. I just added the it-IT locales to the container with:
```
RUN localedef -i en_GB -c -f UTF-8 -A /usr/share/locale/locale.alias en_GB.UTF-8 && \
    localedef -i it_IT -c -f UTF-8 -A /usr/share/locale/locale.alias it_IT.UTF-8
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:it_IT
```
And now it works as expected, thanks!
