### ISSUE TITLE
Errror al importar ICS

### ISSUE THREAD

**Issue by RodrigoReyes91** [meeting-room-booking-system/mrbs-code#3641]
Buen día

Solicito de su valiosa ayuda con el siguiente error, estoy intentando utilizar la función import.php, al importar un archivo ICS me muestra que se importaron correctamente los eventos, sin embargo, al buscarlos por la web o directamente en la base de datos no aparecen las entradas.

El resto del sistema esta funcionando bien pero import.php no guarda los cambios aunque indica que si.

Versión MRBS | MRBS 1.11.4
Versión del esquema de Base de Datos | 82
Versión del esquema local de Base de Datos | 1
$auth['type'] | db
$auth['session'] | php

**Additional context**
El archivo a importar tiene los siguientes datos:

`BEGIN:VCALENDAR`
`METHOD:PUBLISH`<br>`
BEGIN:VTIMEZONE`<br>`
BEGIN:STANDARD`<br>`
END:STANDARD`<br>`
END:VTIMEZONE`<br>`
BEGIN:VEVENT`<br>`
LAST-MODIFIED:202411-Finales-test`<br>`
DTSTART;TZID=America/Mexico_City:20240611T190000`<br>`
DTEND;TZID=America/Mexico_City:20240611T210000`<br>`
RRULE:FREQ=WEEKLY;BYDAY=TU;UNTIL=20240611T190000Z`<br>`
SUMMARY:18880-Proyecto de fin de carrera`<br>`
DESCRIPTION:L00869198 Juan Carlos Alvear Serrano`<br>`
LOCATION:Q-CDTC/401D`<br>`
X-MRBS-TYPE:Clase`<br>`
END:VEVENT`<br>`
END:VCALENDAR`<br>`
BEGIN:VCALENDAR`<br>`
METHOD:PUBLISH`<br>`
BEGIN:VTIMEZONE`<br>`
BEGIN:STANDARD`<br>`
END:STANDARD`<br>`
END:VTIMEZONE`<br>`
BEGIN:VEVENT`<br>`
LAST-MODIFIED:202411-Finales-test`<br>`
DTSTART;TZID=America/Mexico_City:20240612T160000`<br>`
DTEND;TZID=America/Mexico_City:20240612T180000`<br>`
RRULE:FREQ=WEEKLY;BYDAY=WE;UNTIL=20240612T160000Z`<br>`
SUMMARY:27258-Introduccion a la vida profesi`<br>`
DESCRIPTION:L01371591 Alejandra Lucia Arrieta Mendez`<br>`
LOCATION:Q-AI/305`<br>`
X-MRBS-TYPE:Clase`<br>`
END:VEVENT`<br>`
END:VCALENDAR`<br>`
BEGIN:VCALENDAR`<br>`
METHOD:PUBLISH`<br>`
BEGIN:VTIMEZONE`<br>`
BEGIN:STANDARD`<br>`
END:STANDARD`<br>`
END:VTIMEZONE`<br>`
BEGIN:VEVENT`<br>`
LAST-MODIFIED:202411-Finales-test`<br>`
DTSTART;TZID=America/Mexico_City:20240612T160000`<br>`
DTEND;TZID=America/Mexico_City:20240612T180000`<br>`
RRULE:FREQ=WEEKLY;BYDAY=WE;UNTIL=20240612T160000Z`<br>`
SUMMARY:24454-Introduccion a la vida profesi`<br>`
DESCRIPTION:L00292755 Yezmin Lopez Taymani`<br>`
LOCATION:Q-AII/415`<br>`
X-MRBS-TYPE:Clase`<br>`
END:VEVENT`<br>`
END:VCALENDAR`<br>`
BEGIN:VCALENDAR`<br>`
METHOD:PUBLISH`<br>`
BEGIN:VTIMEZONE`<br>`
BEGIN:STANDARD`<br>`
END:STANDARD`<br>`
END:VTIMEZONE`<br>`
BEGIN:VEVENT`<br>`
LAST-MODIFIED:202411-Finales-test`<br>`
DTSTART;TZID=America/Mexico_City:20240612T160000`<br>`
DTEND;TZID=America/Mexico_City:20240612T180000`<br>`
RRULE:FREQ=WEEKLY;BYDAY=WE;UNTIL=20240612T160000Z`<br>`
SUMMARY:24432-Introduccion a la vida profesi`<br>`
DESCRIPTION:L01053272 Lizethe Arlene Tello Garcia`<br>`
LOCATION:Q-AII/416`<br>`
X-MRBS-TYPE:Clase`<br>`
END:VEVENT`<br>`
END:VCALENDAR`<br>`
BEGIN:VCALENDAR`<br>`
METHOD:PUBLISH`<br>`
BEGIN:VTIMEZONE`<br>`
BEGIN:STANDARD`<br>`
END:STANDARD`<br>`
END:VTIMEZONE`<br>`
BEGIN:VEVENT`<br>`
LAST-MODIFIED:202411-Finales-test`<br>`
DTSTART;TZID=America/Mexico_City:20240612T190000`<br>`
DTEND;TZID=America/Mexico_City:20240612T210000`<br>`
RRULE:FREQ=WEEKLY;BYDAY=WE;UNTIL=20240612T190000Z`<br>`
SUMMARY:24453-Planeacion innovacion y susten`<br>`
DESCRIPTION:L03108278 Edgar Salas Rivera`<br>`
LOCATION:Q-AII/416`<br>`
X-MRBS-TYPE:Clase`<br>`
END:VEVENT`<br>`
END:VCALENDAR``<br>`

Y al archivo import se modifico la linea case 'LAST-MODIFIED' con el siguiente codigo para añadir un campo personalizado
`case 'LAST-MODIFIED':`<br>`
          $booking['Periodo'] = $property['value'];`<br>`
          break;`

De antemano gracias por su ayuda.

Saludos

**Comment by campbell-m** [comment]
It's not importing anything because the UNTIL times in your RRULEs are before the first DTSTART times.
