### ISSUE TITLE
May I add more information into reservation slot display on home screen?

### ISSUE THREAD

**Issue by khanhdn0112** [meeting-room-booking-system/mrbs-code#3643]
Hi,
I need your support some items below:

- add more information like: "created by" into the reservation slot display on the home screen as the image attached.
Please advise me what should I do.

- How can I set default room in view by month and week (not show all as of now)?

- How can I add more information of User like: department? 
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/54300028/ad78401c-f873-47d3-8152-ba172c0ea4dd)

Please support me. Thank you so much

**Comment by campbell-m** [comment]
> add more information like: "created by" into the reservation slot display on the home screen as the image attached

See Issue #3569 

> How can I set default room in view by month and week (not show all as of now)?

Set `$default_view_all = false;` in your config file.

> How can I add more information of User like: department?

See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL file.

**Comment by khanhdn0112** [comment]
thanks
