### ISSUE TITLE
Access denied when I click on a cell to book a room in mrbs 1.11.4

### ISSUE THREAD

**Issue by mdeanquin0520** [meeting-room-booking-system/mrbs-code#3645]
I am using cas to authenticate to mrbs system, when I click on a cell to book a room gives me the access denied message instead of redirecting me to cas authentication page, this is the configuration that I have for cas in config.inc.php:
$auth["session"] = "cas";
$auth["type"] = "cas";
$auth['cas']['host'] = 'sso.dev.unc.edu.ar';
$auth['cas']['port'] = 443;
$auth['cas']['no_server_validation'] = true;
$auth['cas']['debug'] = true;
What am I missing so that the site redirects me to cas login page?

**Comment by campbell-m** [comment]
Are you able to login when you click the "Log in" link in the top right hand corner?

**Comment by mdeanquin0520** [comment]
> Are you able to login when you click the "Log in" link in the top right hand corner?

Yes I can login perfectly with cas

**Comment by campbell-m** [comment]
No, you're not missing anything.  That's the way MRBS's CAS authentication works at the moment.  Can you try editing lib/MRBS/Session/SessionCas.php and replacing the method `authGet()` (about line 31) with

~~~php
  public function authGet(?string $target_url=null, ?string $returl=null, ?string $error=null, bool $raw=false) : void
  {
    if (!phpCAS::isAuthenticated())
    {
      phpCAS::forceAuthentication();
    }
  }
~~~

Unfortunately I don't have a CAS server to test against.

**Comment by mdeanquin0520** [comment]
> No, you're not missing anything. That's the way MRBS's CAS authentication works at the moment. Can you try editing lib/MRBS/Session/SessionCas.php and replacing the method `authGet()` (about line 31) with
> 
> ```
>   public function authGet(?string $target_url=null, ?string $returl=null, ?string $error=null, bool $raw=false) : void
>   {
>     if (!phpCAS::isAuthenticated())
>     {
>       phpCAS::forceAuthentication();
>     }
>   }
> ```
> 
> Unfortunately I don't have a CAS server to test against.

Thank you very much, that worked perfectly.

**Comment by campbell-m** [comment]
I've now committed the change in [fd781c5](https://github.com/meeting-room-booking-system/mrbs-code/commit/fd781c5c9a334368b5b2c8fb520f393f9a543642).
