### ISSUE TITLE
Configure mrbs 1.11.4 administrator with cas

### ISSUE THREAD

**Issue by mdeanquin0520** [meeting-room-booking-system/mrbs-code#3646]
How can I configure the administrator for mrbs to use it with cas?

**Comment by campbell-m** [comment]
You configure admins in the MRBS config file using `$auth['admin']`, eg

~~~php
$auth['admin'] = ['user1', 'user2'];
~~~

**Comment by mdeanquin0520** [comment]
> You configure admins in the MRBS config file using `$auth['admin']`, eg
> 
> ```
> $auth['admin'] = ['user1', 'user2'];
> ```

Thank you, do I have to put the code returned by cas in user1, user2, etc.?

**Comment by campbell-m** [comment]
You put the usernames you log in with.

**Comment by mdeanquin0520** [comment]
But the cas server I use returns a string instead of the mail I use to login when I login with cas, do I have to put that string as the administrator?

**Comment by campbell-m** [comment]
Yes, I think so.

**Comment by campbell-m** [comment]
If that doesn't work try adding the line `var_dump($username);` at line 146 in lib/MRBS/Auth/AuthCas.php to see what it's using.

**Comment by mdeanquin0520** [comment]
> If that doesn't work try adding the line `var_dump($username);` at line 146 in lib/MRBS/Auth/AuthCas.php to see what it's using.

Ok, thank you very much
