### ISSUE TITLE
Issue with editing booking on 1.11.4

### ISSUE THREAD

**Issue by ScottLangshaw** [meeting-room-booking-system/mrbs-code#3647]
Ive upgraded our system to 1.11.4 and when staff are creating a booking and then going in to edit their own booking we are receiving the below error

~~~text
fwsd
Event details
Uncaught exception 'Error' in C:\xampp\htdocs\mrbs\web\functions_view.inc at line 113
Call to undefined function MRBS\can_see_email_addresses()
#0 C:\xampp\htdocs\mrbs\web\view_entry.php(774): MRBS\create_details_body(Array, true, false, false)
#1 {main}

MRBS GET: Array
(
    [view] => day
    [year] => 2024
    [month] => 4
    [day] => 15
    [area] => 16
    [id] => 22252
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [csrf_token] => 9c31eec4ccdf394a063a0c7c49c1862d1db2d996d00e1422a0759c32c8d88e4f
    [user] => MRBS\User Object
        (
            [username] => stsl09
            [display_name] => Scott Langshaw
            [email] => ****
            [level] => 2
            [data:protected] => Array
                (
                )

        )

)

Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator.
~~~

Could someone please point me in the right direction to fix this please?

**Comment by ScottLangshaw** [comment]
Also just to add when staff are also trying to login we are using LDAP lookup we are getting the below error as well:

Uncaught exception 'TypeError' in C:\xampp\htdocs\mrbs\web\functions.inc at line 1518
MRBS\get_area(): Argument #1 ($room) must be of type int, null given, called in C:\xampp\htdocs\mrbs\web\mrbs_auth.inc on line 446
#0 C:\xampp\htdocs\mrbs\web\mrbs_auth.inc(446): MRBS\get_area(NULL)
#1 C:\xampp\htdocs\mrbs\web\Themes\default\header.inc(577): MRBS\is_book_admin()
#2 C:\xampp\htdocs\mrbs\web\functions.inc(882): MRBS\print_theme_header(Array, false, false)
#3 C:\xampp\htdocs\mrbs\web\index.php(475): MRBS\print_header(Array)
#4 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [csrf_token] => 540290f88534d65e47f9548ba71ef86d34ff7ed3ebdc9659948a59fc6bc71c1c
    [user] => MRBS\User Object
        (
            [username] => teststaff
            [display_name] => Staff Test
            [email] => teststaff@temac.co.uk
            [level] => 1
            [data:protected] => Array
                (
                )

        )

)

**Comment by campbell-m** [comment]
> Call to undefined function MRBS\can_see_email_addresses()

This should be defined in mrbs_auth.inc.  Try uploading the MRBS 1.11.4 files again.

**Comment by ScottLangshaw** [comment]
Thank you not sure what happened there but replaced the files :)
