### ISSUE TITLE
change of the title of the MRBS web page 

### ISSUE THREAD

**Issue by bahijamahfoud** [meeting-room-booking-system/mrbs-code#3648]
I cannot change the title "your Company".
Room reservation system" on the MRBS page.
the application is based on the docker.
someone can help me?

**Comment by campbell-m** [comment]
Set in your config.inc.php file

~~~php
$mrbs_company = "Your Company";  // Change as required
$vocab_override['en']['mrbs'] = "My Resource Booking System";  // Change 'en' to any language
~~~

**Comment by bahijamahfoud** [comment]
thank you very much, it works  :)
