### ISSUE TITLE
Booking overview

### ISSUE THREAD

**Issue by bks0401** [meeting-room-booking-system/mrbs-code#3654]
Hi

Is it possible to add this info to the user's booking overview.

Adding the name of the room
To see the start and end time of the bookings

/Bruno

MRBS : 1.11.4
![image002](https://github.com/meeting-room-booking-system/mrbs-code/assets/147808398/8c2c174b-89b7-4f19-bf95-84cb58bd6f31)

**Comment by campbell-m** [comment]
You'd need to modify the code in search.php.

**Comment by bks0401** [comment]
Ok thanks, however I will not change in seache.php as I am not good at PHP.

I tell the user that it is not possible
