### ISSUE TITLE
how to add a extra emails Id to the areas and rooms

### ISSUE THREAD

**Issue by abidfakhrealam** [meeting-room-booking-system/mrbs-code#3655]
**Describe the problem you're facing/question you have**
I want to send notifications to different people in different rooms, sending different notifications to more than two people.

**Browser details (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome, safari, mozilla]
 - Version [22.04]

**Server details (please complete the following information):**
 - MRBS version [1.11.4]
 - Web server: [e.g. Apache 2.4.48]

**Additional context**

**Comment by campbell-m** [comment]
You can send notifications to one or more people by entering a comma separated list of email addresses in the room admin email field of the room settings form and also setting `$mail_settings['room_admin_on_bookings'] = true;` in your config file.

However you'd need to modify the MRBS code if you want to send different messages to different people.  If possible, I'd try and construct a generic message that is suitable for all.
