### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by bahijamahfoud** [meeting-room-booking-system/mrbs-code#3658]
Hello, 
I can't translate these two buttons.

Can you help me please?

thanks in advance
![Capture](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/d04afa35-0d44-4149-93bf-bea84a7e66e3)

**Comment by campbell-m** [comment]
Are you running a fork of MRBS?  Those strings don't appear in standard MRBS and you have a non-standard user inteface.  You should search for them in lang/lang.en, or lang.de, and find the associated token and then use `$vocab_override`.  Or else ask the question on the fork's page.

**Comment by bahijamahfoud** [comment]
I'm using the mrbs docker image, I searched for the tokens of these buttons but I didn't find it.
