### ISSUE TITLE
Remember Account Information

### ISSUE THREAD

**Issue by khanhdn0112** [meeting-room-booking-system/mrbs-code#3659]
Hi. 

How can I add a feature to remember Account information instead have to log in whenever web access?

Thank you so much

**Comment by campbell-m** [comment]
Are you using the 'php' setting (the default) for `$auth['session']`?  If so, then you can set

~~~php
$auth["session_php"]["session_expire_time"] = (60*60*24*30); // 30 days - change as required
~~~
