### ISSUE TITLE
Highlight current date

### ISSUE THREAD

**Issue by lagethomas** [meeting-room-booking-system/mrbs-code#3663]
Guys, good afternoon!
For those who want to highlight the current data in the calendar, I leave the css. Just create the custom.css file in the css folder and then call it in the configs.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/ede99475-6eaf-471f-92d2-8952f130db5a)

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/47001888/e5f21b19-b41f-491b-b270-cbf0c668d7b9)

```
.dwm_main#month_main:not(.all_rooms) .today {
  /*background-color: #aaaaaa;*/
  border: 1px solid #d22e2e !important;
  background-color: #ffded9;
}
```

**Comment by campbell-m** [comment]
See also Issue #3564.
