### ISSUE TITLE
Mrbs doesn't work in wifi network

### ISSUE THREAD

**Issue by mdeanquin0520** [meeting-room-booking-system/mrbs-code#3668]
**Describe the problem you're facing/question you have**
Mrbs doesn't work when the computer is connected to a wifi network

**Browser details (please complete the following information):**
 - Browser: chrome

**Server details (please complete the following information):**
 - MRBS version 1.11.4
 - Web server: Apache 2.4.52
 - OS: Ubuntu 22.04.4 LTS
 - PHP version: 8.1.2
 - Database used: MariaDB 10.5.18

**Comment by campbell-m** [comment]
I think there are two problems:

(1) The es-419 locale isn't installed on your server.  You need to install it, or else set `$override_locale` to a locale that is installed.
(2) You either have `$debug = true;` or your php.ini settings are set to display errors in the browser, which causes invalid JavaScript (which is generated by PHP) and so the grid doesn't appear.

**Comment by mdeanquin0520** [comment]
Thank you very much, it works perfect.
