### ISSUE TITLE
How to display Email Field 

### ISSUE THREAD

**Issue by LeVinh2309** [meeting-room-booking-system/mrbs-code#3670]
First of all, thank you very much for creating this software.
Currently I am using version 1.11.5, when I start to create a new meeting, in this version I cannot find the email field like the attached image I found from someone below.
![emailfield](https://github.com/meeting-room-booking-system/mrbs-code/assets/169123048/441ec94b-4624-435f-bdd9-f7620417f15d)

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/169123048/6d4f84c5-f976-4d1c-9b41-c01561e4a1dc)
Do I need to edit the code to display this email field?
If so, which file should I edit?

**Comment by campbell-m** [comment]
You don't need to edit any code.  You just need to add a custom field in the entry and repeat tables.  See the section on "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document.

**Comment by LeVinh2309** [comment]
> You don't need to edit any code. You just need to add a custom field in the entry and repeat tables. See the section on "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document.

Thank you very much, I did it. Now if I fill in an email list in that field, how can it send booking emails to all of them? We need to add code in functions_mail.inc or somewhere , right?

**Comment by campbell-m** [comment]
Yes, just edit the function `create_addresses()` in functions_mail.inc and, assuming your custom field is called 'email', at line 815 add the code

~~~php
  if (!empty($data['email']))
  {
    $to = address_merge($to, $data['email']);
  }
~~~

**Comment by LeVinh2309** [comment]
> Yes, just edit the function `create_addresses()` in functions_mail.inc and, assuming your custom field is called 'email', at line 815 add the code
> 
> ```
>   if (!empty($data['email']))
>   {
>     $to = address_merge($to, $data['email']);
>   }
> ```

I did it, Thank you so much !
