### ISSUE TITLE
How to active The User Infomation Function ?

### ISSUE THREAD

**Issue by LeVinh2309** [meeting-room-booking-system/mrbs-code#3671]
Hi, 

Currently, I create/change the passsword for user manually through Phpmyadmin. 
I saw on this web "https://psy.swan.ac.uk/staff/lucignoli/Room-Lab-Booking-Info.htm" talking about create/modify user infomation function. But i don't see that on this my version MRBS 1.11.5.  

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/169123048/dc9eddf2-2dd7-4c96-ab73-2f399e2fb8ad)
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/169123048/6f699a53-1877-4414-9779-17c3b798f8dc)

Can you tell me, how to active this function  ? 

Thanks

**Comment by campbell-m** [comment]
What have you got `$auth['type']` set to in your config.inc.php file? I am not seeing a "Users" entry in the banner menu, which suggests that it is set to something other than 'db', or else the users.php page is somehow disabled.

**Comment by LeVinh2309** [comment]
> What have you got `$auth['type']` set to in your config.inc.php file? I am not seeing a "Users" entry in the banner menu, which suggests that it is set to something other than 'db', or else the users.php page is somehow disabled.

Oh, I see my problem is `$auth["type"] = "config"` in my config.inc.php . i changed it to `$auth["type"] = "db"` and now i saw what i need. But now i can't login with any account..

can you check my config.inc.php , 

`$auth["admin"][] = "ltvinh"; 
$auth["session"] = "php";
$auth["type"] = "db";
$auth["user"]["ltvinh"] = "12345";`

**Comment by campbell-m** [comment]
Your config is correct, but with the 'db' authentication type users are stored in the database rather than in the config file.  So you now need to set up your users by using tyhe "Add user" button on the Users menu item.

**Comment by LeVinh2309** [comment]
Sorry, i don't understand what you mean. Should i need to add more button ? Because i don't see the "Add user" button.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/169123048/d9a0cf77-f983-44f0-a7a9-3d7c027bdd8b)
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/169123048/5bdc3826-8e1a-479d-ba26-98fb5d0a92c4)

**Comment by campbell-m** [comment]
You will only see the button after you have logged in.  You need to login as an admin, and then you will see the "Users" menu entry.  Click that and you will see an "Add user" button.

**Comment by campbell-m** [comment]
If you have forgotten your password, follow the "Lost your password?" link.  If you don't know your username or email address then look in the users table using phpMyAdmin for a user with level 2.

**Comment by campbell-m** [comment]
Good, glad it's working.  Now you're in you shouldn't need to change any user details using phpMyAdmin.  It is recommended that all user management is done through MRBS.
