### ISSUE TITLE
problem displaying MRBS page

### ISSUE THREAD

**Issue by bahijamahfoud** [meeting-room-booking-system/mrbs-code#3672]
Hello, 

I have this problem.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/26cc336a-b6ee-408e-942b-19688f821e89)

**Comment by campbell-m** [comment]
You need to set `$timezone` in config.inc.php.

**Comment by campbell-m** [comment]
You need to look in your PHP error log to see the detailed error message. Or else, temporarily, set `$debug = true;` in your config file.
