### ISSUE TITLE
modification of words

### ISSUE THREAD

**Issue by bahijamahfoud** [meeting-room-booking-system/mrbs-code#3674]
Hello, 

how can I modify this phrase "edit room" to modify vehicle??

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/a66d29f3-7ab9-4817-841c-3d4ef3a37aa6)

And how can I modify also the word "room", 
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/719318b4-35a5-491f-bc42-6f8127c813e8)

bearing in mind that I put it on my configuration file.

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/f56e94db-e2cb-4fe5-bea2-c7336970deb0)

the same thing for this candy "add a room"

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/78e496a2-fc09-4a7c-8258-7a954b36389f)

Thank you in advance for your help

**Comment by campbell-m** [comment]
It's the same principle as for Issue #3667.

**Comment by bahijamahfoud** [comment]
I can't find the associated token for the "add room" button

![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/43571015/1af8109a-3375-4902-bba3-e8e53ec1ea07)

**Comment by campbell-m** [comment]
Have you searched in lang/lang.fr for "Ajouter une salle"?

**Comment by bahijamahfoud** [comment]
where I can find this file lang/lang.fr  ?

**Comment by campbell-m** [comment]
The file is in the lang directory in the MRBS distribution.  When you have found the string and the associated token, do not modify  the file but instead use `$vocab_override` in your config file.  That way you will be able to upgrade MRBS when a new release is made without having to make the changes again.

**Comment by bahijamahfoud** [comment]
in fact, I found the associated token but the configuration file only applies the modifications that I made 4 days ago, it seems that it does not take into account today's modifications

**Comment by campbell-m** [comment]
That's because you haven't found the token.  In your example above the token should be 'editroom', not 'edit_room'.
