### ISSUE TITLE
unable to amend other admin bookings

### ISSUE THREAD

**Issue by antham1616** [meeting-room-booking-system/mrbs-code#3676]
**Describe the problem you're facing/question you have**
unable to amend other admin bookings

**Browser details (please complete the following information):**
 - Browser [chrome]
 - Version [125.0.6422.77]

**Server details (please complete the following information):**
 - MRBS version [MRBS 1.11.3]
 - 
**Additional context**

i added this snippet of code form campbell and had the desired effect for users - 

~~~php
  // Always allowed to modify your own stuff
  $mrbs_user = session()->getCurrentUser();
  if (isset($mrbs_user) && isset($creator) && (strcasecmp_locale($creator, $mrbs_user->username) === 0))
  {
    return true;
  }

  // Also allowed to modify other people's, provided they are not admins
  if (isset($creator))
  {
    $creator_user = auth()->getUser($creator);
    if (isset($mrbs_user) && isset($creator_user) && ($creator_user->level < 2))
    {
      return true;
    }
  }

  // Otherwise you have to be a (booking) admin for this room
  if (is_book_admin($rooms))
  {
    return true;
  }

  // Unauthorised access
  return false;
~~~

** users are unable to amend admin bookings as expected, but admins also cannot amend each others bookings**
do i need to modify the $cretor to allow user level booking modification?

**Comment by campbell-m** [comment]
Can you post your mrbs_auth.inc file here please?

**Comment by antham1616** [comment]
managed to sort it, 

// Also allowed to modify other people's, provided they are not admins  
  if (isset($creator))
  {    
	$creator_user = auth()->getUser($creator);	
    if (isset($mrbs_user) && isset($creator_user) && **($creator_user->level <= $mrbs_user->level))**
    {
      return true;
    }
  }
