### ISSUE TITLE
Day view max vertical height is too large to fit in most browser windows. 

### ISSUE THREAD

**Issue by ksg1960** [meeting-room-booking-system/mrbs-code#3677]
**Describe the problem you're facing/question you have**

Only in Day display mode the browser always generates a vertical scroll bar because the day view is bigger than will fit into the main browser page.     Maybe if some kind of  space filling footer were added to the bottom of the calendars main page the day window would be pushed up enough for the entire view to be visible.   This generally doesn't have to do with the duration of the time slots per se' because the day view creates its own vertical scroll element automatically.

The footer information such as coloration and booking types is never visible in day view because the browser must be scrolled down to see it.    

Week and Month views do not make the browser create its own scroll element.

I  hope this makes sense.
Scott

**Browser details (please complete the following information):**
 - OS: [Windows 10]
 - Browser [e.g. Edge and Chrome]
 - Version [e.g. 125.0.2535.51]

**Server details (please complete the following information):**
 - MRBS version [1.11.5    goto time branch]
 - Web server: [e.g. Apache 2.4.48]
 - OS: [e.g. redhat 8]
 - PHP version: { 7.2.24]
 - Database used: [ MySQL 8.0.13]

**Additional context**

**Comment by ksg1960** [comment]
I should add, the day_view window seems to always be about 20% too long vertically.

**Comment by campbell-m** [comment]
I'll look at in more detail next week, but in the meantime you can reduce the height by creating a custom CSS file (see systemdefaults.inc.php for how to do this) and adding the rule:

~~~css
.table_container {
    max-height: max(calc(100vh - 28em), 8em);
}
~~~

While this may help your particular case, it probably needs something better for the general case.

**Comment by ksg1960** [comment]
Hi Mr Campbell,

I tried the snippet, to no affect.   In fact, table size appears to be unaffected by any value used in the max-height: setting.   I did notice that the total number of slot's (rows) displayed by the table when its scroll bar is active is 36.  In other words, if I use my web browser's scroll bar to count the all the rows displayed by the calendar view it's seems fixed to 36.   I tried changing the global total of rows displayable by lengthening the slot time from 10 to 20 minutes and still get 36 rows being displaye3d across the scrolling calendar table.   It's as if the scrollable table building function has a fixed number of rows it should make visible and this takes precedence over any vertical size controls.   I looked around in the js functions but couldn't identify anything.


thank youi for your assistance,
Scott






Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>






________________________________

**Comment by campbell-m** [comment]
I've now fixed this issue in the [fix_overflow](https://github.com/meeting-room-booking-system/mrbs-code/tree/fix_overflow) branch.  If you get a chance could you test it please and see if it does what you expect?  Note that:

1. Only the web/css/mrbs.css.php file is different from the main branch, so if you've already got the latest code you only have to download that file.
2. The changes only come into effect if the window is taller than a certain minimum (currently set to 30rem).  That's because you wouldn't be able to see the calendar at all otherwise.

**Comment by ksg1960** [comment]
So far so good.  I loaded the file and the result looks perfect.   I don't have my production server up-to-date with your Main code base, but hope to complete the migration this week or next.


Looks Great!





Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>






________________________________

**Comment by campbell-m** [comment]
In [e2ffae2](https://github.com/meeting-room-booking-system/mrbs-code/commit/e2fae2371fd34b9b01594323ab44b87907c01503) I have tweaked the CSS a bit.   In some circumstances the table itself was very small, or even non-existent, so I've kept the old behaviour for windows up to 50rem high, instead of 30rem, and also introduced a width requirement of 30rem.  See what you think.

**Comment by campbell-m** [comment]
I've now merged the fix_overflow branch back into main.

**Comment by ksg1960** [comment]
That is great,  it really helps when short slot times are generated.

On another note I added some rules customizations to my instance.


  1.   Users now have a new “level”.   Admin has been moved to 3, but none and normal user are still 0 and 1.  So 2 can be used with a check against a new “room” level row, “level” required. The check is in mrbs_sql.inc’s policy check function.
  2.  Several other new attributes similar to the area time slot restrictions were also added to the rooms table.   These provide a room based selection for a more restricted set of slot rules during week days ostensibly 9am to 8pm.

Would you like to see the implementation?  Both seem to work.   But of course they may not be as elegant as the rest of your code.

Scott

Regards,

Scott K Smith
From my cellphone
________________________________

**Comment by campbell-m** [comment]
> 1.   Users now have a new “level”.   Admin has been moved to 3, but none and normal user are still 0 and 1.  So 2 can be used with a check against a new “room” level row, “level” required. The check is in mrbs_sql.inc’s policy check function.
>  2.  Several other new attributes similar to the area time slot restrictions were also added to the rooms table.   These provide a room based selection for a more restricted set of slot rules during week days ostensibly 9am to 8pm.

I think I probably understand the first one, but I'd be interested to know more about the second.  If you're willing to share the code could you raise a new issue please describing in more detail what it does and posting the code there.
