### ISSUE TITLE
Add field to edit_entry page

### ISSUE THREAD

**Issue by OscarERodriguezSaldivar** [meeting-room-booking-system/mrbs-code#3679]
I want to add 2 custom text fields so that you can add utilities needed on the room and another for specific instructions for the room such as cleaning tables or downloading a program beforehand, I added the columns in the bd and added the field editing the edit_entry.php and adit_entry_handler.php but I can't get it to add it to the bd and I'm not sure where is the query that updates or adds the info to the table in mrbs_sql, how can I do this? I'm using the latest version of mrbs but I can downgrade if needed, thanks!

**Comment by campbell-m** [comment]
You don't need to change any MRBS code at all.  Just add the columns to both the entry and repeat tables.  See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document for more details.

**Comment by OscarERodriguezSaldivar** [comment]
been stuck on this since yesterday and started modifying the code without checking the documentation, thank you !!
