### ISSUE TITLE
Display only positive information on view entry

### ISSUE THREAD

**Issue by OscarERodriguezSaldivar** [meeting-room-booking-system/mrbs-code#3681]
I added a lot of custom checkboxes to the edit_entry.php with the bd but I want to know if there's a way to only display on view_entry the ones that got checked and say yes because they are a lot and the list is pretty long, is there a way to only display the ones that are positive?

**Comment by campbell-m** [comment]
You'd have to modify the MRBS code, in particular the function `create_details_body()` in functions_view.inc.  It may not be a concern in your case, but in the general case you need to watch out for private fields and make sure you don't reveal information by virtue of the fact that the field is displayed or not.

**Comment by OscarERodriguezSaldivar** [comment]
thanks for the help!
