### ISSUE TITLE
enable user_level access to create/modify a booking in a specific room 

### ISSUE THREAD

**Issue by ksg1960** [meeting-room-booking-system/mrbs-code#3684]
I have setup a means to make booking a room accessible to a limited number of people and created a room level secondary booking limits for week-day working hours.   Just wondering if these additions are reasonable.   

OS: [Windows 10]
Browser [e.g. Edge and Chrome]
Version [e.g. 125.0.2535.51]
Server details (please complete the following information):

MRBS version [1.11.5 goto time branch]
Web server: [e.g. Apache 2.4.48]
OS: [e.g. redhat 8]
PHP version: [ 7.2.24]
Database used: [ MySQL 8.0.13]

**Additional context**
I have extended the user levels as follows
$vocab["level_0"]            = "none";
$vocab["level_1"]            = "user";
$vocab["level_2"]            =  "Specialist"
$vocab["level_3"]            = "user admin";  

   New rows in "rooms" table
        12    min_user_level int                    No    2             = 2 for special rooms only "Specialist" can use.
        13    PT_start_secs	int			No	32400	start of Primetime  in seconds from midnight		
	14	PT_end_secs	int			No	72000	end of Prime time in seconds from midnight			
	15	PT_max_secs	int			No	3600	Slot maximum in seconds during Primetime 		
	16	PT_pre_secs	int			No	7200	Pre sign-up maximum in seconds during Primetime

 a "specialist" will have access to certain rooms that normal users don't have access too..   
 "min_user_level" now shows up in my Edit Room page.....
And the "Specialist" userlevel shows up for all users.

//   CODE ADDED to function  mrbsCheckPolicy in mrbs_sql.inc, in the "check creation policy" section 

 
 //   Specialist Access
     $mrbs_user  = session()->getCurrentUser();
     $room_details = get_room_details($booking['room_id']);

     if ($mrbs_user->level < $room_details['min_user_level'])
     {
       $violations[] = get_vocab('User not authorized', $mrbs_user->name, htmlspecialchars($room_details['room_name']));
     }

All the room settings for Primetime automatically show up in the room editor (nice work, building the editor page based on the structure of the table).    

// Primetime limits.  
 //  Is primetime enabled
   if ($room_details['primetime_enabled'])
   {
     $dayOfWeek = date('w', $booking['start_time']);

//   Primetime is not active on Weekends
     if (!($dayOfWeek == 6 || $dayOfWeek == 0))
     {
       $start_hour = date('G', $booking['start_time']);
//     Primetime starts at about 9am and ends at about 8pm
       if ($start_hour*3600 > $room_details['PT_start_secs'] && $start_hour*3600 < $room_details['PT_end_secs'])
       {
//        $min_create_ahead = adjust_ahead_seconds($room_details['PT_pre_secs']);  // "Tried this but it doesn't return  a useable value for the test.
         $min_create_ahead = $room_details['PT_pre_secs'];
//       Primetime has minimum pre-signup default is 2 hours
//         if ($booking['start_time'] - $now < $min_create_ahead + cross_dst($now, $booking['start_time']))   // "I tried this too, thinking it should work whether daylight savings time is active or not.   
         if ($booking['start_time'] - $now > $min_create_ahead )
         {  
               $real_time_gap = $booking['start_time'] - $now; 
//            toTimeString($min_create_ahead, $units);   // does this turn seconds into hours automatically?
           $violations[] = get_vocab('Cannot book >2 hrs ahead in PrimeTime limit: ' . $min_create_ahead . 's Realtime gap ' . $real_time
_gap . 's', $booking['start_time'], $units);
         }
//         Primetime maximum slot length default is 1 hour    
         $slot = $booking['end_time'] - $booking['start_time'];
         if ($slot > $room_details['PT_max_secs'])
         {
           $violations[] = get_vocab('Cannot book >1 hrs in PrimeTime! ' . $slot . 's', $booking['start_time'],  htmlspecialchars($room_details['room_name']));
         }
       }
     }
   }

Regards,
Scott K Smith

MRBS user for over two flawless years!   Great platform.

**Comment by ksg1960** [comment]
This was too complicated, and I couldn't get it to work exactly as I intended.  So I reimagined the idea and instead of putting the permissions in both the users and rooms tables.   I have added a bunch of Boolean flags to the users which correspond to the various rooms I need protected.   

    I can get the user details and room details which are then used to check correspondance between the user's permission flags and the name of the room.   All I needed to do was make sure the permission flag used the correct name for the room.   (ie for a room named OX600 the flag was named "spec_OX600" ).   Having a bunch of rooms that don't need special permission, I put them all in the same area and am trying to match the name of the area to the "named" rights level in the user table.    This seems like it should work but I cannot seem to get the name of the area for the current booking.   Below are some of the variable setups that come right before a small set of IF-statements to filter out administrators, ordinary users, and the ordinary "area" and then special rooms.   

section added below checking some creation policies in mrbs_sql.php........

  global $vocab;    //get access to the different level names.
   $mrbs_user  = session()->getCurrentUser();   // get the username and level and what ever spec_roomname flags are needed
     $room_details = get_room_details($booking['room_id']);    // get the room name 
     $area_details = get_area_details($booking['area_id']);       //this should get the area_name and other details about the area
     $level_name = $vocab['level_'.$mrbs_user->level];    // convert the level code for a user to its name
     $area_name = $area_details['area_name'];    // extract the area name from the area details.  ---This does not work; it seems like it should because "area_name" is one of the fields in the area table.....

 $test = 'spec_'.$room_details['room_name'];    
     $room_permission = $mrbs_user->{$test};    ///here I am unsuccessfully trying to substitute a variable into the xxxx->yyy object connector.   It doesn't error out but it doesn;t set room_permission to a 1,0 (tiny int) as defined in the database for that permission.   
 
//I know some of these could alternatively be written directly into the code statements below but I having trouble keeping tack 
// of the correct names and details 
     

//Skip these permission checks if user is admin level

   if ($level_name != "admin") {
       if ($mrbs_user->level == 1) {    //you have to have level of 1 to book anything 
           if ($area_name != $level_name)  {  if the area name matches the user's level we shouldnt need to check anymore a shortcut way to allow a whole bunch of rooms to general access
               if !($room_permission) {    //I was assuming I could use the flag setting to control access.
                   $violations[] = get_vocab($mrbs_user->username .' not authorized for '.$room_details['room_name']. ' permission: '.$room_permission, $mrbs_user->name, htmlspecialchars($room_details['room_name']));
        

I have been using the $violations[] array to track my progress in accessing $user_names and  $room_names
but cannot get any output for the $area_name or $room_permission.

I also just realized that the permission flags that I created in the users table are un-protected from the users own ability to change them.    I know that you have a whole logic around users not being able to level-up themselves; can that be applied to the special rooms that I am trying to use here for restricting access on a user by user basis?        
 

I hope this makes  enough sense to reply to..

Scott

**Comment by ksg1960** [comment]
Okay, Okay, Okay.

I found the missing pieces and it seems to work now.

    global $vocab;

     $mrbs_user  = session()->getCurrentUser();
     $level_name = $vocab['level_'.$mrbs_user->level];
     $area_id = get_area($booking['room_id']);
     $area_name = get_area_name($area_id);
     $room_details = get_room_details($booking['room_id']);
      $room_permission = $mrbs_user->{"spec_".$room_details['room_name']};
          // Note that curly braces were needed to splice the string with the variable

   if ($level_name != "admin") {
       if ($mrbs_user->level == 1) {
           if ($area_name != $level_name)  {    //if they are in the "walkup" area  no need to check further 
               if ($room_permission == 0) {     //  Otherwise check the user permission for the room
                $violations[] = get_vocab('A) '.$mrbs_user->username.' ('.$level_name.') permission = '.$room_permission. ' for '.$room_details['room_name'].' in area:: '.$area_name.'!', $mrbs_user->name, htmlspecialchars($room_details['room_name']));
              }
           }
       } else {
          $violations[] = get_vocab('B) '.$mrbs_user->username.' (level#: '.$mrbs_user->level.') not authorized for signup', $mrbs_user->name, htmlspecialchars($room_details['room_name']));
       }
    }

**Comment by ksg1960** [comment]
1) put all the unrestricted rooms in an area **with a name that matches the user-level/rights (name)**
2) add tiny int fields to the Users table, whose names can be matched to the respective room names.
3) Insert the code above (edit if necessary to match your level names etc...)

Missing:  How do I set these room flags to be immutable by the User; that is, they are only editable by "admin"

**Comment by campbell-m** [comment]
See this section in systemdefaults.inc.php

~~~
// 'auth_db' configuration settings
// List of fields which only admins can edit.   By default these are the
// user level (ie admin/user) and the username.   Custom fields can be added
// as required.  To protect the password field use 'password_hash' - useful
// for public demo sites.
$auth['db']['protected_fields'] = array('level', 'name', 'display_name');
~~~

So to add another field, put the following in your config file:

~~~php
$auth['db']['protected_fields'][] = 'flag1';
// etc
~~~

**Comment by ksg1960** [comment]
Awesome, thank you so much!

By the way, am I duplicating effort in assigning permissions per user for  certain rooms?  I saw a response comment you made for someone else's request with a similar theme.   You pointed them to your roles branch, which I just downloaded.


 Scott



Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>






________________________________

**Comment by campbell-m** [comment]
> By the way, am I duplicating effort in assigning permissions per user for  certain rooms?  I saw a response comment you made for someone else's request with a similar theme.   You pointed them to your roles branch, which I just downloaded.

As I understand it you are trying to achieve two things:

1. Impose policies based on "primetime".
2. Limit certain users' access to certain rooms.

The first can be achieved, as you have done, by modifying `mrbsCheckPolicy()` and would have to be done whatever approach you take to the second objective.

The second can be achieved in one of two ways:

(a) Using the main branch.  You have done this by modifying `mrbsCheckPolicy()`.  I think this should probably work, but the more conventional approach would be to modify `getWritable()` in mrbs_auth.inc.  I don't think there's any need though to introduce an extra level of user rights.
(b) Using the roles branch.  This shouldn't require any modification of the code, but the branch is still under development and it will also upgrade your database so that it's no longer compatible with the main branch.

**Comment by ksg1960** [comment]
Hi Mr Campbell,

Thank you for taking the time to have a short discussion with me, with your assistance I think both my objectives have been met.   ( a bit more testing to be sure).   Your comments also helped me figure out the problem with my selection list of names.    Inconsistent capitalization, was the root cause.

The list consists of faculty who’s students operate my instruments.   Keeping it updated is only a small inconvenience (direct editing of config.inc.php).   But it would probably take the addition of a new table and lots of access code to have them be editable on-line.   The list changes only slowly as faculty are hired or retire and I try it keep it alphabetized for the menu pull down used to assign a “user” to a faculty member.    The sporatic re-editing lead to some inconsistency.

Sorry fo babbling.

Thank you
Scott

Regards,

Scott K Smith
From my cellphone
________________________________
