### ISSUE TITLE
Fatal error: unfortunately the database is not available at the moment.

### ISSUE THREAD

**Issue by antham1616** [meeting-room-booking-system/mrbs-code#3685]
when trying to edit or add entry i get the following message

Fatal error: unfortunately the database is not available at the moment.

when debugging it states

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '80902' for key 'PRIMARY'
SQL: INSERT INTO mrbs_entry (`

**Comment by campbell-m** [comment]
Which version of MRBS are you running?  And have you made any changes to it?  Can you please post the full stack trace from the debug output, having first removed any confidential data.

**Comment by antham1616** [comment]
<html>
<body>

MRBS version | MRBS 1.9.2
-- | --
Database schema version | 77
Database local schema version | 1
$auth['type'] | db
$auth['session'] | php


</body>
</html>

**Comment by antham1616** [comment]
Legacy with many modifications

**Comment by antham1616** [comment]
#0 MRBS\generate_backtrace() called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions_error.inc:152]
#1 MRBS\output_error() called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions_error.inc:182]
#2 MRBS\error_handler(2, Cannot modify header information - headers already sent by (output started at /homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions_error.inc:157), /homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions.inc, 694, array)
#3 header(Expires: Mon, 26 Jul 1997 05:00:00 GMT) called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions.inc:694]
#4 MRBS\expires_header(0) called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions.inc:709]
#5 MRBS\http_headers(array) called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/Themes/default/header.inc:547]
#6 MRBS\print_theme_header(array, true, false) called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions.inc:749]
#7 MRBS\print_header(NULL, true) called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions.inc:718]
#8 MRBS\print_simple_header() called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions_error.inc:220]
#9 MRBS\fatal_error(Fatal error: unfortunately the database is not available at the moment.) called at [/homepages/15/d858295215/htdocs/NDCT-V1.0/web/functions_error.inc:210]
#10 MRBS\exception_handler(object)

**Comment by campbell-m** [comment]
Thanks.  Was there any more of the stack trace?  I'd expect to see some more lines below the last one.

**Comment by antham1616** [comment]
there is but its all the post values with alot of confidential data

**Comment by campbell-m** [comment]
Can you post a screenshot from phpMyAdmin of the structure of your mrbs_entry table?

**Comment by antham1616** [comment]
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/82525735/79990ba9-8f3d-49e7-be3a-9a828bbfcb5f)
![image](https://github.com/meeting-room-booking-system/mrbs-code/assets/82525735/d7f686ef-0f06-453d-ba40-3c27977103e4)

**Comment by campbell-m** [comment]
I don't know why this is happening?  Can you reproduced the problem at will?  If so, does it still hapen if you run vanilla MRBS 1.9.2?

**Comment by antham1616** [comment]
only happens when adding new entry or editing existing, able to open add participants without issue
setup upgraded vanilla database, connected existing site to it no issues so far

**Comment by antham1616** [comment]
will try copying existing database and running upgrade to see if resolves

**Comment by campbell-m** [comment]
> setup upgraded vanilla database, connected existing site to it no issues so far

What happens if you run vanilla MRBS 1.9.2 against your database?

**Comment by berkerY** [comment]
Hi @antham1616, i had same error when editing a message. Please see my bug fix here: https://github.com/meeting-room-booking-system/mrbs-code/issues/3680

**Comment by campbell-m** [comment]
I assume this has now been resolved.
