### ISSUE TITLE
Display an asterisk (*) for required / mandatory fields in edit_entry.php

### ISSUE THREAD

**Issue by berkerY** [meeting-room-booking-system/mrbs-code#3686]
Hello, 

is it possible to display an asterisk for required / mandatory fields at rendering of Form elements in edit_entry.php? 

Thanks
Berker

**Comment by berkerY** [comment]
Hi @campbell-m could you give me a feedback please? 
Thanks

**Comment by campbell-m** [comment]
You could do it with custom js and custom css files (see systemdefaults.inc.php for details of how to create them):

~~~js
$(document).on('page_ready', function() {
  $(':required').not(':disabled').after('<span>*</span>');
});
~~~

and style it with

~~~css
.standard fieldset div span:not(.none) {
  display: inline-block;
  vertical-align: top;
  margin-right: 1em;
}
~~~

**Comment by berkerY** [comment]
Thank you. It works perfectly!
