### ISSUE TITLE
Area specific default view settings 

### ISSUE THREAD

**Issue by ksg1960** [meeting-room-booking-system/mrbs-code#3691]
Not a problem 

**Describe the solution you'd like**
It would be "nice" to be able to have the "week" view set as default for just one of my areas because it contains only rooms with very long reservation blocks.   

The rest of my areas contain rooms that operate on shorter booking increments and much shorter prebooking limits, so the default for them is definitely "day" view.   

**Describe alternatives you've considered**

**Additional context**

**Comment by campbell-m** [comment]
You could achieve this with a fairly simple change to standard_vars.inc.php.  However you should note that the default view only applies if the view hasn't already been specified.  So if you were to go first to one of the areas that has a default view of 'day', and then switch area to one that has a default view of 'week', you would be shown the 'day' view.  Of course this could also be changed in standard_vars.inc.php.

**Comment by ksg1960** [comment]
Thanks for the suggestion.

It may be crude but this works:

if ($area == 4)  // area is for Welch EPR
{
    $view = 'week';
    $view_all = 0;
} else {
    $view = 'day';
}

Cheers,
Scott






Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>






________________________________

**Comment by ksg1960** [comment]
My crude attempt above works but makes the views immutable.  

That is, none of the areas can be viewed in any other "view" but the one set in the "if" statement.    I tried adding a new variable "$lastarea" for use in a nested if clause to toggle between the default and the view selected with the righthand buttons.  It was something like, " if the area hasn't changed then allow the new view "  Either the new variable is not stable or the logic I applied doesn't work.   Perhaps if I knew what happens when one clicks on the view buttons...   Do you have any suggestions?

The code above was inserted directly below "get_area_settings($area);", if that makes any difference.

best regards,
Scott

**Comment by campbell-m** [comment]
You need to remove your code and change the lines

~~~php
$view = get_form_var('view', 'string', $default_view ?? 'day');
$view_all = get_form_var('view_all', 'int', empty($default_view_all) ? 0 : 1);
~~~

to

~~~php
$view = get_form_var('view', 'string', ($area == 4) ? 'week' : 'day');
$view_all = get_form_var('view_all', 'int', ($area == 4) ? 0 : 1);
~~~

but put them after the area has been determined, ie after

~~~php
if (empty($area))
{
  $area = get_default_area();
}
~~~

**Comment by ksg1960** [comment]
Thank you for the suggestion, unfortunately it has no discernable affect at all.






Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>






________________________________

**Comment by campbell-m** [comment]
Could you post your standard_vars.inc.php here please so that I can check it?

**Comment by ksg1960** [comment]
Here is the current version.....




Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>

**Comment by campbell-m** [comment]
Sorry, it didn't come through.  I don't know if you can email attachments to GitHub.  If you can they will almost certainly not allow .php and .inc files.  You'll either have to copy the contents and paste them inline, or rename the file to a .txt file or login and post it that way.

**Comment by ksg1960** [comment]
C:\Users\sks3973>more standard_vars.inc.php
<?php
declare(strict_types=1);
namespace MRBS;

// Gets the standard variables of $day, $month, $year, $area and $room
// Checks that they are valid and assigns sensible defaults if not

// Get the standard form variables
use DateInterval;

$page_date = get_form_var('page_date', 'string');
//$view = get_form_var('view', 'string', $default_view ?? 'day');
//$view_all = get_form_var('view_all', 'int', empty($default_view_all) ? 0 : 1);  // Whether to view all rooms
$year = get_form_var('year', 'int');
$month = get_form_var('month', 'int');
$day = get_form_var('day', 'int');
$area = get_form_var('area', 'int');
$room = get_form_var('room', 'int');
$kiosk = get_form_var('kiosk', 'string');

if (empty($area))
{
  $area = get_default_area();
}
//////////////////////////////////////////////////////////////////////////////
$view = get_form_var('view', 'string', ($area == 4) ? 'week' : 'day');
$view_all = get_form_var('view_all', 'int', ($area == 4) ? 0 : 1);
/////////////////////////////////////////////////////////////////////////////


if (empty($room))
{
  $room = get_default_room($area);
}

// No point in showing all the rooms if there's only one of them.  Show
// the normal view (with time slots) instead
if (($view != 'day') && !$always_offer_view_all & count(get_rooms($area)) == 1)
{
  $view_all = 0;
}

// Get the settings (resolution, etc.) for this area
get_area_settings($area);


if (isset($page_date) && ($page_date !== ''))
{
  if (false === ($page_date_split = split_iso_date($page_date)))
  {
    if (is_ajax())
    {
      http_response_code(500);
      trigger_error("Ajax: invalid page_date '$page_date'", E_USER_NOTICE);
      exit;
    }
    trigger_error("Invalid page_date '$page_date'", E_USER_NOTICE);
  }
  else
  {
    list($year, $month, $day) = $page_date_split;
  }
}

$date = new DateTime();

// If we're in kiosk mode and the current time is after the end of the last slot
// then advance to tomorrow - unless we're in periods mode when we don't know
// the actual time of the last slot.
if (isset($kiosk))
{
  if (!$enable_periods && ($date->getTimestamp() > get_end_last_slot($date->getMonth(), $date->getDay(), $date->getYear())))
  {
    $date->add(new DateInterval('P1D'));
  }
}
// If we are not in kiosk mode and have been given a date then use that
elseif (!empty($day) && !empty($month) && !empty($year))
{
  $date->setDate($year, $month, $day);
}

// Advance to the next non-hidden day
if (!empty($hidden_days) &&     // Use !empty in case $hidden_days is not set
    (count($hidden_days) < 7))  // Avoid an infinite loop
{
  while ($date->isHiddenDay())
  {
    $date->modify('+1 day');
  }
}

$day = $date->getDay();
$month = $date->getMonth();
$year = $date->getYear();

C:\Users\sks3973>




Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>

**Comment by campbell-m** [comment]
Ah, OK, I see what's happening.  The code above will go the correct view for the area if you go to index.php?area=3 or index.php?area=4, but once you've been there the view is set and so if you change area you will stay in the same view.

What do you want to happen if you go to Area 4 and find yourself in the week view, then change area to Area 3.  Presumably switch to the day view?  But if before switching to Area 3 you switched to the month view, would you still expect to go to the day view on switching to Area 3?

**Comment by ksg1960** [comment]
Hmmm,

The idea is to use the assigned "default" whenever first changing to a new area.  So in my case, when changing from area 4 (week view) to area 3/2/1 view them in day mode and visa versa.   But still allow switching views on the active area.   Does this make sense?

Scott




Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>

**Comment by ksg1960** [comment]
What I had hard coded worked with respect to the first part.   It just did not allow switching views independently.




Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>

**Comment by ksg1960** [comment]
Perhaps adding a preferred view to the areas table would make this easier and more extensible.




Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>

**Comment by campbell-m** [comment]
> The idea is to use the assigned "default" whenever first changing to a new area.  So in my case, when changing from area 4 (week view) to area 3/2/1 view them in day mode and visa versa.   But still allow switching views on the active area.   Does this make sense?

So presumably you'd expect the preferred view to take precedence over the previously selected view?  In my example above if you switch to the month view before changing areas you'd expect to end up in either the day or week view for the new area?

**Comment by ksg1960** [comment]
Yes, that is correct.   I would like to set a preferred view that matches (if possible) the expectations of the user.  So it defaults to this whenever casually changing Areas.   As the administrator, I still like access to the historical view provided by a month or a weeks view even for the Areas that are primarily booked for 30 minutes or less.   Those areas are set up with permissions prohibiting next day booking so the month view and even the week view are mostly unusable by the end users.   At the other end of the spectrum, users are permitted to book a system for a couple of days, with access of up to a month ahead of time.

Scott




Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>

**Comment by campbell-m** [comment]
Then I think what you need to do is stick with your original code but add another parameter to the view navigation by editing index.php around line 246:

~~~php
    $vars = array('view'      => $view,
                  'view_all'  => $this_view_all,
                  'force_view => 1,  // add this line
                  'page_date' => format_iso_date($year, $month, $day),
                  'area'      => $area,
                  'room'      => $room);
~~~

and then in standard_vars your code should look like this;

~~~php
$force_view = get_form_var('force_view', 'bool', false);

if (!$force_view)
{
  if ($area == 4)  // area is for Welch EPR
  {
      $view = 'week';
      $view_all = 0;
  } else {
      $view = 'day';
  }
}
~~~

Then if one of the view buttons is clicked your preferred views won't apply and you'll be able to change views.

**Comment by ksg1960** [comment]
Great, that works!   But I am confounded because I don't know why.   It looks like we are creating a new variable for forms "$force_view" and setting it true by default.

Then we query it in the standard.inc.php code (And I don't know when it is actually run), set it to false (only if it's not been set?), and finally kick off my hard coded views if its not true?   I have to admit this makes my head ache.   Is there some simple logic I am missing that makes this make sense?  Is there something transitory about the forms variables such that they are partially cleared after the main display has been completed?

Cheers and thanks again for this!
Scott






Scott K. Smith, Director of NMR Spectroscopy
The University of Texas at Austin | Chemistry | 832-294-1928 | utexas.edu<https://www.utexas.edu/>

**Comment by campbell-m** [comment]
The standard_vars code is run every time a page is loaded and sets up the global variables `$area`, `$room`, `$view`, etc, from the GET or POST parameters.   It is now also looking for `$force_view` and setting that to `false` if it doesn't find it.  The only places that it is set are in the three view buttons (day/week/month) where it is set to 1 (true) and so enables your preferred views to be overridden.

**Comment by ksg1960** [comment]
You make it sound so simple!  

Thank you
