### ISSUE TITLE
batch exporting bookings as ics format

### ISSUE THREAD

**Issue by berkerY** [meeting-room-booking-system/mrbs-code#3692]
Hi, 

is it possible to add a button in search.php to batch export all / shown entries as an ics file?

Greetings,
Berker

**Comment by campbell-m** [comment]
You can do this from the Report page, which is just a glorified Search.  Or is there a particular reason for wanting to do it from Search?

**Comment by berkerY** [comment]
Thanks for answer. Actually, we want to allow ordinary users to batch export only their own entries as an ics file, likely by CSV format in search.php

**Comment by campbell-m** [comment]
OK that makes sense.  I'll have a think about it.

**Comment by berkerY** [comment]
any news here? :)

**Comment by campbell-m** [comment]
Sorry, I got sidetracked.  I don't think it should be too difficult.  I'll try and do something over the next couple of weeks.

**Comment by campbell-m** [comment]
I've now implemented this.  To test it you will need to download the complete set of files by following the green code button on [the main branch](https://github.com/meeting-room-booking-system/mrbs-code).
