### ISSUE TITLE
Session token in URL

### ISSUE THREAD

**Issue by Abhijit-81** [meeting-room-booking-system/mrbs-code#3693]
**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Description:**

Sensitive information within URLs may be logged in various locations, including the user’s browser,
the web server, and any forward or reverse proxy servers between the two endpoints. URLs may also
be displayed on-screen, bookmarked or emailed around by users. They may be disclosed to third
parties via the Referer header when any off-site links are followed. Placing session tokens into the
URL increases the risk that they will be captured by an attacker.

The above report is generated by a **Vulnerability** scanner against MRBS application and reports **Severity: Medium** can you please help to address the issue, details of the platform is below as asked

**Browser details (please complete the following information):**
 - OS: [e.g. iOS]- UBUNTU22
 - Browser [e.g. chrome, safari]- Mozila/Crome

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]- 1.11.5
 - Web server: [e.g. Apache 2.4.48]-2.4.52
 - OS: [e.g. CentOS 7.9] - UBUNTU22
 - PHP version: [e.g. 7.4.23]- 8.1.2

 - Database used: [e.g. MySQL 8.0.26] -MariaDB 10.6.16
 - 

**Additional context**

**Comment by campbell-m** [comment]
I've created [a new branch](https://github.com/meeting-room-booking-system/mrbs-code/tree/3693-session-token-in-url) to fix this issue and committed some code there.  You can download the code by following the green Code button.  Could you test the code please and re-run your vulnerability scanner and let me know of any problems?

**Comment by Abhijit-81** [comment]
I am just trying to show you the specific result  as follows to give idea, I have updated your code as per fix but before going to vulnerability scanner kindly confirm if this has been addressed by checking the result, thanks

**Specific Result**

The URL in the request appears to contain a session token within
↪→ the query string : https :// site.name / index .
↪→ php ? csrf \ _token =45
↪→ b 4 c 0 5 2 2 a 8 d 9 2 3 7 d d 3 4 7 6 f b 2 9 d 7 4 4 c 3 2 e e 3 b 1 1 2 d 7 9 4 7 a e 8 7 5 1 e c 9 8 2 1 3 c 6 3 1 8 d
↪→ \& amp ; view = day \& amp ; area =0\& amp ; page \ _date =2024 -06 -27

**Comment by campbell-m** [comment]
Did you get a chance to re-run the vulnerability scanner?

**Comment by Abhijit-81** [comment]
it is managed by separate team, I have uploaded your revised code, once they reply I will definitely get back to you. Thanks

**Comment by campbell-m** [comment]
OK, thanks.

**Comment by Abhijit-81** [comment]
Yes, your revised code is finally passed in  vulnerability scanner, thanks a lot for your support

**Comment by Abhijit-81** [comment]
is postfix supported by mrbs?

**Comment by jberanek** [comment]
> is postfix supported by mrbs?

That sounds like a different question, please open a new ticket.

**Comment by Abhijit-81** [comment]
ok sorry
