### ISSUE TITLE
MRBS very slow when using, Getting me sign out.

### ISSUE THREAD

**Issue by josmoral** [meeting-room-booking-system/mrbs-code#3695]
When using MRBS, the platform is very slow, and getting me sign out.

**Browser details (please complete the following information):**

 - Browser [e.g. chrome] Latest version
 - 
**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]
 - Web server:2.4.52 (Ubuntu)]
 - PHP version: [8.1.2-1]
 - Database used: [e.g. MySQL 8.0.37]

**Additional context**
Pleas help.

**Comment by campbell-m** [comment]
Which version of MRBS are you using?  What have you got `$auth['type']` and `$auth['session']` set to?  Has this just started happening or is this a fresh install?  What in particular is slow?

**Comment by josmoral** [comment]
it just start happening, it has been workin well. 
How I can find the version?

How I can set those two options?

Thanks.
Jossué

**Comment by josmoral** [comment]
version is: MRBS 1.11.0

**Comment by campbell-m** [comment]
You can find those other two settings on the Help page when you are logged in as an admin.

**Comment by josmoral** [comment]
I will try that, but still very slow.

**Comment by josmoral** [comment]
I found this errors on Apache log:
[Thu Jul 11 17:09:58.913624 2024] [php:notice] [pid 2454] [client 192.168.66.66:61599] \nE_USER_WARNING in /var/www/educ/schedule/web/lib/MRBS/DB_mysql.php at line 302\nGET_LOCK timed out after 20 seconds\nMRBS GET: Array\n(\n)\nMRBS POST: Array\n(\n    [refresh] => 1\n    [view] => day\n    [view_all] => 1\n    [page_date] => 2024-07-11\n    [area] => 3\n    [room] => 3\n)\n\n, referer: https://educ.aguadilla.inter.edu/schedule/web/index.php
[Thu Jul 11 17:09:58.913853 2024] [php:notice] [pid 2454] [client 192.168.66.66:61599] \nE_USER_WARNING in /var/www/educ/schedule/web/lib/MRBS/SessionHandlerDb.php at line 230\nFailed to acquire a lock\nMRBS GET: Array\n(\n)\nMRBS POST: Array\n(\n    [refresh] => 1\n    [view] => day\n    [view_all] => 1\n    [page_date] => 2024-07-11\n    [area] => 3\n    [room] => 3\n)\n\n, referer: https://educ.aguadilla.inter.edu/schedule/web/index.php
[Thu Jul 11 17:09:59.633662 2024] [php:notice] [pid 2435] [client 192.168.66.66:61601] \nE_USER_WARNING in /var/www/educ/schedule/web/lib/MRBS/DB_mysql.php at line 302\nGET_LOCK timed out after 20 seconds\nMRBS GET: Array\n(\n)\nMRBS POST: Array\n(\n    [refresh] => 1\n    [view] => day\n    [view_all] => 1\n    [page_date] => 2024-07-11\n    [area] => 3\n    [room] => 3\n)\n\n, referer: https://educ.aguadilla.inter.edu/schedule/web/index.php
[Thu Jul 11 17:09:59.633876 2024] [php:notice] [pid 2435] [client 192.168.66.66:61601] \nE_USER_WARNING in /var/www/educ/schedule/web/lib/MRBS/SessionHandlerDb.php at line 230\nFailed to acquire a lock\nMRBS GET: Array\n(\n)\nMRBS POST: Array\n(\n    [refresh] => 1\n    [view] => day\n    [view_all] => 1\n    [page_date] => 2024-07-11\n    [area] => 3\n    [room] => 3\n)\n\n, referer: https://educ.aguadilla.inter.edu/schedule/web/index.php
[Thu Jul 11 17:10:09.014173 2024] [php:notice] [pid 2864] [client 207.46.13.7:53573] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:10:36.766016 2024] [php:notice] [pid 2434] [client 157.55.39.8:4235] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:10:41.865398 2024] [php:notice] [pid 2441] [client 52.167.144.192:56536] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256

**Comment by josmoral** [comment]
More from the Apache Log:
[Thu Jul 11 17:29:39.479451 2024] [php:notice] [pid 1964] [client 157.55.39.200:43988] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:29:53.525172 2024] [php:notice] [pid 4993] [client 52.167.144.235:53468] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:29:58.017898 2024] [php:error] [pid 4994] [client 52.167.144.235:53442] script '/var/www/educ/schedule/web/day.php' not found or unable to stat
[Thu Jul 11 17:29:58.389264 2024] [php:notice] [pid 4994] [client 52.167.144.235:53442] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:30:13.744917 2024] [php:notice] [pid 2454] [client 157.55.39.56:54016] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:30:18.332140 2024] [php:notice] [pid 2434] [client 157.55.39.56:64859] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:30:30.225640 2024] [php:notice] [pid 2440] [client 157.55.39.200:49032] PHP Notice:  Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'. in /var/www/educ/schedule/web/language.inc on line 256
[Thu Jul 11 17:30:41.896634 2024] [php:notice] [pid 2422] [client 192.168.66.66:62022] \nE_USER_WARNING in /var/www/educ/schedule/web/lib/MRBS/DB_mysql.php at line 302\nGET_LOCK timed out after 20 seconds\nMRBS GET: Array\n(\n    [view] => day\n    [view_all] => 1\n    [page_date] => 2024-07-12\n    [area] => 3\n    [room] => 3\n)\nMRBS POST: Array\n(\n)\n\n, referer: https://educ.aguadilla.inter.edu/schedule/web/
[Thu Jul 11 17:30:41.896864 2024] [php:notice] [pid 2422] [client 192.168.66.66:62022] \nE_USER_WARNING in /var/www/educ/schedule/web/lib/MRBS/SessionHandlerDb.php at line 230\nFailed to acquire a lock\nMRBS GET: Array\n(\n    [view] => day\n    [view_all] => 1\n    [page_date] => 2024-07-12\n    [area] => 3\n    [room] => 3\n)\nMRBS POST: Array\n(\n)\n\n, referer: https://educ.aguadilla.inter.edu/schedule/web/

**Comment by campbell-m** [comment]
Thanks.  Could you let me know please what got `$auth['type']` and `$auth['session']` are set to, as reported on the Help page when logged in as an admin?

Also could you give more details please of what exactly is slow and how many seconds it takes to do it?

**Comment by josmoral** [comment]
Thanks for the time, the slowness problem it was an issue with our DNS.

**Comment by campbell-m** [comment]
Good, glad it's solved.

An unrelated issue is that you are getting the message "PHP Notice: Server failed to set locale to ["en.UTF-8","en-GB.UTF-8","en_GB.UTF-8"] for language tag 'en'." in your logs.  You can solve this by installing the en or en-GB locales on your server, or else by setting `$override_locale` to a locale that is installed.
