### ISSUE TITLE
MRBS SUPPORT FOR POSTFIX

### ISSUE THREAD

**Issue by Abhijit-81** [meeting-room-booking-system/mrbs-code#3697]
**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Browser details (please complete the following information):**
 - OS: [UBUNTU] 
 - Browser [Mozila/Crome] 
 - Version [22]

**Server details (please complete the following information):**
 - MRBS version [1.11.5]
 - Web server: [Apache 2.4.52
 - OS: [UBUNTU]
 - PHP version: [8.1.2]
 - Database used: [Mariadb 10.6.16]

**Additional context**
Postfix not working in context of mail send from mrbs, while sendmail is working properly, is postfix is supported by MRBS.

**Comment by campbell-m** [comment]
It should work.  What is your MRBS mail configuration?

**Comment by Abhijit-81** [comment]
$mail_settings['admin_backend'] = 'mail';

$sendmail_settings['path'] = '/usr/sbin/sendmail';

$smtp_settings['host'] = 'smtp.server';

$smtp_settings['port'] = 'Port';

$smtp_settings['auth'] = false;


$smtp_settings['secure'] = '';


$smtp_settings['hostname'] = '';

I was just wondering its working fine with sendmail, but not postfix as a mail client.

**Comment by jberanek** [comment]
If you set the backend to 'mail', you rely upon your PHP installation's email configuration. None of the other settings you've posted will be used.

**Comment by jberanek** [comment]
See https://github.com/meeting-room-booking-system/mrbs-code/blob/main/web/systemdefaults.inc.php#L1709-L1794

**Comment by campbell-m** [comment]
MRBS uses PHPMailer to send mail.  It would be worth searching for how to send mail using PHPMailer and Postfix.

**Comment by Abhijit-81** [comment]
thanks i got the hint, it works
