### ISSUE TITLE
Site can't be reached

### ISSUE THREAD

**Issue by Summerfield655** [meeting-room-booking-system/mrbs-code#3698]
**Describe the bug**
Not able to reach the site. 
ERR_CONNECTION_TIMED_OUT

**To Reproduce**
1. Go to 'calendar.summerfieldwaldorf.org'
2. Error message:
'This site can’t be reachedcalendar.summerfieldwaldorf.org took too long to respond.
Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT'

**Expected behavior**
expected to be able to access the site and use the MRBS

**Screenshots**
![calendar summerfieldwaldorf org](https://github.com/user-attachments/assets/8bc29c40-10a6-41e7-ade3-bf1590133682)

**Browser details (please complete the following information):**
 - OS: 64-bit operating system, x64-based processor
 - Browser: Chrome
 - Version: Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by campbell-m** [comment]
This sounds like a network problem rather than an MRBS problem. Have you tried following the suggestions in the screenshot?

**Comment by Summerfield655** [comment]
Yes, nothing has changed.

**Comment by Summerfield655** [comment]
I will recheck with our IT professional about the network. Thanks

**Comment by campbell-m** [comment]
Not an MRBS problem.
