### ISSUE TITLE
To add Notification email option while creating a booking against the Room

### ISSUE THREAD

**Issue by Abhijit-81** [meeting-room-booking-system/mrbs-code#3699]
**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Browser details (please complete the following information):**
 - OS: [e.g. iOS]-UBUNTU
 - Browser [e.g. chrome, safari]- Mozilla/Chrome

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4] - 1.11.5
 - Web server: [e.g. Apache 2.4.48]- 2.4.52
 - OS: [e.g. CentOS 7.9] - Ubuntu
 - PHP version: [e.g. 7.4.23] - 8
 - Database used: [e.g. MySQL 8.0.26] - Mariadb 10.6

**Additional context**

Actually I was wondering if there is any option to add email address for sending notification to corresponding users while create/Modify a booking (Add Entry) option, it is specially require for the situation if someone create a booking on behalf of others a notification email should go to concerned person (others), and this email id should be enter manually by booking creator, it can be multiple id to be enter depends on requirement.

**Comment by campbell-m** [comment]
Are the other users to whom the email should be sent registered users of MRBS or not?

**Comment by Abhijit-81** [comment]
No they are not registered users it is just to send them a notification that booking has been made based on there request.

**Comment by campbell-m** [comment]
See Issue #3670.

**Comment by Abhijit-81** [comment]
Colum need to add in mrbs_room or mrbs_entry table?

**Comment by campbell-m** [comment]
In the mrbs_entry and mrbs_repeat tables.

**Comment by Abhijit-81** [comment]
Thanks for the hint it works
