### ISSUE TITLE
Unfortunately your browser isn't supported by MRBS

### ISSUE THREAD

**Issue by Steve1971Git** [meeting-room-booking-system/mrbs-code#3706]
We have just upgraded our Windows IIS server to the latest version of php and also remove Oracle Java and replaced it with OpenJDK.  When I tried to address the mrbs page, I got a blank screen, no error messages.

It has been some time since we installed mrbs, so I have downloaded the latest release from your GitHub repo and upgraded our installation.  This prompted me to upgrade the database also, which I did.

The mrbs page now displays, but has a message that the browser us unsupported.  I have tried both Firefox (latest release) and Microsoft 
Edge (latest release) and both seem to display the page, but have lost all formatting.

Is there something that I have overlooked during my upgrade.

Kind regards, Steve.

**Comment by campbell-m** [comment]
You may be running a cached version of the CSS.  Try doing a hard refresh on your browser. If that fails open your browser's developer tools and see if you are getting any error messages in the console.

**Comment by Steve1971Git** [comment]
Hi campbell-m, 

Thank you for coming back to me so quickly.

I have cleared all my broswer history and cache, but still have the same result I'm afraid.  I have put Firefox in to We Developer mode, but as far as I can see, I have no erros, I'm guessing these would be easy to spot?

I have added a screen capture to my reply, this is what the layout now looks like.

Kind regards, Steve.

![Screenshot 2024-07-29 165936](https://github.com/user-attachments/assets/5a88a211-db8e-4468-9835-947b1114294b)

**Comment by Steve1971Git** [comment]
Further to my last reply, I have now found these 3 errors:

GET
https://calendar.lboro.ac.uk/css/mrbs.css.php?v=1722260612
[HTTP/2 500  42ms]
JQMIGRATE: Migrate is installed, version 3.4.0

<html><body>
<span class="message-body-wrapper"><span class="message-flex-body"><span class="message-body devtools-monospace"><span class="method">GET</span><a class="url" title="https://calendar.lboro.ac.uk/css/mrbs-print.css.php?v=1722260612" href="https://calendar.lboro.ac.uk/css/mrbs-print.css.php?v=1722260612">https://calendar.lboro.ac.uk/css/mrbs-print.css.php?v=1722260612</a><a class="status"><span class="status-info">[HTTP/2 <span class="status-code" data-code="500" title="Learn More">500</span>  38ms]</span></a></span> </span><div class="network-info network-monitor"><div class="devtools-sidebar-tabs"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item panel-with-code is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div></div></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><div id="headers-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="headers-tab"><div class="tab-panel panel-with-code"><div class="headers-panel-container"><div class="devtools-toolbar devtools-input-toolbar"><div class="devtools-searchbox"><input class="devtools-filterinput" placeholder="Filter Headers" type="search" value=""></div></div><div class="panel-container"><div class="headers-overview"><div class="url-preview"><div class="properties-view"><div class="tree-container">
  |  
-- | --
GET | https://calendar.lboro.ac.uk/css/mrbs-print.css.php?v=1722260612

</span>
</body>
</html>

<html><body>
<span class="message-body-wrapper"><span class="message-flex-body"><span class="message-body devtools-monospace"><span class="method">GET</span><a class="url" title="https://calendar.lboro.ac.uk/favicon.ico" href="https://calendar.lboro.ac.uk/favicon.ico">https://calendar.lboro.ac.uk/favicon.ico</a><a class="status"><span class="status-info">[HTTP/2 <span class="status-code" data-code="404" title="Learn More">404</span>  0ms]</span></a></span> </span><div class="network-info network-monitor"><div class="devtools-sidebar-tabs"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item panel-with-code is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div></div></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><div id="headers-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="headers-tab"><div class="tab-panel panel-with-code"><div class="headers-panel-container"><div class="devtools-toolbar devtools-input-toolbar"><div class="devtools-searchbox"><input class="devtools-filterinput" placeholder="Filter Headers" type="search" value=""></div></div><div class="panel-container"><div class="headers-overview"><div class="url-preview"><div class="properties-view"><div class="tree-container">
  |  
-- | --
GET | https://calendar.lboro.ac.uk/favicon.ico

</span>
</body>
</html>

**Comment by Steve1971Git** [comment]
GET https://calendar.lboro.ac.uk/css/mrbs.css.php?v=1722260612
[HTTP/2 500  42ms]

GET https://calendar.lboro.ac.uk/css/mrbs-print.css.php?v=1722260612
[HTTP/2 500  38ms]

GET https://calendar.lboro.ac.uk/favicon.ico
[HTTP/2 404  0ms]

**Comment by Steve1971Git** [comment]
I'm not sure I am doing this right or not, but if I expand the error for:
GET https://calendar.lboro.ac.uk/css/mrbs-print.css.php?v=1722260612

I get the following

Status 500
VersionHTTP/2
Transferred193 B (0 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem

GET
https://calendar.lboro.ac.uk/css/mrbs.css.php?v=1722260612
[HTTP/2 500  28ms]

	
GET
	https://calendar.lboro.ac.uk/css/mrbs.css.php?v=1722260612
Status
500
VersionHTTP/2
Transferred193 B (0 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem
    	
HTTP/2 500 
content-type: text/html; charset=UTF-8
server: Microsoft-IIS/10.0
x-powered-by: PHP/8.3.9
x-powered-by: ASP.NET
date: Mon, 29 Jul 2024 16:53:41 GMT

Do you need more?

The "DNS ResolutionSystem" error seems a strange one, my DNS name resolves to the server with IIS and the website.

**Comment by campbell-m** [comment]
No, what you need to do is look at the "Sources" tab (if using Chrome developer tools) and then the source of mrbs.css.php.  I suspect it contains a PHP error message which is invalidating the CSS file, which is why you aren't getting any formatting.

**Comment by campbell-m** [comment]
Did you manage to have a look at the source of mrbs.css.php?

**Comment by Steve1971Git** [comment]
Hi @campbell-m, sorry I havn't come back to you sooner, I've been on holiday.

I managed to solve the issue, it was to do with the version of PHP.  As I said in the beginnig the server had a php upgrade and went to version 8.3.9.  When I dropped the version to 7.4.28 everything started to work without issue.

Thanks for your support.

**Comment by campbell-m** [comment]
Well that means there's probably a problem when running with 8.3.9 which it would be good to solve because it's supposed to work. If you get a chance it would be good to have the source of mrbs.css.php as delivered to the browser.

**Comment by qbiecom** [comment]
@Steve1971Git Did you ever figure this out with PHP8? We're having the same issue at UoBham with IIS.

the css.php file delivers no content, and we get a 500 server error.

**Comment by campbell-m** [comment]
> We're having the same issue at UoBham with IIS. the css.php file delivers no content, and we get a 500 server error.

What error messages are you getting in your PHP error log?  And what versions of MRBS and PHP are you running?

**Comment by qbiecom** [comment]
@campbell-m We were running an older version (the DB updated from v36!!) but updated to a fresh copy of 1.11.5, with PHP 8.3.13

We think we've narrowed it down to something in our config file, as replacing it with a fresh copy seems to have fixed it. We're going to try reapplying our config step by step and seeing what breaks it, will report back if we figure it out!
