### ISSUE TITLE
How can I add new menu tab for specific area?

### ISSUE THREAD

**Issue by khanhdn0112** [meeting-room-booking-system/mrbs-code#3708]
Hi.

I want to create a new area and add a new menu display only in that area. Is that possible? 

Thank you so much!

**Comment by campbell-m** [comment]
If you are running MRBS 1.11.5 then edit the function `print_menu_items()` in the file Themes/default/header.inc and at the end of the function add the lines

~~~php
  global $area;
  if ($area == 4) // Change 4 to the id of the area you want
  {
    echo '<a href="https://yoursite.com/yourpage">Your menu item</a>';
  }
~~~
