### ISSUE TITLE
Debug email

### ISSUE THREAD

**Issue by BrzIGH** [meeting-room-booking-system/mrbs-code#3710]
Hi folks,

had a good working installation till today - when I tried pointing to a new smtp server that requires authentication.
Made the relevant changes in the config. Things did not work out. So I rolled back the settings.

But now that does not work. I then enabled email debugging. My understanding is that this should provide error messages in the browser session but nothing happens.

What am I missing ?

Running version 1.6.1 (and it worked just fine till this morning)

**Comment by campbell-m** [comment]
By default mail debug output goes to the PHP error log:

~~~php
// Where to send the debug output.  Can be 'browser' or 'log' (for the error_log)
$mail_settings['debug_output'] = 'log';
~~~

By the way, is there any good reason why you are not running the latest release, MRBS 1.11.5?

**Comment by BrzIGH** [comment]
Ahh..I did not have that line in there...will add it now..
I suppose I just got reminded that I need to upgrade :-)
Thanks

**Comment by BrzIGH** [comment]
So here is the section where apparently TLS crashes:

[31-Jul-2024 12:42:27 America/Vancouver] SERVER -> CLIENT: 220 Ready to start TLS
[31-Jul-2024 12:42:27 America/Vancouver] SMTP Error: Could not connect to SMTP host.
[31-Jul-2024 12:42:27 America/Vancouver] CLIENT -> SERVER: QUIT

have this line in my config:
$smtp_settings['secure'] = '';

Should I change anything here ?

**Comment by campbell-m** [comment]
I would get 1.6.1 working again with your old SMTP server, then upgrade to 1.11.5 and make sure that works with the old server, then get 1.11.5 working with the new server.

**Comment by jberanek** [comment]
I'd have a few guesses:

* Try $smtp_settings['secure'] = 'tls';
* Your MRBS server isn't trusting the TLS certificate from the SMTP server, due to the issuing CA not being trusted.

**Comment by BrzIGH** [comment]
It turns out that the old server was also upgraded yesterday so moving it back will not solve it...

I have verified that IIS and the smtp relay have the same intermediate CA certificate.

Can the line below specify a version of TLS ?
$smtp_settings['secure'] = 'tls';

**Comment by BrzIGH** [comment]
Also, how can I turn TLS off completely ? So that TLS connection is not even attempted ?

**Comment by jberanek** [comment]
https://github.com/meeting-room-booking-system/mrbs-code/blob/mrbs-1_6_1/web/systemdefaults.inc.php#L1080

**Comment by jberanek** [comment]
Your PHP installation will have its own CA trust store, it won't be anything to do with IIS.

**Comment by BrzIGH** [comment]
The issue seems to be that my installation did not support TLS 1.2. 
As soon as they allowed TLS 1.1 on the smtp relay it started working.
What do you think are my options ?

**Comment by jberanek** [comment]
1. Enable TLS on the mail today (not recommended) 
2. Disable TLS in MRBS config the way I showed (not recommended) 
3. Upgrade your MRBS server/PHP to sort TLS 1.2/1.3

**Comment by BrzIGH** [comment]
Thank you. Please consider this closed.
