### ISSUE TITLE
Database upgrade incomplete

### ISSUE THREAD

**Issue by BrzIGH** [meeting-room-booking-system/mrbs-code#3711]
Built a new server. Confirmed working OK.

After restoring from backup the database upgrade process runs fine for ver 52 (or so) to version 55.

But it fails at version 56

To complete the upgrade the database now needs to be upgraded. Please backup your database before proceeding.
Upgrading to database version: 56
Fatal error: unfortunately the database is not available at the moment.

I am upgrading from 1.6

Thanks

**Comment by campbell-m** [comment]
What's the detailed error message that appears in your PHP error log? Or if you can't find the log you can, temporarily, make error messages appear in the browser by setting `$debug = true;` in your config file.

**Comment by BrzIGH** [comment]
[01-Aug-2024 22:02:17 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_gd2.dll' (tried: C:\Program Files\php-8.3.10-Win32-vs16-x64\ext\php_gd2.dll (The specified module could not be found), C:\Program Files\php-8.3.10-Win32-vs16-x64\ext\php_php_gd2.dll.dll (The specified module could not be found)) in Unknown on line 0
[01-Aug-2024 22:02:17 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_xmlrpc.dll' (tried: C:\Program Files\php-8.3.10-Win32-vs16-x64\ext\php_xmlrpc.dll (The specified module could not be found), C:\Program Files\php-8.3.10-Win32-vs16-x64\ext\php_php_xmlrpc.dll.dll (The specified module could not be found)) in Unknown on line 0

Both of these modules are enabled in IIS.

**Comment by campbell-m** [comment]
No, those messages won't be causing this problem.  I'd expect to see something like "Uncaught exception ...".

**Comment by BrzIGH** [comment]
Should I use the mrbs database access credentials from the source machine ?

**Comment by campbell-m** [comment]
Upgrade step 56 is

~~~sql
CREATE TABLE %DB_TBL_PREFIX%sessions
(
  id      varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  access  int unsigned DEFAULT NULL,
  data    text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  
  PRIMARY KEY (id),
  KEY idxAccess (access)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
~~~

Does your database user have rights to CREATE TABLE?

**Comment by BrzIGH** [comment]
yes...
![image](https://github.com/user-attachments/assets/a78b52f1-9156-44a2-a0b1-ab18804153bb)

**Comment by BrzIGH** [comment]
Rolled back to using mrbs 1.11.4 and php 8.2.12 (instead of 8.3.10).

Site builds fine but after importing dump file the upgrade now shows the following:

To complete the upgrade the database now needs to be upgraded. Please backup your database before proceeding.

Upgrading to database version: 50
OK

Upgrading to database version: 51
OK

Upgrading to database version: 52
OK

Upgrading to database version: 53
OK

Upgrading to database version: 54
OK

Upgrading to database version: 55
OK

Upgrading to database version: 56Uncaught exception 'MRBS\DBException' in C:\inetpub\wwwroot\lib\MRBS\DB.php at line 208
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mrbs_sessions' already exists
SQL: CREATE TABLE mrbs_sessions( id varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL, access int unsigned DEFAULT NULL, data text CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL, PRIMARY KEY (id), KEY idxAccess (access)) ENGINE=InnoDB DEFAULT CHARSET=utf8
Params: Array
(
)

#0 C:\inetpub\wwwroot\upgrade.inc(197): MRBS\DB->query()
#1 C:\inetpub\wwwroot\upgrade.inc(237): MRBS\upgrade_database()
#2 C:\inetpub\wwwroot\upgrade.inc(101): MRBS\do_upgrade()
#3 C:\inetpub\wwwroot\defaultincludes.inc(35): require_once('...')
#4 C:\inetpub\wwwroot\index.php(8): require('...')
#5 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
    [csrf_token] => ad3dd8a1c63d68746023796b3105c01f6137f6d9d4874ee9f9c3e46684c196a4
    [form_username] => mrbs
    [form_password] => M123456789zl_*1
)
MRBS SESSION: Array
(
    [last_page] => /
    [this_page] => /index.php
    [csrf_token] => ad3dd8a1c63d68746023796b3105c01f6137f6d9d4874ee9f9c3e46684c196a4
    [user] => MRBS\User Object
        (
            [username] => yoda
            [display_name] => yoda
            [email] => yoda@yoda.net
            [level] => 2
            [data:protected] => Array
                (
                    [id] => 1
                    [password_hash] => $2y$10$xYcPGwPKNhWOVRYUNJXWae3iy1sVghwE5pzvwZxvTR80F92Ch/Gfq
                    [timestamp] => 2024-08-02 10:47:18
                    [last_login] => 1722620843
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

#0 MRBS\generate_backtrace() called at [C:\inetpub\wwwroot\functions_error.inc:219]
#1 MRBS\output_error() called at [C:\inetpub\wwwroot\functions_error.inc:262]
#2 MRBS\output_exception_error(object) called at [C:\inetpub\wwwroot\functions_error.inc:270]
#3 MRBS\exception_handler(object)
Fatal error: unfortunately the database is not available at the moment.

**Comment by jberanek** [comment]
If you really do have a table called mrbs_sessions before you get to DB Version 56 then it's suggests you have a custom table already. I'd check the contents of that table and if it looks like you don't need it, then drop the table and continue the upgrade.

**Comment by campbell-m** [comment]
Yes. I think the problem is that you are starting with a 1.11.5 (or 1.11.4) set of tables and then importing your 1.6.0 database. I would drop _all_ the 1.11.5 tables before you import the 1.6.0 database.

**Comment by BrzIGH** [comment]
Yes, I would always start the base version going then do an sql dump import.

I will now just create a new clean database and import the sql dump right away (without first creating tables in the target database).

Thanks
