### ISSUE TITLE
Remove Option For External/Internal Colour Code as well as while make a new entry

### ISSUE THREAD

**Issue by Abhijit-81** [meeting-room-booking-system/mrbs-code#3715]
**Describe the problem you're facing/question you have**
A clear and concise description of the problem you're facing, or the question you have.

**Browser details (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari]: Chrome/Mozilla
 - Version [e.g. 22] 22

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4] 1.11.5
 - Web server: [e.g. Apache 2.4.48] apache 2.4.52
 - OS: [e.g. CentOS 7.9] ubuntu
 - PHP version: [e.g. 7.4.23] 8.1
 - Database used: [e.g. MySQL 8.0.26] 10.4 mariadb

**Additional context**

Is there any possibility to remove Internal/External Option while booking, and also remove from home page

**Comment by campbell-m** [comment]
Put in your config file:

~~~php
unset($booking_types);
~~~

See systemdefaults.inc.php for more information.

**Comment by Abhijit-81** [comment]
Thank you very much it works, your guidance and support are unmatched in opensource platform
