### ISSUE TITLE
No Email Address and no Password in Edit User

### ISSUE THREAD

**Issue by stueja** [meeting-room-booking-system/mrbs-code#3716]
**Describe the bug**
The email address field and the password field in edit_users.php is empty.

**To Reproduce**
1. Log in as administrator
2. Click on User List
3. Click on a user name

**Expected behavior**
The email address and password (as dots) is visible. Otherwise I am not sure if I am overwriting the email address with an empty value.

**Screenshots**
Image 1: email addresses are there
Image 2: email address is not there

![1](https://github.com/user-attachments/assets/ffccde21-2569-4377-95db-ed709a7094a3)
![2](https://github.com/user-attachments/assets/f0721642-59d2-469d-a4ff-04580ed0692b)

**Browser details (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 17.5

**Server details (please complete the following information):**
 - MRBS version 1.11.4
 - Web server: nginx/1.22.1
 - OS: Ubuntu 5.15.0 (in docker container)
 - PHP version: 	8.1.20
 - Database used: mariadb.org binary distribution 11.4.2-MariaDB-ubu2404

**Additional context**

**Comment by campbell-m** [comment]
For the email address, I cannot reproduce this.  Are you getting any error messages in your PHP error log?

For the password, MRBS does not display the password because it doesn't know what it is.  It only stores the hashed value.

**Comment by campbell-m** [comment]
OK, I can reproduce it now using Safari on macOS.  I'll investigate tomorrow.

**Comment by campbell-m** [comment]
The problem is caused by the `multiple` attribute in the input element.  It looks like a Safari problem.  See also [this post on stackoverflow](https://stackoverflow.com/questions/78403943/safari-issues-with-input-type-email-and-multiple-attribute).

I'll try and come up with a workaround.

**Comment by campbell-m** [comment]
Updating from Sonoma 14.5 to 14.6.1 doesn't seem to fix the problem.

**Comment by campbell-m** [comment]
I have raised this as a bug report on Safari.  In the meantime I think the workaround is to use a different browser.

**Comment by campbell-m** [comment]
If you want to keep using Safari then another workaround is to create a custom JavaScript file (see systemdefaults.inc for how to do this) and add the code

~~~js
$(document).on('page_ready', function() {
  $('input[type="email"]').each(function() {
    $(this).attr('type', 'text').attr('type', 'email');
  });
});
~~~

Switching the type to 'text' causes the value to be displayed, after which it can be switched back to 'email'.

**Comment by stueja** [comment]
Thank you for figuring that out! Using a different browser is definitely OK for me.
