### ISSUE TITLE
Allow html / a href in rooms / message

### ISSUE THREAD

**Issue by stueja** [meeting-room-booking-system/mrbs-code#3718]
**Is your feature request related to a problem? Please describe.**
I tried to put a message up which contained an html tag (`<a href="link to manual">Manual</a>`). The html tag showed up as html code and not as an interpreted link.

**Describe the solution you'd like**
html code, at least `a href` should be interpreted.

**Describe alternatives you've considered**
I can paste the URL into the message field as-is. The users must then copy the URL and navigate themselves.

  **Additional context**
I am not sure which security implications arise from allowing html / a href tags. On the other hand, "only" administrators are allowed to fill the message box, narrowing down the list of people with evil intentions.

**Comment by campbell-m** [comment]
I'll have a think about the implications.  In the meantime you can easily modify the MRBS code by removing the `htmlspecialchars()` from this line (approx 400) in index.php:

~~~php
    return '<p class="message_top">' . htmlspecialchars($message->getText()) . "</p>\n";
~~~
 
ie, by changing it to 

~~~php
    return '<p class="message_top">' . $message->getText() . "</p>\n";
~~~

**Comment by campbell-m** [comment]
To make it slightly safer you could use

~~~php
    return '<p class="message_top">' . strip_tags($message->getText(), '<a>') . "</p>\n";
~~~

which will strip out all tags except `<a>`.  It's still not 100% safe though, but as you say it's only being used by admins.

Would it be helpful to have a config setting that specifies allowable tags for the message?  If it's empty then MRBS would do an `htmlspecialchars()` as at present.  Otherwise it would do a `strip_tags()`.

**Comment by stueja** [comment]
A configuration option would be helpful, I think. It would give administrators the possibility to define the tags they need. I assume the configuration option would sit in config.inc.php?

**Comment by campbell-m** [comment]
> I assume the configuration option would sit in config.inc.php?

Yes.

Now implemented in [8378f67](https://github.com/meeting-room-booking-system/mrbs-code/commit/8378f6740e5625a201725ff7d93763bdf52e8209).

**Comment by stueja** [comment]
I cannot appreciate enough how lightning fast you are developing this great tool! Thank you very much! I will test later.

**Comment by stueja** [comment]
This works like a charm. Thank you very much. 

However there is a slight difference to the behaviour before.
Without the change, in the original version, `<a href="xzy">TEST</a>` was rendered just like that `<a href="xzy">TEST</a>` in the calendar view.
With the current change, it is rendered 
 - as `TEST`, if `'a'` is not in the array of `$message_allowed_tags` (but maybe `'span'` is),
 - as `<a href="xzy">TEST</a>`, if the array of `$message_allowed_tags` is empty

I personally like the current change better.

**Comment by stueja** [comment]
Ah, forgot to close.
