### ISSUE TITLE
Highlight day and/or cell in month view

### ISSUE THREAD

**Issue by stueja** [meeting-room-booking-system/mrbs-code#3720]
**Is your feature request related to a problem? Please describe.**
When hovering over the month's calendar, the name of the room is highlighted. The day of the month (or the corresponding crossing cell room x day) is not highlighted.

**Describe the solution you'd like**
Especially in the month view it might be helpful to also highlight the day of the month and/or the room x day crossing cell

**Describe alternatives you've considered**
none so far

**Additional context**
This mainly concerns month views with a longer list of rooms, like mine. 
MacOS cannot create screenshots of areas with a mouse cursor. The mouse cursor sits on August 13, highlighted room.
![4](https://github.com/user-attachments/assets/0793afd4-4e4c-4b0e-8d2d-9453b30a5d1c)

**Comment by campbell-m** [comment]
I've now implemented this in [d910738](https://github.com/meeting-room-booking-system/mrbs-code/commit/d91073829ed200020189a68b35a6981280af6c86).  A couple of notes:

1. I've also implemented it in the all rooms week view.  I don't know if that's unnecessary?
2. The highlighting will be lost when the page refreshes (if you have automatic refresh enabled) and will only come back when the mouse is moved.  I don't know if that's a problem?

**Comment by stueja** [comment]
Campbell,

that's just awesome. From my point of view,
  1. it does not hurt to have it in the week view, too, For me, it's very helpful.
  2. I believe I turned refresh off or set it to a time which is longer than the user would take to find a room and a day. I think that your change helps to minimize the time a user needs to stay in the month/week view, therefore I doubt it's a problem. If the user should still be in the month/week view after a refresh, I would think they are moving the mouse soon after to "find" a suitable room/day.
  3. in my productive environment, I currently use one single period, which allows to jump from the month view to the entry page. In the release environment, I try to come up with solution for time-based booking. In the day calendar, hours 0 - 24, there is currently no coloring. I'd find it consequent if highlighting was there, too, because it's basically the same "problem" as users have with 31 days.

**Comment by campbell-m** [comment]
> I believe I turned refresh off or set it to a time which is longer than the user would take to find a room and a day.

Quick question on this.  Just wondering why you did this?  The refresh should be transparent to users and will help them avoid selecting a room and a day that has just been booked by somebody else.  The only downside is the load on the server if you have a lot of users.  (I think I will implement preservation of the highlighting over a refresh anyway.)

**Comment by stueja** [comment]
The users usually book a specific room well in advance; but I have had a look at the configuration now, it says
```php
$refresh_rate = 10;
$ajax_refresh_rate = 10;
```

so I probably had an earlier test in mind.
