### ISSUE TITLE
Only one room shown in month view in second area

### ISSUE THREAD

**Issue by stueja** [meeting-room-booking-system/mrbs-code#3726]
**Describe the bug**
The first, original area is showing all rooms in the month view, "all rooms".
When I select the new second area, only one of three rooms is displayed in "all rooms". 

**To Reproduce**
1. Go to `index.php`
2. Click on the second area in the area select dropdown
3. See error

**Expected behavior**
All rooms should appear.

**Screenshots**
Settings:
![3](https://github.com/user-attachments/assets/fe2ca8d8-ae1b-4d93-b64a-aae78e3a9d9d)
`index.php` after reload:
![1](https://github.com/user-attachments/assets/2e0e8e2b-a016-4eb5-81e4-4f2670d183b4)
selected "Second", rooms `Bravo` and `Charlie` are missing
![2](https://github.com/user-attachments/assets/34f8d1f5-0f36-4d52-b408-713a7ff22c35)

**Browser details (please complete the following information):**
 - OS: Arch Linux 6.10.0
 - Browser Firefox
 - Version 129.0.1

**Server details (please complete the following information):**
 - MRBS version 1.11.5
 - Web server: nginx/1.22.1
 - OS: Linux 0a4bb6666050 5.15.0-113-generic 123-Ubuntu
 - PHP version: 8.1.20
 - Database used: mariadb 11.4.3

**Additional context**

**Comment by campbell-m** [comment]
Are you sure they are not there?  When I try and reproduce this I get a very wide first row, but the other rooms are there - you just have to scroll down to see them.   Of course, the first row should not be very wide and that's a bug.

This only seems to happen with Firefox.

**Comment by stueja** [comment]
Oh! I didn't notice the scoll bar. You are absolutely right, they are there, but must be scrolled to. I just tested with Chrome, and there they appear right away.

**Comment by campbell-m** [comment]
OK, I'll try and take a look during the week.

**Comment by campbell-m** [comment]
I've now fixed this in [3c6a3e6](https://github.com/meeting-room-booking-system/mrbs-code/commit/3c6a3e68b0da99dc2a9a4cdd646ea6bd6b3defc3).  There may be some consequences I haven't spotted yet, so if you notice any strange behaviour let me know.

**Comment by stueja** [comment]
This looks very good in Firefox now. I will report consequences if I find any. Many thanks!
