### ISSUE TITLE
Register a number of guests for event

### ISSUE THREAD

**Issue by stueja** [meeting-room-booking-system/mrbs-code#3727]
**Describe the problem you're facing/question you have**
I am looking for a solution that more than the logged-in user can be registered for an entry. Example: an entry is open not only for a user with a login, but also for their friends, their family, their children. If the logged-in user registers for an event, they cannot do this a second, third, ... time to cater for friends and family. On the other hand, the administrator can not or does not want to create accounts for, say, 5 family members of which 2 are toddlers without capabilities to register.

My idea was that 
1. the user logs in
2. the user opens the event (`view_entry.php`)
3. the user fills an input field (e. g. `Additional Guests:`) with a number greater or equal 1
4. the user clicks "register" to register this amount of *additional* people + 1 for the user themselves.

I know that I can add additional fields to the `entry` and `repeat` tables to add additional fields to the event. An `additional_guests` field, however, can only be changed during creation of an event, not while registering for an existing event.

Is there a possibility like that which I am not able to see or another procedure which might be suitable?

Thanks alot.

**Browser details (please complete the following information):**
 - OS: Arch Linux 6.10.0
 - Browser Firefox
 - Version 129.0.1

**Server details (please complete the following information):**
 - MRBS version 1.11.5
 - Web server: nginx/1.22.1
 - OS: Linux 0a4bb6666050 5.15.0-113-generic 123-Ubuntu
 - PHP version: 8.1.20
 - Database used: mariadb 11.4.3

**Additional context**

**Comment by campbell-m** [comment]
There's a configuration setting something like 'users_can_register_others' which allows users to register other people. These can either be existing users from the drop-down or you can type some text at the top. Remember to press Enter after typing the text.

**Comment by stueja** [comment]
And I stopped reading the file at `auth`, thinking it's authentication settings only. Again, very helpful. Many thanks!

**Comment by campbell-m** [comment]
Yes, it's `$auth['users_can_register_others']`.
