### ISSUE TITLE
Can you hide the ALL DAY button?

### ISSUE THREAD

**Issue by jshrek** [meeting-room-booking-system/mrbs-code#3737]
I have set my rooms with maximum duration of 3 hours for meeting times, so the ALL DAY button is not needed.

Is there a way to hide it?

Thanks

**Comment by campbell-m** [comment]
It will be hidden for ordinary users.  It will be shown for admins because the maximum duration doesn't apply to them.

**Comment by jshrek** [comment]
Got it! Thanks
