### ISSUE TITLE
Unable to create new room booking

### ISSUE THREAD

**Issue by darwinleung34** [meeting-room-booking-system/mrbs-code#3743]
**Describe the problem you're facing/question you have**
I just freshly installed the mrbs at a remote web hosting platform, but I cannot create booking, when I click into a time slot, error popped, I turned on the debug mode with the following log printed, hope to get some help, thank you!

Uncaught exception 'TypeError' in /home/fitbwhzh/public_html/mrbs/functions.inc at line 928
abs(): Argument #1 ($num) must be of type int|float, string given
#0 /home/fitbwhzh/public_html/mrbs/functions.inc(928): abs()
#1 /home/fitbwhzh/public_html/mrbs/edit_entry.php(1633): MRBS\toTimeString()
#2 {main}

MRBS GET: Array
(
    [view] => day
    [year] => 2024
    [month] => 9
    [day] => 14
    [area] => 1
    [room] => 1
    [hour] => 11
    [minute] => 30
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [last_page] => /mrbs/index.php
    [this_page] => /mrbs/edit_entry.php?view=day&year=2024&month=9&day=14&area=1&room=1&hour=11&minute=30
    [csrf_token] => a86b5b3b5f1fb3d1b00833afd3e2770f83854b6157ac6a5dd1543f1c5ca5f63d
    [user] => MRBS\User Object
        (
            [username] => admin
            [display_name] => Administrator
            [email] => 
            [level] => 2
            [data:protected] => Array
                (
                    [id] => 1
                    [password_hash] => 
                    [timestamp] => 2024-09-14 03:21:08
                    [last_login] => 1726300066
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

#0 MRBS\generate_backtrace() called at [/home/fitbwhzh/public_html/mrbs/functions_error.inc:226]
#1 MRBS\output_error() called at [/home/fitbwhzh/public_html/mrbs/functions_error.inc:280]
#2 MRBS\output_exception_error(object) called at [/home/fitbwhzh/public_html/mrbs/functions_error.inc:288]
#3 MRBS\exception_handler(object)
Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator.

**Browser details (please complete the following information):**

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4]
 - Web server: [e.g. Apache 2.4.48]
 - OS: [e.g. CentOS 7.9]
 - PHP version: [e.g. 7.4.23]
 - Database used: [e.g. MySQL 8.0.26]

**Additional context**

**Comment by campbell-m** [comment]
Can you try upgrading to the latest development code from the [main branch](https://github.com/meeting-room-booking-system/mrbs-code). Follow the green Code button on that page and treat it like a new release.

**Comment by darwinleung34** [comment]
Thanks! It resolved the problem~
