### ISSUE TITLE
Cannot Approve Bookings

### ISSUE THREAD

**Issue by fuzezeze** [meeting-room-booking-system/mrbs-code#3744]
Hi, we faced an issue that the system would keep loading when an admin press the "approve" the bookings. Would you have a look and suggest us to troubleshoot? Many thanks for your help!
![Screenshot 2024-09-16 145657](https://github.com/user-attachments/assets/224b1571-29af-4b19-9146-6558c86d8da7)

**Browser details (please complete the following information):**

Edge newest version

**Server details (please complete the following information):**

MRBS 1.6.1
Web server: Apache
OS: Ubuntu 16
Database used: MySql

**Comment by campbell-m** [comment]
I assume this has now been resolved.
