### ISSUE TITLE
Unable to Sync data between two web pages 

### ISSUE THREAD

**Issue by Aglau11** [meeting-room-booking-system/mrbs-code#3745]
Hey everyone, I'm sorry but I'm struggling and need advice.

I have two Webpages at the moment.

Classroom Booking: webapp/roomcal/day.php?day...

Room Booking Schedule: webapp/roomcal/roombooking/dailyviewhtml

I am to create a new room into the system and after dabbing I'm able to create the new room to appear on the table under Room Booking. However, I'm unable to create the new room in the classroom site unless I go in through the admin portal. But I leant that this method is no use to sync botb site. As now I both pages to show the new added Room and to show the details correctly when someone makes the booking in the classroom booking system.

Any idea or advice I can look into to do this? Thx. 

![20240917_115302.jpg](https://github.com/user-attachments/assets/32425ae1-985c-42f4-9d85-93e42f10391a)

![20240917_115320.jpg](https://github.com/user-attachments/assets/9eb3a675-2753-4dd5-acb4-99572e551945)

Sbould note, that my previous colleague said he did not use web admin but added the room via command line...

**Comment by campbell-m** [comment]
Could you explain some more about what you are trying to do please?  I don't understand what you want to do and what you have done.
