### ISSUE TITLE
Catalan translation improvement

### ISSUE THREAD

**Issue by fburrull** [meeting-room-booking-system/mrbs-code#3747]
[lang.ca.txt](https://github.com/user-attachments/files/17046724/lang.ca.txt)

Using google translation I have re-done the catalan lang.ca file (uploaded as catalan.ca.txt)

Here it is the test page of our future reservation system:
https://aulasetsit.upct.es/etsitgestion/checklang.php?lang[]=ca

Francesc

**Comment by campbell-m** [comment]
Thanks.  Now committed in [da327a9](https://github.com/meeting-room-booking-system/mrbs-code/commit/da327a913f2b4396b3139d1b1ff39c8b16cbeb24).
