### ISSUE TITLE
Catalan translation update + catalan faq

### ISSUE THREAD

**Issue by fburrull** [meeting-room-booking-system/mrbs-code#3748]
[lang.ca.txt](https://github.com/user-attachments/files/17069981/lang.ca.txt)
[site_faq_ca.html.txt](https://github.com/user-attachments/files/17069982/site_faq_ca.html.txt)

**Comment by campbell-m** [comment]
Thanks.  Now committed in [f497b2f](https://github.com/meeting-room-booking-system/mrbs-code/commit/f497b2fb9ed0b6bfdd68d6ea0ececea327d545b8) and [c9bbd45](https://github.com/meeting-room-booking-system/mrbs-code/commit/c9bbd4590385c12eac530e51dd1fd65b4744313a).
