### ISSUE TITLE
Uncaught exception in 'TypeError' in mrbs_sql.inc at line 1742

### ISSUE THREAD

**Issue by Draky50110** [meeting-room-booking-system/mrbs-code#3749]
**Describe the bug**
Hello.
Have this bug : 
Uncaught exception 'TypeError' in /home/XXX/mrbs/mrbs_sql.inc at line 1742
MRBS\get_booking_info(): Argument #1 ($id) must be of type int, null given, called in /home/XXX/mrbs/view_entry.php on line 607
#0 /home/XXX/mrbs/view_entry.php(607): MRBS\get_booking_info(NULL, false)
#1 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [last_page] => /pro/mrbs/del_entry.php
    [this_page] => /pro/mrbs/view_entry.php
    [csrf_token] => 22ccd8edf0151fc182157848535c41af8eabca997ceefb8320edd11675a8ab17
    [user] => MRBS\User Object
        (
            [username] => name.surname
            [display_name] => Name SURNAME
            [email] => name.surname@email.com
            [level] => 2
            [data:protected] => Array
                (
                    [id] => 1
                    [password_hash] => HASH OF PASSWORD
                    [timestamp] => 2024-09-20 12:51:14
                    [last_login] => 1726831181
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

**To Reproduce**
- I created a meeting with registration
- I created an user
- I used this new user to register the meeting
- I logged in as admin/meeting creator and tried to delete the meeting
- Got hits error above.

**Expected behavior**
Meeting to be deleted

**Screenshots**
XXX

**Browser details (please complete the following information):**
 - OS: [e.g. iOS] Win 7
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] ESR 115

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.9.4] 1.11.5
 - Web server: [e.g. Apache 2.4.48] Apache 2.54
 - OS: [e.g. CentOS 7.9] Linux
 - PHP version: [e.g. 7.4.23] PHP 8.2
 - Database used: [e.g. MySQL 8.0.26] MariaDB 10.11

**Additional context**
Meeting have been deleted tought.

**Comment by campbell-m** [comment]
I think this has been fixed in the latest development code.  Can you try downloading the latest code by following the green Code button on [this page](https://github.com/meeting-room-booking-system/mrbs-code)?  Treat it like a new release.
