### ISSUE TITLE
room page after new entry

### ISSUE THREAD

**Issue by dougbevan** [meeting-room-booking-system/mrbs-code#3751]
**Describe the problem you're facing/question you have**

After a new booking is created, it current returns users to the areas overview page.  Instead, we would like to return to the month view for that particular room as a way of confirmation visually for users.  Is it possible to adjust?

.

**Comment by campbell-m** [comment]
Can you explain the problem and how to reproduce it in more detail please?

**Comment by dougbevan** [comment]
Of course...

Let's say we have an area called "conference rooms" and within it rooms A B and C.  If I schedule an event in Room A, after event creation I am returned to a month overview for the area "conference rooms" listing rooms A, B, and C.

Instead, users would like to be returned to a month (or week) view of room "A" so they can visually confirm that the event has been created.

**Comment by campbell-m** [comment]
Which version of MRBS are you running?  Which view are you starting off from when you make the booking?  And if that's a week or month view are you viewing all the rooms, or just a single room?

**Comment by dougbevan** [comment]
Sure...

It is the same behavior if I start from the week, month or day view of either the "area" overview or the individual room within the area..  It always returns to the "area" overview.

It's an older version, MRBS 1.9.4.

**Comment by campbell-m** [comment]
This doesn't happen in the latest release (1.11.5).  I think you need to upgrade.

**Comment by dougbevan** [comment]
Can you confirm that in the latest release it returns to the page of the booked room?  

Could it be any directives in my config file?  Otherwise I will plan an upgrade.

**Comment by campbell-m** [comment]
No, it's nothing to do with your config file.   Yes, if you're in the week view looking at Room A and you book a room then 1.11.5 returns to the week view looking at Room A.  However I recommend you install a test version of 1.11.5 first, before upgrading, to make sure it does exactly what you want.
