### ISSUE TITLE
Minicalendar in catalan does not change days on click -SOLVED-

### ISSUE THREAD

**Issue by fburrull** [meeting-room-booking-system/mrbs-code#3752]
The minicalendar is supposed (in English and Spanish it works well, not in Catalan) to change the displayed day.

When you want to display, i.e. October 12th, [Today is October 3rd, currently displayed] you click in the minicalendar the October 12th little circle and MRBS should display October 12th.

It does it in Spanish and English, NOT in Catalan (does not change the day displayed)

I deduced it could be a javascript issue. 

I went to the folder /js/flatpickr/l10
$> cd /js/flatpickr/l10

The file ca.js was not there, instead cat.js. I did a
$> ln -s cat.js ca.js

$> ls

ar-dz.js  ca.js   eo.js  gr.js  it.js  mk.js  pa.js  sq.js      uz_latn.js
ar.js     cat.js  es.js  he.js  ja.js  mn.js  pl.js  sr-cyr.js  vn.js
at.js     ckb.js  et.js  hi.js  ka.js  ms.js  pt.js  sr.js      zh.js
az.js     cs.js   fa.js  hr.js  km.js  my.js  ro.js  sv.js      zh-tw.js
be.js     cy.js   fi.js  hu.js  ko.js  nb.js  ru.js  th.js
bg.js     da.js   fo.js  hy.js  kz.js  nl.js  si.js  tr.js
bn.js     de.js   fr.js  id.js  lt.js  nn.js  sk.js  uk.js
bs.js     en.js   ga.js  is.js  lv.js  no.js  sl.js  uz.js

Now the minicalendar works fine

SOLUTION: In the folder /js/flatpickr/l10 rename the file cat.js to ca.js

**Comment by campbell-m** [comment]
It was indeed a JavaScript problem, but changing the file name is not the solution.  The problem was an unescaped text string causing a JavaScript syntax error.  I have now committed a fix in [3800e65](https://github.com/meeting-room-booking-system/mrbs-code/commit/3800e651fdc32ae79b5f170fcda390b07ed1cd2e).

**Comment by campbell-m** [comment]
Did you get this working with the new code?

**Comment by campbell-m** [comment]
I haven't heard back, but assume this is now working.
