### ISSUE TITLE
Error messages thrown - like '/var/www/html/mrbs/week.php' not found or unable to stat

### ISSUE THREAD

**Issue by jayalalsarma** [meeting-room-booking-system/mrbs-code#3755]
**Describe the bug**
After an upgrade to the latest version (1.11.5) I get the following error messages.
[Wed Oct 09 19:58:04.032246 2024] [php:error] [pid 40540:tid 40540] [client 40.77.167.7:9105] script '/var/www/html/mrbs/week.php' not found or unable to stat
similar messages for day.php and month.php

**To Reproduce**
the error messages appear in apache2 log

**Expected behavior**
I noticed that the week.php and day.php are missing in the new version code base.

**Screenshots**

**Server details (please complete the following information):**
 - MRBS version 1.11.5
 - Web server: Apache2
 - OS: Debian 12.2
 - PHP version: 8.2
 - Database used: MariadDB ver 15.1

**Additional context**

**Comment by campbell-m** [comment]
This isn't a bug.  In MRBS 1.11.5 the pages day.php, week.php and month.php have been removed and you should use index.php instead.
