### ISSUE TITLE
Synology DSM6.2.4 install issue

### ISSUE THREAD

**Issue by Faqbe9** [meeting-room-booking-system/mrbs-code#3757]
Trying to install/use MRBS 1.11.5 on a Synology DSM 6.2.4 with Apache 2.4 - PHP7.4 and web station.
Configured config.inc.php with necessary variables. Tried with specific port the one specified on DB installation) and without.

When initiating http://myServer/mrbs/index.php, following error messages are displayed:

~~~text
Uncaught exception 'MRBS\Exception' in /volume1/web/mrbs/lib/MRBS/DBFactory.php at line 39
Undefined class constant 'PDO::MYSQL_ATTR_FOUND_ROWS'
#0 /volume1/web/mrbs/dbsys.inc(90): MRBS\DBFactory::create('mysql', '127.0.0.1', 'me', 'myPwd*', 'mrbs', false, NULL, Array)
#1 /volume1/web/mrbs/dbsys.inc(102): MRBS\db()
#2 /volume1/web/mrbs/lib/MRBS/Session/Session.php(82): MRBS\db_schema_version()
#3 /volume1/web/mrbs/lib/MRBS/Session/Session.php(28): MRBS\Session\Session->init(2592000)
#4 /volume1/web/mrbs/lib/MRBS/Session/SessionWithLogin.php(31): MRBS\Session\Session->__construct()
#5 /volume1/web/mrbs/lib/MRBS/Session/SessionPhp.php(19): MRBS\Session\SessionWithLogin->__construct()
#6 /volume1/web/mrbs/lib/MRBS/Session/SessionFactory.php(14): MRBS\Session\SessionPhp->__construct()
#7 /volume1/web/mrbs/mrbs_auth.inc(33): MRBS\Session\SessionFactory::create('php')
#8 /volume1/web/mrbs/init.inc(41): MRBS\session()
#9 /volume1/web/mrbs/defaultincludes.inc(35): require_once('/volume1/web/mr...')
#10 /volume1/web/mrbs/index.php(11): require('/volume1/web/mr...')
#11 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
)
~~~

Database seems right and can be read using PhpMyAdmin.
OrangeHrm and VToger are working correctly (using Web Station).
Any assistance would be welcome

**Comment by campbell-m** [comment]
Have you got the PDO MySQL driver enabled?

**Comment by Faqbe9** [comment]
Thks 4 asking, if PDO stands for MariaDb10, the answer is yes. However, I'm a bit lost to know whether when installing MariaDb10,  MySql connector comes with the package and is properly installed. Packages like OrangeHrm or Vtiger are correctly running on my NAS (DS920+) but maybe these are not using the same "connector"
Is there any specific activation to perform after MariaDb10 installation ?

**Comment by campbell-m** [comment]
No, I mean the PHP PDO_MySQL driver.  Check your php.ini file and make sure the line

~~~ini
extension=pdo_mysql
~~~

is uncommented.

**Comment by Faqbe9** [comment]
Thks 4 your comments, however there are "lots" of php.ini files on a DSM... I've finally found in "Web station" Syno app, the section "extensions" and I ticked "pdo_mysql" and "mysqli". I also ticked the boxes related to error display.  A new test now shows:
"Parse error: syntax error, unexpected '=' in /volume1/web/mrbs/config.inc.php on line 68"
Line 68 is the password line. Pwd and login have been checked (I can connect to mrbs with phpMyAdmin using the said credentials.

Summary content of config.inc.php uncommented lines is now:

<?php // -*-mode: PHP; coding:utf-8;-*-
namespace MRBS;
use IntlDateFormatter;
require_once 'lib/autoload.inc';
$dbsys = "mysqli";
(also tested unsuccesfully with pdo_mysql)

$db_host = "127.0.0.1";
$db_port = 3307;
$db_database = "mrbs";
$db_login = "me";
db_password = "MyPwd";
$db_tbl_prefix = "mrbs_";
$db_persist = false;

Any idea ?

**Comment by Faqbe9** [comment]
"<?php // -*-mode: PHP; coding:utf-8;-*-
namespace MRBS;
use IntlDateFormatter;
require_once 'lib/autoload.inc';
$dbsys = "mysqli";
(also tested unsuccesfully with pdo_mysql)

$db_host = "127.0.0.1";
$db_port = 3307;
$db_database = "mrbs";
$db_login = "me";
db_password = "MyPwd";
$db_tbl_prefix = "mrbs_";
$db_persist = false;

**Comment by Faqbe9** [comment]
Any idea ?

**Comment by campbell-m** [comment]
You are missing a `$` in front of `db_password`.

**Comment by Faqbe9** [comment]
OMG.... grrrr THANKS a lot.
Too much focused on a text makes youmissing elementary points !
This is now solved thanks to you. As a summary of solutions applied: in DSM 6.2, web Station, in tab "PHP parameters, tick boxes related to the "right" PDO used (mysqli or pdo_mysql). Adapt config.inc.php accordingly.
Check DB credentials with phpMyAdmin - et voilà...

**Comment by Faqbe9** [comment]
Have a nice day and thak you again.

**Comment by campbell-m** [comment]
Just close the issue.

By the way, 'mysqli' in the config is just treated as 'mysql'.  It's just there for backwards compatibility.
