### ISSUE TITLE
Making a custom field compulsory

### ISSUE THREAD

**Issue by vipula65** [meeting-room-booking-system/mrbs-code#3758]
I have added a custom field (Host_department) in the booking form. I need to make it compulsory. Need a validation of that field.  How to achieve that. Appreciate If you can explain an easy way to add new field and make it compulsory.

**Comment by campbell-m** [comment]
Set in your config.inc.php file

~~~php
$is_mandatory_field['entry.Host_department'] = true;
~~~

See systemdefaults.inc.php for more details.

**Comment by vipula65** [comment]
I did it but still it can book without host_department

**Comment by jberanek** [comment]
Column names are case-sensitive, so is your column called Host_department or host_department ?

**Comment by vipula65** [comment]
column name correct. it is Host_department in table. If i enter host department manually it is aving to table and showing in the display I did it like below
$is_mandatory_field['entry.Host_department'] = true;
$max_booking_date_enabled = true;
$max_booking_date = "2024-12-31";  // Must be a string in the format "yyyy-mm-dd"

**Comment by campbell-m** [comment]
> pls tell me the process of adding a custom field also

See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL file.

**Comment by vipula65** [comment]
> > pls tell me the process of adding a custom field also
> 
> See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL file.

I know how to add a column to table. I want to know how to get it to the entry form and make it mandatory field. thanks

**Comment by campbell-m** [comment]
Note also that if your custom field is going to be a drop-down using `$select_options` then

~~~php
// If you want to make the select field a mandatory field (see below) then include
// an empty string as one of the values, eg
//
//$select_options['entry.catering'] = array(''  => 'Please select one option',
//                                          'c' => 'Coffee',
//                                          's' => 'Sandwiches',
//                                          'h' => 'Hot Lunch');
~~~

**Comment by campbell-m** [comment]
> I know how to add a column to table. I want to know how to get it to the entry form and make it mandatory field. thanks

As I say, please read that section in the INSTALL document.

**Comment by vipula65** [comment]
> > I know how to add a column to table. I want to know how to get it to the entry form and make it mandatory field. thanks
> 
> As I say, please read that section in the INSTALL document.

I solved the problem it was Host_Department not Host-department. thanks
