### ISSUE TITLE
Having hard time trying to send an email with MailQueue:add()

### ISSUE THREAD

**Issue by KawaMood** [meeting-room-booking-system/mrbs-code#3759]
Hi, I'm back with https://github.com/meeting-room-booking-system/mrbs-code/issues/3756, unfortunately having a new issue.

To set the context back, I'm trying to inform new users by email that an account has been created for them. 
I'm using the MRBS roles branch.

I'm trying to implement the right way using `MailQueue::add()` as recommended, in order to use the PHPMailer lib MRBS already embeds. Until here I did my tests with `sendmail` and the native PHP `\mail()` method on local, so it worked as I could define anything I want.

I tried to rewrite my code with the `MailQueue:add()` method of MRBS, but no mail was sent anymore, and there were no error in the logs.

So I tried to directly implement the example you can find on [PHPMailer's documentation ](https://github.com/PHPMailer/PHPMailer?tab=readme-ov-file#a-simple-example), manually setting the SMTP config in this part to see if it would work. But doing it, it throws an error on the page when you press "save" saying headers are already declared in the source file:
```
Cannot modify header information - headers already sent by (output started at C:\wamp64\www\mrbs\lib\PHPMailer\src\SMTP.php:300)
```
Even if the mail was sent somehow. But I can't keep the errors showing like this. I also need to send the email in utf-8 and it doesn't seem to use this charset by default.

Here is the SMTP config I put in `config.inc.php`:
```php
// Mail config
$mail_settings['from'] = 'xxxx';  // (Hidden for the support request)
// SMTP Config
$smtp_settings['host'] = 'mail.gandi.net';  
$smtp_settings['port'] = 465;
$smtp_settings['auth'] = true;
$smtp_settings['secure'] = 'ssl';
$smtp_settings['username'] = 'xxxx';  // (Hidden for the support request)
$smtp_settings['password'] = 'xxxx';  // (Hidden for the support request)
$smtp_settings['hostname'] = '';
$smtp_settings['helo'] = '';
$smtp_settings['disable_opportunistic_tls'] = false;
$smtp_settings['ssl_verify_peer'] = true;
$smtp_settings['ssl_verify_peer_name'] = true;
$smtp_settings['ssl_allow_self_signed'] = false;
```

Here is the part I edited from `user_edit_handler.php` from line 232:
```php
// UPDATE
elseif (isset($update_button)) {
    // If it's a new user, or if for some reason the getById() failed, then
    // create a new one.

    // @CUSTOM-CODE: START
    $is_new_user = false;
    // @CUSTOM-CODE: END

    if (!isset($user)) {
        $user = new User();
        // @CUSTOM-CODE: START
        $is_new_user = true;
         // @CUSTOM-CODE: END
    }

    // Get the form data
    get_form_data($user);

    // Validate the data
    $errors = validate_form_data($user);

    if (empty($errors)) {
        $user->save();
        // @CUSTOM-CODE: START
        // Send mail to the new user on registration
        if ($is_new_user === true) {
            // Prepare body and subject
            $subject = 'Meetings Rooms System from XXXX - Your Account';
            $template = file_get_contents(__DIR__ . '/xxxx/mail/registration_template.html');
            $template = str_replace('{{display_name}}', $user->display_name, $template);
            $template = str_replace('{{name}}', $user->name, $template);
            $template = str_replace('{{password}}', $user->password0, $template);
            // Send mail
            MailQueue::add([$user->email], $subject, '', $template, null, 'utf8');
        }
        // @CUSTOM-CODE: END
    } else {
    // ...
```
Is there something I can do to make it works?

Note apart, maybe a reason: My host wait for us to send the mail as "from" in headers, but there is no parameter where I can define this in the `MailQueue::add()` method.

I'm sorry, I'm not really comfortable with back-end on apps, so I hope I didn't make obvious mistakes.
I sincerely appreciate your help. Thank you for your time.

**Comment by campbell-m** [comment]
I suggest that before you try and send a mail about new users, you make sure that the existing mail system is working by checking that an email is sent when you create a new booking.  I will answer your other queries later.

**Comment by campbell-m** [comment]
Here are some more comments:

1. The `$addresses` parameter should be an array indexed by 'from', 'reply_to', 'to' and 'cc' with each element consisting of a comma separated list of email addresses.  I will update the comments.
2. The `$charset` should be 'utf-8', or better still use `get_mail_charset()`.

**Comment by KawaMood** [comment]
Oh you're right, I should have study the MailQueue class a bit further.
I also forgot to set `$mail_settings['admin_backend']` to `'smtp'`;
It works now, thank you very much!
