### ISSUE TITLE
Disable Type Repeat Section

### ISSUE THREAD

**Issue by dyerry79** [meeting-room-booking-system/mrbs-code#3760]
**Describe the problem you're facing/question you have**
Hello, we've initially implemented the MRBS in our organization. Our partners wanted to disable the Repeat Type option since it was pointed out that it is no longer needed. I can't find any options in the config file (or maybe I am just blind) and from the other options available. If I edit, what files should that be? Could you point me in the right direction? I have seen this implementation, but I forgot the link. I think it's related to library reading scheduling (not sure).

I am using version 1.11.5.

**Comment by campbell-m** [comment]
Setting in your config file

~~~php
$auth['only_admin_can_book_repeat'] = true;
~~~

will disable the repeat section for ordinary users, though admins will still see it.

**Comment by dyerry79** [comment]
i failed to see that. this will do for now. thanks campbell :)
