### ISSUE TITLE
Added custom fields not displayed properly

### ISSUE THREAD

**Issue by dyerry79** [meeting-room-booking-system/mrbs-code#3761]
**Describe the problem you're facing/question you have**
1. Hi! I have successfully added custom fields to the mbrs_entry and mbrs_repeat tables. I have named the columns/fields requirements and contact_name respectively. Here's the screenshot for you to look over.

![image](https://github.com/user-attachments/assets/0fcc4d10-08e3-466c-b465-30dd480ad912)

2. After adding the columns, I have declared the following to the config file

$vocab_override['entry.requirements'] = "Requirements";
$vocab_override['entry.contact_name'] = "Contact Name";

3. However, upon viewing the site, the added columns were not displayed as expected with the following points observed:
   3.1. The names of the columns as declared in the mbrs_entry and mbrs_repeat tables were taken as labels of the fields. 
   3.2. The data type of contact _name is varchar but it is displayed as a textarea.

Here's the screenshot:

![image](https://github.com/user-attachments/assets/0ef665f9-7de6-455d-9f6a-26b4f5829311)

4. I tried playing with changing the entry to mbrs_entry in config as shown below but I am still getting the same ouput.

$vocab_override['mbrs_entry.requirements'] = "Requirements";
$vocab_override['mbrs_entry.contact_name'] = "Contact Name";

By the way, i have installed the MRBS 1.11.5 in my windows machine with laragon as my web server bundled with apache v 2.4.54 and mysql 8.0.30. 

TIA.

**Comment by dyerry79** [comment]
hmm. I lowered the length of contact_name column and the column is now displayed as text. 

In my previous post, 3.1 seems to be the problem and additional question, how can I rearrange the columns? Say, I want that the contact_name field be the first to display in the form followed by the rest of components.

**Comment by campbell-m** [comment]
You are missing the language key.  It should be, for example:

~~~php
$vocab_override['en']['mbrs_entry.requirements'] = "Requirements";
$vocab_override['en']['mbrs_entry.contact_name'] = "Contact Name";
~~~

The language key allows you to offer different translations for different languages if you are running a multilingual site.

**Comment by dyerry79** [comment]
> You are missing the language key. It should be, for example:
> 
> ```
> $vocab_override['en']['mbrs_entry.requirements'] = "Requirements";
> $vocab_override['en']['mbrs_entry.contact_name'] = "Contact Name";
> ```
> 
> The language key allows you to offer different translations for different languages if you are running a multilingual site.

Thanks for the prompt reply. It's working now. I only have 1 issue now which is how to rearrange the fields in the form.

**Comment by campbell-m** [comment]
> hmm. I lowered the length of contact_name column and the column is now displayed as text.

You can control the point at which it is displayed as a textarea with the following config setting:

~~~php
// The maximum length of a database field for which a text input can be used on a form
// (eg when editing a user or room).  If longer than this a text area will be used.
$text_input_max = 70;  // characters
~~~

**Comment by campbell-m** [comment]
>  However, I want to rearrange the fields in the form. Say I want to have the Requirements as the top field in the form. Any ideas how to do that?

Look for `$edit_entry_field_order` in systemdefaults.inc.php (though make any changes in config.inc.php rather than systemdefaults.inc.php).

**Comment by dyerry79** [comment]
Thanks campbell
