### ISSUE TITLE
Notify anonymous booker.

### ISSUE THREAD

**Issue by dyerry79** [meeting-room-booking-system/mrbs-code#3762]
Hi Campbell,

Is there a way that an anonymous booker can be notified upon booking, approval, rejection, etc? I tried adding an email column in the entry table but the anonymous booker is not being notified.

**Comment by campbell-m** [comment]
You'll need to modify the MRBS code.  See Issue #3670.

**Comment by dyerry79** [comment]
Nice. Thanks for the prompt response
