### ISSUE TITLE
Hide field in the edit_entry file

### ISSUE THREAD

**Issue by dyerry79** [meeting-room-booking-system/mrbs-code#3763]
**Describe the problem you're facing/question you have**
Hello again. I have successfully added the custom fields needed for booking. However, I wanted to hide one of the fields I created from non-admin users. To be specific, I added "terms_and_conditions" field and set it to mandatory. See screenshot below:
![image](https://github.com/user-attachments/assets/9c6f37e6-4708-4aa4-bb2f-935fde6c6f49)

What I want to do is to hide that field for admin users so only non-admin users are required to tick it. On the other hand, its default value to admin users is checked. Perhaps this could be similar to the approval status; once an admin user books, it is automatically approved. 

Any ideas on how to implement this? It might already exist in the latest MRBS 1.11.5.

TIA

**Comment by campbell-m** [comment]
There isn't a config setting for this. You'd need to edit the MRBS code in edit_entry.php.

**Comment by dyerry79** [comment]
Thanks. What particular function should I consider so I can start delving with edit_entry? With that, it would be easier for me to move on with what I wanted to achieve. TIA.

**Comment by dyerry79** [comment]
Ok. I was able to hide the "terms_and_conditions" field by editing the file you mentioned by going through the get_field_custom() function. This however, removed the "Terms and Conditions" label declared in the config file. 

here's my edit

if ($key == 'terms_and_conditions') {
      return is_book_admin() ?
      new ElementInputHidden(VAR_PREFIX.$key, '1') :
      new FieldInputCheckbox(VAR_PREFIX.$key);
}

tried to do some revisions but i am getting the same output, the label declared in the config is missing and the booking is accepted even if the checkbox is not ticked. here's the revised code but same output with the first one

	if ($key == 'terms_and_conditions') {
		if (is_book_admin()) {
			$field = new ElementInputHidden(VAR_PREFIX.$key, '1');
			return $field;
		} else {
			$field = new FieldInputCheckbox(VAR_PREFIX.$key, '', array(
				'label' => 'Terms and Conditions',
				'attributes' => array('required' => true)
				));

			if ($_POST && empty($_POST[VAR_PREFIX.$key])) {
				$error = 'Please accept Terms and Conditions';
			}
			
			return $field;
		}

	}

Any idea on this?

**Comment by campbell-m** [comment]
> For now, the lines did the trick

That will work as long as you only have one custom field.  If you have more than one you'll need:

~~~php
  if (($key == 'terms_and_conditions') && is_book_admin()) {
    $field = new ElementInputHidden(VAR_PREFIX . 'terms_and_conditions', '1');
    return $field;
  } 
~~~

**Comment by campbell-m** [comment]
> One thing that I wanted to do next is create a text/label after the checkbox that is clickable.

I think the following should work, though I haven't tested it:

~~~php
$div = new ElementDiv();
$div->setText("Your text");
$field->addElement($div);
~~~

**Comment by dyerry79** [comment]
The settext function won't allow html tags so I can't make my pop-up so I reverted back to the clickable label which shows the Terms and Conditions. However, the client just wanted to have a protected textarea for the content of the terms and conditions.

So the idea is there should be a default content for the textarea when a user books. I've read somewhere in one of your posts that $default_description = "Texts goes here" coud be used for this.

The code above will work for the column description but when applied to a custom textarea field, it is no working. I tried to add $term_content = $default_term_content; in the edit_entry then declaring 
$default_term_content="This is the content for terms and conditions"; in the config file.

However, this doesn't work.

Any ideas on this on how to move forward? By the way, placeholders for custom textareas also doesn't seem to work. except fot the desciption column. On the other hand, placeholders for custom textboxes work.

TIA.

**Comment by campbell-m** [comment]
> The settext function won't allow html tags

`setText()` takes three parameters: `setText(string $text, bool $text_at_start=false, bool $raw=false)`.  If you set `$raw` to true the text won't be escaped.  Alternatively you could do something like

~~~php
$div = new ElementDiv();
$a = new ElementA();
$a->setAttribute('href', 'https://somewhere.com');
$a->setText("Your text");
$div->addElement($a);
$field->addElement($div);
~~~

**Comment by campbell-m** [comment]
Note also that you should probably set

~~~php
$is_mandatory_field['entry.terms_and_conditions'] = true;
~~~

to force the users to tick the terms and conditions box.

**Comment by campbell-m** [comment]
> By the way, placeholders for custom textareas also doesn't seem to work. except fot the desciption column. On the other hand, placeholders for custom textboxes work.

Thanks for spotting this.  Now fixed in [b497f54](https://github.com/meeting-room-booking-system/mrbs-code/commit/b497f5427ab1b1f89d406b56aea0b8a0413b074a).

**Comment by dyerry79** [comment]
Thanks for the prompt reply and for fixing the placeholder. However, my client says he wanted to have something like this. The T and C should be above the checkbox.

![image](https://github.com/user-attachments/assets/d0e6d1d2-c354-4e18-8144-f8fb3a6214a8)

However, both of these failed on my end

1. Trying the $default_term_content='Terms and Conditions Content' won't work for custom fields.
2. Using a placeholder for the content of the Terms and Conditions is a good alternative. However, I found out that protected fields only work for the users' table.

Any idea where I would start whichever is easier for the two.

**Comment by campbell-m** [comment]
Why not just make a link to the Terms and Conditions?  For example,

"I agree to the [Terms and Conditions]()".

**Comment by dyerry79** [comment]
Ok. For now, that should be a good option. This is what I have so far:
1. For admin users, the checkbox is auto-check and hidden; and
2. The checkbox is visible to non-admin users.

here's the dirty code I have.

if ($key == 'terms_and_conditions') {
    if (is_book_admin()) {
	    $field = new ElementInputHidden(VAR_PREFIX . $key, '1');  // Auto-checked for admins
	    return $field;
    } else {
	    $element = new ElementDiv();
	    $checkbox = new ElementInputCheckbox();
		      $checkbox->setAttributes(array('name'     => 'f_terms_and_conditions',
										     'id'       => 'f_terms_and_conditions',
										     'required' => 'required'));
    
	    $beforelink = new ElementLabel();
	    $link = new ElementA();
	    $link->setAttribute('href', 'https://somewhere.com');
	    $link->setText("Terms and Conditions");
	    $beforelink->setText('I agree to the')
			             ->setAttribute('class', 'no_suffix');
    
	    $beforelink->addElement($checkbox);
	    $element->addElement($beforelink);
	    $element->addElement($link);
			    
	    return $element;
    }
}

3. The script above produces this
![image](https://github.com/user-attachments/assets/ac507833-1fd1-4bdb-a946-4a0b52000a5b)

The columns in the screenshot are all custom fields. My question now is, how can I move the checkbox so it will be aligned with the previous fields in the form?

**Comment by campbell-m** [comment]
This is what you want just before the `return $field;` line at the bottom of `get_field_custom()`:

~~~php
  if ($key == 'terms_and_conditions')
  {
    if (is_book_admin())
    {
      $field = new ElementInputHidden(VAR_PREFIX . $key, '1');  // Auto-checked for admins
    }
    else
    {
      // Create a <div> that will contain the original control and the new text
      $div = new ElementDiv();
      // Create a <span> that will contain the new text (and link)
      $a = new ElementA();
      $a->setAttribute('href', 'https://somewhere.com');
      $a->setText("Terms and Conditions");
      $span = new ElementSpan();
      $span->setText("I agree to the ", true);
      $span->addElement($a);
      // Get and remove the control
      $control = $field->getControl();
      $field->removeControl();
      // Put everything in the <div> and then into the field
      $div->addElement($control)->addElement($span);
      $field->addElement($div);
    }
  }

~~~

**Comment by dyerry79** [comment]
![image](https://github.com/user-attachments/assets/0cd2c923-f6f2-43af-9835-df4c67f4f0a3)

Thanks. It's working as expected now.

**Comment by dyerry79** [comment]
This is the final look at the terms and conditions popup implementation.

![image](https://github.com/user-attachments/assets/2024dccc-29b3-449c-aa07-2acc1b4ba591)

Thanks for the guidance Campbell! :)

**Comment by dyerry79** [comment]
Hi Campbell. Sorry for reopening this issue though I have already achieved what I want.

The thing is, our client wanted to implement the same thing with the contact_requirements field. By the way, the contact_requirements field is a textarea. I've already prepared a simple placeholder for the users but the client wanted to include the instructions/notation beside the textarea just like the terms and conditions. The notation is also clickable.

tried using echo '<pre>',var_dump("Entering get_field_custom() with key: $key,"),'</pre>'; but this one only returns 
string(59) "Entering get_field_custom() with key: terms_and_conditions," which hinders the implementation done in the terms and conditions to the detailed requriements.

**Comment by campbell-m** [comment]
Almost exactly the same as before, except that this time you need to replace the line further up the function that looks like

~~~php
    return get_field_entry_input($params);
~~~

with

~~~php
    $field = get_field_entry_input($params);
    if ($key == 'contact_requirements')
    {
      // Create a <div> that will contain the original control and the new text
      $div = new ElementDiv();
      // Create a <span> that will contain the new text (and link)
      $a = new ElementA();
      $a->setAttribute('href', 'https://somewhere.com');
      $a->setText("Terms and Conditions");
      $span = new ElementSpan();
      $span->setText("I agree to the ", true);
      $span->addElement($a);
      // Get and remove the control
      $control = $field->getControl();
      $field->removeControl();
      // Put everything in the <div> and then into the field
      $div->addElement($control)->addElement($span);
      $field->addElement($div);
    }
    return $field;
~~~

Of course you may not need the `<a>` this time, in which case you can take that bit out.

**Comment by dyerry79** [comment]
thanks campbell..

it's working as expected now. 

![image](https://github.com/user-attachments/assets/b078f4df-95a3-4ea7-9b5b-8e4825978e86)
