### ISSUE TITLE
Non-admin user can view private bookings made by admin

### ISSUE THREAD

**Issue by dyerry79** [meeting-room-booking-system/mrbs-code#3770]
Seems that non-admin users can view private bookings made by an admin user. To start, I have this settings in one of my areas:
![1](https://github.com/user-attachments/assets/6d481d09-e7f1-4424-af48-d2b46c5739d4)

A non-admin user viewing a booking made by a non-admin user works fine. Here is the screenshot
![2](https://github.com/user-attachments/assets/a82a59ec-cda4-42be-9fcb-50b9386ee4a6)

However, when a non-admin user views a booking done by an admin user, the private settings seems not working. Here is the screenshot.
![3](https://github.com/user-attachments/assets/46dbdc26-5d8e-45e0-ba13-2bbb87f6d60b)

Pls. check. 

TIA

**Comment by campbell-m** [comment]
Now fixed in [c0c000e](https://github.com/meeting-room-booking-system/mrbs-code/commit/c0c000e0d8fecf73dbda89233d6809112937eb57).

**Comment by dyerry79** [comment]
Thanks campbell.
