### ISSUE TITLE
Fatal error when save a booking if min_booking_date is enabled

### ISSUE THREAD

**Issue by piotr119955** [meeting-room-booking-system/mrbs-code#3773]
**Describe the bug**
Fatal error when save a booking if min_booking_date is enabled

**To Reproduce**

1. In config.inc.php, enabled min_booking_date = true and set min_booking_date to a day
2. Go to booking system, add a entry and click 'save'
3. it throws a fatal error

**Expected behavior**
4. Save successfully

**Browser details (please complete the following information):**
- OS: Windows
- Browser - chrome
- Version 130.0.6723.59

**Server details (please complete the following information):**
 - MRBS version 1.11.6
 - Web server: Apache 2.4.48
 - OS: cPanel
 - PHP version: 8.2
 - Database used: MySQL 8.0.26

**Comment by piotr119955** [comment]
Additional context
After checking the log, the error is on a mrbs_sql.inc line 605 (checkdate function). The function expects to get int as parameters but system pass string to it.

**Comment by campbell-m** [comment]
Thanks.  Now fixed in [9977616](https://github.com/meeting-room-booking-system/mrbs-code/commit/997761601612dfb56a160ff7f1e7a2242c5174b9).
