### ISSUE TITLE
in a series booking whether the last booking is included at the end date depends on time of day during booking

### ISSUE THREAD

**Issue by cluster15** [meeting-room-booking-system/mrbs-code#3774]
When you book a series of events whether the last entry is booked depends on the time of day during booking relative to the event. If you book the event before the event starting time the last event will not be included at the end date, if the event is booked at a time of after the event would end the event is included at the end date. 

It looks like the time of day during booking is included to determine when the series ends. This is at least unexpected behaviour.

**To Reproduce**
Steps to reproduce the behaviour:
1. create a series event where that event starts _after_ the current time of day while booking (call it "After"). 
    Say it is now 10:00am and the event should be booked for 12:00-13:00. 
2. Make it a daily series running from tomorrow up to 5 days later
3. Look at the end date, the last event (called "After") is _not_ booked. 
4. Repeat the above but this time the event starts and ends _before_ the current time of day while booking (call "Before")
    Say it is now 10:00am and the event should be booked for 8:00-9:00. 
5. Make it a daily series running from tomorrow up to 5 days later
6.  Look at the end date, the last event (called "Before") _is_ booked. 

If I enter an end date for a series booking it should include bookings on that date up to 24:00 (or 23:59) independent on the time of day during booking. 

**Server details (please complete the following information):**
 - MRBS version [1.11.4]
 - PHP version: [8.3.12]
 - Database used: [10.11.9-MariaDB]

**Comment by campbell-m** [comment]
I think this has already been fixed.  I cannot reproduce it in the latest release (1.11.6).

**Comment by cluster15** [comment]
I did not find anything in the release notes for 1.11.5 and 1. 11.6 which indicated anything in that direction, but I'll give it a go.

**Comment by campbell-m** [comment]
Did you get a chance to test 1.11.6?

**Comment by jberanek** [comment]
https://github.com/meeting-room-booking-system/mrbs-code/commit/e731c8a80b9c0c54a436195ff81be8d6ef79fd51

**Comment by cluster15** [comment]
That fixed it. Sorry for not getting back earlier.
