### ISSUE TITLE
Uncaught exception 'TypeError' in .../MRBS/Form/Form.php at line 27

### ISSUE THREAD

**Issue by cstrizzolo** [meeting-room-booking-system/mrbs-code#3776]
I have just tried upgrading my MRBS 1.11.5 instance to MRBS 1.11.6.

When I try accessing the new MRBS instance for the first time, the following error gets added to the error log:

~~~text
[Tue Nov 12 10:06:27.423432 2024] [proxy_fcgi:error] [pid 2563228:tid 2563296] [remote 140.105.221.102:48400] AH01071: Got error 'PHP message: Uncaught exception 'TypeError' in (...)/mrbs/lib/MRBS/Form/Form.php at line 27\nMRBS\\Form\\Form::__construct(): Argument #1 ($method) must be of type int, string given, called in (...)/mrbs/Themes/default/header.inc on line 349\n#0 (...)/mrbs/Themes/default/header.inc(349): MRBS\\Form\\Form->__construct()\n#1 (...)/mrbs/Themes/default/header.inc(400): MRBS\\print_logonoff_button()\n#2 (...)/mrbs/Themes/default/header.inc(455): MRBS\\print_logoff()\n#3 (...)/mrbs/Themes/default/header.inc(665): MRBS\\print_banner()\n#4 (...)/mrbs/functions.inc(884): MRBS\\print_theme_header()\n#5 (...)/mrbs/index.php(493): MRBS\\print_header()\n#6 {main}\n\nMRBS GET:...'
~~~

MRBS version: 1.11.6
Web server: Apache 2.4.57
OS: Oracle Linux Server release 9.4 (clone of RHEL 9.4)
PHP version: 8.1.30
Database used:  MariaDB 10.5.22

**Comment by campbell-m** [comment]
What have you got `$auth['type']` and `$auth['session']` set to?

**Comment by cstrizzolo** [comment]
I have solved the problem.
Sorry for bothering you and thank you for pointing me to the right path.

I am using the ([Shibboleth authentication module by Ondřej Votava](https://gitlab.fel.cvut.cz/fel-svti-aplikace/mrbs-shibboleth)).
Since MRBS 1.11.6 it looks like the lib/MRBS/Session/SessionShibboleth.php file provided by the module must be slightly patched. If anyone is interested, the attached patch seems to work.

[SessionShibboleth_patch.txt](https://github.com/user-attachments/files/17714287/SessionShibboleth_patch.txt)
