### ISSUE TITLE
ajax search

### ISSUE THREAD

**Issue by dyerry79** [meeting-room-booking-system/mrbs-code#3777]
Hi again. One requirement given was to add monitoring for approved bookings to check how many bookings were completed. I managed to add the page based on the requirements, which patterned with the files that come with MRBS. See screenshot below:

![image](https://github.com/user-attachments/assets/90d2b05d-e159-4400-b90e-2d99c93b7c14)

Just got an issue with the search bar. It works fine with with everything (I guess) except for the COMPLETED status. I posted the screenshot to see the difference between the keyword search using the status.

For ONGOING - works fine
![image](https://github.com/user-attachments/assets/f6e03f00-0c02-4e88-957c-add2f8f26db1)

For COMPLETED - filter doesn't work
![image](https://github.com/user-attachments/assets/004bd357-eae0-4f00-8b18-2be62ef01cba)

Any tip on how to go about this? 

Another thing. It's a dirty work-around but this is how I got the pagination,  the filter and the search bar working. I added this in my file just to get it working. I guess that this is not the proper way to do it since I haven't seen this implementation in the MRBS core files.

~~~php
print_header($context);
?>
<script src="jquery/datatables/datatables.min.js"></script>
<script src="jquery/datatables/plugins.js"></script>
<script src="js/datatables.js.php?area=1"></script>
<script src="js/manage.js.php?area=1"></script>
<?php
echo "<h1>" . get_vocab("manage_bookings") . "</h1>\n";
~~~

Your usual help is highly appreciated. TIA.

**Comment by campbell-m** [comment]
> Another thing. It's a dirty work-around but this is how I got the pagination, the filter and the search bar working. I added this in my file just to get it working. I guess that this is not the proper way to do it since I haven't seen this implementation in the MRBS core files.

The JavaScript files are loaded by js.inc.  I think you probably just need to modify line 96 to add your 'manage' page.  It should pick up your manage.js.php automatically, and I assume that is modelled on one of the other files such as search.js.php.

> For COMPLETED - filter doesn't work

I think it is working.  The problem is that the filter searches all columns and in your screenshot the second row is showing "Not completed" under the column "Actual Date/Time Completed".  If you made that text just "-" or something instead of "Not completed" then that row won't show.

**Comment by dyerry79** [comment]
> The JavaScript files are loaded by js.inc. I think you probably just need to modify line 96 to add your 'manage' page. It should pick up your manage.js.php automatically, and I assume that is modelled on one of the other files such as search.js.php.

thanks. that did the trick


> I think it is working. The problem is that the filter searches all columns and in your screenshot the second row is showing "Not completed" under the column "Actual Date/Time Completed". If you made that text just "-" or something instead of "Not completed" then that row won't show.

my bad :) ... you're right. it's all sorted out now. 

thank you Campbell.
