### ISSUE TITLE
conditional dropdown dependent on room selection

### ISSUE THREAD

**Issue by dyerry79** [meeting-room-booking-system/mrbs-code#3778]
Hi, after resolving the holiday and management of approved bookings. I stumbled a roadblock again. What I am trying to do is to create a dropdown whose values are dependent on the room selected by the user. Here are the things I have done so far.

1. Added a custom_field named as venue_setup. And in the config file, I have declared it following the instructions in the systemdefaults. This works perfectly fine and created the whole set of items for the dropdown.

~~~php
$select_options['entry.venue_setup'] = array('PC' => 'Classroom  - 1,100 pax',
                                             'PB' => 'Banquet    - 500 pax',
                                             'PF' => 'Conference - 500 pax',
					     '1C' => 'Classroom  - 40 pax',
                                             '1B' => 'Banquet    - 30 pax',
                                             '1F' => 'Conference - 30 pax',
					      '2C' => 'Classroom  - 200 pax',
                                             '2B' => 'Banquet    - 160 pax',
                                             '2F' => 'Conference - 160 pax',);
~~~

2. I then added in my custom js to map the items from the config file to the the venue_setup dropdown. I tested it first like this.

~~~js
document.addEventListener('DOMContentLoaded', function() {
    const roomDropdown = document.getElementById('rooms'); // Reference to the rooms dropdown
    const venueSetupDropdown = document.getElementById('f_venue_setup'); // Reference to the existing dropdown
	
	//const venueOptions = <?php echo json_encode($select_options['entry.venue_setup']); ?>;

    if (!roomDropdown || !venueSetupDropdown) {
        console.error("Error: Required dropdowns not found in the DOM.");
        return;
    }

    // Add event listener for room selection
    roomDropdown.addEventListener('change', function() {
        const selectedRoomIds = Array.from(roomDropdown.selectedOptions).map(option => option.value);
        filterVenueSetupOptions(selectedRoomIds);
    });

    // Function to filter options based on selected rooms
    function filterVenueSetupOptions(selectedRoomIds) {
        venueSetupDropdown.innerHTML = ''; // Clear existing options

        const venueOptions = {
            "1": ["PC", "PB", "PF"], 
            "2": ["1C", "1B", "1F"], 
            "3": ["2C", "2B", "2F"], 
            // Add more mappings as needed
        };

        // Set to keep track of added options to avoid duplicates
        const addedOptions = new Set();

        // Populate the dropdown based on selected rooms
        selectedRoomIds.forEach(roomId => {
            const optionsForRoom = venueOptions[roomId] || [];
            optionsForRoom.forEach(optionValue => {
                if (!addedOptions.has(optionValue)) {
                    const newOption = document.createElement('option');
                    newOption.value = optionValue;
                    newOption.textContent = optionValue; // Adjust text as needed
                    venueSetupDropdown.appendChild(newOption);
                    addedOptions.add(optionValue); // Track added options to avoid duplicates
                }
            });
        });

        // Optional: Select the first available option if any
        if (venueSetupDropdown.options.length > 0) {
            venueSetupDropdown.value = venueSetupDropdown.options[0].value; // Select the first option
        }
    }

    // Initialize the dropdown with the current selected rooms
    const initialRoomIds = Array.from(roomDropdown.selectedOptions).map(option => option.value);
    filterVenueSetupOptions(initialRoomIds);
});
~~~

the test went well as seen in the screenshot for the three rooms

![image](https://github.com/user-attachments/assets/c4be73bd-409b-40fd-b877-4159c7a18fbe)

However, commenting out this line in the javascript nullified the mapping reverting the dropdown values to their original values. you can see in the screenshot below

`//const venueOptions = <?php echo json_encode($select_options['entry.venue_setup']); ?>; `

![image](https://github.com/user-attachments/assets/fdeb8bfd-2297-41c2-b4d0-8492fb8aa7a5)

Your expert ideas are much appreciated. TIA

**Comment by campbell-m** [comment]
I can't see the line that you commented out in your code.

**Comment by dyerry79** [comment]
> I can't see the line that you commented out in your code.

//const venueOptions = <?php echo json_encode($select_options['entry.venue_setup']); ?>;

I tried playing with its placement but never got lucky.

**Comment by campbell-m** [comment]
Sorry, I'm not quite sure what the problem is.  You said it was all working until you commented out the line

~~~js
//const venueOptions = <?php echo json_encode($select_options['entry.venue_setup']); ?>; 
~~~

but I can't see that line in your code.  Besides, if it was all working why did you comment it out?

**Comment by dyerry79** [comment]
Thanks for your patience Campbell. Let me go over again

1. I added a custom field as venue_setup. In my config file, I declared it like the codes below to create the values of the dropdown.

`$select_options['entry.venue_setup'] = array('PC' => 'Classroom  - 1,100 pax',
                                             'PB' => 'Banquet    - 500 pax',
                                             'PF' => 'Conference - 500 pax',
					     '1C' => 'Classroom  - 40 pax',
                                             '1B' => 'Banquet    - 30 pax',
                                             '1F' => 'Conference - 30 pax',
					      '2C' => 'Classroom  - 200 pax',
                                             '2B' => 'Banquet    - 160 pax',
                                             '2F' => 'Conference - 160 pax',);`
 
2. My goal is to filter the contents of the dropdown declared in the config file based on the  room selected. Allow me to show it through the table below. If the room selected is Plenary, the dropdown contents are ones under the dropdown options.

**Room**        **Table Value**		**Dropdown Options**
Plenary		PC				Classroom - 1,100 pax
			PB				Banquet - 500 pax
			PF				Conference - 500 pax

Room1		1C				Classroom - 40 pax
			1B				Banquet - 30 pax
			1F				Conference - 30 pax
			
Room2		2C				Classroom - 200 pax
			2B				Banquet - 160 pax
			2F				Conference - 160 pax

3. The output. Using the javascript above without the const venueOptions = <?php echo json_encode($select_options['entry.venue_setup']); ?>;

![image](https://github.com/user-attachments/assets/feccb73a-3843-4f92-8f92-c52cede8c5a1)

As you can see, the filtering works well except that the dropdown options are missing. You mar refer to number 2 under dropdown options. What is included in the dropdown are just the table values.

4. When I included this line in the javascript const venueOptions = <?php echo json_encode($select_options['entry.venue_setup']); ?>; to map the venue_setup from the config file to the javascript, the filter doesn't work anymore when clicking any of the rooms just like the screenshot below

![image](https://github.com/user-attachments/assets/c1b490d8-441a-4ba2-9538-a23ef3e3980c)

**Comment by campbell-m** [comment]
~~~js
newOption.textContent = optionValue; // Adjust text as needed
~~~

You are setting the text in the options to be the same as the value, instead of the text in the `$select_options` array.

**Comment by dyerry79** [comment]
Thanks Campbell. While thinking of a simpler way to do it. I got it working but I'm not satisfied. In the meantime, I'll stay with this since it's giving the output I want. Still, I want to share for those who may experience the same hurdles as me.

`document.addEventListener('DOMContentLoaded', function() {
    const roomDropdown = document.getElementById('rooms'); // Reference to the rooms dropdown
    const venueSetupDropdown = document.getElementById('f_venue_setup'); // Reference to the existing dropdown

    // Ensure the dropdowns exist
    if (!roomDropdown || !venueSetupDropdown) {
        console.error("Error: Required dropdowns not found in the DOM.");
        return;
    }

    // Venue options mapping
    const venueOptions = {
        'PC': 'Classroom  - 1,100 pax',
        'PB': 'Banquet    - 500 pax',
        'PF': 'Conference - 500 pax',
        '1C': 'Classroom  - 40 pax',
        '1B': 'Banquet    - 30 pax',
        '1F': 'Conference - 30 pax',
        '2C': 'Classroom  - 200 pax',
        '2B': 'Banquet    - 160 pax',
        '2F': 'Conference - 160 pax',
    };

    // Room to venue mapping
    const roomToVenueMapping = {
        "1": ["PC", "PB", "PF"], 
        "2": ["1C", "1B", "1F"], 
        "3": ["2C", "2B", "2F"], 
    };

    // Add event listener for room selection
    roomDropdown.addEventListener('change', function() {
        const selectedRoomIds = Array.from(roomDropdown.selectedOptions).map(option => option.value);
        filterVenueSetupOptions(selectedRoomIds);
    });

    // Function to filter options based on selected rooms
    function filterVenueSetupOptions(selectedRoomIds) {
        venueSetupDropdown.innerHTML = ''; // Clear existing options

        // Set to keep track of added options to avoid duplicates
        const addedOptions = new Set();

        // Populate the dropdown based on selected rooms
        selectedRoomIds.forEach(roomId => {
            const optionsForRoom = roomToVenueMapping[roomId] || [];
            optionsForRoom.forEach(optionValue => {
                if (!addedOptions.has(optionValue)) {
                    const newOption = document.createElement('option');
                    newOption.value = optionValue;
                    newOption.textContent = venueOptions[optionValue]; // Use the description from venueOptions
                    venueSetupDropdown.appendChild(newOption);
                    addedOptions.add(optionValue); // Track added options to avoid duplicates
                }
            });
        });

        // Optional: Select the first available option if any
        if (venueSetupDropdown.options.length > 0) {
            venueSetupDropdown.value = venueSetupDropdown.options[0].value; // Select the first option
        }
    }

    // Initialize the dropdown with the current selected rooms
    const initialRoomIds = Array.from(roomDropdown.selectedOptions).map(option => option.value);
    filterVenueSetupOptions(initialRoomIds);
});`

this is now the final screenshot

![image](https://github.com/user-attachments/assets/ad455e4c-3836-40b9-90c4-f1fb2b35c022)
