### ISSUE TITLE
Monthly calender view didnt show description when mouse over

### ISSUE THREAD

**Issue by akramjannah** [meeting-room-booking-system/mrbs-code#3780]
When i mouse over to event title, popup comment didnt show description, just only time and title

Browser Detail :
 - OS: Windows 11
 - Browser : chrome
 - Version Version 130.0.6723.117 (Official Build) (64-bit)

Server Detail :
 - MRBS version : 1.11.6
 - Web server: Apache 2.4.58
 - OS: Windows server 2019
 - PHP version: 8.2.12
 - Database used: 10.4.32-MariaDB

![1731915411924](https://github.com/user-attachments/assets/6eca16b3-c606-4d52-b49c-3001cfcaf30c)

**Comment by campbell-m** [comment]
I've now added this in [1952066](https://github.com/meeting-room-booking-system/mrbs-code/commit/1952066f385235f3609e2ceede671396ade39a09).
