### ISSUE TITLE
Need help with fine-tuning MRBS 1.11.6 after upgrade

### ISSUE THREAD

**Issue by embeh** [meeting-room-booking-system/mrbs-code#3783]
We finally! upgraded from MRBS 1.8.0 to 1.11.6 but now struggle a bit to fine-tune the new installation and re-apply some of our customizations.

1. How to globally change the **time display** to 24-hour and **date display** to dd.mm.yyyy format, regardless of web browser settings?
2. How to **turn of auto-scrolling** (especially in week view)? Right now, MRBS always scrolls the view such that the current time is centered but we would like it to always scroll to the top, to show the first time of the day)
3. How to show the **full name of the booker** along with the **booking creation date** in the tooltip of a booking? We used to get the real name from a username via authLdapGetName() but that no longer exists.
4. The helper file **help_report.php** seems no longer available?

Thanks very much in advance!

**Comment by campbell-m** [comment]
1. Setting `$override_locale = 'en-GB';` will do that, but it will also force the language to be English.  But maybe that's OK?

2. Edit js/refresh.js.php and comment out the line (approx 617) `    scrollToCurrentSlot();`.  I'll look at making this a config option.

3. You can get the real name given the username by using `auth()->getUser($username)`.  This returns an object with a `display_name` property.

4. It's called help_report.html (as it always was!) and is in the top level directory.

**Comment by campbell-m** [comment]
> Edit js/refresh.js.php and comment out the line (approx 617)     scrollToCurrentSlot();. I'll look at making this a config option.

I've now added this as a config option in [2f93688](https://github.com/meeting-room-booking-system/mrbs-code/commit/2f93688260c2d8d8c96c08cc4a3d817acc8b057a).

**Comment by embeh** [comment]
Awesome! Thanks very much!! Every single question addressed perfectly - and super-fast, too!
