### ISSUE TITLE
Room message should not be displayed in "<all>" view

### ISSUE THREAD

**Issue by embeh** [meeting-room-booking-system/mrbs-code#3784]
Switching the room filter from a specific room to `<all>` will still display the room message.

**To Reproduce**
1. Run MRBS version 1.11.6
2. Add a message to a room
3. Verify the message is shown for that room by switching to week view and selecting that room from the right dropdown menu.
4. Still in week view, change the right dropdown filter for rooms from the individual room to "all" rooms
5. The room message is still shown

**Expected behavior**
I would expect no message to be shown, as it is not clear anymore which room the message relates to.
Maybe the message could be shown as a tooltip on the room name instead?

**Comment by campbell-m** [comment]
The message is not specific to a room, or even an area, but is a general system message.   Maybe it would help if the title were renamed to "System message" from "Message"?

**Comment by embeh** [comment]
Doh! I see - my bad! Sorry!

"System message" would indeed help confused persons like me.

So there is no way to place such a message above a room?

**Comment by campbell-m** [comment]
> "System message" would indeed help confused persons like me.

OK, I'll change it.

> I guess what confused me was the fact that it showed up when editing the Room Details.

Yes, it was a quick and dirty place to put it.  The menu really needs restructuring.

> So there is no way to place such a message above a room?

Not at the moment, I'm afraid.
