### ISSUE TITLE
Need help with LDAP integration

### ISSUE THREAD

**Issue by NR-201** [meeting-room-booking-system/mrbs-code#3789]
I have been trying to integrate LDAP into the MRBS system but I keep getting unknown user errors no matter what credentials I try. The server is able to communicate with the LDAP server and initial bind was successful according to the logs but I am getting an operations error. Is it an issue with the binds 

**Browser details:**
 - OS: [Debian 12]
 - Browser [Chrome]
 

**Server details:**
 - MRBS version [e.g. 1.11.6]
 - Web server: [e.g. Apache 2.4.62]
 - OS: [Debian12]
 - PHP version: [8.4.1]
 - Database used: [e.g. MySQL 15.1]

![image](https://github.com/user-attachments/assets/af2b3343-e525-4c4d-a063-4e8d3a6a3f0c)
Error Log
![image](https://github.com/user-attachments/assets/2acaae24-102d-4ae2-8e3b-38fffbcb476b)
Config file (I just edited out the password info)

**Comment by campbell-m** [comment]
Sorry, I've just seen the debug info!

**Comment by NR-201** [comment]
No worries!

**Comment by campbell-m** [comment]
Can you post please the full line from the debug info that shows 'ldap_search failed', preferably as text rather than as an image.

**Comment by NR-201** [comment]
[Tue Dec 17 06:29:21.926036 2024] [php:notice] [pid 10787:tid 10787] [client 127.0.0.1:34372] [MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(768): ldap_search failed: Operations error [000004DC: LdapErr: DSID-0C090C>0C090C78, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4f7c], referer: http://0.0.0.0/admin.php

**Comment by campbell-m** [comment]
I searched for the error message and found [this post](https://github.com/flamencist/ldap4net/issues/108).   Can you try setting

~~~php
$ldap_disable_referrals = true;
~~~

**Comment by NR-201** [comment]
![image](https://github.com/user-attachments/assets/bb1b73ac-5d7d-442a-ba3b-e33b6d997f0a)
No luck

**Comment by NR-201** [comment]
Nevermind it worked!

**Comment by campbell-m** [comment]
Good!

**Comment by NR-201** [comment]
Thanks much!
