### ISSUE TITLE
Increase the size of each table - grid item to display more characters

### ISSUE THREAD

**Issue by pippogiuseppe** [meeting-room-booking-system/mrbs-code#3790]
Good morning Thanks for the great booking system. I set up the summary grid of bookings on a period basis, setting the different booking shifts. I need to increase the size of each element of the grid (where the description of the reservation appears and if I hover over it the detail of the reservation). 
![MRBS](https://github.com/user-attachments/assets/30b354bf-4bd5-474f-b551-9bdfc95f5c5d)

The MRBS version is 1.10.0
Thank you

**Comment by campbell-m** [comment]
Create a custom CSS file (see systemdefalts.inc.php for how) and add the rule

~~~css
.dwm_main th, .dwm_main td {
    min-height: 1.5em;
    line-height: 1.5em;
}
~~~

1.5em is the default height; increase it as required keeping both values the same, eg

~~~css
.dwm_main th, .dwm_main td {
    min-height: 3em;
    line-height: 3em;
}
~~~

This works on MRBS 1.11.6.  I haven't tested it on 1.10.0, but I recommend upgrading anyway.

**Comment by pippogiuseppe** [comment]
thanks 1000, it also works with my version of mrbs. it increases only my height.

**Comment by campbell-m** [comment]
To increase the width add

~~~css
.dwm_main td {
    min-width: 20em; /* change value as required */
}
~~~

**Comment by pippogiuseppe** [comment]
Great thanks, it works great.
One last request, I think it always concerns css.
I would like to better format the characters of only the main row and column, in particular:
- Larger font
- Bold font
- red font
![mrbs](https://github.com/user-attachments/assets/b16dd30a-4a7e-4ec8-b266-88cb214fbc80)

**Comment by pippogiuseppe** [comment]
As for the name of the horizontal rooms I solved it with the css rule:

`.dwm_main th[data-room] a {
  color: red;
  font-weight: bold;
  font-size: 14pt
}`

I miss the vertical part of the periods.
Help me please

**Comment by pippogiuseppe** [comment]
It works!!
Thank you very much
