### ISSUE TITLE
Areas' selection

### ISSUE THREAD

**Issue by kalacho** [meeting-room-booking-system/mrbs-code#3793]
**Describe the problem you're facing/question you have**
Our library is using an older version of MRBS and we are considering the upgrade. We use different areas for different types of study rooms. In the current version, an area is selected by default when you open the MRBS' home page, and the other areas are not visible. Is it possible to not have any area selected by default, which will force students to choose an area that they need?

**Comment by campbell-m** [comment]
Sorry, it's not possible without changing the MRBS code.

**Comment by kalacho** [comment]
I see. Thanks a lot for letting me know.
