### ISSUE TITLE
Issues with SMTP 

### ISSUE THREAD

**Issue by NR-201** [meeting-room-booking-system/mrbs-code#3795]
I can't seem to get emails to be sent whenever I book a room
![image](https://github.com/user-attachments/assets/c4b4c1a6-e42c-4028-9ab5-7fcedb15c1b4)
This is my config

![image](https://github.com/user-attachments/assets/a025f4f5-38b1-448c-863b-7907f340c812)
And this is the debug Im getting
It looks as though it trying to pull from the sAMAccountname rather than their email

**Comment by campbell-m** [comment]
You need to make sure that you have `$ldap_get_user_email = true;` and `$ldap_email_attrib` set to the LDAP attribute which holds the user's email address.

**Comment by NR-201** [comment]
I set the $ldap_email_attrib='mail'; but im still getting the same debug error

**Comment by campbell-m** [comment]
Have you set `$ldap_get_user_email = true;`?

**Comment by NR-201** [comment]
Yes
![image](https://github.com/user-attachments/assets/6f38bbdd-51ac-445e-93bc-8980ab19d9d9)

and when I do an ldapsearch for mail
![image](https://github.com/user-attachments/assets/9b4e4b02-5ceb-4008-8d31-c5c7c156597a)
its pulling the email

**Comment by campbell-m** [comment]
Ah, I see the debug output is saying "No recipients".  You need to set at least one of the following to `true`:

~~~php
$mail_settings['admin_on_bookings']      = false;  // the addresses defined by $mail_settings['recipients'] below
$mail_settings['area_admin_on_bookings'] = false;  // the area administrator
$mail_settings['room_admin_on_bookings'] = false;  // the room administrator
$mail_settings['booker']                 = false;  // the person making the booking
$mail_settings['book_admin_on_approval'] = false;  // the booking administrator when booking approval is enabled
                                                   // (which is the MRBS admin, but this setting allows MRBS
                                                   // to be extended to have separate booking approvers)
~~~

**Comment by NR-201** [comment]
![image](https://github.com/user-attachments/assets/15da32ab-cff2-435b-bf6a-bbf5bebae6d9)
No such luck

![image](https://github.com/user-attachments/assets/8d721042-6571-443b-b95f-7e7444eade29)
Getting the same errors

**Comment by campbell-m** [comment]
What happens when you set `$ldap_debug_attributes = true;`?  Do you see the attribute name and value you are expecting?

**Comment by NR-201** [comment]
Okay so I just logged into the no-reply account and the email was sent from no-reply to no-reply I just reset the admin emails for the area and it worked thank you very much!
