### ISSUE TITLE
error when searhing

### ISSUE THREAD

**Issue by pmonstad** [meeting-room-booking-system/mrbs-code#3797]
Running 1.11.6 (upgraded during the years). When I do a search I get an error:
Argument 2 passed to MRBS\period_date_string() must be of the type int, string given, called in /home/...../search.php on line 101

Seems to fail when I select a date several years back in time.

**Comment by campbell-m** [comment]
Thanks for spotting this.  Now fixed in [1ed8ef4](https://github.com/meeting-room-booking-system/mrbs-code/commit/1ed8ef42144bb703aa424b5d77aa9e74c33d890a).
