### ISSUE TITLE
read meeting info from python request

### ISSUE THREAD

**Issue by Satheeshkumar-Duraisamy** [meeting-room-booking-system/mrbs-code#39]
**Problem description**

http://<ip-address>/view_entry.php?view=day&year=2022&month=05&day=22&area=1&id=2
requests.get(url, allow_redirects=True, timeout=10, auth=HTTPBasicAuth('username', 'password'))

I am reading the meeting information through python request with authentication like above but It returns the login page instead of meeting information page. Can you support here to get the actual meeting info?

**Browser details (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]

**Server details (please complete the following information):**
<html>
<body>

MRBS version | MRBS 1.10.0
-- | --
Database schema version | 82
Database local schema version | 1
$auth['type'] | db
$auth['session'] | php

</body>
</html>

<html>
<body>

Database | MySQL 5.7.37-0ubuntu0.18.04.1
-- | --
System | Linux ozd1932u 5.4.0-107-generic #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64
Server time | Mon 23 May 2022 10:01:58 AM IST
Server software | Apache/2.4.29 (Ubuntu)
PHP | 7.2.24-0ubuntu0.18.04.11
Extensions | Core, PDO, Phar, Reflection, SPL, Zend OPcache, apache2handler, calendar, ctype, date, exif, fileinfo, filter, ftp, gettext, hash, iconv, json, libxml, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, zlib

</body>
</html>

**Comment by campbell-m** [comment]
I think that it should work if you set in your MRBS config file `$auth['type'] = 'none';` and `$auth['session'] = 'http';` .   Or else if you want to keep your existing set up you could create another MRBS installation in a different directory pointing at the same database but using those config settings.

The other solution would be to make the view_entry page open to all by editing mrbs_auth.inc, but you may not want to do this.

What is it that you are trying to achieve anyway?  There may be another way of meeting the requirement.

**Comment by Satheeshkumar-Duraisamy** [comment]
The $auth['type'] = 'none'; and $auth['session'] = 'http'; works but neither able to switch user nor logout now. I want both the method(python request as well as login and logout option in browser). If nothing possible, making view_entry page to public also fine.

The below is my requirement

Input
------
- username
- room id
- area id

Output
--------
- Is given room booked now? (boolean)
- Is given room booked now by given user (boolean)
- Return name, description, start time, end time(if booked by anybody)

Process
--------
- python script with request module shall read all the above mentioned information

**Comment by campbell-m** [comment]
No, you'd have to modify view_entry.php to get the username - it would only be a small change.

It might be better overall just to write a small PHP page that gives you exactly the information you need in a convenient format, eg JSON.

**Comment by jberanek** [comment]
Advice was given.
