### ISSUE TITLE
UPGRADE documentation only updated to MRBS 1.8.0

### ISSUE THREAD

**Issue by jasper2virtual** [meeting-room-booking-system/mrbs-code#40]
Hello, we are using the MRBS at 1.7.3, and we love it.
We would like to upgrade to MRBS 1.10.0, but cannot find any upgrade guide.
May I know will you update the UPGRADE to include 1.10.0, or else we will find out the procedure ourselves and contribute it later.

**Comment by campbell-m** [comment]
The UPGRADE document covers the upgrade from 1.7.3 to 1.10.0.  The only thing to watch out for is that 1.10.0 requires PHP 7.2 or above.

**Comment by jasper2virtual** [comment]
hi @campbell-m ,
thanks, may I know the line 1 - 44 of UPGRADE, which mention only to version 1.8.0, 
it also covers the 1.7.3 to 1.10.0 too? 
Good day bro

**Comment by campbell-m** [comment]
Yes, it covers upgrading from 1.7.3 to 1.10.0.   The reference to version 1.8.0 on line 31 is "Upgrading _from_ prior to MRBS 1.8.0" not upgrading _to_ MRBS 1.8.0.
