### ISSUE TITLE
i want add "prompt text" in “edit_entry.php” 

### ISSUE THREAD

**Issue by wilia** [meeting-room-booking-system/mrbs-code#41]
hello , i want add “Explanatory notes”and text content is "prompt text" in “edit_entry.php” 
Picture see link：[https://imgtu.com/i/XWtNmF](https://imgtu.com/i/XWtNmF)

The text content can only display a single line, how can I modify it into multiple lines？

code show as below:
> function get_field_des_text($value, $disabled=true)
> {
>   $params = array('label'    => get_vocab('des_text'),
>                   'name'     => 'des_text',
>                   'field'    => 'entry.des_text',
>                   'value'    => get_vocab('des_help9'),
>                   'required' => !empty($is_mandatory_field['des_text']),
>                   'disabled' => $disabled);
> 
>   return get_field_entry_input($params);
> }

**Comment by campbell-m** [comment]
You don't need to modify the MRBS code.  You just need to add a custom field to the entry and repeat tables and MRBS will automatically handle it.   See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document.

**Comment by wilia** [comment]
> You don't need to modify the MRBS code. You just need to add a custom field to the entry and repeat tables and MRBS will automatically handle it. See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document.

Thanks for the guidance，But I modified to add the 'prompt_text' field in the database entry table and repeat, set the attribute to 'text', call the code in edit_entry.php, and successfully add the 'prompt_text' module on the 'add entry' page, but the module title is also It shows that 'prompt_text' cannot be modified. 

Picture see link：[https://imgtu.com/i/XhZsLq](https://imgtu.com/i/XhZsLq)

In addition, how can the text content be set to call for translation in other languages? The settings cannot be edited.

code show as below:
> function get_field_prompt($value, $disabled=true)
> {
>   //$vocab_override['en']['prompt_text']=get_vocab('des_text');
>   $vocab_override['en']['prompt_text']='test text';
> }

I'm very sorry, my PHP knowledge is weak, I'm a rookie, I don't understand anything, thank you for your help

**Comment by campbell-m** [comment]
> But if I don't modify the MRBS code, this new text module will not be displayed in the interface.
Yes, it will be.  MRBS will automatically detect the new database column and include a field on the form.

>Is this command `$vocab_override['en']['entry.prompt_text']='test text';` written in edit_entry.php?
No, it should be in config.inc.php.

**Comment by wilia** [comment]
> > But if I don't modify the MRBS code, this new text module will not be displayed in the interface.
> 
> Yes, it will be. MRBS will automatically detect the new database column and include a field on the form.
> 
> > Is this command `$vocab_override['en']['entry.prompt_text']='test text';` written in edit_entry.php?
> 
> No, it should be in config.inc.php.

thanks for your guidance，I did it, after writing "$vocab_override['en']['entry.prompt_text']='test text';" in config.inc.php, the title of the text module is already showing as "test text", but There are a few more questions to ask:
1. Modify the text 'test text' in "$vocab_override['en']['entry.prompt_text']='test text';" to other languages such as 'Chinese' ("$vocab_override['en'][' entry.prompt_text']='Chinese';"), it cannot be displayed
2. How can I set it to display the specified text by default and cannot be modified?

**Comment by campbell-m** [comment]
In your screenshot all your text is in English.   If you want it to appear in Chinese then you should either

(a) enable automatic language detection so that MRBS respects the language preferences of your browser by setting `$disable_automatic_language_changing = false;` in your config file.  (This is the default setting anyway.)  Or,
(b) force Chinese to be the language by setting `$override_locale = 'zh-CN';`.

Then for your prompt text should appear in Chinese.

**Comment by campbell-m** [comment]
> How can I set it to display the specified text by default and cannot be modified?

I am not sure what you mean by this?  Can you explain a bit more?

**Comment by wilia** [comment]
> > How can I set it to display the specified text by default and cannot be modified?
> 
> I am not sure what you mean by this? Can you explain a bit more?

1. For the Chinese language problem, I configure "$disable_automatic_language_changing = false;" and "$override_locale = 'zh-CN';", and then configure "$vocab_override['en']['entry.prompt_text']='test text ';" is invalid,
Picture see link：
Code：[https://imgtu.com/i/X5SMk9](https://imgtu.com/i/X5SMk9)
page：[https://imgtu.com/i/X5SJOO](https://imgtu.com/i/X5SJOO)

2. I want to set the newly added data column to display the content I specified to prompt the user how to fill in the 'full description', lock the writing function in the red box of the picture, and show that the multi-line content cannot be edited.
Picture see link：[https://imgtu.com/i/X5pxaQ](https://imgtu.com/i/X5pxaQ)

**Comment by wilia** [comment]
> `$vocab_override['en']['entry.prompt_text']='test text ';` does not work because your page is now in Chinese. You need `$vocab_override['zh-cn'][' entry.prompt_text']='中文';`.
> 
> > I want to set the newly added data column to display the content I specified to prompt the user how to fill in the 'full description'
> 
> Ah, now I understand what you are trying to do. I think it would be better to put your instructions in the label for the full description and/or use a placeholder prompt. I will add the ability to use a placeholder later. You can modify the label by setting `$vocab_override['zh-cn'][' fulldescription']='中文';`.

1. I followed your instructions to configure, as shown in the figure:[https://imgtu.com/i/X5KnxS](https://imgtu.com/i/X5KnxS)，But the add entry page still cannot be displayed normally:[https://imgtu.com/i/X5KkVA](https://imgtu.com/i/X5KkVA)
2. The configuration '$vocab_override['zh-cn'][' fulldescription']='Chinese';' should not be able to achieve my needs, my needs are as shown in the figure：[https://imgtu.com/i/X5KWse](https://imgtu.com/i/X5KWse)

**Comment by wilia** [comment]
> > my needs are as shown in the figure
> 
> Would a placeholder work? As in [this example](https://www.w3schools.com/tags/att_textarea_placeholder.asp)?

not work

**Comment by campbell-m** [comment]
No, that won't work.  But I could write the code later for you if you think that solution would work in principle.

**Comment by wilia** [comment]
> No, that won't work. But I could write the code later for you if you think that solution would work in principle.

ok，I’m really very grateful to you.

**Comment by campbell-m** [comment]
I've now [aa5b0a3d](https://github.com/meeting-room-booking-system/mrbs-code/commit/aa5b0a3d9474147f124f52feda37ef7991055924) the ability to set placeholder text in text fields on the edit_entry form.  You should download the complete set of MRBS files by following the green "Code" button on [this page](https://github.com/meeting-room-booking-system/mrbs-code).  Treat the download like an MRBS upgrade.

Once you have installed the latest code you can set the placeholder text by adding the following line to your MRBS config file:

`$vocab_override['zh-cn']['entry.description.placeholder'] = "中文";`

**Comment by wilia** [comment]
> I've now ([aa5b0a3d](https://github.com/meeting-room-booking-system/mrbs-code/commit/aa5b0a3d9474147f124f52feda37ef7991055924)) added the ability to set placeholder text in text fields on the edit_entry form. You should download the complete set of MRBS files by following the green "Code" button on [this page](https://github.com/meeting-room-booking-system/mrbs-code). Treat the download like an MRBS upgrade.
> 
> Once you have installed the latest code you can set the placeholder text by adding the following line to your MRBS config file:
> 
> `$vocab_override['zh-cn']['entry.description.placeholder'] = "中文";`

Thank you very much for your help, but I still have a few questions that I need to continue to consult with you...
1. After I updated the new code:[screenshot](https://imgtu.com/i/XoFzv9), in the 'add entry' page, the corresponding prompt text appears in the 'full description' fill-in box, as shown in the figure:[screenshot](https://imgtu.com/i/XokRq1),But when I change the prompt text in the code to Chinese,[screenshot](https://imgtu.com/i/XoAbfU), the text box of 'fulldescription' in the 'add entry' page does not display any prompt text,[screenshot](https://imgtu.com/i/XoAz01).Is it possible to call the translation in the language file instead in this configuration?

2. Since I also hope that the text of the prompt can be used as a template for users to copy and paste and modify,Can the 1-part or 2-part red frame position of the 'add entry' page be the same as the 3-part red frame position of the 'view entry' page, showing the prompt text?,[screenshot](https://imgtu.com/i/Xom6xO).

**Comment by campbell-m** [comment]
> ,But when I change the prompt text in the code to Chinese,[screenshot](https://imgtu.com/i/XoAbfU), the text box of 'fulldescription' in the 'add entry' page does not display any prompt text

That's because you should use lowercase 'cn' instead of uppercase 'CN', eg `$vocab_override['zh-cn']['entry.description.placeholder'] = "中文";`.

> Since I also hope that the text of the prompt can be used as a template for users to copy and paste and modify

Ah, now I understand a bit more.  Would it be better to have a default description for new bookings instead of having a placeholder?

**Comment by wilia** [comment]
> > But when I change the prompt text in the code to Chinese,[screenshot](https://imgtu.com/i/XoAbfU), the text box of 'fulldescription' in the 'add entry' page does not display any prompt text
> 
> That's because you should use lowercase 'cn' instead of uppercase 'CN', eg `$vocab_override['zh-cn']['entry.description.placeholder'] = "中文";`.
> 
> > Since I also hope that the text of the prompt can be used as a template for users to copy and paste and modify
> 
> Ah, now I understand a bit more. Would it be better to have a default description for new bookings instead of having a placeholder?

Thank you for your reply，
Regarding the first point, I tried to change '$vocab_override['zh-cn']['entry.description.placeholder'] = "Chinese";' to '$vocab_override['zh-cn']['entry.description .placeholder'] = "Chinese";',[screenshot](https://imgtu.com/i/XTkGpF), the 'full description' of the 'add entry' page is still not displayed[screenshot](https://imgtu.com/i/XTkcXd)；

The second point, because I want to create a 'full description' filling template, so that users can modify the filling content based on the template, so I still hope that users can directly copy the template content. The disadvantage of using a placeholder is that when the user starts editing 'full description' It will no longer be displayed at the time, which will cause the user not to fill in the specified template style.

**Comment by campbell-m** [comment]
>  the 'full description' of the 'add entry' page is still not displayed

What have you got `$override_locale` set to?

> The second point, because I want to create a 'full description' filling template, so that users can modify the filling content based on the template, so I still hope that users can directly copy the template content. The disadvantage of using a placeholder is that when the user starts editing 'full description' It will no longer be displayed at the time, which will cause the user not to fill in the specified template style.

Yes, that's why I suggested a default description instead of a placeholder.  With a default description a new booking form will automatically be filled with that text and then the user can edit it.

**Comment by wilia** [comment]
> What have you got `$override_locale` set to?

I set '$override_locale = 'zh-cn'', '$override_locale = 'zh-CN'' plus '$disable_automatic_language_changing = false;'[screenshot](https://imgtu.com/i/XTnp36), have no effect[screenshot](https://imgtu.com/i/XTng8x),

> Yes, that's why I suggested a default description instead of a placeholder. With a default description a new booking form will automatically be filled with that text and then the user can edit it.

How can I configure the default description to automatically fill in the text?

**Comment by campbell-m** [comment]
> How can I configure the default description to automatically fill in the text?

`$default_description = "中文";`

**Comment by campbell-m** [comment]
But if you have a template for your description it might be better to split that template out into separate custom fields.   For example if your template is

`
Number of people:
Number of lunches:
`
Then create two custom fields for "number of people" and "number of lunches".

**Comment by wilia** [comment]
thank you very much for your reply.

> > How can I configure the default description to automatically fill in the text?
> 
> `$default_description = "中文";`

Is this code configured in the description module in 'add_entry.php'? doesn't work in config_inc.php，
Moreover, if you directly fill in 'Chinese' in the configuration file config.inc.php or any php source code page, it will not take effect. It can only take effect by calling Chinese through a command similar to get_vocab('description') in ADD_entry.php.

> But if you have a template for your description it might be better to split that template out into separate custom fields. For example if your template is
> 
> `Number of people: Number of lunches:` Then create two custom fields for "number of people" and "number of lunches".

Are the two fields established in the 'entry table' table in mysql? How to set up the call in code?

**Comment by campbell-m** [comment]
> Is this code configured in the description module in 'add_entry.php'? doesn't work in config_inc.php，
Moreover, if you directly fill in 'Chinese' in the configuration file config.inc.php or any php source code page, it will not take effect. It can only take effect by calling Chinese through a command similar to get_vocab('description') in ADD_entry.php.

It should go in config.inc.php.  (By the way, there isn't a file called add_entry.php - I am not sure why you have one.)  I have just tested it on my site and it works OK for me.

> Are the two fields established in the 'entry table' table in mysql? How to set up the call in code?

You don't need to modify the MRBS code. You just need to add a custom field to the entry and repeat tables and MRBS will automatically handle it. See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document.

**Comment by wilia** [comment]
> It should go in config.inc.php. (By the way, there isn't a file called add_entry.php - I am not sure why you have one.) I have just tested it on my site and it works OK for me.
> 
> > Are the two fields established in the 'entry table' table in mysql? How to set up the call in code?
> 
> You don't need to modify the MRBS code. You just need to add a custom field to the entry and repeat tables and MRBS will automatically handle it. See the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document.

Test that it can work, my text encoding in the configuration file has not been changed to utf8, which makes it impossible to recognize Chinese. After adjustment, it can work normally,thank you very much for your help.

**Comment by wilia** [comment]
I have another question, that is, the new version of 'http://localhost\index.php' page does not display the content of 'full description' after the reserved conference room, how can I make it display it? I didn't find the feature switch in 'systemdefaults.inc.php'

**Comment by campbell-m** [comment]
> I have another question, that is, the new version of '[http://localhost\index.php](http://localhost%5Cindex.php/)' page does not display the content of 'full description' after the reserved conference room, how can I make it display it? I didn't find the feature switch in 'systemdefaults.inc.php'

Do you mean display the full description on the calendar view?  If so, MRBS has never displayed it, except when you hover over the slot.  Did you have a modified version of MRBS before?

> In 'config.inc.php', the 'fun.se' account in the AD domain is configured as an administrator, and the code is: $mrbs_admin = "fun.se". After logging in to the MRBS system, this account has no administrator rights. How to adjust?

Set `$auth['admin'][] = 'fun.se';`.

> How to enable MRBS local account after AD domain is configured

Sorry, I don't understand.  Could you explain some more please?

By the way, in future could you create a new issue for each new topic please?  Thanks.

**Comment by wilia** [comment]
> > I have another question, that is, the new version of '[http://localhost\index.php](http://localhost%5Cindex.php/)' page does not display the content of 'full description' after the reserved conference room, how can I make it display it? I didn't find the feature switch in 'systemdefaults.inc.php'
> 
> Do you mean display the full description on the calendar view? If so, MRBS has never displayed it, except when you hover over the slot. Did you have a modified version of MRBS before?
> 
> > In 'config.inc.php', the 'fun.se' account in the AD domain is configured as an administrator, and the code is: $mrbs_admin = "fun.se". After logging in to the MRBS system, this account has no administrator rights. How to adjust?
> 
> Set `$auth['admin'][] = 'fun.se';`.
> 
> > How to enable MRBS local account after AD domain is configured
> 
> Sorry, I don't understand. Could you explain some more please?
> 
> By the way, in future could you create a new issue for each new topic please? Thanks.

Ok, let me sort it out and create a new issue again
