### ISSUE TITLE
Issues related to administrator rights after MRBS is associated with an AD domain

### ISSUE THREAD

**Issue by wilia** [meeting-room-booking-system/mrbs-code#42]
**Describe the problem you're facing/question you have**
thank you for your help,I have the following questions for help:
1.In 'config.inc.php', configure the 'fun.se' account in the AD domain as an administrator, the code is: $mrbs_admin = "fun.se" or $auth['admin']='fun.se '; After logging in to the MRBS system, the account does not have administrator rights. How to adjust?

2.The new version of the mrbs calendar page ''http://localhost\index.php'' cannot see the complete description of the reserved meeting, The mrbs1.5.0 that our current network is using shows this content. I don't know if it is the colleague who has left the previous period. Some adjustments have been made, [screenshots](https://imgtu.com/i/XHS98H)

3.After mrbs is configured with the AD domain, the admin administrator account created locally by mrbs cannot log in. Based on the first problem, the AD domain account cannot be set as an administrator, so I would like to ask if it is possible to enable local management while enabling the AD domain. member account admin?

**Browser details (please complete the following information):**
 - OS: [e.g. Windows 2008R2]
 - Browser :[e.g. chrome]
 - Version [e.g. 49.0]

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.10.0]
 - Web server: [e.g. Apache 2.4.37]
 - OS: [e.g. Windows 2008R2]
 - PHP version: [e.g. 7.3.1]
 - Database used: [e.g. MySQL 5.7.24]

**Comment by campbell-m** [comment]
(1) and (3).  Are you using LDAP authentication?  Have you got `$auth['type'] = 'ldap';`?

(2).  Could you raise this as a separate issue please?  It's a completely different topic.

**Comment by wilia** [comment]
> (1) and (3). Are you using LDAP authentication? Have you got `$auth['type'] = 'ldap';`?

Yes, I set $auth['type'] = 'ldap';, now I can log in mrbs with AD account normally
