### ISSUE TITLE
Issue with calendar view showing full description of scheduled meetings

### ISSUE THREAD

**Issue by wilia** [meeting-room-booking-system/mrbs-code#43]
**Describe the problem you're facing/question you have**
thank you for your help,I have the following questions for help:
The new version of the mrbs calendar page ''http://localhost\index.php'' cannot see the complete description of the reserved meeting, but the mrbs 1.5.0 we use again can display it. I don't know if it is the colleague who has left the previous period. Some adjustments have been made, [screenshots](https://imgtu.com/i/XHS98H)

**Browser details (please complete the following information):**
 - OS: [e.g. Windows 2008R2]
 - Browser :[e.g. chrome]
 - Version [e.g. 49.0]

**Server details (please complete the following information):**
 - MRBS version [e.g. 1.10.0]
 - Web server: [e.g. Apache 2.4.37]
 - OS: [e.g. Windows 2008R2]
 - PHP version: [e.g. 7.3.1]
 - Database used: [e.g. MySQL 5.7.24]

**Additional context**

**Comment by campbell-m** [comment]
You need to edit the function prepare_entry() in mrbs_sql.inc and at line 12 add the line

`    $entry['name'] .= ' ' . $entry['description'];`

**Comment by wilia** [comment]
> You need to edit the function prepare_entry() in mrbs_sql.inc and at line 12 add the line
> 
> ` $entry['name'] .= ' ' . $entry['description'];`

I followed the instructions to configure mrbs_sql.inc, [screenshot](https://fastly.jsdelivr.net/gh/chen-xing/figure_bed_02/cdn/20220617094652464.png), but it doesn't work

**Comment by campbell-m** [comment]
You haven't added the line but replaced all the existing code in `prepare_entry()` with that line.   The function should look like this:

`
function prepare_entry(array $entry) : array
{
  global $is_private_field, $show_registration_level, $auth;

  $entry['name'] .= ' ' . $entry['description'];

  // Add in the registration level details
  if ($show_registration_level && $entry['allow_registration'])
  {
  // etc.
`

**Comment by wilia** [comment]
> prepare_entry()

Is it replaced in 'mrbs_sql.inc'? I didn't find any prepare_entry() on this page

**Comment by campbell-m** [comment]
Oh, sorry, my fault!  I meant functions_table.inc.

**Comment by wilia** [comment]
> Oh, sorry, my fault! I meant functions_table.inc.

It works, but the full description is directly following the brief description, is it possible to make him start on a new line?

**Comment by campbell-m** [comment]
In that case, instead of the previous edit, case replace line 370 of functions_table.inc which is

```
        $html .= htmlspecialchars($booking['name']) . '</a>';
```

with

```
        $html .= htmlspecialchars($booking['name']) . "<br>" . htmlspecialchars($booking['description']) . '</a>';
```

**Comment by wilia** [comment]
> In that case, instead of the previous edit, case replace line 370 of functions_table.inc which is

It works fine, thank you very much for your help, love you
