### ISSUE TITLE
Issues related to administrator rights after MRBS is associated with an AD domain

### ISSUE THREAD

**Issue by wilia** [meeting-room-booking-system/mrbs-code#44]
Describe the problem you're facing/question you have
Sorry, my last issue was wrong, what I want to say is that my mrbs can log in with the ad domain account normally, but even if I have set the account [fun.se] <account not real> through '$mrbs_admin = "fun. se"' or '$auth["admin"]="fun.se ";' is set as the administrator, but when I officially log in to the [fun.se] account in mrbs, [fun.se] is still a normal account

After mrbs is configured with the AD domain, the admin administrator account created locally by mrbs cannot log in. Based on the first problem, the AD domain account cannot be set as an administrator, so I would like to ask if it is possible to enable local management while enabling the AD domain. member account admin?

Browser details (please complete the following information):

OS: [e.g. Windows 2008R2]
Browser :[e.g. chrome]
Version [e.g. 49.0]
Server details (please complete the following information):

MRBS version [e.g. 1.10.0]
Web server: [e.g. Apache 2.4.37]
OS: [e.g. Windows 2008R2]
PHP version: [e.g. 7.3.1]
Database used: [e.g. MySQL 5.7.24]

Since I am not in the company now, the original configuration code cannot be displayed, but it is basically the same as the following code：

> $mrbs_admin = "fun.se"
> 
> $auth["session"]="php";
> $auth["type"]="ldap";
> $cookie_path_override='/mrbs/';
> $auth["realm"]="mrbs";
> $auth["admin"][]="fun.se";
> $ldap_host="X.X.X.X";
> $ldap_port=389;
> $ldap_v3=true;
> $ldap_tls=false;
> $ldap_base_dn="OU=my-department,DC=XXX,DC=com,DC=cn"; //此OU下所有User都可以使用
> $ldap_user_attrib="cn";
> $ldap_dn_search_attrib="sAMAccountName";
> $ldap_dn_search_dn="CN=my-account,,OU=my-department,DC=XXX,DC=com,DC=cn"; 
> $ldap_dn_search_password="password";

**Comment by campbell-m** [comment]
I'm not quite sure what you are asking.  If you are asking whether it is possible to have both local and LDAP authentication then you could do this by having two different installations of MRBS configured to use the same database but different authentication types.

**Comment by jberanek** [comment]
Perhaps @wilia is wanting to specify LDAP-authenticated users as administrators by setting something like:

~~~
$auth["admin"][] = "myusername";
~~~

Was this something that the LDAP auth scheme used to be able to do? Looking back at MRBS 1.7.4 (version picked randomly), it was...

https://github.com/meeting-room-booking-system/mrbs-code/blob/mrbs-1_7_4/web/auth/auth_ldap.inc#L685

**Comment by jberanek** [comment]
So...presumably that functionality got lost when we went from auth_ldap.inc to the class?

**Comment by wilia** [comment]
> Perhaps @wilia is wanting to specify LDAP-authenticated users as administrators by setting something like:
> 
> ```
> $auth["admin"][] = "myusername";
> ```
> 
> Was this something that the LDAP auth scheme used to be able to do? Looking back at MRBS 1.7.4 (version picked randomly), it was...
> 
> https://github.com/meeting-room-booking-system/mrbs-code/blob/mrbs-1_7_4/web/auth/auth_ldap.inc#L685

The ad function was not enabled in the old version, and only after the upgrade of mrbs1.10.0 did we start to consider associating AD domain controllers

**Comment by campbell-m** [comment]
> So...presumably that functionality got lost when we went from auth_ldap.inc to the class?

No, the functionality's still there.  If `$ldap_admin_group_dn` is not defined then the level is taken from `$auth['admin']`, otherwise it is set according to whether the user is in `$ldap_admin_group_dn`.

**Comment by campbell-m** [comment]
> After the AD domain is enabled, the administrator account created by the local mrbs system cannot log in, and use $auth["admin"][] = "my-admin-user" in config.inc.php;[screenshot](https://fastly.jsdelivr.net/gh/chen-xing/figure_bed_02/cdn/20220617100113190.png), I set my AD domain account as administrator, but I can't get administrator rights

I am still not clear.  Are you saying that when using LDAP authentication (a) the admin user cannot login at all or (b) that the admin user can login but isn't granted administrator rights?

**Comment by wilia** [comment]
> that the admin user can login but isn't granted administrator rights

that the admin user can login but isn't granted administrator rights

**Comment by campbell-m** [comment]
Have you got `$ldap_admin_group_dn` set in your config file or not?

**Comment by wilia** [comment]
> Have you got `$ldap_admin_group_dn` set in your config file or not?

I did not configure this, because there are multiple administrator departments, and not all other staff in each department are administrators

**Comment by campbell-m** [comment]
> No, the functionality's still there. If $ldap_admin_group_dn is not defined then the level is taken from $auth['admin'], otherwise it is set according to whether the user is in $ldap_admin_group_dn.

I've just test this and it works as expected.

**Comment by campbell-m** [comment]
> I did not configure this

Good, that is correct.  However I don't understand why `$auth["admin"][] = "my-admin-user";` is not working.  Perhaps it's a Chinese character issue - I will do some more testing.

**Comment by campbell-m** [comment]
No, it's not a Chinese character issue.  I have successfully tested "会议室预约系统" on my system.

**Comment by campbell-m** [comment]
Are you sure that when you have set `$auth["admin"][] = "my-admin-user";` then "my-admin-user" is the username (not display name) of the admin user logging in?

**Comment by wilia** [comment]
> No, it's not a Chinese character issue. I have successfully tested "会议室预约系统" on my system.

I set it to $auth["admin"][] = "fun.se"; the account I use when logging in is also fun.se not the display name

**Comment by campbell-m** [comment]
> No, it's not a Chinese character issue. I have successfully tested "会议室预约系统" on my system.

It's not connected to this problem, but in the course of my testing I found another problem which I have fixed in [f17e3c4](https://github.com/meeting-room-booking-system/mrbs-code/commit/f17e3c439eb9db2a87b781b190a79e14a9a9d373).

**Comment by campbell-m** [comment]
[Auth.php.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/8926614/Auth.php.txt)

Can you replace the file lib/MRBS/Auth/Auth.php with the attached diagnostic file and let me know the output when you try and login as fun.se?  Note that you will need to rename the file from Auth.php.txt to Auth.php as GitHub won't accept .php extensions.

It should produce output in the browser like

string(6) "fun.se" array(3) { [0]=> string(9) "127.0.0.1" [1]=> string(13) "administrator" [2]=> string(6) "fun.se" } NULL

**Comment by wilia** [comment]
> [Auth.php.txt](https://github.com/meeting-room-booking-system/mrbs-code/files/8926614/Auth.php.txt)
> 
> Can you replace the file lib/MRBS/Auth/Auth.php with the attached diagnostic file and let me know the output when you try and login as fun.se? Note that you will need to rename the file from Auth.php.txt to Auth.php as GitHub won't accept .php extensions.
> 
> It should produce output in the browser like
> 
> string(6) "fun.se" array(3) { [0]=> string(9) "127.0.0.1" [1]=> string(13) "administrator" [2]=> string(6) "fun.se" } NULL

php output result is：


 string(9) "付洓" array(5) { [0]=> string(9) "127.0.0.1" [1]=> string(13) "administrator" [2]=> string(22) "fun.se@test.com.cn" [3]=> string(8) "my-admin-user2" [4]=> string(8) "my-admin-user3" } string(95) "OU=02_项目组,OU=01_公司名,OU=00_域用户,dc=domain,dc=domain,dc=domain,dc=com"

**Comment by campbell-m** [comment]
Thanks.  I can see two problems:

1. You have `$ldap_admin_group_dn` set somewhere, either in systemdefaults.inc.php or config.inc.php - please check.
2. Even when you comment that out it still won't work because you are logging in as "付洓" but you have "fun.se" configured as an admin in the config file.  You either need to login as fun.se or else set `$auth["admin"][] = "付洓";`.

**Comment by campbell-m** [comment]
> but you have "fun.se" configured as an admin in the config file. You either need to login as fun.se

In fact you have "fun.se@test.com.cn" configured in the config file, so you would need to login as that.

**Comment by wilia** [comment]
> Thanks. I can see two problems:
> 
> 1. You have `$ldap_admin_group_dn` set somewhere, either in systemdefaults.inc.php or config.inc.php - please check.
> 2. Even when you comment that out it still won't work because you are logging in as "付洓" but you have "fun.se" configured as an admin in the config file.  You either need to login as fun.se or else set `$auth["admin"][] = "付洓";`.

Perfect, now this account has administrator privileges, thank you very much for your help, You are awesome
