### ISSUE TITLE
How to add multi-select function

### ISSUE THREAD

**Issue by wilia** [meeting-room-booking-system/mrbs-code#45]
**Describe the problem you're facing/question you have**
I want to add a multi-option to the edit_entry interface, [screenshot](https://fastly.jsdelivr.net/gh/chen-xing/figure_bed_02/cdn/20220617195421226.png), but I refer to the section "ADDING EXTRA COLUMNS TO THE DATABASE TABLES" in the INSTALL document. The branch field is created in the mrbs_entry and mrbs_repeat tables of mysql, [screenshot](https://fastly.jsdelivr.net/gh/chen-xing/figure_bed_02/cdn/20220617195444720.png), in config.inc .php did the corresponding configuration,  [screenshot](https://fastly.jsdelivr.net/gh/chen-xing/figure_bed_02/cdn/20220617195517617.png)，configure the screenshot, but the actual result is: [screenshot](https://fastly.jsdelivr.net/gh/chen-xing/figure_bed_02/cdn/20220617195745911.png)，

Browser details (please complete the following information):

OS: [e.g. Windows 2008R2]
Browser :[e.g. chrome]
Version [e.g. 49.0]
Server details (please complete the following information):

MRBS version [e.g. 1.10.0]
Web server: [e.g. Apache 2.4.37]
OS: [e.g. Windows 2008R2]
PHP version: [e.g. 7.3.1]
Database used: [e.g. MySQL 5.7.24]
 - Database used: [e.g. MySQL 8.0.26]

**Comment by campbell-m** [comment]
The problem is that you have defined the branch column as a TINYINT(4) and so MRBS will treat it as a checkbox.  You need to define it as an INT, CHAR or VARCHAR.

**Comment by wilia** [comment]
> The problem is that you have defined the branch column as a TINYINT(4) and so MRBS will treat it as a checkbox. You need to define it as an INT, CHAR or VARCHAR.

When I set it to int, char, VARCHAR, a dropdown box that can only display a single option，[screenshot](https://imgtu.com/i/Xj9NVJ). How can I configure it so that it can be set to the following effect:
1) single option，[screenshot](https://imgtu.com/i/Xj9DxK),
2) multiple options (can multiple options be checked at the same time?)[screenshot](https://imgtu.com/i/Xj9RIA),

**Comment by campbell-m** [comment]
If you want a checkbox you need a TINYINT.  If you want a drop-down `<select>` element with one option selectable, then you need a CHAR or VARCHAR column and to set `$select_options` in your config file - see systemdefaults.inc.php for more details.

A `<select>` element with multiple options selectable isn't possible at the moment.  Instead you could have multiple columns, each being a TINYINT.

**Comment by wilia** [comment]
> If you want a checkbox you need a TINYINT. If you want a drop-down `<select>` element with one option selectable, then you need a CHAR or VARCHAR column and to set `$select_options` in your config file - see systemdefaults.inc.php for more details.
> 
> A `<select>` element with multiple options selectable isn't possible at the moment. Instead you could have multiple columns, each being a TINYINT.

I see, thanks a lot for your help
