### ISSUE TITLE
Date format is locale specific

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#450]
Now date formats are defined in systemdefaults.inc.php
However they are locale specific setting and should be defined in lang.*.

Current implementation is not a good idea if the company has users who use diffrent languages.

Reported by: t-matsuu

Original Ticket: [mrbs/bugs/241](https://sourceforge.net/p/mrbs/bugs/241)

**Comment by campbell-m** [comment]
MRBS now uses the IntlDateFormatter class.
