### ISSUE TITLE
edit_users.php uses always md5

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#482]
edit_users.php encrypts passwords always using md5 regardless password_format configuration.

Reported by: *anonymous

Original Ticket: [mrbs/bugs/274](https://sourceforge.net/p/mrbs/bugs/274)

**Comment by campbell-m** [comment]
`$auth['db_ext']['password_format']` now supports any algorithm supported by the PHP hash() function.
