### ISSUE TITLE
Not able to add users in 1.4.10

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#491]
I am using:

$auth["session"] = "host";
$auth["type"] = "db";

Host authentication takes in session uid from SAML - this works fine on every other part of version 1.4.10.  Then authenticates based on uid=username on the database.  I have this working perfectly with 1.4.09.

In version 1.4.10 edit_users.php I can add the first user and update that user except for its rights.  When I try to add another user it goes through the entire process, with no php errors but never adds the user to db - again no errors.  When I take the edit_users.php version 1.4.09 it allows me to add or edit new users based on perms... albeit with a lot of warnings because it looks like there were a lot of changes to the file in new version.  

thanks
Dave

Reported by: *anonymous

Original Ticket: [mrbs/bugs/284](https://sourceforge.net/p/mrbs/bugs/284)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
