### ISSUE TITLE
Multiple days in day view 30-90

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#494]
I am trying to develop a grid view for all rooms in an area.  So basically it looks just like the days view (with rooms at top) but with a lot of days - I would like to do somewhere between 30 and 90.  Has anyone done this?  

Also if the powers that be can start me off on the right track of exploding the days down the left hand side (using the function day_table_innerhtml or whatever they feel is the right way) I will gladly work on the formatting of the large amount of data and css.  

thanks in advance

Reported by: *anonymous

Original Ticket: [mrbs/bugs/286](https://sourceforge.net/p/mrbs/bugs/286)

**Comment by campbell-m** [comment]
Closed as now very old.
