### ISSUE TITLE
"Back"-Button on edit_entry_handler points to the wrong page

### ISSUE THREAD

**Issue by being-peace** [meeting-room-booking-system/mrbs-code#5]
**What I did:**
 * edit_entry with a conflict --> Save
 * edit_entry_handler shows conflict
 * I press "Back" button
 
**What I expected:**
 * I come back to the edit_entry page, at best with the fields filled as before the Save

**What I have seen:**
 * I come back to the index. This gave users even the impression that the editing was saved. :-1: 
 
If I use the browser´s "Back" button, I come to back edit_entry, but as it is not cached, all fields are cleared. This is suboptimal, but better than to the index.

So, is there a special reason, why not to use the browser history? https://www.w3schools.com/jsref/met_his_back.asp

**Sidenote:** Even better UI would be, if it is not possible to submit an entry with a conflict (if it´s not a repeated one with the checkbox for "ignore conflicts" is on).

**Comment by jberanek** [comment]
See #12
