### ISSUE TITLE
When the administrator enters the pending.php page to approve the meeting, an E_warning error occurs

### ISSUE THREAD

**Issue by wilia** [meeting-room-booking-system/mrbs-code#50]
**Describe the problem you're facing/question you have**
When the administrator enters the pending.php page to approve the meeting, an E_warning error occurs.

Browser details (please complete the following information):

OS: [e.g. Windows 2008R2]
Browser :[e.g. chrome]
Version [e.g. 49.0]
Server details (please complete the following information):

MRBS version [e.g. 1.10.0]
Web server: [e.g. Apache 2.4.37]
OS: [e.g. Windows 2008R2]
PHP version: [e.g. 7.3.1]
Database used: [e.g. MySQL 5.7.24]

error log：

> E_WARNING in C:\wamp64\www\mrbs\lib\MRBS\Auth\Auth.php at line 111
> array_column() expects parameter 1 to be array, bool given
> MRBS GET: Array
> (
>     [view] => day
>     [page_date] => 2022-06-27
>     [area] => 14
>     [room] => 8
> )
> MRBS POST: Array
> (
> )
> MRBS SESSION: Array
> (
>     [csrf_token] => 13830f83414b4c1dae91199b2cdd48462d4e537c22a9f3171b9fce2626f1fecb
>     [user] => MRBS\User Object
>         (
>             [username] => 测试用户
>             [display_name] => 测试用户
>             [email] => test_user@test.com
>             [level] => 2
>             [data:protected] => Array
>                 (
>                 )
> 
>         )
> 
> )

![会议系统pending php页面](https://user-images.githubusercontent.com/3975384/175859163-ccfcf51f-13c5-4dfb-9033-9c272328b805.png)

**Comment by campbell-m** [comment]
There are two problems here: (1) the error handling in `getDisplayName()` and (2) the original error.

Could you please

(a) set `$debug = true;` in your config file.  This will give more information.
(b) post your ldap_debug trace which should give a clue to the original error.

Please remember to remove any confidential information (or else you can email the data to me).

**Comment by wilia** [comment]
> There are two problems here: (1) the error handling in `getDisplayName()` and (2) the original error.
> 
> Could you please
> 
> (a) set `$debug = true;` in your config file. This will give more information. (b) post your ldap_debug trace which should give a clue to the original error.
> 
> Please remember to remove any confidential information (or else you can email the data to me).

The log generated after setting `$debug = true;` is as follows
[php_error.log](https://github.com/meeting-room-booking-system/mrbs-code/files/8989978/php_error.log)

**Comment by campbell-m** [comment]
> The log generated after setting $debug = true; is as follows

Thanks.  And what output do you get in the browser?  You should get a stack trace.

**Comment by campbell-m** [comment]
I've now improved the error handling.  You'll still get an error (this time an E_USER_NOTICE error instead of an E_WARNING error, or an uncaught exception using PHP 8.2), but that's to draw your attention to the fact that the LDAP search is failing.  I think that's probably due to an error in your LDAP configuration, but I'm not sure at the moment exactly what the error is.

**Comment by wilia** [comment]
> I've now improved the error handling. You'll still get an error (this time an E_USER_NOTICE error instead of an E_WARNING error, or an uncaught exception using PHP 8.2), but that's to draw your attention to the fact that the LDAP search is failing. I think that's probably due to an error in your LDAP configuration, but I'm not sure at the moment exactly what the error is.

After I re-downloaded and deployed the new complete package, the pending.php page did not report an error message.
View the PHP error log file as follows:
[php_error.log](https://github.com/meeting-room-booking-system/mrbs-code/files/8996535/php_error.log)

My AD domain controller configuration is as follows:

> $auth["session"]="php";
> $auth["type"]="ldap";
> $cookie_path_override='/mrbs/';
> $auth["realm"]="mrbs";
> $auth["admin"][]="张先生";
> $ldap_host="www.test.com";
> $ldap_port="389";
> $ldap_v3=true;
> $ldap_tls=false;
> $ldap_get_user_email = false;
> $ldap_base_dn="OU=001_测试环境,DC=www,DC=test,DC=com";
> $ldap_user_attrib="cn";
> $ldap_dn_search_attrib="sAMAccountName";
> $ldap_dn_search_dn="CN=赵某某,OU=002_IT技术部,OU=001_测试环境,DC=www,DC=test,DC=com";
> $ldap_dn_search_password="MyPassword";
> $ldap_debug=true;

Now access the interface:
![内网通截图20220628081534](https://user-images.githubusercontent.com/3975384/176061187-73f670ff-fc37-4d7f-85ed-587ab5ff6f4b.png)

**Comment by campbell-m** [comment]
Try setting

```
$ldap_user_attrib = "sAMAccountName";  // instead of "cn"
$ldap_name_attrib = "cn";
```

**Comment by wilia** [comment]
> Try setting
> 
> ```
> $ldap_user_attrib = "sAMAccountName";  // instead of "cn"
> $ldap_name_attrib = "cn";
> ```
Change the setting to $ldap_user_attrib = "sAMAccountName"; // instead of "cn"
$ldap_name_attrib = "cn"; After the command, the administrator account has no administrator rights after logging in, and now reset it to $ldap_user_attrib = "cn"; everything is normal, no error is reported

**Comment by campbell-m** [comment]
Although you may not be seeing an error when you set the user attribute to "cn", there is one and MRBS will be operating very slowly.  It will be fetching user details one by one in separate LDAP searches, instead of fetching all the users' details in one search.

You should set the user attribute to "sAMAccountName". You should then change your `$auth['admin']` settings so that they are using the username instead  of the common name.

**Comment by wilia** [comment]
> Although you may not be seeing an error when you set the user attribute to "cn", there is one and MRBS will be operating very slowly. It will be fetching user details one by one in separate LDAP searches, instead of fetching all the users' details in one search.
> 
> You should set the user attribute to "sAMAccountName". You should then change your `$auth['admin']` settings so that they are using the username instead of the common name.

Now I get it!
I have made the corresponding changes, thank you very much for your help
