### ISSUE TITLE
MRBS V.1.4.11 Email not send (When use PHP V. higher than 5.2.6)

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#530]
Thank you very much for the best free system.
I'm newbie php code.
In my case all feature is work good but I found some problem about sending Email for approve.

I test setting following (PHP higher than 5.2.6)
$smtp_settings['host'] = 'mail.mycompany.com';  // SMTP server
$smtp_settings['port'] = 25;           // SMTP port number
$smtp_settings['auth'] = TRUE;        // Whether to use SMTP authenticatio
$smtp_settings['username'] = 'xxxxxx';       // Username (if using authentication)
$smtp_settings['password'] = 'xxxxxx';       // Password (if using authentication)

- when set auth is TRUE system cannot send any Email. (When booking web is error but can book normal when refresh page)

- when set auth is FALSE system can send email but can send only domain the same " $smtp_settings['host'] mail.mycompany.com " cannot send to other domain.

It work fine on
MRBS 1.4.11
PHP:	5.2.6
apache 2.2.8

But my host is 
MRBS 1.4.11	
MySQL 5.1.69
PHP:	5.3.3
have the same problem too. (Email not send)

How to config to use send mail in normally

I need your help.
Thank you so much.
Best regards

Reported by: *anonymous

Original Ticket: [mrbs/bugs/322](https://sourceforge.net/p/mrbs/bugs/322)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
