### ISSUE TITLE
JS Datepicker failing to acquire timezone.

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#604]
I have a new 1.7.0 installation and booking single entries works, but repeats fail because there is no datepicker for the repeat end date. (Reports also have no datepickers.) 

I've double-checked the config.inc.php file and the databsae, and timezones are set correctly.

mysql> select timezone from mrbs_zoneinfo;
+------------------+
| timezone         |
+------------------+
| America/New_York |
+------------------+
1 row in set (0.00 sec)

mysql> select timezone from mrbs_area;
+------------------+
| timezone         |
+------------------+
| America/New_York |
+------------------+
1 row in set (0.00 sec)

Is there a way to remove the js_hidden tag and force MRBS to show the old datepicker when the javascript one fails?

Installation: Centos 6, Remi PHP 5.6.32. Except for config.inc.php, all files are symlinks to /usr/local/share/mrbs/web/*

Reported by: *anonymous

Original Ticket: [mrbs/bugs/399](https://sourceforge.net/p/mrbs/bugs/399)

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
