### ISSUE TITLE
Cannot unset InvalidTypes in a resource.

### ISSUE THREAD

**Issue by fourofspades** [meeting-room-booking-system/mrbs-code#61]
**Describe the bug**
Once a invalid resource type has been set, there doesn't appear to be a way to unset it, only change one.

**To Reproduce**
1. in Rooms, select a resource.
2. Select an Invalid type
3. Select Save
4. Open up resource and try to clear all invalid types.

**Expected behavior**
Invalid types can be unset.

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 108

**Server details (please complete the following information):**
 - MRBS version MRBS 1.10.0
 - Web server: IIS10
 - OS: Windows
 - PHP version: 8.1.13
 - Database used: PostgreSQL 10.23

**Comment by campbell-m** [comment]
You need to CTRL and click on the type to deselect it.

**Comment by fourofspades** [comment]
Many thanks.  That fixed it.   Perhaps a tooltip or something might be useful here to mention that?

**Comment by campbell-m** [comment]
Good idea.
