### ISSUE TITLE
edit_users.php?datatable=1 fails to show user lists

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#610]
Recently updated from mrbs 1.4.11 to 1.7.1 and using php 7.2.3 with MySQL 5.7.21. The "?datatable=1" is automatically added to the "Users List" link at the end. From what I can tell, this is intentional, but it causes the list of users to not populate. If I remove that addition such that it is just "edit_users.php" instead of "edit_users.php?datatable=1" the table populates perfectly fine.

Nothing game-breaking in my opinion, but figured I'd let you guys know.

If it helps, I'm using the latest Google Chrome version, not sure if it's a browser thing.

Reported by: *anonymous

Original Ticket: [mrbs/bugs/405](https://sourceforge.net/p/mrbs/bugs/405)

**Comment by campbell-m** [comment]
Closed following no response.
