### ISSUE TITLE
LDAPS + Samba4

### ISSUE THREAD

**Issue by Galvy** [meeting-room-booking-system/mrbs-code#63]
When I enable LDAPS isted of LDAP i see this message:
MRBS DEBUG] MRBS\\Auth\\AuthLdap->action(754): initial bind failed: Can't contact LDAP server, 
Whiy out "S" ldap auth work with out problem
I have a valid self signe certificate in my AD 
https://wiki.samba.org/index.php/Configuring_LDAP_over_SSL_(LDAPS)_on_a_Samba_AD_DC

 - OS: Debian 11 fresh install

**Server details (please complete the following information):**
 - MRBS 1.11.0
 - Web server: Apache/2.4.54
 - OS: Debian 11 clean (installed today)
 - PHP 7.4.33

**Comment by jberanek** [comment]
The self-signed certificate is the problem. PHP's LDAP extension won't trust a self-signed certificate unless you configure OpenSSL appropriately. See https://www.php.net/manual/en/function.ldap-connect.php#36156 for a worked example.

**Comment by Galvy** [comment]
> The self-signed certificate is the problem. PHP's LDAP extension won't trust a self-signed certificate unless you configure OpenSSL appropriately. See https://www.php.net/manual/en/function.ldap-connect.php#36156 for a worked example.

Thanks!!
now works.
I followed this post https://andreas.heigl.org/2020/01/31/handle-self-signed-certificates-with-phps-ldap-extension/
I hope it will be useful to someone else.
