### ISSUE TITLE
checklang.php copies one first line of multiline strings

### ISSUE THREAD

**Issue by Klap-in** [meeting-room-booking-system/mrbs-code#65]
**Describe the bug**
If enabled, the checklang.php copies the missing strings in the incomplete language file. However, the copy action considers only the first line, not all the lines of localized string.

**To Reproduce**
1. Run checklang.php?lang=nl
2. Check e.g. the strings with the keys `confirm_rep_end_date` or `edit_entry_nonexistent_room`.
3. Only first line is copied

**Expected behavior**
 - no broken strings, which could potentially break the interface.

**Screenshots**
 - none

**Browser details (please complete the following information):**

**Server details (please complete the following information):**
 - MRBS version 1.11.0
 - Database | MariaDB Server 10.3.28-MariaDB
 - Systeem | Linux jerry 4.18.0-372.9.1.1.lve.el8.x86_64 # 1 SMP Tue May 24 07:49:22 EDT 2022 x86_64
 - Server software | Apache/2.4
 - PHP | 7.4.30, maybe I runned this script still on 7.2

**Additional context**
none

**Comment by Klap-in** [comment]
At first sight, the script did skip also the strings after the strings related to the Entry types, the last five strings.

**Comment by campbell-m** [comment]
Thanks for spotting this.  Fixed by https://github.com/meeting-room-booking-system/mrbs-code/pull/68.
