### ISSUE TITLE
no from date on search page results in fatal error

### ISSUE THREAD

**Issue by Klap-in** [meeting-room-booking-system/mrbs-code#66]
**Describe the bug**
The search throws the error: `Whoops! Unfortunately MRBS has encountered a fatal error. Please consult your system administrator.` if no from date is set. I'm emptied that field manually.

**To Reproduce**
1. Go to search page (search.php)
2. Fill something in the 'Search for', but empty the 'From' field
3. Press on Search throws the error.

**Expected behavior**
The invalid input is handled at least similar as the invalid input for search term, and not throwing an error. 
(ideally, in my view, leaving out the from date, would search in all bookings. But that would be another, feature, request ;-) )

**Screenshots**
none

**Browser details (please complete the following information):**
 - Chrome on Ubuntu 22.04

**Server details (please complete the following information):**
- MRBS version 1.11.0
- Database | MariaDB Server 10.3.28-MariaDB
- Systeem | Linux jerry 4.18.0-372.9.1.1.lve.el8.x86_64 # 1 SMP Tue May 24 07:49:22 EDT 2022 x86_64
- Server software | Apache/2.4
- PHP | 7.4.30

**Additional context**
Error log:
```
.../mrbs/search.php (warn): Backend log: Uncaught exception 'MRBS\\Exception' in /.../mrbs/search.php at line 135
Invalid from_date ''
#0 {main}

MRBS GET: Array
(
)
MRBS POST: Array
(
    [csrf_token] => ...
    [search_str] => test
    [from_date] => 
    [datatable] => 1
)
MRBS SESSION: Array
(
    [last_page] => /mrbs/search.php
    [this_page] => /mrbs/search.php
    [csrf_token] => ...
    [user] => MRBS\\User Object
        (
            [username] => name
            [display_name] => name
            [email] => email
            [level] => 2
            [data:protected] => Array
                (
                )
        )
)
```

**Comment by campbell-m** [comment]
I've now fixed the bug and also implemented your suggestion.  Many thanks.

**Comment by Klap-in** [comment]
Thanks, this works fine now. And that was a quick response!

As minor observation, this implementaion changes the default behaviour. For me that is fine, but I can image it has influence on other users. That is your intention?

**Comment by campbell-m** [comment]
Yes, I think that's fine.  If you search from the banner by just entering a search string it still searches from the current page date.  If you searched from search.php and didn't enter a date then you used to get a fatal error as you pointed out.   So I don't think it can be an issue for other users.

**Comment by campbell-m** [comment]
Ah, I see what you mean.  I've now restored the default behaviour in [974c3e3](https://github.com/meeting-room-booking-system/mrbs-code/commit/974c3e3932ed8c3041240ea00a562151f7b53a2b).
