### ISSUE TITLE
V1.9.0  upgrade from v1.7.1 vocab error

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#677]
Hi, I'm not sure if this is a bug or if I've missed something in the upgrade file.  I am upgrading from v1.7.1 to v1.9.0.  I have a few $vocab_override['en'] variables set in my config.php file. After copying the new v1.9.0 files to the web root, I access the website and I'm greeted with a blank page.  The error log shows:

~~~
PHP Fatal error:  Uncaught Error: Class 'MRBS\System' not found in /home/XXXXXXXX/public_html/dev3/language.inc:198
Stack trace:
#0 /home/XXXXXXXX/public_html/dev3/language.inc(159): MRBS\set_mrbs_locale('en-GB')
#1 /home/XXXXXXXX/public_html/dev3/defaultincludes.inc(28): require_once('/home/XXXXXXXX/...')
#2 /home/XXXXXXXX/public_html/dev3/index.php(8): require('/home/XXXXXXXX/...')
#3 {main}
  thrown in /home/XXXXXXXX/public_html/dev3/language.inc on line 198
~~~

After I comment out all the  $vocab_override['en'] entries the page works correctly and prompts me to upgrade the database.  
Cheers.

Reported by: *anonymous

Original Ticket: [mrbs/bugs/474](https://sourceforge.net/p/mrbs/bugs/474)

**Comment by campbell-m** [comment]
I assume this has now been resolved.
