### ISSUE TITLE
view_entry.php always shows logged in user as createdby/modifiedby

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#683]
If a user choses "public" as privacy status when creating a booking, the booking is always displayed as belonging to the logged in user (not the creator).

It's a little bit confusing sometimes :)

Reported by: vform06

Original Ticket: [mrbs/bugs/481](https://sourceforge.net/p/mrbs/bugs/481)

Attachments:
  https://sourceforge.net/p/mrbs/bugs/481/attachment/Public%20schedule%20-%20create.png
  https://sourceforge.net/p/mrbs/bugs/481/attachment/Public%20schedule%20-%20display.png

**Comment by campbell-m** [comment]
I assume this has been resolved by now.
