### ISSUE TITLE
mini-calendars can show incorrect week numbers

### ISSUE THREAD

**Issue by hanslub42** [meeting-room-booking-system/mrbs-code#70]
When `$mincals`  is set in `config.inc.php`,  `mrbs` uses [flatpickr](https://flatpickr.js.org/) to show mini-calendars. 
Moreover, when `$mincalls_week_numbers` is set, this will display week numbers alongside the mini-calendars

This month (January 2023) those week numbers are incorrect (and inconsistent: 1 February is both in week 4 and week 5)
Setting `$weekstarts = 1` doesn't help.

![schermfoto](https://user-images.githubusercontent.com/6263546/212308720-5d8f037d-d886-4329-9d81-086713fddb5b.png)

I believe this is the same `flatpickr` bug as described in https://github.com/flatpickr/flatpickr/issues/1949

A fix for this bug has been merged in `flatpickr` in January 2021. I use a slightly out-of-date mrbs version (1.10.0),  but the `flatpickr` directory in HEAD is still rather older than said bug fix, so I suspect the problem is still there.

**Comment by hanslub42** [comment]
Downloading the newest `flatpickr.min.js` from https://cdnjs.com/libraries/flatpickr and dropping it in the `web/js` folder fixes the problem

**Comment by campbell-m** [comment]
Thanks.  I note that the bug only manifests itself if the week doesn't start on a Monday.
