### ISSUE TITLE
Drag-select bug on scrolled down "day" calendar view

### ISSUE THREAD

**Issue by jberanek** [meeting-room-booking-system/mrbs-code#709]
When trying to click and drag to select multiple rooms over multiple hours, if the calendar view is scrolled down, the wrong times are selected. To recreate this issue, go to "day" view for the calendar, scroll down on the calendar element, and attempt to drag-select multiple rooms over a certain time. You will notice on the edit_entry page that the wrong time frame is selected.

Reported by: *anonymous

Original Ticket: [mrbs/bugs/507](https://sourceforge.net/p/mrbs/bugs/507)

**Comment by campbell-m** [comment]
Closed due to no response.
