### ISSUE TITLE
$this->versionComment() gives wrong details

### ISSUE THREAD

**Issue by NoGAD-de** [meeting-room-booking-system/mrbs-code#72]
**Describe the bug**
Filename: .\mrbs\web\lib\MRBS\DB_mysql.php
The function dbType incorrectly identifies the database type.
$this->versionComment() gives wrong details

**To Reproduce**

1. Enable Debug mode
2. Call the function dbType
3. Check the returned value
4. Observe that it is not the expected value

**Expected behavior**
The function should correctly identify the type of database in use.

**Screenshots**
None

**Browser details (please complete the following information):**
None

**Server details (please complete the following information):**
 - MRBS version: MRBS 1.11.0
 - Database: Ubuntu 20.04 10.3.37-MariaDB-0ubuntu0.20.04.1
 - System: Linux shared18.keymachine.de 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
 - Serversoftware: Apache
 - PHP: 7.4.3-4ubuntu2.17
 - PHP extensions: Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, SourceGuardian, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, ionCube Loader, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib

**Additional context**
The original implementation of the function dbType checks for the presence of the strings "maria" or "mysql" in the result of the function calls versionComment and version. The issue with this approach is that it may not correctly identify the type of database in use, leading to unexpected behavior. The correction made to the function, which only checks for the presence of "maria" or "mysql" in the result of versionComment, should result in a more accurate identification of the database in use.

Fixed function:

 private function dbType() : ?int
 {
    global $debug;

    if (!isset($this->db_type))
    {
      if ((false !== utf8_stripos($this->versionComment(), 'maria')) || (false !== utf8_stripos($this->version(), 'maria')))
      {
        $this->db_type = self::DB_MARIADB;
      }
      elseif ((false !== utf8_stripos($this->versionComment(), 'mysql')) || (false !== utf8_stripos($this->version(), 'mysql')))
      {
        $this->db_type = self::DB_MYSQL;
      }
      else
      {
        if ($debug)
        {
          trigger_error("Unknown database type '" . $this->versionComment() . "'");
        }
        $this->db_type = self::DB_OTHER;
      }
    }

    return $this->db_type;
  }

**Comment by campbell-m** [comment]
> The original implementation of the function dbType checks for the presence of the strings "maria" or "mysql" in the result of the function calls versionComment and version

Just checking - don't you mean 'only checks for the presence of "maria" or "mysql" in the result of versionComment' and vice versa for the correction?

**Comment by campbell-m** [comment]
Thanks.  Now fixed in [3530101](https://github.com/meeting-room-booking-system/mrbs-code/commit/353010156e9be833498db1c3e07a3e33549dc1d6).

**Comment by NoGAD-de** [comment]
Thx for fixing :-)

In my case, "$this->versionComment()" was just "Ubuntu 20.04".

With best regards
Mathias
