### ISSUE TITLE
Fatal Error on WordPress Authentication

### ISSUE THREAD

**Issue by cbratschi** [meeting-room-booking-system/mrbs-code#78]
**Describe the problem you're facing/question you have**
With default authentication MRBS works fine. As soon as the WordPress authentication is enabled I am getting a fatal_error. I enabled error logging in the config file but nothing is shown in this case.

The wp-config.php file was modified and WordPress runs fine.

**Server details (please complete the following information):**
 - MRBS version 1.11.0
 - Web server: Apache
 - PHP version: 8.0
 - Database used: MariaDB
 - WordPress 6.2

**Additional context**
Error message in German "Oh je! Leider ist in MRBS ein schwerwiegender Fehler aufgetreten. Bitte konsultieren Sie Ihren Systemadministrator.". Which is a fatal_error.

**Comment by cbratschi** [comment]
Found the error in the WordPress log:

```
[03-Apr-2023 17:22:29 Europe/Zurich] Uncaught exception 'Error' in /home/xyz/wp-content/plugins/query-monitor/collectors/assets_scripts.php at line 12
Class "QM_Collector_Assets" not found
#0 /home/xyz/wp-content/plugins/query-monitor/classes/QueryMonitor.php(48): include_once()
#1 /home/xyz/wp-content/plugins/query-monitor/query-monitor.php(82): QueryMonitor->set_up()
#2 /home/xyz/wp-settings.php(453): include_once('/home/bratsnet/...')
#3 /home/xyz/wp-config.php(133): require_once('/home/bratsnet/...')
#4 /home/xyz/wp-load.php(50): require_once('/home/bratsnet/...')
#5 /home/xyz/mrbs/web/auth/cms/wordpress.inc(12): require_once('/home/xyz/...')
#6 /home/xyz/mrbs/web/lib/MRBS/Session/SessionWordpress.php(7): require_once('/home/xyz/...')
#7 /home/xyz/mrbs/web/lib/autoload.inc(21): require('/home/xyz/...')
#8 /home/xyz/mrbs/web/lib/MRBS/Session/SessionFactory.php(14): {closure}('MRBS\\Session\\Se...')
#9 /home/xyz/mrbs/web/mrbs_auth.inc(33): MRBS\Session\SessionFactory::create('wordpress')
#10 /home/xyz/mrbs/web/init.inc(29): MRBS\session()
#11 /home/xyz/mrbs/web/defaultincludes.inc(34): require_once('/home/xyz/...')
#12 /home/xyz/mrbs/web/edit_users.php(44): require('/home/xyz/...')
#13 {main}
```

We are using Query Monitor and it cannot find the QM_Collector_Assets class.

**Comment by campbell-m** [comment]
What's puzzling me is why edit_users.php is being called.  That's only applicable to 'db' authentication.  What happens when you go to index.php?

**Comment by cbratschi** [comment]
Query Monitor code is here: https://github.com/johnbillion/query-monitor/blob/60da795c040e0f08850891c74a36b2f566cee14d/collectors/assets_scripts.php

**Comment by campbell-m** [comment]
I can't reproduce this.  Which version of QueryMonitor are you using?

**Comment by cbratschi** [comment]
It is version 3.12.1 and WordPress is installed in a subdirectory: domain.com/folder/. Probably the latter could be the root cause of the missing class.

**Comment by campbell-m** [comment]
When I said that I couldn't reproduce it I should have added that I was using the latest development code from the [main branch](https://github.com/meeting-room-booking-system/mrbs-code).  I don't think it will make any difference but you could try upgrading.

**Comment by cbratschi** [comment]
I found the root cause of the issue: the glob() call returns the found files in slightly different order. The result gets sorted by name.

https://github.com/johnbillion/query-monitor/blob/develop/classes/QueryMonitor.php#L32

WordPress order:

- admin.php
- assets.php
- assets_scripts.php
- assets_styles.php

MRBS call order:

- admin.php
- assets_scripts.php
- assets_styles.php
- assets.php

I guess this has to do with the active locale which uses a different sort algorithm. Therefore assets.php is loaded later in the German case and the class is not defined. We use English in WordPress and MRBS uses German based on my browser locale.

Can we force MRBS to use English all the time?

**Comment by cbratschi** [comment]
Using no sorting would be a solution:

```php
$files = glob( $this->plugin_path( 'collectors/*.php' ), GLOB_NOSORT );
```

Works in both cases. Hopefully the order is consistent across file systems.

**Comment by campbell-m** [comment]
Interesting!  Unfortunately I can't reproduce this even when I set the MRBS locale to German.  I had thought that if I could, then a circumvention in MRBS for the QueryMonitor problem could be to modify auth/cms/wordpress.inc to save the current locale and set the locale to English before calling wp-load.php and then restoring the original locale afterwards.

**Comment by campbell-m** [comment]
I wonder whether the locale of the operating system is also a factor?

**Comment by cbratschi** [comment]
Yes, I agree this kind of loading operating is quite dangerous and any change could have other side effects. The loading order should consistently be the same. Let's wait for an answer of the author of Query Monitor.

**Comment by cbratschi** [comment]
This is now fixed in Query Monitor. @campbell-m, thanks for your support.
