### ISSUE TITLE
No new release since December 2022

### ISSUE THREAD

**Issue by paulmenzel** [meeting-room-booking-system/mrbs-code#84]
MRBS 1.11.0 was release on December 22nd, 2022. To profit from the latest changes, it’d be great, if a new release was cut. Thank you for you great work.

**Comment by campbell-m** [comment]
You can always download the latest code from https://github.com/meeting-room-booking-system/mrbs-code.

**Comment by campbell-m** [comment]
Yes, agreed.  I'd be interested to know if you have tried the latest code and, if so, whether there were any issues?  There are some major changes in the area of date/time formatting, eliminating the use of the deprecated `strftime()` function.

**Comment by campbell-m** [comment]
MRBS 1.11.1 has just been released.
